// Словарь по секциям курса английского. Каждая секция (unit) = список слов из
// учебника + связный текст (story), где эти слова встречаются в контексте.
// Слово: { k: ключ ровно как в списке из курса, w: словарная форма, form: часть
// речи / конструкция, ipa?, ru, def (EN-определение), reg: регистр,
// ex: [2 примера], use / use_en: где и как употреблять + типичная ловушка,
// gap: { s: предложение с ___, a: ответ в нужной форме } — для режима «Пропуски».
// В story слова размечены как [[k]] или [[k|как показать]] (другой регистр) —
// ключ должен совпадать с k буква в букву.
// Новые секции — добавлять в конец UNITS; проверка: npm test (english.test.js).

export type Word = {
  k: string; // ключ ровно как в списке из курса
  w: string; // словарная форма
  form: string; // часть речи / конструкция
  ipa?: string;
  ru: string;
  def: string; // EN-определение
  reg: string; // регистр
  ex: string[]; // 2 примера
  use: string;
  use_en: string;
  gap: { s: string; a: string };
};
export type Unit = {
  id: string;
  title: string;
  title_en: string;
  theme: string;
  theme_en: string;
  story: string;
  words: Word[];
};
export type UnitWord = Word & { unit: string };

export const UNITS: Unit[] = [
  {
    id: "s2",
    title: "Section 2 · Голос, которого не было раньше",
    title_en: "Section 2 · A voice unlike anything before",
    theme: "Биография певицы: формальный, журналистский регистр",
    theme_en: "A singer's biography: formal, journalistic register",
    story:
      "Born in the early 1900s, she became a [[renowned]] contralto and one of the most [[prominent]] Black artists of her century. [[Indeed]], critics wrote that her [[powerful voice was unlike anything that had come before]]. She [[dropped out]] of school to help her family. She [[had hoped]] to enter a music academy, but in a [[race-conscious culture]] she was turned away at the door. During the war she toured Europe, and it was [[when she was entertaining soldiers and prisoners of war]] that her fame spread. [[In the rare instances]] when she sang at home, audiences were [[segregated in terms of colour]], and she kept a single white gown [[for such occasions]]. Some of her contemporaries achieved a [[high level of notoriety]] through scandal; she chose dignity instead. [[She paved the way]] for every Black singer who followed.",
    words: [
      {
        k: "renowned", w: "renowned", form: "adjective", ipa: "/rɪˈnaʊnd/",
        ru: "прославленный, знаменитый (за что-то конкретное и хорошее)",
        def: "famous and admired for a particular quality, skill or achievement",
        reg: "formal · written",
        ex: ["a renowned soprano", "The region is renowned for its wine."],
        use: "Всегда с чем-то положительным: renowned FOR (за что) / renowned AS (в качестве кого). Звучит книжно — в живой речи скажут famous. Ловушка: notorious — тоже «известный», но дурной славой.",
        use_en: "Always positive: renowned FOR something / renowned AS someone. Bookish — in speech people say famous. Trap: notorious also means «well-known», but for something bad.",
        gap: { s: "The city is ___ for its Gothic architecture.", a: "renowned" },
      },
      {
        k: "prominent", w: "prominent", form: "adjective", ipa: "/ˈprɒmɪnənt/",
        ru: "видный, заметный, занимающий важное положение; физически выступающий",
        def: "important and well known within a field; also sticking out so as to be easily seen",
        reg: "formal · neutral",
        ex: ["a prominent lawyer / politician / member of the community", "She played a prominent role in the campaign."],
        use: "Не «знаменитый», а «на видном месте»: prominent figure, prominent role, prominent position. Второе значение — физическое: prominent cheekbones, a prominent nose, displayed in a prominent place.",
        use_en: "Not «famous» but «in a visible position»: a prominent figure / role / position. Second meaning is physical: prominent cheekbones, displayed in a prominent place.",
        gap: { s: "She became a ___ figure in the civil rights movement.", a: "prominent" },
      },
      {
        k: "Indeed", w: "indeed", form: "adverb", ipa: "/ɪnˈdiːd/",
        ru: "действительно; более того, в самом деле",
        def: "used to emphasise or confirm a statement, or to add a stronger point",
        reg: "formal · written",
        ex: ["The tour was a success. Indeed, every show sold out.", "It was very cold indeed."],
        use: "Три роли: 1) в начале предложения — усиливает предыдущую мысль («более того»); 2) после very + прилагательное (BrE): very kind indeed; 3) ответ «Indeed.» — «именно». Ловушка: русскоязычные ставят Indeed в каждое второе предложение как «действительно» — в тексте один-два раза максимум, иначе звучит напыщенно или иронично.",
        use_en: "Three roles: 1) sentence-initial to strengthen the previous point («what is more»); 2) after very + adjective (BrE): very kind indeed; 3) as a one-word reply «Indeed.» Trap: overusing it as a translation of «действительно» sounds pompous or sarcastic — once or twice per text.",
        gap: { s: "The concert was a triumph. ___, it sold out within an hour.", a: "Indeed" },
      },
      {
        k: "dropped out", w: "drop out (of)", form: "phrasal verb", ipa: "/drɒp aʊt/",
        ru: "бросить (учёбу, курс, гонку) до завершения",
        def: "to leave school, university, a course or a competition before finishing it",
        reg: "neutral",
        ex: ["He dropped out of university in his second year.", "Two runners dropped out of the race."],
        use: "Сам ушёл: drop out OF school / college / the race. Существительное: a college dropout. Ловушка: если отчислили — expelled (школа) / kicked out (разг.), не dropped out.",
        use_en: "Leaving by your own choice: drop out OF school / college / the race. Noun: a college dropout. Trap: if the school removed you, that is expelled / kicked out, not dropped out.",
        gap: { s: "He ___ of college after one year to start a band.", a: "dropped out" },
      },
      {
        k: "had hoped", w: "had hoped (to)", form: "grammar: past perfect", ipa: "",
        ru: "надеялся(ась)… но не вышло",
        def: "past perfect of hope: a hope in the past that was NOT fulfilled",
        reg: "neutral",
        ex: ["She had hoped to study in Vienna, but the war changed everything.", "We had hoped for better weather."],
        use: "Past perfect с hope / expect / intend / mean / want = нереализованное намерение: I had hoped to call you — надеялся, но не позвонил. Ловушка: I hoped to… — нейтрально, результат не ясен; I had hoped to… — слушатель уже знает, что не получилось.",
        use_en: "Past perfect with hope / expect / intend / mean / want signals an unfulfilled intention: I had hoped to call you — but didn't. Trap: I hoped to… is neutral; I had hoped to… tells the listener it didn't happen.",
        gap: { s: "We ___ to arrive before dark, but the train was delayed for hours.", a: "had hoped" },
      },
      {
        k: "race-conscious culture", w: "race-conscious", form: "compound adjective", ipa: "",
        ru: "общество, где расовая принадлежность постоянно замечается и влияет на отношение",
        def: "(a culture) in which people are constantly aware of race and treat others according to it",
        reg: "formal · academic",
        ex: ["Growing up in a race-conscious culture, she learned early which doors were closed.", "health-conscious consumers, a price-conscious buyer"],
        use: "Модель X-conscious = «обращающий внимание на X»: health-conscious, price-conscious, fashion-conscious, class-conscious (BrE, о классах). Ловушка: conscious (осознающий) ≠ conscientious (добросовестный) ≠ self-conscious (стесняющийся).",
        use_en: "Pattern X-conscious = «paying attention to X»: health-conscious, price-conscious, fashion-conscious, class-conscious. Trap: conscious (aware) ≠ conscientious (diligent) ≠ self-conscious (embarrassed, shy).",
        gap: { s: "Shoppers have become far more price-___ since the crisis.", a: "conscious" },
      },
      {
        k: "when she was entertaining soldiers and prisoners of war", w: "entertain (an audience)", form: "verb · past continuous", ipa: "/ˌentəˈteɪn/",
        ru: "развлекать, выступать перед публикой; принимать гостей",
        def: "to perform for people and amuse them; also to have guests at your home",
        reg: "neutral",
        ex: ["She spent the war entertaining the troops.", "We're entertaining friends on Saturday."],
        use: "Past continuous (was entertaining) — фон, на котором случилось главное событие. Prisoners of war (POWs) — военнопленные. Ловушка: entertain an idea / a proposal — формальное «рассматривать, допускать», не «развлекать».",
        use_en: "Past continuous (was entertaining) sets the background against which the main event happens. Prisoners of war (POWs). Trap: entertain an idea / a proposal is formal for «consider», nothing to do with amusement.",
        gap: { s: "During the war she toured Europe, ___ the troops.", a: "entertaining" },
      },
      {
        k: "In the rare instances", w: "in the rare instances (when)", form: "noun phrase", ipa: "/ˈɪnstənsɪz/",
        ru: "в тех редких случаях, когда",
        def: "on the few occasions when something happens",
        reg: "formal · written",
        ex: ["In the rare instances when she performed at home, the hall was packed.", "In this instance, the rule does not apply."],
        use: "instance = конкретный случай/пример явления (for instance — например; in this instance — в данном случае). Ловушка: occasion — событие/момент («по такому случаю»), case — ситуация/дело; instance — один из повторяющихся примеров.",
        use_en: "instance = a particular example of something happening (for instance; in this instance). Trap: occasion is an event or moment, case is a situation; instance is one example among repeated ones.",
        gap: { s: "In the rare ___ when she was allowed on stage, the hall was full.", a: "instances" },
      },
      {
        k: "for such occasions", w: "occasion", form: "noun", ipa: "/əˈkeɪʒən/",
        ru: "особый случай, событие, торжество",
        def: "a special or particular event, or the time when it happens",
        reg: "neutral · formal",
        ex: ["She kept one gown for such occasions.", "a dress for a special occasion; rise to the occasion"],
        use: "on this occasion — в этот раз; on occasion — иногда; dress for the occasion; rise to the occasion — оказаться на высоте. Ловушка №1 русскоязычных: occasion ≠ «возможность» — I had an occasion to… ✗ → I had an opportunity / a chance to….",
        use_en: "on this occasion; on occasion (= sometimes); dress for the occasion; rise to the occasion. Trap for Russian speakers: occasion is NOT «opportunity» — I had an occasion to… ✗ → I had a chance to….",
        gap: { s: "She kept one white gown for such ___.", a: "occasions" },
      },
      {
        k: "segregated in terms of colour", w: "segregated / in terms of", form: "adjective + preposition phrase", ipa: "/ˈseɡrɪɡeɪtɪd/",
        ru: "разделённый по расовому признаку; in terms of — в отношении, с точки зрения",
        def: "kept apart by race (segregation); in terms of = with regard to a particular aspect",
        reg: "formal",
        ex: ["Audiences were segregated: Black listeners sat at the back.", "In terms of cost, the plan is fine; in terms of time, it isn't."],
        use: "segregate / segregation — про разделение групп людей (расовое, гендерное), не про «отделить файлы». in terms of — канцелярская связка, по возможности заменять: as regards, when it comes to. colour — британское написание (AmE color).",
        use_en: "segregate / segregation is about separating groups of people (by race, gender), not files. in terms of is bureaucratic filler — prefer when it comes to. colour is the British spelling (AmE color).",
        gap: { s: "Audiences were ___ : Black listeners had to sit at the back.", a: "segregated" },
      },
      {
        k: "high level of notoriety", w: "notoriety", form: "noun", ipa: "/ˌnəʊtəˈraɪəti/",
        ru: "дурная / скандальная известность",
        def: "the state of being famous for something bad or shocking",
        reg: "formal",
        ex: ["The club gained notoriety for its wild late-night shows.", "a notorious criminal"],
        use: "Почти всегда негативно или скандально: gain / achieve notoriety FOR. Прилагательное notorious — печально известный. Ловушка: использовать как красивый синоним fame — ошибка; о хорошем говорят fame, renown, recognition.",
        use_en: "Nearly always negative or scandalous: gain / achieve notoriety FOR. Adjective: notorious. Trap: using it as a fancy synonym of fame — for good things say fame, renown, recognition.",
        gap: { s: "The nightclub gained ___ for its wild late-night shows.", a: "notoriety" },
      },
      {
        k: "powerful voice was unlike anything that had come before", w: "unlike anything that had come before", form: "idiomatic phrase", ipa: "",
        ru: "ни на что прежнее не похожий",
        def: "completely new and different from everything earlier",
        reg: "journalistic · praising",
        ex: ["The album was unlike anything that had come before.", "a style like nothing before it"],
        use: "Формула для описания новизны: unlike + существительное (unlike anything / anyone). Past perfect had come before — «всё, что было ДО того момента». Ловушка: unlike — предлог, без than: unlike than ✗.",
        use_en: "A set formula for novelty: unlike + noun (unlike anything / anyone). Past perfect had come before = everything up to that moment. Trap: unlike is a preposition — no than after it.",
        gap: { s: "Her debut album was ___ anything that had come before.", a: "unlike" },
      },
      {
        k: "She paved the way", w: "pave the way (for)", form: "idiom", ipa: "/peɪv/",
        ru: "проложить путь, подготовить почву (для кого-то / чего-то)",
        def: "to make it easier for something to happen or for someone to follow later",
        reg: "neutral · journalistic",
        ex: ["Her victory paved the way for other women in the sport.", "The talks paved the way for a peace deal."],
        use: "pave the way FOR (не to). Буквально pave — мостить (paved road, pavement — тротуар BrE). Близкие: open the door for, set the stage for, be a trailblazer.",
        use_en: "pave the way FOR (not to). Literally, pave = cover with stones (paved road; pavement = BrE sidewalk). Related: open the door for, set the stage for, be a trailblazer.",
        gap: { s: "Her victory ___ the way for other women in the sport.", a: "paved" },
      },
    ],
  },
  {
    id: "s3",
    title: "Section 3 · За кулисами детского шоу",
    title_en: "Section 3 · Backstage at a kids' show",
    theme: "Интервью с артистом: разговорный британский, сленг",
    theme_en: "An interview with a performer: spoken British English, slang",
    story:
      "[[I’m backstage at]] a small theatre, talking to a children's entertainer. Has the job changed over twenty years? '[[It certainly has]]. There's more [[rowdiness]] now — kids arrive high on sugar and phones.' [[How do you cope with that?]] 'With a [[rowdy kid]], [[We bring the parent up|we bring the parent up]] on stage and let the child watch them squirm. [[You never know what they’re going to come up with]], [[But I’m up for that.|but I’m up for that.]] The [[onus]] is on me to keep control, and you [[Can’t diverge from the script|can’t diverge from the script]] too far or the whole room goes with you.' The corporate side, he admits, is [[very lucrative]]. '[[But what has also driven me is the fact that I was dyslexic]]. School was a [[tough crowd]]. Adults are worse, mind — they [[Get boozed up|get boozed up]] at Christmas parties and heckle.'",
    words: [
      {
        k: "I’m backstage at", w: "backstage", form: "adverb / adjective", ipa: "/ˌbækˈsteɪdʒ/",
        ru: "за кулисами (буквально, в театре или на концерте)",
        def: "in the area behind the stage where performers prepare",
        reg: "neutral",
        ex: ["I'm backstage at the arena, waiting for the band.", "a backstage pass; go backstage after the show"],
        use: "Буквальное место: backstage at + площадка. Ловушка: переносное «за кулисами» (закрытая часть процесса) — behind the scenes: behind-the-scenes negotiations.",
        use_en: "A literal place: backstage at + venue. Trap: the figurative «behind the curtain» of a process is behind the scenes: behind-the-scenes negotiations.",
        gap: { s: "The presenter is ___ at the arena, waiting for the band to arrive.", a: "backstage" },
      },
      {
        k: "It certainly has", w: "It certainly has.", form: "grammar: echo answer", ipa: "",
        ru: "ещё как (изменилось) — короткий ответ с вспомогательным глаголом",
        def: "a short emphatic answer repeating the auxiliary verb of the question",
        reg: "spoken",
        ex: ["— Has the show changed? — It certainly has.", "— Do you miss it? — I really do."],
        use: "Модель: подлежащее + certainly / really / definitely + вспомогательный глагол из вопроса (has, does, did, can). Ловушка: русскоязычные отвечают «Yes, it changed» — грамматически можно, но эхо-ответ звучит естественнее и живее.",
        use_en: "Pattern: subject + certainly / really / definitely + the auxiliary from the question (has, does, did, can). Trap: answering «Yes, it changed» is possible but the echo answer sounds far more natural.",
        gap: { s: "— Has the tour been exhausting? — It ___ has.", a: "certainly" },
      },
      {
        k: "rowdiness", w: "rowdiness", form: "noun", ipa: "/ˈraʊdinəs/",
        ru: "буйство, шумное и неуправляемое поведение (толпы, публики)",
        def: "noisy, rough and slightly aggressive behaviour, usually of a group",
        reg: "neutral · informal",
        ex: ["The stewards struggled to control the rowdiness of the crowd.", "There was some rowdiness after the match."],
        use: "Про группу, которая шумит и слегка агрессивна: болельщики, паб в пятницу, класс без учителя. Ловушка: просто громко — loud / noisy; rowdy добавляет «буйно, на грани хулиганства».",
        use_en: "About a group that is noisy and a bit aggressive: fans, a pub on Friday, a class with no teacher. Trap: merely loud is loud / noisy; rowdy adds «unruly, close to trouble».",
        gap: { s: "The stewards struggled to control the ___ of the crowd.", a: "rowdiness" },
      },
      {
        k: "How do you cope with that?", w: "cope with", form: "verb + preposition", ipa: "/kəʊp/",
        ru: "справляться с (чем-то трудным, стрессом)",
        def: "to deal successfully with a difficult situation or emotion",
        reg: "neutral",
        ex: ["How do you cope with hecklers?", "She's coping well with the pressure."],
        use: "cope WITH, и никогда cope up with (частая ошибка). cope — про то, чтобы выдержать трудное (стресс, потеря, нагрузка); deal with / handle — шире, про любые дела. Без дополнения тоже можно: I can't cope.",
        use_en: "cope WITH — never cope up with. cope is about enduring something hard (stress, loss, workload); deal with / handle are broader. Also used alone: I can't cope.",
        gap: { s: "How do you ___ with hecklers in the front row?", a: "cope" },
      },
      {
        k: "You never know what they’re going to come up with", w: "come up with", form: "phrasal verb", ipa: "",
        ru: "придумать, выдать (идею, ответ, отговорку)",
        def: "to think of or produce an idea, answer or plan",
        reg: "neutral · informal",
        ex: ["Kids always come up with the strangest questions.", "We need to come up with a name by Friday."],
        use: "Неотделяемый: come up with an idea, не come an idea up. Ловушка: come up (возникнуть, всплыть: something came up) и come across (наткнуться) — другие глаголы.",
        use_en: "Inseparable: come up with an idea, never come an idea up. Trap: come up (arise: something came up) and come across (find by chance) are different verbs.",
        gap: { s: "Kids always ___ up with the strangest questions.", a: "come" },
      },
      {
        k: "But I’m up for that.", w: "be up for (something)", form: "idiom · spoken", ipa: "",
        ru: "быть готовым / не против, «я за»",
        def: "to be willing and keen to do something",
        reg: "informal · spoken",
        ex: ["Karaoke tonight? — Sure, I'm up for that.", "Anyone up for a walk?"],
        use: "Приглашение и согласие: up for a drink / a challenge / anything. Ловушка: be up TO — либо «замышлять» (What are you up to?), либо «быть в силах» (I'm not up to it today). Одна буква — другой смысл.",
        use_en: "Invitations and agreement: up for a drink / a challenge / anything. Trap: be up TO means either «doing something sneaky» (What are you up to?) or «capable of» (I'm not up to it today).",
        gap: { s: "Karaoke after the show? — Sure, I'm ___ for that.", a: "up" },
      },
      {
        k: "rowdy kid", w: "rowdy", form: "adjective", ipa: "/ˈraʊdi/",
        ru: "шумный, буйный, неуправляемый",
        def: "noisy and behaving in a rough, uncontrolled way",
        reg: "informal",
        ex: ["A rowdy kid in the front row kept shouting.", "a rowdy crowd / pub / party"],
        use: "Про людей и компании, не про машины или музыку. Сравни: naughty kid — непослушный (мягче); disruptive — срывающий занятие (учительское слово).",
        use_en: "About people and groups, not machines or music. Compare: a naughty kid is misbehaving (milder); disruptive is the teacher's word for spoiling a lesson.",
        gap: { s: "A ___ kid in the front row kept shouting over the jokes.", a: "rowdy" },
      },
      {
        k: "We bring the parent up", w: "bring somebody up (on stage)", form: "phrasal verb", ipa: "",
        ru: "вызвать на сцену; (другие значения) воспитывать; поднять тему",
        def: "to call someone onto the stage; also to raise a child; also to mention a topic",
        reg: "spoken",
        ex: ["If a child misbehaves, we bring the parent up on stage.", "I was brought up in Leeds. / Don't bring up the divorce at dinner."],
        use: "Три значения одного глагола, контекст решает: bring the parent up (на сцену), be brought up (быть воспитанным), bring up a subject (поднять тему). Отделяемый: bring him up / bring up the parent.",
        use_en: "Three meanings, context decides: bring the parent up (onto the stage), be brought up (raised), bring up a subject (mention it). Separable: bring him up / bring up the parent.",
        gap: { s: "If a child misbehaves, we ___ the parent up on stage.", a: "bring" },
      },
      {
        k: "onus", w: "the onus (is on somebody)", form: "noun · singular only", ipa: "/ˈəʊnəs/",
        ru: "бремя ответственности, обязанность",
        def: "the responsibility or duty to do something",
        reg: "formal (used in speech for emphasis)",
        ex: ["The onus is on the performer to keep the audience on side.", "The onus of proof lies with the prosecution."],
        use: "Всегда the onus, всегда единственное число: the onus is ON somebody TO do something. Юридически-формальное слово, в разговоре добавляет веса. Ловушка: onus of — редко и только в юр. штампах (onus of proof).",
        use_en: "Always the onus, always singular: the onus is ON somebody TO do something. Legal-formal, adds weight in speech. Trap: onus of appears only in fixed legal phrases (onus of proof).",
        gap: { s: "The ___ is on the performer to keep the audience on side.", a: "onus" },
      },
      {
        k: "Can’t diverge from the script", w: "diverge from", form: "verb + preposition", ipa: "/daɪˈvɜːdʒ/",
        ru: "отклоняться от (сценария, плана, нормы); расходиться (о путях, мнениях)",
        def: "to move away from a plan, script or standard; to go in different directions",
        reg: "formal · neutral",
        ex: ["In a scripted show you can't diverge from the text.", "Our opinions diverge on this point."],
        use: "diverge FROM. Ловушка: digress — отклоняться от темы в речи (But I digress); deviate from — отклониться от нормы/маршрута (ближайший синоним). Существительное — divergence.",
        use_en: "diverge FROM. Trap: digress is going off-topic while speaking (But I digress); deviate from is the closest synonym (from a norm or route). Noun: divergence.",
        gap: { s: "In a scripted show you can't ___ from the text for long.", a: "diverge" },
      },
      {
        k: "very lucrative", w: "lucrative", form: "adjective", ipa: "/ˈluːkrətɪv/",
        ru: "прибыльный, доходный (о деле, контракте, рынке)",
        def: "producing a lot of money",
        reg: "neutral · formal",
        ex: ["Corporate gigs are dull but very lucrative.", "a lucrative contract / market / career"],
        use: "Про деятельность и сделки, не про людей: a lucrative man ✗. Ловушка: profitable — бухгалтерское «в плюсе»; lucrative — «приносит большие деньги», часто с оттенком «ради денег, не ради души».",
        use_en: "About activities and deals, not people: a lucrative man ✗. Trap: profitable is the accountant's «in the black»; lucrative means «brings in big money», often hinting «for the money, not the love».",
        gap: { s: "Corporate gigs are boring but very ___.", a: "lucrative" },
      },
      {
        k: "But what has also driven me is the fact that I was dyslexic", w: "what has driven me is…", form: "grammar: cleft sentence · drive somebody", ipa: "/dɪsˈleksɪk/",
        ru: "что двигало мной — так это… ; dyslexic — с дислексией",
        def: "drive somebody = to motivate or push them; a cleft sentence puts the emphasis on the reason",
        reg: "spoken · emphatic",
        ex: ["What has driven me all these years is the fear of an office job.", "She's a very driven person."],
        use: "Cleft-конструкция What… is… выносит причину в фокус: What matters is… / What drove me was…. driven (прилагательное) — целеустремлённый. Ловушка: What drives you? — «что тебя мотивирует», не «что ты водишь».",
        use_en: "The cleft What… is… puts the reason in focus: What matters is… / What drove me was…. driven (adjective) = highly motivated. Trap: What drives you? asks about motivation, not cars.",
        gap: { s: "What has ___ me all these years is the fear of going back to an office job.", a: "driven" },
      },
      {
        k: "tough crowd", w: "tough crowd", form: "idiom", ipa: "/tʌf/",
        ru: "трудная публика (не смеётся, не реагирует); шутливо о любой неблагодарной аудитории",
        def: "an audience that is hard to please; jokingly, any unresponsive group",
        reg: "informal · humorous",
        ex: ["Nobody laughed at my joke in the meeting. Tough crowd.", "Teenagers are a tough crowd for a magician."],
        use: "Из стендапа, но живёт везде: сказать Tough crowd после шутки, которую не оценили коллеги, — самоирония. Ловушка: crowd здесь «публика», не «толпа на улице».",
        use_en: "From stand-up, but used everywhere: saying Tough crowd after a joke your colleagues ignored is self-mockery. Trap: crowd here means «audience», not a street crowd.",
        gap: { s: "Nobody laughed at my joke in the meeting. ___ crowd.", a: "Tough" },
      },
      {
        k: "Get boozed up", w: "get boozed up", form: "slang · phrasal", ipa: "/buːzd/",
        ru: "напиться, набраться",
        def: "to get drunk (booze = alcohol, informal)",
        reg: "slang · BrE",
        ex: ["By ten the stag party had got well and truly boozed up.", "There's plenty of booze in the fridge."],
        use: "Только с друзьями или в шутку: booze (выпивка), boozer (паб или пьяница, BrE), a booze-up (попойка). Регистр по возрастанию: boozed up → drunk → intoxicated (полиция, отчёты).",
        use_en: "Only among friends or as a joke: booze (alcohol), boozer (a pub or a drinker, BrE), a booze-up (a drinking session). Register ladder: boozed up → drunk → intoxicated (police, reports).",
        gap: { s: "By ten the stag party had got well and truly ___ up.", a: "boozed" },
      },
    ],
  },
  {
    id: "s4",
    title: "Section 4 · Летние каникулы",
    title_en: "Section 4 · Summer holidays",
    theme: "Рассказ об отдыхе: неформальный британский",
    theme_en: "Talking about holidays: informal British English",
    story:
      "As a kid, the [[endless summer hols]] meant six weeks of [[Just pottering around|just pottering around]]. [[inevitably|Inevitably]] I got bored, [[hung around]] the park with mates and put off [[tidying up]] my room until the last day. Last year my friends [[had been pestering me]] for months about a [[getaway]], and I finally said yes, though [[I was dreading]] it. We left [[at the crack of dawn]]; [[Within three hours|within three hours]] we were by the sea. [[no lugging baggage|No lugging baggage]] — one rucksack each. My mate drove; [[I’d never have made it otherwise]]. [[we did have to chip in with the washing up|We did have to chip in with the washing up]], but there was [[plenty]] of time to do nothing at all. Oddly, after a week of doing nothing [[I was more shattered]] than after a month at work. Now it's back to the [[grindstone]].",
    words: [
      {
        k: "endless summer hols", w: "hols", form: "noun · BrE informal", ipa: "/hɒlz/",
        ru: "каникулы (сокращение от holidays)",
        def: "short for holidays: school or work holidays (BrE)",
        reg: "informal · BrE",
        ex: ["Six weeks of summer hols — I had no idea what to do with myself.", "What are you doing over the hols?"],
        use: "Британское: holiday = отпуск/каникулы (on holiday), в AmE это vacation, а holidays там — рождественские праздники. hols — детско-школьное сокращение, взрослые говорят с улыбкой.",
        use_en: "British: holiday = time off (on holiday); in AmE that is vacation, and the holidays means the Christmas season. hols is a schoolkid's clipping — adults use it with a smile.",
        gap: { s: "Six weeks of summer ___ — I had no idea what to do with myself.", a: "hols" },
      },
      {
        k: "Just pottering around", w: "potter around / about", form: "phrasal verb · BrE", ipa: "/ˈpɒtə/",
        ru: "возиться без цели, неспешно заниматься мелочами (по дому, в саду)",
        def: "to spend time doing small, pleasant, unimportant things without hurrying",
        reg: "informal · BrE",
        ex: ["Dad spent Sunday pottering around in the garden.", "I just pottered about the house all morning."],
        use: "Уютное слово про безделье без вины. AmE — putter around. Ловушка: не путать с potter (гончар) — Harry Potter не при чём; и не mess around (валять дурака, с оттенком неодобрения).",
        use_en: "A cosy word for guilt-free idleness. AmE: putter around. Trap: nothing to do with a potter (who makes pots), and not mess around (fooling about, slightly disapproving).",
        gap: { s: "Dad spent the whole Sunday ___ around in the garden.", a: "pottering" },
      },
      {
        k: "inevitably", w: "inevitably", form: "adverb", ipa: "/ɪnˈevɪtəbli/",
        ru: "неизбежно; как и следовало ожидать",
        def: "as was certain to happen; unavoidably",
        reg: "neutral",
        ex: ["We planned a barbecue and, inevitably, it poured with rain.", "Inevitably, the conversation turned to work."],
        use: "Часто с иронией вводит предсказуемо-нежелательный исход. Ставится в начале или между запятыми. Прилагательное inevitable: the inevitable happened.",
        use_en: "Often ironic, introducing a predictable, unwelcome outcome. Sentence-initial or between commas. Adjective: inevitable — the inevitable happened.",
        gap: { s: "We planned a barbecue and, ___, it poured with rain.", a: "inevitably" },
      },
      {
        k: "hung around", w: "hang around", form: "phrasal verb", ipa: "",
        ru: "слоняться, торчать где-то без дела; hang around with — тусоваться с",
        def: "to spend time somewhere doing nothing much; hang around with = spend time with",
        reg: "informal",
        ex: ["We just hung around the shopping centre all afternoon.", "He hangs around with the wrong crowd."],
        use: "Ловушка из трёх hang: hang around (торчать без дела, чуть негативно), hang out (проводить время вместе, позитивно, AmE-оттенок), hang on (подожди). Past — hung (hanged — только о казни).",
        use_en: "Three hangs: hang around (loiter, slightly negative), hang out (spend time together, positive), hang on (wait). Past tense hung — hanged is only for executions.",
        gap: { s: "We just ___ around the shopping centre all afternoon.", a: "hung" },
      },
      {
        k: "tidying up", w: "tidy up", form: "phrasal verb · BrE", ipa: "/ˈtaɪdi/",
        ru: "прибраться, навести порядок",
        def: "to make a place neat by putting things where they belong",
        reg: "neutral · BrE",
        ex: ["Before Mum got home we spent an hour tidying up.", "Tidy your room up!"],
        use: "tidy — про порядок (разложить вещи), clean — про грязь (помыть). AmE чаще clean up / straighten up. Отделяемый: tidy up the room / tidy the room up.",
        use_en: "tidy is about order (putting things away), clean is about dirt. AmE prefers clean up / straighten up. Separable: tidy up the room / tidy the room up.",
        gap: { s: "Before Mum got home we spent an hour ___ up.", a: "tidying" },
      },
      {
        k: "I was more shattered", w: "shattered", form: "adjective · BrE informal", ipa: "/ˈʃætəd/",
        ru: "вымотанный, без сил; (буквально) разбитый вдребезги",
        def: "extremely tired (BrE informal); literally, broken into pieces",
        reg: "informal · BrE",
        ex: ["After the night flight I was absolutely shattered.", "shattered glass; her dreams were shattered"],
        use: "Британское «я выжат»: I'm shattered / knackered. Ловушка: американец может понять shattered как «раздавлен горем»; в AmE говорят exhausted, beat, wiped out. Усилитель — absolutely, не very.",
        use_en: "British for «drained»: I'm shattered / knackered. Trap: to an American shattered may sound like «emotionally devastated»; AmE says exhausted, beat, wiped out. Intensifier: absolutely, not very.",
        gap: { s: "After the overnight flight I was absolutely ___.", a: "shattered" },
      },
      {
        k: "no lugging baggage", w: "lug (something)", form: "verb · informal", ipa: "/lʌɡ/",
        ru: "тащить, волочь что-то тяжёлое",
        def: "to carry or drag something heavy with effort",
        reg: "informal",
        ex: ["No lugging suitcases up five flights of stairs this year.", "I lugged the shopping home in the rain."],
        use: "carry — нейтрально нести; lug — тяжело и с раздражением. Существительное luggage / baggage — багаж (неисчисляемые: a piece of luggage). no + -ing в заголовках и заметках = «никакого …».",
        use_en: "carry is neutral; lug means heavy and annoying. Nouns luggage / baggage are uncountable (a piece of luggage). no + -ing in notes and headlines = «none of that».",
        gap: { s: "No ___ suitcases up five flights of stairs this year.", a: "lugging" },
      },
      {
        k: "Within three hours", w: "within (a period)", form: "preposition", ipa: "/wɪðˈɪn/",
        ru: "не позже чем через; в пределах",
        def: "before a period of time has passed; inside a limit",
        reg: "neutral",
        ex: ["Within three hours we were on the beach.", "Reply within five working days. / within walking distance"],
        use: "Три предлога времени: within three hours (максимум за три часа), in three hours (ровно через три часа), for three hours (на протяжении трёх часов). within также про расстояние и границы: within budget, within reach.",
        use_en: "Three time prepositions: within three hours (three at most), in three hours (after exactly three), for three hours (duration). within also covers limits: within budget, within reach.",
        gap: { s: "The taxi came, and ___ three hours we were on the beach.", a: "within" },
      },
      {
        k: "at the crack of dawn", w: "at the crack of dawn", form: "idiom", ipa: "/kræk əv dɔːn/",
        ru: "с первыми лучами, ни свет ни заря",
        def: "very early in the morning, as soon as it gets light",
        reg: "informal",
        ex: ["We had to get up at the crack of dawn to catch the flight.", "The builders arrive at the crack of dawn."],
        use: "Разговорная идиома с оттенком жалобы. Формально — at first light / at daybreak. Противоположность — at dusk (в сумерках), in the dead of night (глубокой ночью).",
        use_en: "A conversational idiom with a hint of complaint. Formal: at first light / at daybreak. Opposites: at dusk, in the dead of night.",
        gap: { s: "We had to get up at the ___ of dawn to catch the flight.", a: "crack" },
      },
      {
        k: "I’d never have made it otherwise", w: "make it / otherwise", form: "idiom + grammar: third conditional", ipa: "",
        ru: "иначе я бы никак не успел / не добрался",
        def: "make it = arrive or succeed in time; otherwise = if not, in a different situation",
        reg: "informal",
        ex: ["Thanks for the lift — I'd never have made it otherwise.", "Hurry, or we won't make it."],
        use: "I'd = I would (не I had!) → would never have made — третий тип условного, условие спрятано в otherwise. make it — успеть/добраться/пробиться: make it to the meeting, make it big (стать звездой).",
        use_en: "I'd = I would (not I had!) → would never have made — a third conditional whose if-clause is hidden in otherwise. make it = arrive / succeed: make it to the meeting, make it big.",
        gap: { s: "Thanks for the lift — I'd never have ___ it otherwise.", a: "made" },
      },
      {
        k: "I was dreading", w: "dread (doing something)", form: "verb", ipa: "/dred/",
        ru: "страшиться (предстоящего), с ужасом ждать",
        def: "to feel very worried about something that is going to happen",
        reg: "neutral",
        ex: ["I was dreading the eight-hour coach journey.", "I dread to think what it cost."],
        use: "Только про будущее: dread + -ing / dread the thought of. Пауков не dread, их be scared of / fear. Устойчивое: I dread to think… — страшно подумать.",
        use_en: "Only about the future: dread + -ing / dread the thought of. You don't dread spiders — you are scared of them. Set phrase: I dread to think….",
        gap: { s: "I was ___ the eight-hour coach journey.", a: "dreading" },
      },
      {
        k: "had been pestering me", w: "pester somebody (to do)", form: "verb · past perfect continuous", ipa: "/ˈpestə/",
        ru: "доставать, приставать с просьбами",
        def: "to annoy someone by asking for something again and again",
        reg: "informal",
        ex: ["The kids had been pestering me for weeks to take them to the water park.", "Stop pestering your sister."],
        use: "Past perfect continuous (had been pestering) — процесс тянулся долго ДО другого события в прошлом. Шкала: bother (мягко) → pester (настойчиво, надоедливо) → harass (серьёзно, вплоть до юридического).",
        use_en: "Past perfect continuous (had been pestering) — an activity that went on for a long time before another past event. Scale: bother (mild) → pester (persistent, annoying) → harass (serious, potentially legal).",
        gap: { s: "The kids had been ___ me for weeks to take them to the water park.", a: "pestering" },
      },
      {
        k: "getaway", w: "getaway", form: "noun", ipa: "/ˈɡetəweɪ/",
        ru: "короткий отпуск, побег от рутины; (другое) бегство с места преступления",
        def: "a short holiday; also an escape after a crime (a getaway car)",
        reg: "informal · marketing",
        ex: ["A weekend getaway to the coast was exactly what we needed.", "The robbers' getaway car was found abandoned."],
        use: "Слово из рекламы турфирм: a romantic / weekend / city getaway. Второе значение — криминальное: make a getaway, getaway driver. Глагол пишется раздельно: get away — сбежать, вырваться.",
        use_en: "Travel-brochure word: a romantic / weekend / city getaway. Second meaning is criminal: make a getaway, getaway driver. The verb is two words: get away.",
        gap: { s: "A weekend ___ to the coast was exactly what we needed.", a: "getaway" },
      },
      {
        k: "we did have to chip in with the washing up", w: "chip in (with) / the washing up", form: "phrasal verb + emphatic did", ipa: "/tʃɪp/",
        ru: "внести свою долю (деньгами или помощью); washing up — мытьё посуды (BrE)",
        def: "chip in = contribute money or help; the washing up = the dirty dishes (BrE)",
        reg: "informal · BrE",
        ex: ["Everyone had to chip in with the cooking.", "We all chipped in for a present. / Whose turn is it to do the washing up?"],
        use: "did have to — эмфатическое did: «пришлось-таки». chip in for (деньгами) / with (помощью) / chip in — вставить реплику. AmE: do the dishes вместо do the washing up.",
        use_en: "did have to — emphatic did: «we DID have to». chip in for (money) / with (help); also chip in = add a remark. AmE says do the dishes rather than do the washing up.",
        gap: { s: "Everyone had to ___ in with the cooking and cleaning.", a: "chip" },
      },
      {
        k: "plenty", w: "plenty (of)", form: "pronoun / determiner", ipa: "/ˈplenti/",
        ru: "много, вдоволь, с избытком",
        def: "a large amount, as much as or more than is needed",
        reg: "neutral",
        ex: ["There was plenty of time to explore the old town.", "— More tea? — No thanks, that's plenty."],
        use: "plenty OF + существительное (и исчисляемое, и нет): plenty of time / plenty of chairs. Само по себе plenty — местоимение: That's plenty. Оттенок «хватает с запасом», в отличие от нейтрального many / much. Ловушка: plenty time ✗.",
        use_en: "plenty OF + noun (countable or not): plenty of time / plenty of chairs. Alone it is a pronoun: That's plenty. Implies «enough and more», unlike neutral many / much. Trap: plenty time ✗.",
        gap: { s: "There was ___ of time to explore the old town.", a: "plenty" },
      },
      {
        k: "grindstone", w: "(back to) the grindstone", form: "noun · idiom", ipa: "/ˈɡraɪndstəʊn/",
        ru: "точильный камень; идиома — вкалывать без передышки; back to the grindstone — снова за работу",
        def: "a stone for sharpening tools; keep your nose to the grindstone = work hard without a break",
        reg: "informal · idiom",
        ex: ["Holiday's over — back to the grindstone on Monday.", "She kept her nose to the grindstone all term."],
        use: "После отпуска: Back to the grindstone! — с усталой самоиронией. Родственное: the daily grind — рутина; grind (v) — молоть, точить; a grind — нудная тяжёлая работа.",
        use_en: "After a holiday: Back to the grindstone! — tired self-mockery. Related: the daily grind (routine); grind (v) = to mill or sharpen; a grind = tedious hard work.",
        gap: { s: "Holiday's over — back to the ___ on Monday.", a: "grindstone" },
      },
    ],
  },
  {
    id: "s5",
    title: "Section 5 · Суматошная неделя и годовой review",
    title_en: "Section 5 · A hectic week and the annual review",
    theme: "Работа, деньги, погода: нейтральный и деловой регистр",
    theme_en: "Work, money, weather: neutral and business register",
    story:
      "It had been a [[hectic]] week, and Friday brought the [[tricky moment]]: my annual review. My [[intention]] was simple — to [[preserve]] my role and, if the market's [[buoyancy]] allowed, to [[increase amount 2 percent|increase the amount by 2 percent]] or more. The manager [[acknowledged]] the [[tremendous]] effort I had put in, went [[thorougthly|thoroughly]] through my [[prefferences|preferences]] for next year and then, [[apropos]] of nothing, asked about my [[demand]] for a bigger monitor. I could hardly [[Conceive|conceive]] of a stranger question. Still, the deal [[is sealed]]: [[remuneration]] up, a new [[dimension]] to my job, and a promise to [[enlarge]] the team and change its [[makeup]]. HR will [[enforce]] the new policy from January. All that patience bore [[fruit]]. Walking home through heavy [[precipitation]], I stepped straight into a [[puddle]] and decided that whoever had forecast 'light rain' was a bit of a [[git]].",
    words: [
      {
        k: "tricky moment", w: "tricky", form: "adjective", ipa: "/ˈtrɪki/",
        ru: "непростой, каверзный, требующий осторожности (момент, вопрос, ситуация)",
        def: "difficult to deal with and needing care or skill; likely to cause problems",
        reg: "neutral · informal",
        ex: ["Friday brought a tricky moment: the annual review.", "That's a tricky question — give me a second."],
        use: "a tricky question / situation / bit; It's tricky. Ловушка: tricky ≠ «хитрый человек» (это cunning / sly) и ≠ «трюковый». Про человека tricky говорят редко и значит «ненадёжный, с подвохом».",
        use_en: "a tricky question / situation / bit; It's tricky. Trap: tricky is not «cunning» (a person) and not «trick-related». Applied to a person it means «not to be trusted».",
        gap: { s: "Negotiating salary with a friend is always a bit ___.", a: "tricky" },
      },
      {
        k: "hectic", w: "hectic", form: "adjective", ipa: "/ˈhektɪk/",
        ru: "суматошный, лихорадочный (о дне, графике, периоде)",
        def: "full of frantic activity; extremely busy and rushed",
        reg: "neutral · informal",
        ex: ["It had been a hectic week.", "a hectic schedule; things are pretty hectic at work right now"],
        use: "Про время и обстановку, не про человека: a hectic day / week / schedule / pace. Ловушка: русское «занятой человек» — busy, не hectic. Отвечая на How are things? — Hectic! звучит естественно.",
        use_en: "About periods and situations, not people: a hectic day / week / schedule / pace. Trap: a busy person is busy, not hectic. As a reply to How are things? — Hectic! sounds natural.",
        gap: { s: "December is always ___ in retail — twelve-hour shifts and no days off.", a: "hectic" },
      },
      {
        k: "intention", w: "intention (of doing / to do)", form: "noun", ipa: "/ɪnˈtenʃən/",
        ru: "намерение",
        def: "something you plan or mean to do",
        reg: "neutral · formal",
        ex: ["My intention was to preserve my role.", "I have no intention of resigning."],
        use: "have no intention OF doing (самая частая конструкция); intention TO do; with the intention of. Ловушка: «нечаянно» — unintentionally / by accident; «специально» — intentionally / on purpose. Глагол — intend to.",
        use_en: "have no intention OF doing (the most common pattern); intention TO do; with the intention of. Trap: «by accident» is unintentionally; «on purpose» is intentionally. Verb: intend to.",
        gap: { s: "I have no ___ of working through another weekend.", a: "intention" },
      },
      {
        k: "preserve", w: "preserve", form: "verb (also noun)", ipa: "/prɪˈzɜːv/",
        ru: "сохранить (в прежнем состоянии), уберечь; (сущ.) варенье; заповедник",
        def: "to keep something as it is, protect it from change or damage; (noun) jam; a protected area",
        reg: "formal · neutral",
        ex: ["to preserve my role and the team's trust", "The building has been carefully preserved. / strawberry preserve; a nature preserve"],
        use: "Три родственника: preserve — сохранить как есть (традиции, здание, отношения); conserve — беречь ресурс (energy, water); save — общее «сберечь». Ловушка: «сохранить файл» — save, не preserve.",
        use_en: "Three cousins: preserve — keep as it is (traditions, a building, a relationship); conserve — use a resource sparingly (energy, water); save — the general word. Trap: you save a file, you don't preserve it.",
        gap: { s: "The museum's job is to ___ the manuscripts for future generations.", a: "preserve" },
      },
      {
        k: "Conceive", w: "conceive (of)", form: "verb", ipa: "/kənˈsiːv/",
        ru: "представить себе, вообразить; задумать (план); зачать (ребёнка)",
        def: "to imagine or form an idea of something; to devise a plan; to become pregnant",
        reg: "formal",
        ex: ["I could hardly conceive of a stranger question.", "The project was conceived as a two-year experiment."],
        use: "conceive OF something (представить), conceive a plan / an idea (задумать), conceive a child. Обычно в отрицании: I can't conceive of… Ловушка: не путать с concede (уступить, признать) и conceit (самомнение).",
        use_en: "conceive OF something (imagine), conceive a plan / an idea (devise), conceive a child. Mostly in the negative: I can't conceive of…. Trap: not concede (admit, give in) or conceit (vanity).",
        gap: { s: "It is hard to ___ of a world without the internet.", a: "conceive" },
      },
      {
        k: "tremendous", w: "tremendous", form: "adjective", ipa: "/trəˈmendəs/",
        ru: "огромный, колоссальный; потрясающий",
        def: "very great in amount, scale or intensity; extremely good",
        reg: "neutral · emphatic",
        ex: ["The manager acknowledged the tremendous effort I had put in.", "a tremendous success / amount of work / pressure"],
        use: "Усилитель для количеств и усилий: a tremendous amount / effort / help; также «отличный»: You've been tremendous. Ловушка: этимологически от tremble (дрожать), но сейчас никакого «ужасного» оттенка нет — это положительное или нейтральное слово.",
        use_en: "An intensifier for amounts and effort: a tremendous amount / effort / help; also «excellent»: You've been tremendous. Trap: despite the tremble root, there is no «terrible» shade left — it is positive or neutral.",
        gap: { s: "Moving the whole team to a new office took a ___ amount of planning.", a: "tremendous" },
      },
      {
        k: "buoyancy", w: "buoyancy", form: "noun", ipa: "/ˈbɔɪənsi/",
        ru: "плавучесть; (перен.) подъём, оживление (рынка); жизнерадостность",
        def: "the ability to float; (figurative) a lively, rising state of a market or mood",
        reg: "formal · business",
        ex: ["if the market's buoyancy allowed", "a buoyant economy; she has a natural buoyancy that lifts the whole team"],
        use: "В деловой речи чаще прилагательное: a buoyant market / demand / mood — на подъёме. Произношение — ловушка: /ˈbɔɪ-ənsi/, «бой-энси», не «бу-». Буква u не читается.",
        use_en: "Business English mostly uses the adjective: a buoyant market / demand / mood — rising, lively. Pronunciation trap: /ˈbɔɪ-ənsi/ — the u is silent.",
        gap: { s: "The ___ of the housing market surprised even the optimists.", a: "buoyancy" },
      },
      {
        k: "apropos", w: "apropos (of)", form: "adverb / preposition", ipa: "/ˌæprəˈpəʊ/",
        ru: "кстати, по поводу; apropos of nothing — ни с того ни с сего",
        def: "with reference to; apropos of nothing = without any connection to what was said before",
        reg: "formal · slightly literary",
        ex: ["Then, apropos of nothing, he asked about my monitor.", "Apropos of your email, the meeting is moved to Monday."],
        use: "Живёт в основном во фразе apropos of nothing («вдруг, без связи») и в formal apropos of X (по поводу X). Из французского, s на конце не читается: /ˌæprəˈpəʊ/. В обычной речи — by the way, speaking of which.",
        use_en: "Lives mainly in apropos of nothing («out of the blue») and formal apropos of X (regarding X). French: the final s is silent, /ˌæprəˈpəʊ/. Everyday alternatives: by the way, speaking of which.",
        gap: { s: "___ of nothing, she asked whether I had ever been to Lisbon.", a: "Apropos" },
      },
      {
        k: "git", w: "git", form: "noun · BrE slang (also the version-control tool)", ipa: "/ɡɪt/",
        ru: "придурок, зануда, противный тип (мягкое британское ругательство)",
        def: "(BrE, informal, mildly rude) a stupid or unpleasant person",
        reg: "slang · BrE",
        ex: ["Whoever forecast 'light rain' was a bit of a git.", "Don't be such a git — give him his phone back."],
        use: "Мягкое ругательство, чаще шутливое между своими: a miserable / stupid / old git. Для разработчика — та же буква, что система контроля версий: Линус Торвальдс сам говорил, что назвал Git так, потому что «I'm an egotistical bastard, and I name all my projects after myself». В рабочей переписке слово только про инструмент.",
        use_en: "A mild insult, often jokey among friends: a miserable / stupid / old git. For a developer it is also the version-control tool — Linus Torvalds joked that he named it after himself. In work chat the word means only the tool.",
        gap: { s: "He took the last biscuit and laughed — what a ___.", a: "git" },
      },
      {
        k: "is sealed", w: "be sealed (the deal is sealed)", form: "verb · passive", ipa: "/siːld/",
        ru: "решено окончательно, скреплено (о сделке, судьбе); запечатано",
        def: "settled finally and definitely (a deal, someone's fate); physically closed tight",
        reg: "neutral · idiomatic",
        ex: ["Still, the deal is sealed: remuneration up.", "Her fate was sealed the moment she signed. / a sealed envelope"],
        use: "seal the deal — довести сделку до конца (и flirt-версия: закрепить успех); sb's fate is sealed — участь решена; sealed envelope / jar. Ловушка: «печать» на документе — stamp; seal — это либо восковая печать, либо герметичность, либо тюлень.",
        use_en: "seal the deal — close it for good; sb's fate is sealed — decided beyond change; a sealed envelope / jar. Trap: an office stamp is a stamp; seal is a wax seal, an airtight closure, or the animal.",
        gap: { s: "Once the contract was signed, the deal was ___.", a: "sealed" },
      },
      {
        k: "acknowledged", w: "acknowledge", form: "verb", ipa: "/əkˈnɒlɪdʒ/",
        ru: "признать (факт, заслугу); подтвердить получение; поблагодарить за вклад",
        def: "to accept that something is true; to confirm you have received something; to express thanks for",
        reg: "formal · neutral",
        ex: ["The manager acknowledged the tremendous effort I had put in.", "Please acknowledge receipt of this email. / an acknowledged expert"],
        use: "Три рабочих значения: acknowledge a mistake / the problem (признать), acknowledge receipt (подтвердить получение), acknowledge sb's help (отметить вклад). Произношение: k не читается, /əkˈnɒlɪdʒ/. an acknowledged expert — общепризнанный.",
        use_en: "Three work meanings: acknowledge a mistake / the problem (admit), acknowledge receipt (confirm), acknowledge sb's help (give credit). Pronunciation: the k is silent, /əkˈnɒlɪdʒ/. an acknowledged expert — recognised by everyone.",
        gap: { s: "The airline finally ___ that the delay was its own fault.", a: "acknowledged" },
      },
      {
        k: "makeup", w: "makeup / make-up", form: "noun", ipa: "/ˈmeɪkʌp/",
        ru: "состав, структура (команды, населения); макияж; (make up — глагол: составлять, мириться, выдумывать)",
        def: "the way something is composed (the makeup of a team); cosmetics",
        reg: "neutral",
        ex: ["a promise to enlarge the team and change its makeup", "the ethnic makeup of the city; she wears very little makeup"],
        use: "Существительное — одно слово (makeup / make-up): состав или косметика. Глагол — раздельно и многозначен: make up a team (составлять), make up a story (выдумать), make up with sb (помириться), make up for (компенсировать). Ловушка: «косметика вообще» — cosmetics, makeup — то, что нанесено на лицо.",
        use_en: "The noun is one word (makeup / make-up): composition or cosmetics. The verb is two words and busy: make up a team (form), make up a story (invent), make up with sb (reconcile), make up for (compensate). Trap: cosmetics is the product category; makeup is what's on the face.",
        gap: { s: "The survey looked at the age ___ of the workforce.", a: "makeup" },
      },
      {
        k: "precipitation", w: "precipitation", form: "noun · uncountable", ipa: "/prɪˌsɪpɪˈteɪʃən/",
        ru: "осадки (дождь, снег, град) — термин прогнозов",
        def: "rain, snow, sleet or hail falling from the sky (weather-forecast term)",
        reg: "formal · technical",
        ex: ["Walking home through heavy precipitation, I stepped into a puddle.", "The forecast gives a 60 percent chance of precipitation."],
        use: "Слово из прогноза погоды и науки; в разговоре скажут rain / snow / it's pouring. Только единственное число (precipitations ✗). Ловушка: precipitate (глагол) — ускорить, спровоцировать (precipitate a crisis); precipitous — обрывистый, резкий.",
        use_en: "A forecast / science word; in conversation say rain / snow / it's pouring. Uncountable (precipitations ✗). Trap: precipitate (verb) = to trigger or hasten (precipitate a crisis); precipitous = steep, sudden.",
        gap: { s: "Tomorrow: cloudy, with a 40 percent chance of ___.", a: "precipitation" },
      },
      {
        k: "prefferences", w: "preferences (spelling: one f, one r)", form: "noun · plural", ipa: "/ˈprefərənsɪz/",
        ru: "предпочтения; в интерфейсах — настройки",
        def: "the things you like better than others; in software, settings",
        reg: "neutral",
        ex: ["He went through my preferences for next year.", "Open Preferences and change the font size. / a preference FOR tea over coffee"],
        use: "Правописание: pre-fer-ence — одна f, одна r (в списке была опечатка). Конструкции: a preference FOR X (over Y); in order of preference; I'd prefer to / I'd rather. Ловушка: preferably — «желательно», а не «предпочтительнее».",
        use_en: "Spelling: pre-fer-ence — one f, one r (the list had a typo). Patterns: a preference FOR X (over Y); in order of preference; I'd prefer to / I'd rather. Trap: preferably means «ideally», not «more preferable».",
        gap: { s: "List the three cities in order of ___.", a: "preference" },
      },
      {
        k: "remuneration", w: "remuneration", form: "noun · uncountable", ipa: "/rɪˌmjuːnəˈreɪʃən/",
        ru: "вознаграждение, оплата труда (формально, в контрактах и HR)",
        def: "payment for work or services (formal, HR / legal)",
        reg: "formal · HR",
        ex: ["Remuneration up, a new dimension to my job.", "The remuneration package includes a bonus and share options."],
        use: "Слово HR-документов и контрактов: remuneration package / committee / policy. В разговоре — pay, salary, compensation (AmE). Ловушка на произношение: re-MU-ne-ra-tion, часто переставляют буквы в «renumeration» — это ошибка.",
        use_en: "HR-and-contract word: remuneration package / committee / policy. In speech: pay, salary, compensation (AmE). Trap: re-MU-ne-ra-tion — the letters often get swapped into «renumeration», which is wrong.",
        gap: { s: "The board reviews executive ___ once a year.", a: "remuneration" },
      },
      {
        k: "increase amount 2 percent", w: "increase (something) BY 2 percent", form: "grammar: increase by / to", ipa: "",
        ru: "увеличить сумму НА 2 процента",
        def: "increase BY = the size of the change; increase TO = the new level",
        reg: "neutral · business",
        ex: ["to increase the amount by 2 percent", "Sales rose by 5% to 2.1 million. / Prices went up 3 percent."],
        use: "Ловушка из списка — пропущены предлог и артикль: increase amount 2 percent ✗ → increase THE amount BY 2 percent. BY — на сколько, TO — до какого уровня; a 2 percent increase IN salary (в чём). Ударение: глагол in-CREASE, существительное IN-crease.",
        use_en: "The list item drops the preposition and article: increase amount 2 percent ✗ → increase THE amount BY 2 percent. BY = how much, TO = the new level; a 2 percent increase IN salary. Stress: verb in-CREASE, noun IN-crease.",
        gap: { s: "Rent went up ___ two percent, from 500 to 510.", a: "by" },
      },
      {
        k: "dimension", w: "dimension", form: "noun", ipa: "/daɪˈmenʃən/",
        ru: "измерение, сторона, аспект (проблемы); (мн.) размеры",
        def: "an aspect or side of something; (plural) measurements — length, width, height",
        reg: "neutral · formal",
        ex: ["a new dimension to my job", "The dimensions of the box are 30 by 20 by 10 cm. / The scandal took on a political dimension."],
        use: "add a new dimension TO; take on a dimension; the social / ethical dimension of X. Размеры — dimensions во множественном. Ловушка: «размер одежды» — size, не dimension; «объём» — volume.",
        use_en: "add a new dimension TO; take on a dimension; the social / ethical dimension of X. Measurements are plural dimensions. Trap: clothes have a size, not a dimension; capacity is volume.",
        gap: { s: "Remote work adds a whole new ___ to team management.", a: "dimension" },
      },
      {
        k: "puddle", w: "puddle", form: "noun", ipa: "/ˈpʌdl/",
        ru: "лужа",
        def: "a small pool of rainwater or other liquid on the ground",
        reg: "neutral",
        ex: ["I stepped straight into a puddle.", "The kids jumped in every puddle on the way home."],
        use: "step in / jump in / splash through a puddle. Ловушка размера: puddle — маленькая лужа после дождя; pool — водоём или бассейн; pond — пруд. Не путать с paddle (весло / шлёпать по воде).",
        use_en: "step in / jump in / splash through a puddle. Size trap: a puddle is small, a pool is a body of water or a swimming pool, a pond is a small lake. Not paddle (an oar / to wade).",
        gap: { s: "After the storm the car park was one giant ___.", a: "puddle" },
      },
      {
        k: "thorougthly", w: "thoroughly (spelling: thor-ough-ly)", form: "adverb", ipa: "/ˈθʌrəli/",
        ru: "тщательно, досконально; совершенно (thoroughly enjoyed)",
        def: "carefully and completely; (as an intensifier) very much",
        reg: "neutral",
        ex: ["He went thoroughly through my preferences.", "Wash your hands thoroughly. / I thoroughly enjoyed the trip."],
        use: "Правописание: thorough + ly, без t в середине (в списке опечатка). Произношение /ˈθʌrəli/ — «ТHА-рэ-ли», gh не читается. Ловушка: thorough (тщательный) ≠ through (сквозь) ≠ though (хотя) ≠ thought (мысль).",
        use_en: "Spelling: thorough + ly, no extra t (the list had a typo). Pronounced /ˈθʌrəli/, the gh is silent. Trap: thorough (careful) ≠ through ≠ though ≠ thought.",
        gap: { s: "Read the contract ___ before you sign anything.", a: "thoroughly" },
      },
      {
        k: "demand", w: "demand", form: "noun / verb", ipa: "/dɪˈmɑːnd/",
        ru: "требование, спрос; (глагол) требовать",
        def: "a firm request; the amount people want to buy; (verb) to ask for firmly",
        reg: "neutral · business",
        ex: ["my demand for a bigger monitor", "Demand for electric cars is growing. / The job demands patience. / in demand"],
        use: "Существительное: demand FOR (спрос на); in demand (востребованный); supply and demand. Глагол — жёсткий: demand that sb (should) do; demand an apology. Ловушка: русское «спросить» — ask; demand — «требовать», в письме клиенту прозвучит как ультиматум.",
        use_en: "Noun: demand FOR (market demand); in demand; supply and demand. The verb is forceful: demand that sb (should) do; demand an apology. Trap: to «ask» is ask; demand in an email to a client reads as an ultimatum.",
        gap: { s: "There is huge ___ for Python developers right now.", a: "demand" },
      },
      {
        k: "fruit", w: "fruit (usually uncountable) · bear fruit", form: "noun · idiom", ipa: "/fruːt/",
        ru: "фрукты (неисчисляемое); плоды (перен.); bear fruit — принести плоды",
        def: "the edible part of plants (uncountable as a category); result (the fruits of your labour); bear fruit = produce results",
        reg: "neutral",
        ex: ["All that patience bore fruit.", "Eat more fruit and vegetables. / the fruits of ten years' work"],
        use: "Ловушка числа: fruit как категория — без -s (I eat a lot of fruit; fruits ✗). fruits — только про разные виды (tropical fruits) или в идиоме the fruits of X (плоды труда). bear fruit — дать результат: The plan finally bore fruit.",
        use_en: "Number trap: fruit as a category takes no -s (I eat a lot of fruit; fruits ✗). fruits only for different kinds (tropical fruits) or in the fruits of X. bear fruit = produce results: The plan finally bore fruit.",
        gap: { s: "Months of quiet lobbying finally bore ___.", a: "fruit" },
      },
      {
        k: "enforce", w: "enforce (a rule)", form: "verb", ipa: "/ɪnˈfɔːs/",
        ru: "обеспечить соблюдение (закона, правила); принудительно применять",
        def: "to make people obey a law or rule",
        reg: "formal · legal",
        ex: ["HR will enforce the new policy from January.", "The speed limit is rarely enforced here."],
        use: "Объект — правило, закон, договор: enforce a law / a policy / a contract / a ban. Ловушка: enforce ≠ force. Заставить человека — force sb TO do; enforce — заставить правило работать. Существительное: enforcement (law enforcement — правоохранительные органы).",
        use_en: "The object is a rule, law or contract: enforce a law / a policy / a contract / a ban. Trap: enforce ≠ force. You force a person TO do something; you enforce a rule. Noun: enforcement (law enforcement).",
        gap: { s: "A rule nobody is willing to ___ is just a suggestion.", a: "enforce" },
      },
      {
        k: "enlarge", w: "enlarge", form: "verb", ipa: "/ɪnˈlɑːdʒ/",
        ru: "увеличить (в размере), расширить; enlarge on — развить мысль",
        def: "to make bigger; enlarge on / upon = to say more about",
        reg: "neutral · formal",
        ex: ["a promise to enlarge the team", "Click to enlarge the image. / Could you enlarge on that point?"],
        use: "Про физический размер и объём: enlarge a photo / a building / the team. Ловушка выбора: увеличить число — increase; расширить бизнес / ассортимент — expand; растянуть срок — extend. enlarge on a point — рассказать подробнее (formal).",
        use_en: "Physical size and scope: enlarge a photo / a building / the team. Choice trap: a number is increased; a business or range is expanded; a deadline is extended. enlarge on a point = elaborate (formal).",
        gap: { s: "Click the thumbnail to ___ the picture.", a: "enlarge" },
      },
    ],
  },
];

export const ALL_WORDS: UnitWord[] = UNITS.flatMap((u) => u.words.map((w) => ({ ...w, unit: u.id })));
