// Словарь по секциям курса английского. Каждая секция (unit) = список слов из
// учебника + связный текст (story), где эти слова встречаются в контексте.
// Слово: { k: ключ ровно как в списке из курса, w: словарная форма, form: часть
// речи / конструкция, ipa?, ru, def (EN-определение), reg: регистр,
// ex: [2 примера], use / use_en: где и как употреблять + типичная ловушка,
// gap: { s: предложение с ___, a: ответ в нужной форме } — для режима «Пропуски».
// В story слова размечены как [[k]] или [[k|как показать]] (другой регистр) —
// ключ должен совпадать с k буква в букву.
// Новые секции — добавлять в конец UNITS; проверка: npm test (english.test.js).

export const UNITS = [
  {
    id: "s2",
    title: "Section 2 · Голос, которого не было раньше",
    title_en: "Section 2 · A voice unlike anything before",
    theme: "Биография певицы: формальный, журналистский регистр",
    theme_en: "A singer's biography: formal, journalistic register",
    story:
      "Born in the early 1900s, she became a [[renowned]] contralto and one of the most [[prominent]] Black artists of her century. [[Indeed]], critics wrote that her [[powerful voice was unlike anything that had come before]]. She [[dropped out]] of school to help her family. She [[had hoped]] to enter a music academy, but in a [[race-conscious culture]] she was turned away at the door. During the war she toured Europe, and it was [[when she was entertaining soldiers and prisoners of war]] that her fame spread. [[In the rare instances]] when she sang at home, audiences were [[segregated in terms of colour]], and she kept a single white gown [[for such occasions]]. Some of her contemporaries achieved a [[high level of notoriety]] through scandal; she chose dignity instead. [[She paved the way]] for every Black singer who followed.",
    words: [
      {
        k: "renowned", w: "renowned", form: "adjective", ipa: "/rɪˈnaʊnd/",
        ru: "прославленный, знаменитый (за что-то конкретное и хорошее)",
        def: "famous and admired for a particular quality, skill or achievement",
        reg: "formal · written",
        ex: ["a renowned soprano", "The region is renowned for its wine."],
        use: "Всегда с чем-то положительным: renowned FOR (за что) / renowned AS (в качестве кого). Звучит книжно — в живой речи скажут famous. Ловушка: notorious — тоже «известный», но дурной славой.",
        use_en: "Always positive: renowned FOR something / renowned AS someone. Bookish — in speech people say famous. Trap: notorious also means «well-known», but for something bad.",
        gap: { s: "The city is ___ for its Gothic architecture.", a: "renowned" },
      },
      {
        k: "prominent", w: "prominent", form: "adjective", ipa: "/ˈprɒmɪnənt/",
        ru: "видный, заметный, занимающий важное положение; физически выступающий",
        def: "important and well known within a field; also sticking out so as to be easily seen",
        reg: "formal · neutral",
        ex: ["a prominent lawyer / politician / member of the community", "She played a prominent role in the campaign."],
        use: "Не «знаменитый», а «на видном месте»: prominent figure, prominent role, prominent position. Второе значение — физическое: prominent cheekbones, a prominent nose, displayed in a prominent place.",
        use_en: "Not «famous» but «in a visible position»: a prominent figure / role / position. Second meaning is physical: prominent cheekbones, displayed in a prominent place.",
        gap: { s: "She became a ___ figure in the civil rights movement.", a: "prominent" },
      },
      {
        k: "Indeed", w: "indeed", form: "adverb", ipa: "/ɪnˈdiːd/",
        ru: "действительно; более того, в самом деле",
        def: "used to emphasise or confirm a statement, or to add a stronger point",
        reg: "formal · written",
        ex: ["The tour was a success. Indeed, every show sold out.", "It was very cold indeed."],
        use: "Три роли: 1) в начале предложения — усиливает предыдущую мысль («более того»); 2) после very + прилагательное (BrE): very kind indeed; 3) ответ «Indeed.» — «именно». Ловушка: русскоязычные ставят Indeed в каждое второе предложение как «действительно» — в тексте один-два раза максимум, иначе звучит напыщенно или иронично.",
        use_en: "Three roles: 1) sentence-initial to strengthen the previous point («what is more»); 2) after very + adjective (BrE): very kind indeed; 3) as a one-word reply «Indeed.» Trap: overusing it as a translation of «действительно» sounds pompous or sarcastic — once or twice per text.",
        gap: { s: "The concert was a triumph. ___, it sold out within an hour.", a: "Indeed" },
      },
      {
        k: "dropped out", w: "drop out (of)", form: "phrasal verb", ipa: "/drɒp aʊt/",
        ru: "бросить (учёбу, курс, гонку) до завершения",
        def: "to leave school, university, a course or a competition before finishing it",
        reg: "neutral",
        ex: ["He dropped out of university in his second year.", "Two runners dropped out of the race."],
        use: "Сам ушёл: drop out OF school / college / the race. Существительное: a college dropout. Ловушка: если отчислили — expelled (школа) / kicked out (разг.), не dropped out.",
        use_en: "Leaving by your own choice: drop out OF school / college / the race. Noun: a college dropout. Trap: if the school removed you, that is expelled / kicked out, not dropped out.",
        gap: { s: "He ___ of college after one year to start a band.", a: "dropped out" },
      },
      {
        k: "had hoped", w: "had hoped (to)", form: "grammar: past perfect", ipa: "",
        ru: "надеялся(ась)… но не вышло",
        def: "past perfect of hope: a hope in the past that was NOT fulfilled",
        reg: "neutral",
        ex: ["She had hoped to study in Vienna, but the war changed everything.", "We had hoped for better weather."],
        use: "Past perfect с hope / expect / intend / mean / want = нереализованное намерение: I had hoped to call you — надеялся, но не позвонил. Ловушка: I hoped to… — нейтрально, результат не ясен; I had hoped to… — слушатель уже знает, что не получилось.",
        use_en: "Past perfect with hope / expect / intend / mean / want signals an unfulfilled intention: I had hoped to call you — but didn't. Trap: I hoped to… is neutral; I had hoped to… tells the listener it didn't happen.",
        gap: { s: "We ___ to arrive before dark, but the train was delayed for hours.", a: "had hoped" },
      },
      {
        k: "race-conscious culture", w: "race-conscious", form: "compound adjective", ipa: "",
        ru: "общество, где расовая принадлежность постоянно замечается и влияет на отношение",
        def: "(a culture) in which people are constantly aware of race and treat others according to it",
        reg: "formal · academic",
        ex: ["Growing up in a race-conscious culture, she learned early which doors were closed.", "health-conscious consumers, a price-conscious buyer"],
        use: "Модель X-conscious = «обращающий внимание на X»: health-conscious, price-conscious, fashion-conscious, class-conscious (BrE, о классах). Ловушка: conscious (осознающий) ≠ conscientious (добросовестный) ≠ self-conscious (стесняющийся).",
        use_en: "Pattern X-conscious = «paying attention to X»: health-conscious, price-conscious, fashion-conscious, class-conscious. Trap: conscious (aware) ≠ conscientious (diligent) ≠ self-conscious (embarrassed, shy).",
        gap: { s: "Shoppers have become far more price-___ since the crisis.", a: "conscious" },
      },
      {
        k: "when she was entertaining soldiers and prisoners of war", w: "entertain (an audience)", form: "verb · past continuous", ipa: "/ˌentəˈteɪn/",
        ru: "развлекать, выступать перед публикой; принимать гостей",
        def: "to perform for people and amuse them; also to have guests at your home",
        reg: "neutral",
        ex: ["She spent the war entertaining the troops.", "We're entertaining friends on Saturday."],
        use: "Past continuous (was entertaining) — фон, на котором случилось главное событие. Prisoners of war (POWs) — военнопленные. Ловушка: entertain an idea / a proposal — формальное «рассматривать, допускать», не «развлекать».",
        use_en: "Past continuous (was entertaining) sets the background against which the main event happens. Prisoners of war (POWs). Trap: entertain an idea / a proposal is formal for «consider», nothing to do with amusement.",
        gap: { s: "During the war she toured Europe, ___ the troops.", a: "entertaining" },
      },
      {
        k: "In the rare instances", w: "in the rare instances (when)", form: "noun phrase", ipa: "/ˈɪnstənsɪz/",
        ru: "в тех редких случаях, когда",
        def: "on the few occasions when something happens",
        reg: "formal · written",
        ex: ["In the rare instances when she performed at home, the hall was packed.", "In this instance, the rule does not apply."],
        use: "instance = конкретный случай/пример явления (for instance — например; in this instance — в данном случае). Ловушка: occasion — событие/момент («по такому случаю»), case — ситуация/дело; instance — один из повторяющихся примеров.",
        use_en: "instance = a particular example of something happening (for instance; in this instance). Trap: occasion is an event or moment, case is a situation; instance is one example among repeated ones.",
        gap: { s: "In the rare ___ when she was allowed on stage, the hall was full.", a: "instances" },
      },
      {
        k: "for such occasions", w: "occasion", form: "noun", ipa: "/əˈkeɪʒən/",
        ru: "особый случай, событие, торжество",
        def: "a special or particular event, or the time when it happens",
        reg: "neutral · formal",
        ex: ["She kept one gown for such occasions.", "a dress for a special occasion; rise to the occasion"],
        use: "on this occasion — в этот раз; on occasion — иногда; dress for the occasion; rise to the occasion — оказаться на высоте. Ловушка №1 русскоязычных: occasion ≠ «возможность» — I had an occasion to… ✗ → I had an opportunity / a chance to….",
        use_en: "on this occasion; on occasion (= sometimes); dress for the occasion; rise to the occasion. Trap for Russian speakers: occasion is NOT «opportunity» — I had an occasion to… ✗ → I had a chance to….",
        gap: { s: "She kept one white gown for such ___.", a: "occasions" },
      },
      {
        k: "segregated in terms of colour", w: "segregated / in terms of", form: "adjective + preposition phrase", ipa: "/ˈseɡrɪɡeɪtɪd/",
        ru: "разделённый по расовому признаку; in terms of — в отношении, с точки зрения",
        def: "kept apart by race (segregation); in terms of = with regard to a particular aspect",
        reg: "formal",
        ex: ["Audiences were segregated: Black listeners sat at the back.", "In terms of cost, the plan is fine; in terms of time, it isn't."],
        use: "segregate / segregation — про разделение групп людей (расовое, гендерное), не про «отделить файлы». in terms of — канцелярская связка, по возможности заменять: as regards, when it comes to. colour — британское написание (AmE color).",
        use_en: "segregate / segregation is about separating groups of people (by race, gender), not files. in terms of is bureaucratic filler — prefer when it comes to. colour is the British spelling (AmE color).",
        gap: { s: "Audiences were ___ : Black listeners had to sit at the back.", a: "segregated" },
      },
      {
        k: "high level of notoriety", w: "notoriety", form: "noun", ipa: "/ˌnəʊtəˈraɪəti/",
        ru: "дурная / скандальная известность",
        def: "the state of being famous for something bad or shocking",
        reg: "formal",
        ex: ["The club gained notoriety for its wild late-night shows.", "a notorious criminal"],
        use: "Почти всегда негативно или скандально: gain / achieve notoriety FOR. Прилагательное notorious — печально известный. Ловушка: использовать как красивый синоним fame — ошибка; о хорошем говорят fame, renown, recognition.",
        use_en: "Nearly always negative or scandalous: gain / achieve notoriety FOR. Adjective: notorious. Trap: using it as a fancy synonym of fame — for good things say fame, renown, recognition.",
        gap: { s: "The nightclub gained ___ for its wild late-night shows.", a: "notoriety" },
      },
      {
        k: "powerful voice was unlike anything that had come before", w: "unlike anything that had come before", form: "idiomatic phrase", ipa: "",
        ru: "ни на что прежнее не похожий",
        def: "completely new and different from everything earlier",
        reg: "journalistic · praising",
        ex: ["The album was unlike anything that had come before.", "a style like nothing before it"],
        use: "Формула для описания новизны: unlike + существительное (unlike anything / anyone). Past perfect had come before — «всё, что было ДО того момента». Ловушка: unlike — предлог, без than: unlike than ✗.",
        use_en: "A set formula for novelty: unlike + noun (unlike anything / anyone). Past perfect had come before = everything up to that moment. Trap: unlike is a preposition — no than after it.",
        gap: { s: "Her debut album was ___ anything that had come before.", a: "unlike" },
      },
      {
        k: "She paved the way", w: "pave the way (for)", form: "idiom", ipa: "/peɪv/",
        ru: "проложить путь, подготовить почву (для кого-то / чего-то)",
        def: "to make it easier for something to happen or for someone to follow later",
        reg: "neutral · journalistic",
        ex: ["Her victory paved the way for other women in the sport.", "The talks paved the way for a peace deal."],
        use: "pave the way FOR (не to). Буквально pave — мостить (paved road, pavement — тротуар BrE). Близкие: open the door for, set the stage for, be a trailblazer.",
        use_en: "pave the way FOR (not to). Literally, pave = cover with stones (paved road; pavement = BrE sidewalk). Related: open the door for, set the stage for, be a trailblazer.",
        gap: { s: "Her victory ___ the way for other women in the sport.", a: "paved" },
      },
    ],
  },
  {
    id: "s3",
    title: "Section 3 · За кулисами детского шоу",
    title_en: "Section 3 · Backstage at a kids' show",
    theme: "Интервью с артистом: разговорный британский, сленг",
    theme_en: "An interview with a performer: spoken British English, slang",
    story:
      "[[I’m backstage at]] a small theatre, talking to a children's entertainer. Has the job changed over twenty years? '[[It certainly has]]. There's more [[rowdiness]] now — kids arrive high on sugar and phones.' [[How do you cope with that?]] 'With a [[rowdy kid]], [[We bring the parent up|we bring the parent up]] on stage and let the child watch them squirm. [[You never know what they’re going to come up with]], [[But I’m up for that.|but I’m up for that.]] The [[onus]] is on me to keep control, and you [[Can’t diverge from the script|can’t diverge from the script]] too far or the whole room goes with you.' The corporate side, he admits, is [[very lucrative]]. '[[But what has also driven me is the fact that I was dyslexic]]. School was a [[tough crowd]]. Adults are worse, mind — they [[Get boozed up|get boozed up]] at Christmas parties and heckle.'",
    words: [
      {
        k: "I’m backstage at", w: "backstage", form: "adverb / adjective", ipa: "/ˌbækˈsteɪdʒ/",
        ru: "за кулисами (буквально, в театре или на концерте)",
        def: "in the area behind the stage where performers prepare",
        reg: "neutral",
        ex: ["I'm backstage at the arena, waiting for the band.", "a backstage pass; go backstage after the show"],
        use: "Буквальное место: backstage at + площадка. Ловушка: переносное «за кулисами» (закрытая часть процесса) — behind the scenes: behind-the-scenes negotiations.",
        use_en: "A literal place: backstage at + venue. Trap: the figurative «behind the curtain» of a process is behind the scenes: behind-the-scenes negotiations.",
        gap: { s: "The presenter is ___ at the arena, waiting for the band to arrive.", a: "backstage" },
      },
      {
        k: "It certainly has", w: "It certainly has.", form: "grammar: echo answer", ipa: "",
        ru: "ещё как (изменилось) — короткий ответ с вспомогательным глаголом",
        def: "a short emphatic answer repeating the auxiliary verb of the question",
        reg: "spoken",
        ex: ["— Has the show changed? — It certainly has.", "— Do you miss it? — I really do."],
        use: "Модель: подлежащее + certainly / really / definitely + вспомогательный глагол из вопроса (has, does, did, can). Ловушка: русскоязычные отвечают «Yes, it changed» — грамматически можно, но эхо-ответ звучит естественнее и живее.",
        use_en: "Pattern: subject + certainly / really / definitely + the auxiliary from the question (has, does, did, can). Trap: answering «Yes, it changed» is possible but the echo answer sounds far more natural.",
        gap: { s: "— Has the tour been exhausting? — It ___ has.", a: "certainly" },
      },
      {
        k: "rowdiness", w: "rowdiness", form: "noun", ipa: "/ˈraʊdinəs/",
        ru: "буйство, шумное и неуправляемое поведение (толпы, публики)",
        def: "noisy, rough and slightly aggressive behaviour, usually of a group",
        reg: "neutral · informal",
        ex: ["The stewards struggled to control the rowdiness of the crowd.", "There was some rowdiness after the match."],
        use: "Про группу, которая шумит и слегка агрессивна: болельщики, паб в пятницу, класс без учителя. Ловушка: просто громко — loud / noisy; rowdy добавляет «буйно, на грани хулиганства».",
        use_en: "About a group that is noisy and a bit aggressive: fans, a pub on Friday, a class with no teacher. Trap: merely loud is loud / noisy; rowdy adds «unruly, close to trouble».",
        gap: { s: "The stewards struggled to control the ___ of the crowd.", a: "rowdiness" },
      },
      {
        k: "How do you cope with that?", w: "cope with", form: "verb + preposition", ipa: "/kəʊp/",
        ru: "справляться с (чем-то трудным, стрессом)",
        def: "to deal successfully with a difficult situation or emotion",
        reg: "neutral",
        ex: ["How do you cope with hecklers?", "She's coping well with the pressure."],
        use: "cope WITH, и никогда cope up with (частая ошибка). cope — про то, чтобы выдержать трудное (стресс, потеря, нагрузка); deal with / handle — шире, про любые дела. Без дополнения тоже можно: I can't cope.",
        use_en: "cope WITH — never cope up with. cope is about enduring something hard (stress, loss, workload); deal with / handle are broader. Also used alone: I can't cope.",
        gap: { s: "How do you ___ with hecklers in the front row?", a: "cope" },
      },
      {
        k: "You never know what they’re going to come up with", w: "come up with", form: "phrasal verb", ipa: "",
        ru: "придумать, выдать (идею, ответ, отговорку)",
        def: "to think of or produce an idea, answer or plan",
        reg: "neutral · informal",
        ex: ["Kids always come up with the strangest questions.", "We need to come up with a name by Friday."],
        use: "Неотделяемый: come up with an idea, не come an idea up. Ловушка: come up (возникнуть, всплыть: something came up) и come across (наткнуться) — другие глаголы.",
        use_en: "Inseparable: come up with an idea, never come an idea up. Trap: come up (arise: something came up) and come across (find by chance) are different verbs.",
        gap: { s: "Kids always ___ up with the strangest questions.", a: "come" },
      },
      {
        k: "But I’m up for that.", w: "be up for (something)", form: "idiom · spoken", ipa: "",
        ru: "быть готовым / не против, «я за»",
        def: "to be willing and keen to do something",
        reg: "informal · spoken",
        ex: ["Karaoke tonight? — Sure, I'm up for that.", "Anyone up for a walk?"],
        use: "Приглашение и согласие: up for a drink / a challenge / anything. Ловушка: be up TO — либо «замышлять» (What are you up to?), либо «быть в силах» (I'm not up to it today). Одна буква — другой смысл.",
        use_en: "Invitations and agreement: up for a drink / a challenge / anything. Trap: be up TO means either «doing something sneaky» (What are you up to?) or «capable of» (I'm not up to it today).",
        gap: { s: "Karaoke after the show? — Sure, I'm ___ for that.", a: "up" },
      },
      {
        k: "rowdy kid", w: "rowdy", form: "adjective", ipa: "/ˈraʊdi/",
        ru: "шумный, буйный, неуправляемый",
        def: "noisy and behaving in a rough, uncontrolled way",
        reg: "informal",
        ex: ["A rowdy kid in the front row kept shouting.", "a rowdy crowd / pub / party"],
        use: "Про людей и компании, не про машины или музыку. Сравни: naughty kid — непослушный (мягче); disruptive — срывающий занятие (учительское слово).",
        use_en: "About people and groups, not machines or music. Compare: a naughty kid is misbehaving (milder); disruptive is the teacher's word for spoiling a lesson.",
        gap: { s: "A ___ kid in the front row kept shouting over the jokes.", a: "rowdy" },
      },
      {
        k: "We bring the parent up", w: "bring somebody up (on stage)", form: "phrasal verb", ipa: "",
        ru: "вызвать на сцену; (другие значения) воспитывать; поднять тему",
        def: "to call someone onto the stage; also to raise a child; also to mention a topic",
        reg: "spoken",
        ex: ["If a child misbehaves, we bring the parent up on stage.", "I was brought up in Leeds. / Don't bring up the divorce at dinner."],
        use: "Три значения одного глагола, контекст решает: bring the parent up (на сцену), be brought up (быть воспитанным), bring up a subject (поднять тему). Отделяемый: bring him up / bring up the parent.",
        use_en: "Three meanings, context decides: bring the parent up (onto the stage), be brought up (raised), bring up a subject (mention it). Separable: bring him up / bring up the parent.",
        gap: { s: "If a child misbehaves, we ___ the parent up on stage.", a: "bring" },
      },
      {
        k: "onus", w: "the onus (is on somebody)", form: "noun · singular only", ipa: "/ˈəʊnəs/",
        ru: "бремя ответственности, обязанность",
        def: "the responsibility or duty to do something",
        reg: "formal (used in speech for emphasis)",
        ex: ["The onus is on the performer to keep the audience on side.", "The onus of proof lies with the prosecution."],
        use: "Всегда the onus, всегда единственное число: the onus is ON somebody TO do something. Юридически-формальное слово, в разговоре добавляет веса. Ловушка: onus of — редко и только в юр. штампах (onus of proof).",
        use_en: "Always the onus, always singular: the onus is ON somebody TO do something. Legal-formal, adds weight in speech. Trap: onus of appears only in fixed legal phrases (onus of proof).",
        gap: { s: "The ___ is on the performer to keep the audience on side.", a: "onus" },
      },
      {
        k: "Can’t diverge from the script", w: "diverge from", form: "verb + preposition", ipa: "/daɪˈvɜːdʒ/",
        ru: "отклоняться от (сценария, плана, нормы); расходиться (о путях, мнениях)",
        def: "to move away from a plan, script or standard; to go in different directions",
        reg: "formal · neutral",
        ex: ["In a scripted show you can't diverge from the text.", "Our opinions diverge on this point."],
        use: "diverge FROM. Ловушка: digress — отклоняться от темы в речи (But I digress); deviate from — отклониться от нормы/маршрута (ближайший синоним). Существительное — divergence.",
        use_en: "diverge FROM. Trap: digress is going off-topic while speaking (But I digress); deviate from is the closest synonym (from a norm or route). Noun: divergence.",
        gap: { s: "In a scripted show you can't ___ from the text for long.", a: "diverge" },
      },
      {
        k: "very lucrative", w: "lucrative", form: "adjective", ipa: "/ˈluːkrətɪv/",
        ru: "прибыльный, доходный (о деле, контракте, рынке)",
        def: "producing a lot of money",
        reg: "neutral · formal",
        ex: ["Corporate gigs are dull but very lucrative.", "a lucrative contract / market / career"],
        use: "Про деятельность и сделки, не про людей: a lucrative man ✗. Ловушка: profitable — бухгалтерское «в плюсе»; lucrative — «приносит большие деньги», часто с оттенком «ради денег, не ради души».",
        use_en: "About activities and deals, not people: a lucrative man ✗. Trap: profitable is the accountant's «in the black»; lucrative means «brings in big money», often hinting «for the money, not the love».",
        gap: { s: "Corporate gigs are boring but very ___.", a: "lucrative" },
      },
      {
        k: "But what has also driven me is the fact that I was dyslexic", w: "what has driven me is…", form: "grammar: cleft sentence · drive somebody", ipa: "/dɪsˈleksɪk/",
        ru: "что двигало мной — так это… ; dyslexic — с дислексией",
        def: "drive somebody = to motivate or push them; a cleft sentence puts the emphasis on the reason",
        reg: "spoken · emphatic",
        ex: ["What has driven me all these years is the fear of an office job.", "She's a very driven person."],
        use: "Cleft-конструкция What… is… выносит причину в фокус: What matters is… / What drove me was…. driven (прилагательное) — целеустремлённый. Ловушка: What drives you? — «что тебя мотивирует», не «что ты водишь».",
        use_en: "The cleft What… is… puts the reason in focus: What matters is… / What drove me was…. driven (adjective) = highly motivated. Trap: What drives you? asks about motivation, not cars.",
        gap: { s: "What has ___ me all these years is the fear of going back to an office job.", a: "driven" },
      },
      {
        k: "tough crowd", w: "tough crowd", form: "idiom", ipa: "/tʌf/",
        ru: "трудная публика (не смеётся, не реагирует); шутливо о любой неблагодарной аудитории",
        def: "an audience that is hard to please; jokingly, any unresponsive group",
        reg: "informal · humorous",
        ex: ["Nobody laughed at my joke in the meeting. Tough crowd.", "Teenagers are a tough crowd for a magician."],
        use: "Из стендапа, но живёт везде: сказать Tough crowd после шутки, которую не оценили коллеги, — самоирония. Ловушка: crowd здесь «публика», не «толпа на улице».",
        use_en: "From stand-up, but used everywhere: saying Tough crowd after a joke your colleagues ignored is self-mockery. Trap: crowd here means «audience», not a street crowd.",
        gap: { s: "Nobody laughed at my joke in the meeting. ___ crowd.", a: "Tough" },
      },
      {
        k: "Get boozed up", w: "get boozed up", form: "slang · phrasal", ipa: "/buːzd/",
        ru: "напиться, набраться",
        def: "to get drunk (booze = alcohol, informal)",
        reg: "slang · BrE",
        ex: ["By ten the stag party had got well and truly boozed up.", "There's plenty of booze in the fridge."],
        use: "Только с друзьями или в шутку: booze (выпивка), boozer (паб или пьяница, BrE), a booze-up (попойка). Регистр по возрастанию: boozed up → drunk → intoxicated (полиция, отчёты).",
        use_en: "Only among friends or as a joke: booze (alcohol), boozer (a pub or a drinker, BrE), a booze-up (a drinking session). Register ladder: boozed up → drunk → intoxicated (police, reports).",
        gap: { s: "By ten the stag party had got well and truly ___ up.", a: "boozed" },
      },
    ],
  },
  {
    id: "s4",
    title: "Section 4 · Летние каникулы",
    title_en: "Section 4 · Summer holidays",
    theme: "Рассказ об отдыхе: неформальный британский",
    theme_en: "Talking about holidays: informal British English",
    story:
      "As a kid, the [[endless summer hols]] meant six weeks of [[Just pottering around|just pottering around]]. [[inevitably|Inevitably]] I got bored, [[hung around]] the park with mates and put off [[tidying up]] my room until the last day. Last year my friends [[had been pestering me]] for months about a [[getaway]], and I finally said yes, though [[I was dreading]] it. We left [[at the crack of dawn]]; [[Within three hours|within three hours]] we were by the sea. [[no lugging baggage|No lugging baggage]] — one rucksack each. My mate drove; [[I’d never have made it otherwise]]. [[we did have to chip in with the washing up|We did have to chip in with the washing up]], but there was [[plenty]] of time to do nothing at all. Oddly, after a week of doing nothing [[I was more shattered]] than after a month at work. Now it's back to the [[grindstone]].",
    words: [
      {
        k: "endless summer hols", w: "hols", form: "noun · BrE informal", ipa: "/hɒlz/",
        ru: "каникулы (сокращение от holidays)",
        def: "short for holidays: school or work holidays (BrE)",
        reg: "informal · BrE",
        ex: ["Six weeks of summer hols — I had no idea what to do with myself.", "What are you doing over the hols?"],
        use: "Британское: holiday = отпуск/каникулы (on holiday), в AmE это vacation, а holidays там — рождественские праздники. hols — детско-школьное сокращение, взрослые говорят с улыбкой.",
        use_en: "British: holiday = time off (on holiday); in AmE that is vacation, and the holidays means the Christmas season. hols is a schoolkid's clipping — adults use it with a smile.",
        gap: { s: "Six weeks of summer ___ — I had no idea what to do with myself.", a: "hols" },
      },
      {
        k: "Just pottering around", w: "potter around / about", form: "phrasal verb · BrE", ipa: "/ˈpɒtə/",
        ru: "возиться без цели, неспешно заниматься мелочами (по дому, в саду)",
        def: "to spend time doing small, pleasant, unimportant things without hurrying",
        reg: "informal · BrE",
        ex: ["Dad spent Sunday pottering around in the garden.", "I just pottered about the house all morning."],
        use: "Уютное слово про безделье без вины. AmE — putter around. Ловушка: не путать с potter (гончар) — Harry Potter не при чём; и не mess around (валять дурака, с оттенком неодобрения).",
        use_en: "A cosy word for guilt-free idleness. AmE: putter around. Trap: nothing to do with a potter (who makes pots), and not mess around (fooling about, slightly disapproving).",
        gap: { s: "Dad spent the whole Sunday ___ around in the garden.", a: "pottering" },
      },
      {
        k: "inevitably", w: "inevitably", form: "adverb", ipa: "/ɪnˈevɪtəbli/",
        ru: "неизбежно; как и следовало ожидать",
        def: "as was certain to happen; unavoidably",
        reg: "neutral",
        ex: ["We planned a barbecue and, inevitably, it poured with rain.", "Inevitably, the conversation turned to work."],
        use: "Часто с иронией вводит предсказуемо-нежелательный исход. Ставится в начале или между запятыми. Прилагательное inevitable: the inevitable happened.",
        use_en: "Often ironic, introducing a predictable, unwelcome outcome. Sentence-initial or between commas. Adjective: inevitable — the inevitable happened.",
        gap: { s: "We planned a barbecue and, ___, it poured with rain.", a: "inevitably" },
      },
      {
        k: "hung around", w: "hang around", form: "phrasal verb", ipa: "",
        ru: "слоняться, торчать где-то без дела; hang around with — тусоваться с",
        def: "to spend time somewhere doing nothing much; hang around with = spend time with",
        reg: "informal",
        ex: ["We just hung around the shopping centre all afternoon.", "He hangs around with the wrong crowd."],
        use: "Ловушка из трёх hang: hang around (торчать без дела, чуть негативно), hang out (проводить время вместе, позитивно, AmE-оттенок), hang on (подожди). Past — hung (hanged — только о казни).",
        use_en: "Three hangs: hang around (loiter, slightly negative), hang out (spend time together, positive), hang on (wait). Past tense hung — hanged is only for executions.",
        gap: { s: "We just ___ around the shopping centre all afternoon.", a: "hung" },
      },
      {
        k: "tidying up", w: "tidy up", form: "phrasal verb · BrE", ipa: "/ˈtaɪdi/",
        ru: "прибраться, навести порядок",
        def: "to make a place neat by putting things where they belong",
        reg: "neutral · BrE",
        ex: ["Before Mum got home we spent an hour tidying up.", "Tidy your room up!"],
        use: "tidy — про порядок (разложить вещи), clean — про грязь (помыть). AmE чаще clean up / straighten up. Отделяемый: tidy up the room / tidy the room up.",
        use_en: "tidy is about order (putting things away), clean is about dirt. AmE prefers clean up / straighten up. Separable: tidy up the room / tidy the room up.",
        gap: { s: "Before Mum got home we spent an hour ___ up.", a: "tidying" },
      },
      {
        k: "I was more shattered", w: "shattered", form: "adjective · BrE informal", ipa: "/ˈʃætəd/",
        ru: "вымотанный, без сил; (буквально) разбитый вдребезги",
        def: "extremely tired (BrE informal); literally, broken into pieces",
        reg: "informal · BrE",
        ex: ["After the night flight I was absolutely shattered.", "shattered glass; her dreams were shattered"],
        use: "Британское «я выжат»: I'm shattered / knackered. Ловушка: американец может понять shattered как «раздавлен горем»; в AmE говорят exhausted, beat, wiped out. Усилитель — absolutely, не very.",
        use_en: "British for «drained»: I'm shattered / knackered. Trap: to an American shattered may sound like «emotionally devastated»; AmE says exhausted, beat, wiped out. Intensifier: absolutely, not very.",
        gap: { s: "After the overnight flight I was absolutely ___.", a: "shattered" },
      },
      {
        k: "no lugging baggage", w: "lug (something)", form: "verb · informal", ipa: "/lʌɡ/",
        ru: "тащить, волочь что-то тяжёлое",
        def: "to carry or drag something heavy with effort",
        reg: "informal",
        ex: ["No lugging suitcases up five flights of stairs this year.", "I lugged the shopping home in the rain."],
        use: "carry — нейтрально нести; lug — тяжело и с раздражением. Существительное luggage / baggage — багаж (неисчисляемые: a piece of luggage). no + -ing в заголовках и заметках = «никакого …».",
        use_en: "carry is neutral; lug means heavy and annoying. Nouns luggage / baggage are uncountable (a piece of luggage). no + -ing in notes and headlines = «none of that».",
        gap: { s: "No ___ suitcases up five flights of stairs this year.", a: "lugging" },
      },
      {
        k: "Within three hours", w: "within (a period)", form: "preposition", ipa: "/wɪðˈɪn/",
        ru: "не позже чем через; в пределах",
        def: "before a period of time has passed; inside a limit",
        reg: "neutral",
        ex: ["Within three hours we were on the beach.", "Reply within five working days. / within walking distance"],
        use: "Три предлога времени: within three hours (максимум за три часа), in three hours (ровно через три часа), for three hours (на протяжении трёх часов). within также про расстояние и границы: within budget, within reach.",
        use_en: "Three time prepositions: within three hours (three at most), in three hours (after exactly three), for three hours (duration). within also covers limits: within budget, within reach.",
        gap: { s: "The taxi came, and ___ three hours we were on the beach.", a: "within" },
      },
      {
        k: "at the crack of dawn", w: "at the crack of dawn", form: "idiom", ipa: "/kræk əv dɔːn/",
        ru: "с первыми лучами, ни свет ни заря",
        def: "very early in the morning, as soon as it gets light",
        reg: "informal",
        ex: ["We had to get up at the crack of dawn to catch the flight.", "The builders arrive at the crack of dawn."],
        use: "Разговорная идиома с оттенком жалобы. Формально — at first light / at daybreak. Противоположность — at dusk (в сумерках), in the dead of night (глубокой ночью).",
        use_en: "A conversational idiom with a hint of complaint. Formal: at first light / at daybreak. Opposites: at dusk, in the dead of night.",
        gap: { s: "We had to get up at the ___ of dawn to catch the flight.", a: "crack" },
      },
      {
        k: "I’d never have made it otherwise", w: "make it / otherwise", form: "idiom + grammar: third conditional", ipa: "",
        ru: "иначе я бы никак не успел / не добрался",
        def: "make it = arrive or succeed in time; otherwise = if not, in a different situation",
        reg: "informal",
        ex: ["Thanks for the lift — I'd never have made it otherwise.", "Hurry, or we won't make it."],
        use: "I'd = I would (не I had!) → would never have made — третий тип условного, условие спрятано в otherwise. make it — успеть/добраться/пробиться: make it to the meeting, make it big (стать звездой).",
        use_en: "I'd = I would (not I had!) → would never have made — a third conditional whose if-clause is hidden in otherwise. make it = arrive / succeed: make it to the meeting, make it big.",
        gap: { s: "Thanks for the lift — I'd never have ___ it otherwise.", a: "made" },
      },
      {
        k: "I was dreading", w: "dread (doing something)", form: "verb", ipa: "/dred/",
        ru: "страшиться (предстоящего), с ужасом ждать",
        def: "to feel very worried about something that is going to happen",
        reg: "neutral",
        ex: ["I was dreading the eight-hour coach journey.", "I dread to think what it cost."],
        use: "Только про будущее: dread + -ing / dread the thought of. Пауков не dread, их be scared of / fear. Устойчивое: I dread to think… — страшно подумать.",
        use_en: "Only about the future: dread + -ing / dread the thought of. You don't dread spiders — you are scared of them. Set phrase: I dread to think….",
        gap: { s: "I was ___ the eight-hour coach journey.", a: "dreading" },
      },
      {
        k: "had been pestering me", w: "pester somebody (to do)", form: "verb · past perfect continuous", ipa: "/ˈpestə/",
        ru: "доставать, приставать с просьбами",
        def: "to annoy someone by asking for something again and again",
        reg: "informal",
        ex: ["The kids had been pestering me for weeks to take them to the water park.", "Stop pestering your sister."],
        use: "Past perfect continuous (had been pestering) — процесс тянулся долго ДО другого события в прошлом. Шкала: bother (мягко) → pester (настойчиво, надоедливо) → harass (серьёзно, вплоть до юридического).",
        use_en: "Past perfect continuous (had been pestering) — an activity that went on for a long time before another past event. Scale: bother (mild) → pester (persistent, annoying) → harass (serious, potentially legal).",
        gap: { s: "The kids had been ___ me for weeks to take them to the water park.", a: "pestering" },
      },
      {
        k: "getaway", w: "getaway", form: "noun", ipa: "/ˈɡetəweɪ/",
        ru: "короткий отпуск, побег от рутины; (другое) бегство с места преступления",
        def: "a short holiday; also an escape after a crime (a getaway car)",
        reg: "informal · marketing",
        ex: ["A weekend getaway to the coast was exactly what we needed.", "The robbers' getaway car was found abandoned."],
        use: "Слово из рекламы турфирм: a romantic / weekend / city getaway. Второе значение — криминальное: make a getaway, getaway driver. Глагол пишется раздельно: get away — сбежать, вырваться.",
        use_en: "Travel-brochure word: a romantic / weekend / city getaway. Second meaning is criminal: make a getaway, getaway driver. The verb is two words: get away.",
        gap: { s: "A weekend ___ to the coast was exactly what we needed.", a: "getaway" },
      },
      {
        k: "we did have to chip in with the washing up", w: "chip in (with) / the washing up", form: "phrasal verb + emphatic did", ipa: "/tʃɪp/",
        ru: "внести свою долю (деньгами или помощью); washing up — мытьё посуды (BrE)",
        def: "chip in = contribute money or help; the washing up = the dirty dishes (BrE)",
        reg: "informal · BrE",
        ex: ["Everyone had to chip in with the cooking.", "We all chipped in for a present. / Whose turn is it to do the washing up?"],
        use: "did have to — эмфатическое did: «пришлось-таки». chip in for (деньгами) / with (помощью) / chip in — вставить реплику. AmE: do the dishes вместо do the washing up.",
        use_en: "did have to — emphatic did: «we DID have to». chip in for (money) / with (help); also chip in = add a remark. AmE says do the dishes rather than do the washing up.",
        gap: { s: "Everyone had to ___ in with the cooking and cleaning.", a: "chip" },
      },
      {
        k: "plenty", w: "plenty (of)", form: "pronoun / determiner", ipa: "/ˈplenti/",
        ru: "много, вдоволь, с избытком",
        def: "a large amount, as much as or more than is needed",
        reg: "neutral",
        ex: ["There was plenty of time to explore the old town.", "— More tea? — No thanks, that's plenty."],
        use: "plenty OF + существительное (и исчисляемое, и нет): plenty of time / plenty of chairs. Само по себе plenty — местоимение: That's plenty. Оттенок «хватает с запасом», в отличие от нейтрального many / much. Ловушка: plenty time ✗.",
        use_en: "plenty OF + noun (countable or not): plenty of time / plenty of chairs. Alone it is a pronoun: That's plenty. Implies «enough and more», unlike neutral many / much. Trap: plenty time ✗.",
        gap: { s: "There was ___ of time to explore the old town.", a: "plenty" },
      },
      {
        k: "grindstone", w: "(back to) the grindstone", form: "noun · idiom", ipa: "/ˈɡraɪndstəʊn/",
        ru: "точильный камень; идиома — вкалывать без передышки; back to the grindstone — снова за работу",
        def: "a stone for sharpening tools; keep your nose to the grindstone = work hard without a break",
        reg: "informal · idiom",
        ex: ["Holiday's over — back to the grindstone on Monday.", "She kept her nose to the grindstone all term."],
        use: "После отпуска: Back to the grindstone! — с усталой самоиронией. Родственное: the daily grind — рутина; grind (v) — молоть, точить; a grind — нудная тяжёлая работа.",
        use_en: "After a holiday: Back to the grindstone! — tired self-mockery. Related: the daily grind (routine); grind (v) = to mill or sharpen; a grind = tedious hard work.",
        gap: { s: "Holiday's over — back to the ___ on Monday.", a: "grindstone" },
      },
    ],
  },
];

export const ALL_WORDS = UNITS.flatMap((u) => u.words.map((w) => ({ ...w, unit: u.id })));
