import { InterviewQuestion, ModelAnswer, SectionTitle, Gotchas, CodeBlock, L } from "../InterviewBlocks.jsx";

export default function Pipeline() {
  return (
    <>
      <InterviewQuestion en="How does React Native work under the hood? Explain the bridge, JSI, Fabric and TurboModules in detail.">
        Как React Native работает под капотом? Расскажи детально про bridge, JSI, Fabric и TurboModules.
      </InterviewQuestion>

      <ModelAnswer
        en={
          <>
            "My JS runs on <b>Hermes</b> in its own thread; React builds the
            usual tree, but the host targets are <b>native views</b>. In the
            old architecture every JS↔native interaction went through the
            <b> bridge</b>: an asynchronous message queue where calls were
            <b> batched</b> and <b>serialized to JSON</b> on one side and
            deserialized on the other. Three costs follow: serialization
            itself, the async-only nature — you couldn't read layout
            synchronously — and congestion: scroll events, image loads and
            state updates all squeeze through one queue, which is where
            dropped frames on fast lists came from. <b>JSI</b> replaces this
            with a C++ layer: the JS engine exposes <b>HostObjects</b>, so JS
            holds direct references to C++ objects and calls their methods
            <b> synchronously, with no JSON and no queue</b>. On top of JSI
            sit <b>TurboModules</b> — native modules loaded lazily with typed
            bindings generated by <b>codegen</b> from a TS spec — and
            <b> Fabric</b>, the renderer with the shadow tree in C++, which
            works in three phases — render, commit, mount — supports
            concurrent rendering and allows synchronous measurement. Since RN
            0.76 the new architecture — bridgeless — is the default. And
            libraries like Reanimated, MMKV or VisionCamera are fast precisely
            because they are JSI-first."
          </>
        }
      >
        «Мой JS выполняется на <b>Hermes</b> в отдельном потоке; React строит
        обычное дерево, но host-целями являются <b>нативные вью</b>. В старой
        архитектуре каждое взаимодействие JS↔натив шло через <b>bridge</b>:
        асинхронную очередь сообщений, где вызовы <b>батчились</b> и
        <b> сериализовались в JSON</b> на одной стороне и парсились на другой.
        Отсюда три платы: сама сериализация, принципиальная асинхронность —
        нельзя синхронно прочитать layout — и перегрузка очереди: события
        скролла, картинки и обновления state лезут через одно горлышко, отсюда
        пропущенные кадры на быстрых списках. <b>JSI</b> заменяет это
        C++-слоем: движок JS выставляет <b>HostObject</b>-ы, и JS держит
        прямые ссылки на C++-объекты, вызывая их методы <b>синхронно, без
        JSON и без очереди</b>. Поверх JSI стоят <b>TurboModules</b> —
        нативные модули с ленивой загрузкой и типизированными биндингами,
        которые <b>codegen</b> генерирует из TS-спеки — и <b>Fabric</b>,
        рендерер с shadow tree на C++, работающий в три фазы — render,
        commit, mount — поддерживающий concurrent rendering и синхронные
        замеры. С RN 0.76 новая архитектура — bridgeless — включена по
        умолчанию. А Reanimated, MMKV и VisionCamera быстрые именно потому,
        что построены на JSI.»
      </ModelAnswer>

      <SectionTitle en="Deep dive: old architecture">Разбор: старая архитектура</SectionTitle>

      <div className="card">
        <h3><L ru="Bridge: как это работало" en="Bridge: how it worked" /></h3>
        <CodeBlock
          ru={`┌─────────────┐   JSON-сообщения, асинхронно, батчами   ┌──────────────┐
│  JS-поток    │ ──────────────▶ MessageQueue ──────────▶ │  Native (UI) │
│  (Hermes)    │ ◀────────────── MessageQueue ◀────────── │  поток       │
└─────────────┘                                          └──────────────┘

// Каждый вызов превращался в строку:
["UIManager", "createView", [42, "RCTView", 1, { backgroundColor: ... }]]

// Механика:
// 1. JS-вызовы НЕ уходят сразу — копятся в очереди
// 2. Раз в ~5мс (или в конце батча) очередь сериализуется в JSON
// 3. Натив парсит JSON и выполняет вызовы; ответы едут обратно так же
// 4. ВСЁ асинхронно: спросить у натива "какая ширина у вью?" и дождаться
//    ответа в том же кадре — невозможно`}
          en={`┌──────────────┐   JSON messages, async, batched          ┌──────────────┐
│  JS thread    │ ──────────────▶ MessageQueue ──────────▶ │  Native (UI) │
│  (Hermes)     │ ◀────────────── MessageQueue ◀────────── │  thread      │
└──────────────┘                                          └──────────────┘

// Every call turned into a string:
["UIManager", "createView", [42, "RCTView", 1, { backgroundColor: ... }]]

// The mechanics:
// 1. JS calls do NOT go out immediately — they pile up in a queue
// 2. About every ~5ms (or at the end of a batch) the queue is serialized to JSON
// 3. Native parses the JSON and executes the calls; responses travel back the same way
// 4. EVERYTHING is async: asking native "what's this view's width?" and waiting
//    for the answer within the same frame — impossible`}
        />
      </div>

      <div className="card">
        <h3><L ru="Путь одного касания через bridge (почему лагало)" en="One touch's journey through the bridge (why it lagged)" /></h3>
        <CodeBlock
          ru={`1. UI-поток: палец коснулся экрана → нативное событие
2. Событие сериализуется → в очередь → JS-поток
3. JS: onPress → setState → React рендерит → команды для UIManager
4. Команды сериализуются → в очередь → UI-поток
5. UI-поток применяет изменения к вью

Проблемы этой схемы:
• 2 сериализации + 2 перепрыгивания потоков НА КАЖДОЕ взаимодействие
• onScroll с большим числом событий забивает очередь → пропуск кадров
  (поэтому у ScrollView есть scrollEventThrottle!)
• пока JS-поток занят (тяжёлый рендер) — очередь копится, UI «догоняет»
• большие данные (base64-картинка, большой ответ API) = дорогой JSON.parse`}
          en={`1. UI thread: finger touches the screen → native event
2. Event is serialized → into the queue → JS thread
3. JS: onPress → setState → React renders → commands for UIManager
4. Commands are serialized → into the queue → UI thread
5. UI thread applies the changes to the views

Problems with this scheme:
• 2 serializations + 2 thread hops for EVERY single interaction
• onScroll firing lots of events floods the queue → dropped frames
  (this is why ScrollView has scrollEventThrottle!)
• while the JS thread is busy (heavy render) the queue backs up, and the UI "catches up" later
• large payloads (a base64 image, a big API response) = expensive JSON.parse`}
        />
      </div>

      <SectionTitle en="Deep dive: new architecture">Разбор: новая архитектура</SectionTitle>

      <div className="card">
        <h3><L ru="JSI (JavaScript Interface) — фундамент" en="JSI (JavaScript Interface) — the foundation" /></h3>
        <CodeBlock
          ru={`// JSI — это НЕ "быстрый bridge". Это C++ API поверх JS-движка,
// который позволяет JS и нативу держать ссылки друг на друга напрямую.

// HostObject: C++-объект, «просунутый» в JS
class MMKVHostObject : public jsi::HostObject {
  jsi::Value get(jsi::Runtime& rt, const jsi::PropNameID& name) {
    // JS обратился к свойству → этот C++-код выполняется СИНХРОННО
  }
};

// В JS это выглядит как обычный объект:
const value = mmkv.getString("key");   // прямой синхронный вызов C++
                                       // без JSON, без очереди, без потоков

// Что это дало:
// • синхронные вызовы (можно и async, но теперь ЕСТЬ ВЫБОР)
// • нулевая сериализация — данные передаются как jsi::Value (память)
// • JS может держать C++-объекты (и наоборот) — otсюда worklets Reanimated
// • движок заменяем: Hermes/JSC/V8 — JSI абстрагирует движок`}
          en={`// JSI is NOT "a faster bridge." It's a C++ API on top of the JS engine
// that lets JS and native hold direct references to each other.

// HostObject: a C++ object "poked into" JS
class MMKVHostObject : public jsi::HostObject {
  jsi::Value get(jsi::Runtime& rt, const jsi::PropNameID& name) {
    // JS touched the property → this C++ code runs SYNCHRONOUSLY
  }
};

// In JS this looks like a plain object:
const value = mmkv.getString("key");   // direct synchronous C++ call
                                       // no JSON, no queue, no thread hop

// What this bought us:
// • synchronous calls (async is still possible, but now you have a CHOICE)
// • zero serialization — data is passed as a jsi::Value (raw memory)
// • JS can hold C++ objects (and vice versa) — this is where Reanimated worklets come from
// • the engine is swappable: Hermes/JSC/V8 — JSI abstracts the engine away`}
        />
        <p className="hint">
          <L
            ru="Кто построен на JSI: Reanimated (worklets на UI-потоке), MMKV (синхронное хранилище — замена асинхронному AsyncStorage), VisionCamera (frame processors), react-native-skia."
            en="Built on JSI: Reanimated (worklets on the UI thread), MMKV (synchronous storage — a replacement for async AsyncStorage), VisionCamera (frame processors), react-native-skia."
          />
        </p>
      </div>

      <div className="card">
        <h3>TurboModules + codegen</h3>
        <CodeBlock
          ru={`// 1. Пишешь типизированную спеку (source of truth):
export interface Spec extends TurboModule {
  getBatteryLevel(): Promise<number>;
  getDeviceName(): string;              // ← синхронный метод! (bridge не умел)
}
export default TurboModuleRegistry.getEnforcing<Spec>("Device");

// 2. codegen генерирует из неё C++/ObjC/Kotlin-интерфейсы —
//    типы проверяются на этапе СБОРКИ, а не в рантайме

// Отличия от старых NativeModules:
// bridge-модули: ВСЕ инициализировались на старте приложения (медленный TTI)
// TurboModules:  ленивая загрузка при первом обращении
// bridge-модули: только async (промисы/колбэки)
// TurboModules:  можно синхронные методы через JSI`}
          en={`// 1. You write a typed spec (the source of truth):
export interface Spec extends TurboModule {
  getBatteryLevel(): Promise<number>;
  getDeviceName(): string;              // ← a synchronous method! (bridge couldn't do this)
}
export default TurboModuleRegistry.getEnforcing<Spec>("Device");

// 2. codegen generates C++/ObjC/Kotlin interfaces from it —
//    types are checked at BUILD time, not at runtime

// Differences from old NativeModules:
// bridge modules: ALL initialized at app startup (slow TTI)
// TurboModules:   lazy-loaded on first access
// bridge modules: async only (promises/callbacks)
// TurboModules:   can expose synchronous methods via JSI`}
        />
      </div>

      <div className="card">
        <h3><L ru="Fabric — новый рендерер, три фазы" en="Fabric — the new renderer, three phases" /></h3>
        <CodeBlock
          ru={`1. RENDER (JS-поток):    React строит дерево элементов →
                         создаётся Shadow Tree на C++ (иммутабельный)
2. COMMIT (фоновый):     Yoga считает layout (flexbox → x/y/width/height);
                         новое дерево атомарно становится «следующим»
3. MOUNT (UI-поток):     diff старого и нового shadow tree →
                         минимальные операции create/update/delete вью

Что дал Fabric:
• shadow tree в C++ разделён между потоками БЕЗ копирования (раньше —
  три копии дерева: JS, shadow на Java/ObjC, натив)
• синхронный measure: можно измерить вью в том же кадре (нужно для
  concurrent rendering и правильного useLayoutEffect)
• приоритеты обновлений: срочное (жест) может обогнать несрочное
• интероп с concurrent-фичами React 18+ (Suspense, transitions)`}
          en={`1. RENDER (JS thread):   React builds the element tree →
                         a Shadow Tree is created in C++ (immutable)
2. COMMIT (background):  Yoga computes layout (flexbox → x/y/width/height);
                         the new tree atomically becomes "next"
3. MOUNT (UI thread):    diff the old and new shadow tree →
                         minimal create/update/delete operations on views

What Fabric bought us:
• the C++ shadow tree is shared across threads WITHOUT copying (before —
  three copies of the tree: JS, shadow on Java/ObjC, native)
• synchronous measure: a view can be measured within the same frame (needed
  for concurrent rendering and correct useLayoutEffect)
• update priorities: an urgent update (a gesture) can jump ahead of a non-urgent one
• interop with React 18+ concurrent features (Suspense, transitions)`}
        />
      </div>

      <div className="card">
        <h3><L ru="Hermes и вся картина целиком" en="Hermes, and the whole picture" /></h3>
        <CodeBlock
          ru={`Hermes: JS-движок под мобильные ограничения
• компиляция в БАЙТКОД на этапе сборки (AOT) — телефон не парсит JS-текст
• байткод грузится через mmap — быстрый старт, экономия памяти
• нет JIT — намеренно: JIT-прогрев дорог, для UI-кода AOT выгоднее

Новая архитектура целиком (bridgeless, дефолт с RN 0.76):
JS (Hermes) ──JSI──▶ TurboModules (лениво, типизированно, sync/async)
     │
   React ──▶ Fabric: Shadow Tree (C++) ──Yoga──▶ Mount на UI-потоке
     │
  Worklets (Reanimated) — JS-функции, выполняемые ПРЯМО на UI-потоке

Потоки: JS │ UI (main) │ background (Yoga layout) │ + пулы нативных модулей`}
          en={`Hermes: a JS engine built for mobile constraints
• compiles to BYTECODE at build time (AOT) — the phone never parses JS source text
• bytecode loads via mmap — fast startup, lower memory use
• no JIT — deliberately: JIT warm-up is expensive, AOT wins for UI code

The new architecture, end to end (bridgeless, default since RN 0.76):
JS (Hermes) ──JSI──▶ TurboModules (lazy, typed, sync/async)
     │
   React ──▶ Fabric: Shadow Tree (C++) ──Yoga──▶ Mount on the UI thread
     │
  Worklets (Reanimated) — JS functions that run DIRECTLY on the UI thread

Threads: JS │ UI (main) │ background (Yoga layout) │ + native module pools`}
        />
      </div>

      <Gotchas
        items={[
          {
            title: "«JSI — это просто быстрый bridge?»",
            code: `// Нет. Bridge — ОЧЕРЕДЬ СООБЩЕНИЙ (данные копируются через JSON).
// JSI — ПРЯМЫЕ ССЫЛКИ между JS и C++ (данных не копируют вообще).
// Смена парадигмы: из «переписки письмами» в «вызов метода соседа»`,
            text: "Любимый уточняющий вопрос. Ключевые слова ответа: HostObject, синхронность как опция, нулевая сериализация, независимость от движка.",
            en: {
              title: "\"Is JSI just a faster bridge?\"",
              code: `// No. Bridge — a MESSAGE QUEUE (data is copied via JSON).
// JSI — DIRECT REFERENCES between JS and C++ (data isn't copied at all).
// A paradigm shift: from "writing letters back and forth" to "calling your neighbor's method directly"`,
              text: "A favorite follow-up question. Key words for the answer: HostObject, synchronicity as an option, zero serialization, engine independence.",
            },
          },
          {
            title: "«Почему AsyncStorage асинхронный, а MMKV синхронный?»",
            code: `await AsyncStorage.getItem("k");  // bridge: иначе никак — очередь
mmkv.getString("k");              // JSI: прямой вызов C++, мгновенно`,
            text: "Асинхронность AsyncStorage — не дизайн-решение, а ОГРАНИЧЕНИЕ bridge. JSI сняло его — и появились синхронные API там, где это удобно.",
            en: {
              title: "\"Why is AsyncStorage async but MMKV synchronous?\"",
              code: `await AsyncStorage.getItem("k");  // bridge: no other way — it's a queue
mmkv.getString("k");              // JSI: direct C++ call, instant`,
              text: "AsyncStorage's asynchrony isn't a design choice — it's a CONSTRAINT of the bridge. JSI removed that constraint, which is why synchronous APIs showed up wherever they're convenient.",
            },
          },
          {
            title: "«RN рендерит в WebView?»",
            code: `// НЕТ. <View> → UIView / android.view.View
// Это НАСТОЯЩИЕ нативные вью, не HTML`,
            text: "Главное заблуждение. RN ≠ Cordova/Ionic: никакого WebView, UI полностью нативный. Сказать «HTML в вебвью» — сразу минус.",
            en: {
              title: "\"Does RN render into a WebView?\"",
              code: `// NO. <View> → UIView / android.view.View
// These are REAL native views, not HTML`,
              text: "The most common misconception. RN ≠ Cordova/Ionic: no WebView involved, the UI is fully native. Saying \"it's HTML in a WebView\" is an instant red flag.",
            },
          },
          {
            title: "«Почему анимация на JS дёргается?»",
            code: `// JS-поток занят (тяжёлый рендер) → колбэки анимации не успевают
// Фиксы: useNativeDriver: true (Animated),
// Reanimated — worklets прямо на UI-потоке`,
            text: "Проверяют понимание потоков: анимации должны жить на UI-потоке, а не зависеть от загруженности JS.",
            en: {
              title: "\"Why does a JS-driven animation stutter?\"",
              code: `// JS thread is busy (heavy render) → animation callbacks fall behind
// Fixes: useNativeDriver: true (Animated),
// Reanimated — worklets running directly on the UI thread`,
              text: "Tests your understanding of threading: animations should live on the UI thread, not depend on how busy JS is.",
            },
          },
          {
            title: "scrollEventThrottle — зачем он был нужен?",
            code: `<ScrollView scrollEventThrottle={16} onScroll={...} />
// bridge: каждое событие скролла = сериализация в очередь;
// throttle ограничивал их частоту, чтобы не забить мост.
// В новой архитектуре проблема ушла — проп фактически не нужен`,
            text: "Красивый пример «прибор из прошлой эпохи»: сам факт существования этого пропа объясняется устройством bridge.",
            en: {
              title: "scrollEventThrottle — why did it exist?",
              code: `<ScrollView scrollEventThrottle={16} onScroll={...} />
// bridge: every scroll event = one more serialization into the queue;
// throttle limited their frequency so they wouldn't flood the bridge.
// On the new architecture the problem is gone — the prop is effectively unnecessary`,
              text: "A neat example of \"a relic from a past era\": the very existence of this prop is explained entirely by how the bridge worked.",
            },
          },
          {
            title: "Что конкретно ускоряет новая архитектура?",
            code: `// JSI      → убрал сериализацию и дал синхронные вызовы
// TurboModules → ленивая загрузка модулей (быстрее старт)
// Fabric   → одно C++-дерево вместо трёх копий + приоритеты
// Hermes   → байткод AOT (быстрый TTI, меньше памяти)`,
            text: "Ответ «просто быстрее» не засчитают — по каждому компоненту нужно уметь назвать, ЧТО он убрал/добавил.",
            en: {
              title: "What exactly does the new architecture speed up?",
              code: `// JSI          → removed serialization, enabled synchronous calls
// TurboModules → lazy module loading (faster startup)
// Fabric       → one C++ tree instead of three copies + priorities
// Hermes       → AOT bytecode (fast TTI, lower memory)`,
              text: "\"It's just faster\" won't cut it — for each piece you need to be able to name exactly WHAT it removed or added.",
            },
          },
        ]}
      />

      <div className="explain">
        <b><L ru="Резюме одной строкой:" en="One-line summary:" /></b>{" "}
        <L
          ru="старое RN = асинхронный JSON-мост с очередью (сериализация, только async, заторы); новое = JSI (прямые C++-ссылки, sync-вызовы) + TurboModules (лениво, codegen) + Fabric (C++ shadow tree, 3 фазы, concurrent) + Hermes (байткод AOT); bridgeless — дефолт с RN 0.76."
          en="old RN = an async JSON bridge with a queue (serialization, async-only, congestion); new RN = JSI (direct C++ references, sync calls) + TurboModules (lazy, codegen) + Fabric (C++ shadow tree, 3 phases, concurrent) + Hermes (AOT bytecode); bridgeless is the default since RN 0.76."
        />
      </div>
    </>
  );
}
