// Вопросы квиза: секция Claude AI (тема «Claude AI 🤖» в «Разное»)
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

export const CLAUDE_QUESTIONS = [
  {
    t: "Claude · Модели",
    q: "Какая модель — самая способная в актуальной линейке Claude (2026)?",
    o: [
      "Claude Fable 5",
      "Claude Opus 5",
      "Claude Sonnet 5",
      "Claude Haiku 4.5",
    ],
    a: 0,
    e: "Иерархия: Fable 5 (самая способная) → Opus 5 (рабочая лошадка агентного кодинга) → Sonnet 5 (баланс цены и ума) → Haiku 4.5 (быстрая и дешёвая).",
    en: {
      t: "Claude · Models",
      q: "Which model is the most capable in the current Claude lineup (2026)?",
      o: [
        "Claude Fable 5",
        "Claude Opus 5",
        "Claude Sonnet 5",
        "Claude Haiku 4.5",
      ],
      e: "The hierarchy: Fable 5 (most capable) → Opus 5 (the agentic-coding workhorse) → Sonnet 5 (the price/intelligence balance) → Haiku 4.5 (fast and cheap).",
    },
  },
  {
    t: "Claude · Модели",
    q: "Нужно дёшево классифицировать тысячи коротких отзывов. Какую модель взять?",
    o: [
      "Claude Haiku 4.5 — задача простая, скорость и цена решают",
      "Claude Fable 5 — для точности всегда берём самую умную",
      "Claude Opus 5 — классификация требует глубокого рассуждения",
      "Любую: все модели Claude стоят одинаково за токен",
    ],
    a: 0,
    e: "Правило: модель по задаче. Классификация коротких текстов — типичная задача для Haiku: быстро, дёшево, качества хватает. Умные модели — туда, где evals показывают разницу.",
    en: {
      t: "Claude · Models",
      q: "You need to cheaply classify thousands of short reviews. Which model do you pick?",
      o: [
        "Claude Haiku 4.5 — the task is simple, speed and price win",
        "Claude Fable 5 — always take the smartest model for accuracy",
        "Claude Opus 5 — classification demands deep reasoning",
        "Any of them: all Claude models cost the same per token",
      ],
      e: "The rule: model per task. Short-text classification is a textbook Haiku job: fast, cheap, quality holds. Save the smart models for where evals show a real difference.",
    },
  },
  {
    t: "Claude · API",
    q: "Почему нельзя вызывать Anthropic API напрямую из браузера?",
    o: [
      "API-ключ попадёт в бандл и будет виден любому пользователю в DevTools",
      "Браузерный fetch не умеет отправлять нужные API HTTP-заголовки",
      "CORS полностью запрещает любые запросы из браузера к внешним API",
      "SDK написан только под Node.js и в браузере вообще не запускается",
    ],
    a: 0,
    e: "Ключ в клиентском коде — скомпрометирован (флаг в SDK так и называется: dangerouslyAllowBrowser). Правильно: браузер → свой бэкенд-прокси (BFF) → Anthropic; авторизация и rate limiting — на своей стороне.",
    en: {
      t: "Claude · API",
      q: "Why must you not call the Anthropic API directly from the browser?",
      o: [
        "The API key ends up in the bundle, visible to any user in DevTools",
        "The browser's fetch can't send the HTTP headers the API requires",
        "CORS completely forbids any browser requests to external APIs",
        "The SDK is Node.js-only and won't run in a browser at all",
      ],
      e: "A key in client code is compromised (the SDK flag is literally named dangerouslyAllowBrowser). The right shape: browser → your backend proxy (BFF) → Anthropic; auth and rate limiting live on your side.",
    },
  },
  {
    t: "Claude · API",
    q: "Как чат на Messages API «помнит» предыдущие сообщения диалога?",
    o: [
      "Никак сам по себе: клиент шлёт всю историю messages в каждом запросе",
      "Модель дообучается на каждом диалоге и запоминает пользователя навсегда",
      "API хранит сессию по ключу и сам подтягивает историю на сервере",
      "История сохраняется в cookie и передаётся с каждым запросом сама",
    ],
    a: 0,
    e: "API stateless: контекст = ровно то, что пришло в messages. «Память» — это твой код, который добавляет сообщения в историю (как иммутабельный state). Отсюда же рост цены с длиной диалога и приём prompt caching.",
    en: {
      t: "Claude · API",
      q: "How does a chat built on the Messages API \"remember\" earlier messages?",
      o: [
        "It doesn't by itself: the client sends the full messages history on every request",
        "The model fine-tunes on every conversation and remembers the user forever",
        "The API stores a session by key and pulls the history up server-side",
        "The history is saved in a cookie and travels with each request automatically",
      ],
      e: "The API is stateless: context = exactly what arrived in messages. \"Memory\" is your code appending to the history (like immutable state). That's also why cost grows with conversation length — and why prompt caching exists.",
    },
  },
  {
    t: "Claude · Агенты",
    q: "Что происходит, когда Claude «вызывает инструмент» (tool use)?",
    o: [
      "Модель возвращает имя функции и аргументы — исполняет её твой код",
      "Модель исполняет функцию в песочнице Anthropic и шлёт готовый результат",
      "SDK прозрачно исполняет функцию внутри модели без участия клиента",
      "Модель сама делает HTTP-запрос к твоему серверу и дёргает эндпоинт",
    ],
    a: 0,
    e: "Tool use — структурированный вывод, не удалённое исполнение: блок tool_use с именем и input. Твой код исполняет и возвращает tool_result. Значит, валидация, права и подтверждение опасных действий — твоя ответственность.",
    en: {
      t: "Claude · Agents",
      q: "What actually happens when Claude \"calls a tool\" (tool use)?",
      o: [
        "The model returns a function name and arguments — your code executes it",
        "The model runs the function in an Anthropic sandbox and sends back the result",
        "The SDK transparently executes the function inside the model, no client involved",
        "The model itself makes an HTTP request to your server and hits the endpoint",
      ],
      e: "Tool use is structured output, not remote execution: a tool_use block with a name and input. Your code executes it and returns a tool_result. So validation, permissions and confirming dangerous actions are on you.",
    },
  },
  {
    t: "Claude · Агенты",
    q: "Из чего состоит минимальный LLM-агент?",
    o: [
      "Модель + описанные инструменты + цикл «запрос → tool_use → tool_result»",
      "Модель + векторная база данных + пайплайн эмбеддингов для поиска",
      "Несколько моделей, которые голосуют и выбирают лучший общий ответ",
      "Модель + краулер, который заранее собирает и индексирует данные из сети",
    ],
    a: 0,
    e: "Агент = LLM + инструменты + цикл. Крутим запросы, пока stop_reason === \"tool_use\": исполняем запрошенную функцию, отдаём результат, модель решает следующий шаг. Всё остальное (RAG, память) — надстройки.",
    en: {
      t: "Claude · Agents",
      q: "What does a minimal LLM agent consist of?",
      o: [
        "A model + described tools + a \"request → tool_use → tool_result\" loop",
        "A model + a vector database + an embeddings pipeline for retrieval",
        "Several models that vote together and pick the single best answer",
        "A model + a crawler that pre-collects and indexes data from the internet",
      ],
      e: "Agent = LLM + tools + loop. Keep requesting while stop_reason === \"tool_use\": execute the requested function, return the result, the model decides the next step. Everything else (RAG, memory) is layered on top.",
    },
  },
  {
    t: "Claude · API",
    q: "Зачем нужен prompt caching в Claude API?",
    o: [
      "Повторяющийся префикс промпта читается из кэша ≈ за 10% цены input-токенов",
      "Одинаковый вопрос пользователя мгновенно вернёт закэшированный ответ бесплатно",
      "Модель кэширует свои веса ближе к пользователю и отвечает быстрее",
      "История диалога хранится на сервере, чтобы не пересылать её каждый раз",
    ],
    a: 0,
    e: "Кэшируется префикс запроса (system, инструменты, большие документы) по точному совпадению байтов. Чтение ≈ 0.1× цены. Поэтому стабильный контент — в начало промпта, изменяемый (вопрос, время) — в конец.",
    en: {
      t: "Claude · API",
      q: "What is prompt caching in the Claude API for?",
      o: [
        "A repeated prompt prefix is read from cache at ≈ 10% of the input-token price",
        "An identical user question instantly returns a cached answer for free",
        "The model caches its weights closer to the user and responds faster",
        "The conversation history is stored server-side so you don't resend it",
      ],
      e: "The request prefix (system, tools, large documents) is cached by exact byte match. Reads cost ≈ 0.1×. Hence the rule: stable content first in the prompt, volatile content (the question, timestamps) last.",
    },
  },
  {
    t: "Claude · Практика",
    q: "Как надёжно снизить вред от галлюцинаций LLM в продукте?",
    o: [
      "Источники в контексте (RAG / tool use), проверяемый вывод, человек в петле",
      "Строгая инструкция в промпте: «отвечай только правду и не выдумывай»",
      "Понизить temperature до нуля и добавить few-shot примеры с chain-of-thought",
      "Всегда брать самую большую модель — топовые модели не галлюцинируют",
    ],
    a: 0,
    e: "LLM — вероятностная модель текста: промпт «не врать» и temperature это не лечат. Архитектурные митигации: grounding источниками, structured outputs + валидация, human-in-the-loop там, где цена ошибки высока.",
    en: {
      t: "Claude · Practice",
      q: "How do you reliably reduce the damage from LLM hallucinations in a product?",
      o: [
        "Sources in context (RAG / tool use), verifiable output, a human in the loop",
        "A strict prompt instruction: \"only tell the truth and don't make things up\"",
        "Lowering temperature to zero and adding few-shot examples with chain-of-thought",
        "Always using the largest model — top models don't hallucinate",
      ],
      e: "An LLM is a probabilistic text model: a \"don't lie\" prompt and temperature don't fix that. The mitigations are architectural: grounding with sources, structured outputs + validation, human-in-the-loop where mistakes are expensive.",
    },
  },
  {
    t: "Claude · Практика",
    q: "Нужен от модели строго валидный JSON по схеме. Правильный способ — ...",
    o: [
      "Structured outputs: JSON-схема в output_config.format",
      "Попросить JSON в промпте и парсить ответ через try/catch",
      "Вставить JSON-схему в system-промпт и просить ей следовать",
      "Вырезать JSON из ответа регуляркой между ``` и ```",
    ],
    a: 0,
    e: "Structured outputs валидируют ответ по схеме на стороне API — модель физически не может вернуть невалидный JSON. Просьба в промпте — это надежда, а не гарантия.",
    en: {
      t: "Claude · Practice",
      q: "You need strictly schema-valid JSON from the model. The right way is...",
      o: [
        "Structured outputs: a JSON schema in output_config.format",
        "Asking for JSON in the prompt and parsing the reply with try/catch",
        "Pasting the JSON schema into the system prompt and asking to follow it",
        "Extracting the JSON from the reply with a regex between ``` fences",
      ],
      e: "Structured outputs validate the response against the schema on the API side — the model physically can't return invalid JSON. Asking in the prompt is hope, not a guarantee.",
    },
  },
  {
    t: "Claude · Экосистема",
    q: "Что такое MCP (Model Context Protocol)?",
    o: [
      "Открытый стандарт подключения LLM к внешним инструментам и данным",
      "Протокол сжатия контекста для экономии токенов в длинных диалогах",
      "Внутренний формат, в котором Claude хранит историю сообщений",
      "Обязательный формат системного промпта для моделей Anthropic",
    ],
    a: 0,
    e: "MCP — «USB-порт» для LLM: один открытый протокол подключает модель к GitHub, Jira, Figma, своей БД. Написал MCP-сервер один раз — работает с любым MCP-клиентом (Claude Code, Claude.ai и др.).",
    en: {
      t: "Claude · Ecosystem",
      q: "What is MCP (Model Context Protocol)?",
      o: [
        "An open standard for connecting LLMs to external tools and data",
        "A context-compression protocol for saving tokens in long conversations",
        "The internal format Claude uses to store message history",
        "The mandatory system-prompt format for Anthropic models",
      ],
      e: "MCP is a \"USB port\" for LLMs: one open protocol connects a model to GitHub, Jira, Figma, your DB. Write an MCP server once — it works with any MCP client (Claude Code, Claude.ai, etc.).",
    },
  },
  {
    t: "Claude · Экосистема",
    q: "Claude Code — это...",
    o: [
      "Агент в терминале/IDE: сам читает репозиторий, правит файлы, гоняет тесты",
      "Облачная IDE от Anthropic, призванная полностью заменить VS Code",
      "Плагин автокомплита, который подсказывает следующую строку кода",
      "Публичный датасет исходного кода, на котором обучали модели Claude",
    ],
    a: 0,
    e: "Claude Code — агентный инструмент для разработки (CLI, IDE-расширения, веб): модель сама исследует кодовую базу, вносит правки и проверяет их. Настраивается через CLAUDE.md и скиллы проекта.",
    en: {
      t: "Claude · Ecosystem",
      q: "Claude Code is...",
      o: [
        "An agent in the terminal/IDE: it reads the repo, edits files, runs tests itself",
        "A cloud-hosted IDE from Anthropic designed to fully replace VS Code",
        "An autocomplete plugin that suggests the next line of code as you type",
        "A public source-code dataset that the Claude models were trained on",
      ],
      e: "Claude Code is an agentic dev tool (CLI, IDE extensions, web): the model explores the codebase, makes edits and verifies them itself. It's configured via CLAUDE.md and project skills.",
    },
  },
];
