// Вопросы квиза: секция EnginX (инженерные практики)
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

export const ENGINX_QUESTIONS = [
  {
    t: "EnginX · Testing pyramid",
    q: "Почему в пирамиде e2e-тестов мало, а unit — много?",
    o: [
      "E2e сложнее писать, поэтому на них экономят время разработки",
      "E2e медленные, дорогие и флакуют; unit быстрые и стабильные — форма отражает стоимость",
      "Unit-тесты дают больше уверенности в работе приложения целиком",
      "Это историческая традиция из времён ручного тестирования",
    ],
    a: 1,
    e: "Чем выше уровень — тем больше уверенности на один тест, но хуже скорость и стабильность. Перевёрнутая пирамида («рожок мороженого») = 40-минутный флакующий CI, которому не верят.",
    en: {
      t: "EnginX · Testing pyramid",
      q: "Why does the testing pyramid have few e2e tests and many unit tests?",
      o: [
        "E2e tests are harder to write, so teams save development time by skipping them",
        "E2e tests are slow, expensive, and flaky; unit tests are fast and stable — the shape reflects cost",
        "Unit tests give more confidence that the whole application works correctly",
        "It's a historical tradition left over from the days of manual testing",
      ],
      e: "The higher the level, the more confidence each test provides, but the worse its speed and stability. An inverted pyramid (the 'ice cream cone') means a 40-minute flaky CI pipeline nobody trusts.",
    },
  },
  {
    t: "EnginX · Testing pyramid",
    q: "Какой тест НЕ сломается при рефакторинге без изменения поведения?",
    o: [
      "expect(dispatch).toHaveBeenCalledWith(addItem) — проверка вызова экшена",
      "expect(await screen.findByText(/добавлено/)).toBeInTheDocument() — видимый результат",
      "expect(component.state.isOpen).toBe(true) — проверка внутреннего состояния",
      "expect(mockSetState).toHaveBeenCalledTimes(2) — число обновлений state",
    ],
    a: 1,
    e: "Тесты реализации (state, моки внутренних функций) ломаются от рефакторинга и пропускают реальные баги. Девиз Testing Library: тестируй так, как использует пользователь.",
    en: {
      t: "EnginX · Testing pyramid",
      q: "Which test will NOT break from a refactor that doesn't change behavior?",
      o: [
        "expect(dispatch).toHaveBeenCalledWith(addItem) — checking that an action was dispatched",
        "expect(await screen.findByText(/added/)).toBeInTheDocument() — checking the visible result",
        "expect(component.state.isOpen).toBe(true) — checking internal state",
        "expect(mockSetState).toHaveBeenCalledTimes(2) — counting state updates",
      ],
      e: "Implementation tests (state, mocks of internal functions) break on refactors and miss real bugs. Testing Library's motto: test the way a user would use the app.",
    },
  },
  {
    t: "EnginX · Static analysis",
    q: "Как разделены роли ESLint и Prettier?",
    o: [
      "ESLint — для JS, Prettier — для TypeScript и стилей",
      "ESLint ищет проблемы в коде (unused, deps, a11y), Prettier только форматирует",
      "Prettier — быстрая замена ESLint, делают одно и то же",
      "ESLint работает в редакторе, Prettier — только в CI-пайплайне",
    ],
    a: 1,
    e: "Формат — не «ошибка», он либо применён автоматом, либо нет; проблемы кода — зона ESLint. Конфликт стилевых правил решает eslint-config-prettier.",
    en: {
      t: "EnginX · Static analysis",
      q: "How are the responsibilities of ESLint and Prettier divided?",
      o: [
        "ESLint is for JS, Prettier is for TypeScript and styles",
        "ESLint finds problems in the code (unused variables, missing deps, a11y issues); Prettier only formats",
        "Prettier is a fast replacement for ESLint — they do the same thing",
        "ESLint runs in the editor, Prettier only runs in the CI pipeline",
      ],
      e: "Formatting isn't an 'error' — it's either applied automatically or it isn't; code problems are ESLint's domain. Conflicts between stylistic rules are resolved by eslint-config-prettier.",
    },
  },
  {
    t: "EnginX · Static analysis",
    q: "Почему pre-commit хуки не заменяют проверки в CI?",
    o: [
      "Хуки работают только на macOS и Linux, но не на Windows",
      "Хуки обходятся (--no-verify, свежий клон без husky) — источник правды только CI",
      "CI проверяет код быстрее, чем локальная машина разработчика",
      "Pre-commit не умеет запускать ESLint и TypeScript одновременно",
    ],
    a: 1,
    e: "Локальные хуки — удобство для быстрой обратной связи. Гарантия — только сервер: те же команды (lint, tsc --noEmit, тесты) обязаны бежать на каждый PR.",
    en: {
      t: "EnginX · Static analysis",
      q: "Why don't pre-commit hooks replace checks in CI?",
      o: [
        "Hooks only work on macOS and Linux, not on Windows",
        "Hooks can be bypassed (--no-verify, a fresh clone without husky) — CI is the only source of truth",
        "CI checks code faster than a developer's local machine",
        "Pre-commit can't run ESLint and TypeScript at the same time",
      ],
      e: "Local hooks are a convenience for fast feedback. The guarantee comes only from the server: the same commands (lint, tsc --noEmit, tests) must run on every PR.",
    },
  },
  {
    t: "EnginX · Branching",
    q: "Чем trunk-based development отличается от GitHub Flow?",
    o: [
      "Trunk-based полностью запрещает pull request-ы и код-ревью как замедляющие поток практики",
      "Ветки живут часы, мердж в main минимум ежедневно, недоделки прячутся за feature-флагами",
      "В trunk-based интеграционной веткой служит develop, а main остаётся только для релизов",
      "Это одна и та же модель ветвления — просто разные названия у разных компаний",
    ],
    a: 1,
    e: "GitHub Flow: ветки живут дни, merge = deployable. Trunk-based радикальнее: интеграция ежедневно, обязательны сильный CI и флаги — это фундамент continuous deployment.",
    en: {
      t: "EnginX · Branching",
      q: "How does trunk-based development differ from GitHub Flow?",
      o: [
        "Trunk-based completely bans pull requests and code review as practices that slow down the flow",
        "Branches live for hours, merges into main happen at least daily, unfinished work is hidden behind feature flags",
        "In trunk-based development, develop serves as the integration branch while main is reserved for releases",
        "It's the same branching model — just different names used by different companies",
      ],
      e: "GitHub Flow: branches live for days, a merge means deployable. Trunk-based is more radical: daily integration, a strong CI pipeline, and feature flags are mandatory — this is the foundation of continuous deployment.",
    },
  },
  {
    t: "EnginX · Branching",
    q: "Когда git push --force допустим?",
    o: [
      "Всегда — это обычная команда для обновления удалённой ветки",
      "Только в свою ветку и лучше --force-with-lease; общую историю не переписывают",
      "Только при пуше в main — чтобы принудительно поддерживать линейную историю коммитов",
      "Никогда и нигде — force push полностью запрещён в любых корректных git-процессах",
    ],
    a: 1,
    e: "Переписывать можно то, что никто не забрал: свою ветку после rebase. --force-with-lease откажет, если удалёнка ушла вперёд. Общие ветки защищают branch protection.",
    en: {
      t: "EnginX · Branching",
      q: "When is git push --force acceptable?",
      o: [
        "Always — it's a normal command for updating a remote branch",
        "Only on your own branch, and preferably with --force-with-lease; shared history is never rewritten",
        "Only when pushing to main — to forcibly keep a linear commit history",
        "Never, anywhere — force push is completely forbidden in any correct git workflow",
      ],
      e: "You can rewrite what nobody else has pulled: your own branch after a rebase. --force-with-lease will refuse if the remote has moved ahead. Shared branches are protected by branch protection rules.",
    },
  },
  {
    t: "EnginX · Design patterns",
    q: "store.subscribe(listener) в Redux — какой это паттерн?",
    o: [
      "Singleton — стор существует в единственном экземпляре",
      "Observer (pub/sub): подписчики уведомляются об изменении состояния",
      "Factory — подписка производит новые объекты-слушатели",
      "Decorator — слушатель оборачивает поведение стора",
    ],
    a: 1,
    e: "Классический observer: множество слушателей реагируют на событие. Та же механика — addEventListener, useSyncExternalStore, EventEmitter.",
    en: {
      t: "EnginX · Design patterns",
      q: "What pattern is store.subscribe(listener) in Redux an example of?",
      o: [
        "Singleton — the store exists as a single instance",
        "Observer (pub/sub): subscribers are notified when the state changes",
        "Factory — subscribing produces new listener objects",
        "Decorator — the listener wraps the store's behavior",
      ],
      e: "A classic observer: multiple listeners react to an event. Same mechanism as addEventListener, useSyncExternalStore, EventEmitter.",
    },
  },
  {
    t: "EnginX · Design patterns",
    q: "Как идиоматично сделать синглтон в современном JS?",
    o: [
      "Класс со static getInstance(), как в классических языках ООП",
      "Экспортировать экземпляр из ES-модуля — модуль выполняется один раз",
      "Глобальная переменная window.instance с проверкой на существование",
      "Замыкание с приватным флагом created внутри фабрики",
    ],
    a: 1,
    e: "ES-модуль выполняется однократно и кэшируется — export const api = new Client() уже синглтон. getInstance в JS — перенос чужих идиом.",
    en: {
      t: "EnginX · Design patterns",
      q: "What's the idiomatic way to implement a singleton in modern JS?",
      o: [
        "A class with a static getInstance(), like in classic OOP languages",
        "Export an instance from an ES module — the module executes only once",
        "A global window.instance variable with an existence check",
        "A closure with a private created flag inside a factory function",
      ],
      e: "An ES module executes exactly once and is cached — export const api = new Client() is already a singleton. getInstance() in JS is just importing idioms from other languages.",
    },
  },
  {
    t: "EnginX · Antipatterns",
    q: "Что не так?\nconst [filtered, setFiltered] = useState([]);\nuseEffect(() => { setFiltered(items.filter(f)); }, [items]);",
    o: [
      "Метод filter слишком медленный, чтобы вызывать его внутри эффекта на каждом изменении",
      "Производное состояние через эффект: лишний рендер и риск рассинхрона — нужно вычислять при рендере",
      "В массиве deps не хватает функции f, поэтому эффект захватит её устаревшую версию",
      "Вызывать setFiltered внутри useEffect запрещено правилами хуков — только в обработчиках",
    ],
    a: 1,
    e: "То, что вычисляется из имеющихся данных, — не state: const filtered = items.filter(f) (дорого — useMemo). Антипаттерн №1 фронтенда, порождает каскады рендеров.",
    en: {
      t: "EnginX · Antipatterns",
      q: "What's wrong here?\nconst [filtered, setFiltered] = useState([]);\nuseEffect(() => { setFiltered(items.filter(f)); }, [items]);",
      o: [
        "The filter method is too slow to call inside an effect on every change",
        "Derived state computed via an effect: causes an extra render and risks getting out of sync — it should be computed during render instead",
        "The deps array is missing the function f, so the effect captures a stale version of it",
        "Calling setFiltered inside useEffect is forbidden by the rules of hooks — only in event handlers",
      ],
      e: "Anything that can be computed from existing data isn't state: const filtered = items.filter(f) (if it's expensive, use useMemo). Frontend antipattern #1 — it causes cascading re-renders.",
    },
  },
  {
    t: "EnginX · Antipatterns",
    q: "«Дублирование дешевле неправильной абстракции» — о чём это правило?",
    o: [
      "Копирование кода всегда предпочтительнее выделения общих функций и модулей",
      "Общий хелпер, погнутый флагами под разных потребителей, дороже двух похожих кусков кода",
      "Общие абстракции нужно проектировать заранее, ещё до первого повторения кода",
      "Принцип DRY устарел и в современной разработке уже не применяется на практике",
    ],
    a: 1,
    e: "Санди Метц: плохая абстракция обрастает флагами и комбинациями, которые страшно править. Практика — правило трёх: абстрагируй после третьего повторения, по реальным осям.",
    en: {
      t: "EnginX · Antipatterns",
      q: "What does the rule 'duplication is cheaper than the wrong abstraction' mean?",
      o: [
        "Copying code is always preferable to extracting shared functions and modules",
        "A shared helper bent out of shape with flags for different consumers ends up costing more than two similar pieces of code",
        "Shared abstractions should be designed up front, before the first duplication even happens",
        "The DRY principle is outdated and no longer applied in modern development",
      ],
      e: "Sandi Metz: a bad abstraction accumulates flags and combinations that become terrifying to change. In practice, follow the rule of three: abstract after the third repetition, along real axes of variation.",
    },
  },
  {
    t: "EnginX · CI/CD",
    q: "Разница между Continuous Delivery и Continuous Deployment?",
    o: [
      "Delivery — для веба, Deployment — для мобильных приложений",
      "Delivery: зелёный билд готов, деплой кнопкой; Deployment: в прод автоматически, кнопки нет",
      "Deployment включает тесты, Delivery ограничивается сборкой",
      "Это синонимы — обе аббревиатуры означают автодеплой в прод",
    ],
    a: 1,
    e: "Мнемоника: Delivery доставляет до двери (человек решает, когда занести), Deployment заносит в дом сам. Deployment требует флагов, canary и зрелого мониторинга.",
    en: {
      t: "EnginX · CI/CD",
      q: "What's the difference between Continuous Delivery and Continuous Deployment?",
      o: [
        "Delivery is for web, Deployment is for mobile apps",
        "Delivery: a green build is ready and deploy is one button click; Deployment: it goes to production automatically, no button needed",
        "Deployment includes tests, Delivery is limited to the build step",
        "They're synonyms — both terms mean automatic deployment to production",
      ],
      e: "Mnemonic: Delivery drops the package at the door (a human decides when to bring it inside), Deployment carries it in itself. Deployment requires feature flags, canary releases, and mature monitoring.",
    },
  },
  {
    t: "EnginX · CI/CD",
    q: "Что такое canary-выкат?",
    o: [
      "Деплой в отдельное тестовое окружение перед продом",
      "Новая версия сначала на 1-5% пользователей, по метрикам — расширение или откат",
      "Ручное тестирование релиза командой QA перед выкаткой",
      "Параллельная работа двух версий прода с мгновенным переключением",
    ],
    a: 1,
    e: "Канарейка ограничивает радиус поражения плохого релиза. Вариант с двумя окружениями и переключением — это blue-green.",
    en: {
      t: "EnginX · CI/CD",
      q: "What is a canary release?",
      o: [
        "Deploying to a separate test environment before production",
        "The new version first goes to 1-5% of users; based on metrics, it's either expanded or rolled back",
        "Manual testing of a release by the QA team before rollout",
        "Two production versions running in parallel with instant switchover",
      ],
      e: "A canary release limits the blast radius of a bad release. The variant with two environments and a switchover is blue-green deployment.",
    },
  },
  {
    t: "EnginX · OWASP",
    q: "Почему JWT в localStorage считается рискованным?",
    o: [
      "localStorage ограничен пятью мегабайтами и токен может не поместиться",
      "Любой XSS-скрипт прочитает токен; httpOnly cookie для JS недоступна",
      "localStorage очищается при закрытии вкладки и сессия теряется",
      "Токены в localStorage не отправляются в заголовках запросов",
    ],
    a: 1,
    e: "XSS + localStorage = украденный токен работает до истечения. httpOnly cookie XSS-скрипт не видит (хотя запросы от имени юзера всё ещё возможны — поэтому ещё и SameSite, короткий TTL).",
    en: {
      t: "EnginX · OWASP",
      q: "Why is storing a JWT in localStorage considered risky?",
      o: [
        "localStorage is limited to five megabytes and the token might not fit",
        "Any XSS script can read the token; an httpOnly cookie is inaccessible to JS",
        "localStorage is cleared when the tab closes and the session is lost",
        "Tokens in localStorage aren't sent in request headers",
      ],
      e: "XSS + localStorage = a stolen token that works until it expires. An XSS script can't see an httpOnly cookie (though requests on the user's behalf are still possible — which is why you also need SameSite and a short TTL).",
    },
  },
  {
    t: "EnginX · OWASP",
    q: "React экранирует {userInput} автоматически. Где XSS всё-таки проходит?",
    o: [
      "Нигде — React полностью закрывает XSS во всех случаях",
      "dangerouslySetInnerHTML, href с javascript:-URL, innerHTML через ref",
      "Только в классовых компонентах со старым синтаксисом",
      "Только при отключённом StrictMode в продакшен-сборке",
    ],
    a: 1,
    e: "Экранируется только интерполяция. Сырой HTML — через санитизацию (DOMPurify), URL — валидировать протокол, плюс CSP вторым слоем.",
    en: {
      t: "EnginX · OWASP",
      q: "React automatically escapes {userInput}. Where can XSS still get through?",
      o: [
        "Nowhere — React completely closes off XSS in all cases",
        "dangerouslySetInnerHTML, an href with a javascript: URL, innerHTML via a ref",
        "Only in class components using the old syntax",
        "Only when StrictMode is disabled in a production build",
      ],
      e: "Only interpolation is escaped. Raw HTML needs sanitization (DOMPurify), URLs need protocol validation, plus CSP as a second layer of defense.",
    },
  },
  {
    t: "EnginX · OWASP",
    q: "VITE_API_SECRET=sk-live-... в .env фронтенда — что с этим?",
    o: [
      "Нормально — .env не коммитится в репозиторий, значит секрет защищён",
      "Всё с префиксом VITE_ попадает в бандл — секрет публичен; секретные операции только через бэкенд",
      "Это безопасно, если при продакшен-сборке включены минификация и обфускация кода",
      "Опасно только в dev-режиме, в продакшен-сборке переменные вырезаются",
    ],
    a: 1,
    e: "Бандл читается любым желающим — «спрятать» ключ на клиенте невозможно (в RN то же: байткод декомпилируется). Секреты живут на сервере, клиент ходит через прокси.",
    en: {
      t: "EnginX · OWASP",
      q: "VITE_API_SECRET=sk-live-... in a frontend .env file — what's wrong with this?",
      o: [
        "It's fine — .env isn't committed to the repository, so the secret is protected",
        "Anything with the VITE_ prefix gets baked into the bundle — the secret becomes public; secret operations must go through the backend",
        "It's safe as long as the production build has minification and code obfuscation enabled",
        "It's only dangerous in dev mode; the variables get stripped out in the production build",
      ],
      e: "The bundle can be read by anyone — there's no way to 'hide' a key on the client (same in React Native: the bytecode can be decompiled). Secrets live on the server; the client talks to it through a proxy.",
    },
  },
  {
    t: "EnginX · SDLC",
    q: "Назови фазы SDLC по порядку.",
    o: [
      "Планирование → кодирование → релиз → маркетинг → поддержка продаж",
      "Требования → проектирование → реализация → тестирование → развёртывание → сопровождение",
      "Идея → прототип → инвестиции → масштабирование → продажа компании",
      "Дизайн → вёрстка → интеграция → приёмка заказчиком → архивация",
    ],
    a: 1,
    e: "Фазы постоянны, методологии (waterfall/Scrum/Kanban) отличаются способом их обхода: один проход vs короткие итерации.",
    en: {
      t: "EnginX · SDLC",
      q: "Name the SDLC phases in order.",
      o: [
        "Planning → coding → release → marketing → sales support",
        "Requirements → design → implementation → testing → deployment → maintenance",
        "Idea → prototype → investment → scaling → company sale",
        "Design → markup → integration → client acceptance → archiving",
      ],
      e: "The phases stay constant; methodologies (waterfall/Scrum/Kanban) differ in how they traverse them: a single pass vs. short iterations.",
    },
  },
  {
    t: "EnginX · SDLC",
    q: "Почему ошибку в требованиях важно поймать ДО кода?",
    o: [
      "Потому что аналитики обижаются, когда их правки приходят поздно",
      "Цена ошибки растёт на порядок с каждой фазой: разговор на refinement против миграций в проде",
      "После старта спринта требования запрещено менять правилами Scrum",
      "Ошибки в требованиях невозможно исправить после написания кода",
    ],
    a: 1,
    e: "Кривой контракт API на design-фазе — 30 минут разговора; в проде — хотфиксы и миграции. Поэтому senior активно участвует в requirements/design, а не «просто кодирует таску».",
    en: {
      t: "EnginX · SDLC",
      q: "Why is it important to catch a requirements error BEFORE writing code?",
      o: [
        "Because business analysts get offended when their corrections come in late",
        "The cost of an error grows by an order of magnitude with every phase: a conversation during refinement vs. migrations in production",
        "Scrum rules forbid changing requirements after a sprint has started",
        "Requirements errors can't be fixed once the code has already been written",
      ],
      e: "A flawed API contract caught at the design phase is a 30-minute conversation; caught in production it's hotfixes and migrations. That's why a senior engineer actively participates in requirements/design instead of just 'coding the ticket'.",
    },
  },
  {
    t: "EnginX · SDLC",
    q: "Зачем в Kanban нужны WIP-лимиты («не больше 3 задач In Progress»)?",
    o: [
      "Чтобы менеджер видел, кто из разработчиков работает медленнее остальных",
      "Ограничение параллельной работы ускоряет ПОТОК: задачи доделываются, а не копятся начатыми",
      "Чтобы в спринт нельзя было добавить больше задач, чем влезает по оценкам",
      "Это техническое ограничение досок Jira, а не осознанная практика команды",
    ],
    a: 1,
    e: "Kanban оптимизирует lead time: 10 начатых задач = ни одной законченной и постоянные переключения контекста. Лимит заставляет доделывать перед стартом нового (stop starting, start finishing).",
    en: {
      t: "EnginX · SDLC",
      q: "Why does Kanban use WIP limits ('no more than 3 tasks In Progress')?",
      o: [
        "So the manager can see which developers are working slower than the rest",
        "Limiting parallel work speeds up FLOW: tasks get finished instead of piling up half-done",
        "So that a sprint can't have more tasks added than the estimates allow",
        "It's a technical limitation of Jira boards, not a deliberate team practice",
      ],
      e: "Kanban optimizes for lead time: 10 tasks in progress simultaneously means zero finished and constant context switching. The limit forces work to be finished before something new is started (stop starting, start finishing).",
    },
  },
  {
    t: "EnginX · Branching",
    q: "Что даёт формат conventional commits (feat:, fix:, feat!:)?",
    o: [
      "Красивую и единообразную историю коммитов для внешних аудиторов",
      "Автоматику: генерация changelog и вычисление semver-версии (fix→patch, feat→minor, !→major)",
      "Возможность откатывать коммиты по типу — только fix или только feat",
      "Ускорение CI: пайплайн пропускает проверки для коммитов типа chore",
    ],
    a: 1,
    e: "Тип коммита — машиночитаемый сигнал: semantic-release сам поднимает версию и собирает changelog. Без конвенции релизные заметки пишутся руками.",
    en: {
      t: "EnginX · Branching",
      q: "What does the conventional commits format (feat:, fix:, feat!:) give you?",
      o: [
        "A neat, consistent commit history for external auditors",
        "Automation: changelog generation and semver version calculation (fix→patch, feat→minor, !→major)",
        "The ability to revert commits by type — only fix commits or only feat commits",
        "Faster CI: the pipeline skips checks for chore-type commits",
      ],
      e: "The commit type is a machine-readable signal: semantic-release automatically bumps the version and assembles the changelog. Without the convention, release notes have to be written by hand.",
    },
  },
  {
    t: "EnginX · Branching",
    q: "Зачем делать rebase своей ветки на свежий main перед PR?",
    o: [
      "Rebase автоматически разрешает все конфликты, которые merge разрешить не может",
      "История линейная, конфликты разруливаются у себя до ревью, diff PR содержит только свои изменения",
      "После rebase пайплайн CI проходит быстрее, потому что коммитов становится меньше",
      "Это единственный способ подтянуть чужие изменения из main в свою ветку",
    ],
    a: 1,
    e: "Merge из main тоже подтянет изменения, но замусорит историю merge-коммитами. Rebase переписывает СВОЮ ветку — это безопасно, пока её никто не забрал.",
    en: {
      t: "EnginX · Branching",
      q: "Why rebase your branch onto the latest main before opening a PR?",
      o: [
        "Rebase automatically resolves all conflicts that a merge can't resolve",
        "History stays linear, conflicts are resolved locally before review, and the PR diff contains only your own changes",
        "After a rebase, the CI pipeline runs faster because there are fewer commits",
        "It's the only way to pull other people's changes from main into your branch",
      ],
      e: "Merging from main would also pull in the changes, but it clutters history with merge commits. Rebase rewrites YOUR OWN branch — which is safe as long as nobody else has pulled it.",
    },
  },
  {
    t: "EnginX · CI/CD",
    q: "Чем blue-green отличается от canary?",
    o: [
      "Blue-green применяется для бэкенда, canary придуман для фронтенд-приложений",
      "Blue-green: два прода и переключение трафика разом; canary: новая версия постепенно на часть юзеров",
      "Canary требует Kubernetes, а blue-green работает на любой инфраструктуре",
      "Blue-green деплоит без даунтайма, а canary всегда требует окна обслуживания",
    ],
    a: 1,
    e: "Blue-green даёт мгновенный откат (переключить обратно), но всё-или-ничего. Canary ограничивает радиус поражения процентом пользователей и решает по метрикам.",
    en: {
      t: "EnginX · CI/CD",
      q: "How does blue-green deployment differ from canary?",
      o: [
        "Blue-green is used for backends, canary was designed for frontend applications",
        "Blue-green: two production environments and traffic is switched all at once; canary: the new version gradually rolls out to a portion of users",
        "Canary requires Kubernetes, while blue-green works on any infrastructure",
        "Blue-green deploys with zero downtime, while canary always requires a maintenance window",
      ],
      e: "Blue-green gives you an instant rollback (just switch back), but it's all-or-nothing. Canary limits the blast radius to a percentage of users and decides based on metrics.",
    },
  },
  {
    t: "EnginX · CI/CD",
    q: "«Выкат кода ≠ включение фичи» — как это достигается?",
    o: [
      "Кодом в отдельной ветке, которую мерджат только в момент запуска фичи",
      "Feature-флагами: код едет в прод выключенным, включение — без деплоя, можно по сегментам",
      "Комментированием нового кода до даты релиза и раскомментированием в день запуска",
      "Отдельным продакшен-окружением для каждой крупной разрабатываемой фичи",
    ],
    a: 1,
    e: "Флаг разделяет технический деплой и продуктовый запуск: код в проде, но тёмный. Это же — предпосылка trunk-based и мгновенный kill switch при проблемах.",
    en: {
      t: "EnginX · CI/CD",
      q: "'Deploying code ≠ enabling a feature' — how is this achieved?",
      o: [
        "By keeping the code in a separate branch that's only merged when the feature launches",
        "With feature flags: the code ships to production disabled, and enabling it requires no deploy and can be rolled out by segment",
        "By commenting out the new code until the release date and uncommenting it on launch day",
        "By having a separate production environment for every major feature under development",
      ],
      e: "A feature flag separates the technical deploy from the product launch: the code is in production, but dark. This is also a prerequisite for trunk-based development and gives you an instant kill switch when something goes wrong.",
    },
  },
  {
    t: "EnginX · Testing pyramid",
    q: "Чем пишут e2e-тесты для React Native?",
    o: [
      "Playwright и Cypress — они универсальны и работают с любыми приложениями",
      "Detox или Maestro: гоняют реальное приложение на симуляторе/устройстве",
      "Testing Library с jsdom — она полностью эмулирует мобильное окружение",
      "Только вручную: автоматизация e2e для мобильных приложений невозможна",
    ],
    a: 1,
    e: "Playwright/Cypress управляют браузером — в RN браузера нет. Detox (grey-box, синхронизация с RN) и Maestro (простые yaml-флоу) работают с нативным приложением.",
    en: {
      t: "EnginX · Testing pyramid",
      q: "What tools are used to write e2e tests for React Native?",
      o: [
        "Playwright and Cypress — they're universal and work with any application",
        "Detox or Maestro: they run the real app on a simulator/device",
        "Testing Library with jsdom — it fully emulates the mobile environment",
        "Only manually: e2e automation is impossible for mobile applications",
      ],
      e: "Playwright/Cypress drive a browser — React Native has no browser. Detox (grey-box, synchronized with RN) and Maestro (simple YAML flows) work with the native app instead.",
    },
  },
  {
    t: "EnginX · Testing pyramid",
    q: "Почему в интеграционных тестах сеть мокают на уровне network (MSW), а не подменой fetch/axios?",
    o: [
      "MSW работает существенно быстрее, чем jest.mock для модуля с fetch-обёрткой",
      "Тест не знает, ЧЕМ ходят в сеть: рефакторинг fetch→axios не ломает тесты, мок ближе к реальности",
      "Подмена fetch запрещена в строгом режиме и последних версиях Node.js",
      "MSW единственный умеет мокать одновременно REST и GraphQL-запросы",
    ],
    a: 1,
    e: "jest.mock('api') привязывает тест к реализации. MSW перехватывает сам запрос — тестируется весь путь до сериализации, а смена HTTP-клиента ничего не ломает.",
    en: {
      t: "EnginX · Testing pyramid",
      q: "Why do integration tests mock the network at the network level (MSW) instead of replacing fetch/axios?",
      o: [
        "MSW is significantly faster than jest.mock for a module with a fetch wrapper",
        "The test doesn't know WHAT is used to make network calls: refactoring fetch→axios doesn't break the tests, and the mock is closer to reality",
        "Replacing fetch is forbidden in strict mode and recent versions of Node.js",
        "MSW is the only tool that can mock REST and GraphQL requests at the same time",
      ],
      e: "jest.mock('api') ties the test to the implementation. MSW intercepts the actual request — the whole path down to serialization gets tested, and switching HTTP clients breaks nothing.",
    },
  },
  {
    t: "EnginX · Static analysis",
    q: "Зачем в CI запускают tsc --noEmit, если сборку делает Vite?",
    o: [
      "Чтобы прогреть кэш TypeScript до запуска основной продакшен-сборки",
      "Vite/esbuild ТОЛЬКО СТИРАЮТ типы без проверки — ошибки типов сборку не валят, нужен отдельный tsc",
      "tsc --noEmit генерирует .d.ts файлы, необходимые для публикации пакета",
      "Это устаревшая практика из эпохи webpack, с Vite она уже не нужна",
    ],
    a: 1,
    e: "Транспиляция esbuild — не type checking: проект с ошибками типов соберётся успешно. Полная проверка — только tsc --noEmit (или vue-tsc/tsgo) отдельным шагом.",
    en: {
      t: "EnginX · Static analysis",
      q: "Why does CI run tsc --noEmit if Vite already handles the build?",
      o: [
        "To warm up the TypeScript cache before the main production build runs",
        "Vite/esbuild ONLY STRIP types without checking them — type errors don't fail the build, so a separate tsc run is needed",
        "tsc --noEmit generates the .d.ts files required to publish a package",
        "It's an outdated practice left over from the webpack era, no longer needed with Vite",
      ],
      e: "esbuild's transpilation is not type checking: a project with type errors will still build successfully. Full type checking only happens via a separate tsc --noEmit (or vue-tsc/tsgo) step.",
    },
  },
  {
    t: "EnginX · Static analysis",
    q: "Что находит knip (и подобные инструменты)?",
    o: [
      "Уязвимости в зависимостях по базам CVE, как npm audit, но глубже",
      "Мёртвый код: неиспользуемые экспорты, файлы и зависимости в package.json",
      "Циклические импорты между модулями, замедляющие холодный старт сборки",
      "Дубликаты кода, скопированные между разными файлами проекта",
    ],
    a: 1,
    e: "ESLint видит неиспользуемое ВНУТРИ файла, но export «используется» самим фактом экспорта. Knip анализирует граф проекта целиком — находит то, что никто не импортирует.",
    en: {
      t: "EnginX · Static analysis",
      q: "What does knip (and similar tools) find?",
      o: [
        "Vulnerabilities in dependencies against CVE databases, like npm audit but deeper",
        "Dead code: unused exports, files, and dependencies in package.json",
        "Circular imports between modules that slow down cold build start",
        "Duplicate code copied between different files in the project",
      ],
      e: "ESLint sees what's unused WITHIN a file, but an export is considered 'used' by the mere fact of being exported. Knip analyzes the whole project graph and finds what nobody actually imports.",
    },
  },
  {
    t: "EnginX · Design patterns",
    q: "Tabs.Tab и Tabs.Panel с общим состоянием через контекст — что за паттерн?",
    o: [
      "Render props: компоненты передают друг другу функции рендеринга",
      "Compound components: связанные компоненты делят состояние, раскладку контролирует потребитель",
      "Higher-order component: Tabs оборачивает дочерние компоненты новым поведением",
      "Мемоизированный контейнер: Tabs кэширует отрендеренные панели между переключениями",
    ],
    a: 1,
    e: "Состояние общее (через Context), но структуру и порядок задаёт использующий код — гибкость, которой нет у пропа items. Так устроены Radix UI и Headless UI.",
    en: {
      t: "EnginX · Design patterns",
      q: "Tabs.Tab and Tabs.Panel sharing state through context — what pattern is this?",
      o: [
        "Render props: components pass rendering functions to each other",
        "Compound components: related components share state, while the consumer controls the layout",
        "Higher-order component: Tabs wraps child components with new behavior",
        "Memoized container: Tabs caches rendered panels between switches",
      ],
      e: "The state is shared (via Context), but the consuming code determines structure and order — flexibility that an items prop doesn't offer. This is how Radix UI and Headless UI are built.",
    },
  },
  {
    t: "EnginX · Design patterns",
    q: "На каком паттерне/механизме построена «магия» Immer и MobX?",
    o: [
      "Observer: библиотека подписывается на каждое свойство через addEventListener",
      "Proxy: объект-перехватчик ловит чтения и записи свойств и реагирует на них",
      "Decorator: каждое свойство оборачивается функцией с дополнительной логикой",
      "Singleton: единый глобальный стор отслеживает все изменения приложения",
    ],
    a: 1,
    e: "Proxy перехватывает get/set: Immer записывает «мутации» драфта и строит новый иммутабельный объект, MobX отслеживает, какие поля прочитал компонент, чтобы точечно его обновлять.",
    en: {
      t: "EnginX · Design patterns",
      q: "What pattern/mechanism powers the 'magic' behind Immer and MobX?",
      o: [
        "Observer: the library subscribes to every property via addEventListener",
        "Proxy: an intercepting object catches property reads and writes and reacts to them",
        "Decorator: every property is wrapped in a function with extra logic",
        "Singleton: a single global store tracks every change in the application",
      ],
      e: "Proxy intercepts get/set: Immer records 'mutations' of a draft and builds a new immutable object, while MobX tracks which fields a component read so it can update it precisely.",
    },
  },
  {
    t: "EnginX · Antipatterns",
    q: "Что сломается?\nfunction Profile({ user }) {\n  const [name, setName] = useState(user.name);\n  ...",
    o: [
      "Ничего — это стандартный способ сделать поле формы редактируемым",
      "Копия props в state: при обновлении user сверху name НЕ обновится — две рассинхронизированные правды",
      "useState нельзя инициализировать значением из props по правилам хуков",
      "name будет сбрасываться при каждом ре-рендере родительского компонента",
    ],
    a: 1,
    e: "useState читает initial только при монтировании. Пришёл новый user — name остался старым. Фиксы: контролируемое поле снаружи или key={user.id} для честного сброса формы.",
    en: {
      t: "EnginX · Antipatterns",
      q: "What will break?\nfunction Profile({ user }) {\n  const [name, setName] = useState(user.name);\n  ...",
      o: [
        "Nothing — this is the standard way to make a form field editable",
        "Copying props into state: when user updates from above, name will NOT update — two sources of truth get out of sync",
        "useState can't be initialized with a value from props under the rules of hooks",
        "name will reset on every re-render of the parent component",
      ],
      e: "useState reads its initial value only on mount. A new user comes in — name stays stale. Fixes: make the field controlled from outside, or use key={user.id} to properly reset the form.",
    },
  },
  {
    t: "EnginX · OWASP",
    q: "Как SameSite-атрибут cookie защищает от CSRF?",
    o: [
      "Шифрует содержимое cookie так, что чужой сайт не может его прочитать",
      "Браузер не отправляет cookie с запросами, инициированными с чужого сайта — атака теряет сессию",
      "Привязывает cookie к IP-адресу пользователя и отклоняет запросы с других адресов",
      "Заставляет сервер проверять заголовок Referer у каждого входящего запроса",
    ],
    a: 1,
    e: "CSRF работает потому, что браузер шлёт cookie автоматически с любым запросом к домену. SameSite=Lax/Strict отрезает их для cross-site запросов — форма с чужого сайта приходит без сессии.",
    en: {
      t: "EnginX · OWASP",
      q: "How does the SameSite cookie attribute protect against CSRF?",
      o: [
        "It encrypts the cookie's contents so that another site can't read it",
        "The browser doesn't send the cookie with requests initiated from another site — the attack loses the session",
        "It ties the cookie to the user's IP address and rejects requests from other addresses",
        "It forces the server to check the Referer header on every incoming request",
      ],
      e: "CSRF works because the browser automatically sends cookies with any request to a domain. SameSite=Lax/Strict cuts them off for cross-site requests — a form submitted from another site arrives without a session.",
    },
  },
  {
    t: "EnginX · Branching",
    q: "Для какого продукта Git Flow (develop + release/hotfix-ветки) остаётся оправданным?",
    o: [
      "Для веб-приложения с деплоем в прод по несколько раз в день",
      "Для продукта с версионными релизами: мобильное приложение в сторах, on-prem софт",
      "Для прототипа-одиночки, где вся разработка идёт в одной ветке",
      "Ни для какого — Git Flow полностью устарел и заменён trunk-based",
    ],
    a: 1,
    e: "Release-ветка — место стабилизации перед релизом, который нельзя откатить кнопкой (ревью стора — дни). Для continuous delivery веба церемония Git Flow — накладные расходы.",
    en: {
      t: "EnginX · Branching",
      q: "For what kind of product does Git Flow (develop + release/hotfix branches) still make sense?",
      o: [
        "For a web application that deploys to production multiple times a day",
        "For a product with versioned releases: a mobile app distributed through app stores, on-prem software",
        "For a solo prototype where all development happens on a single branch",
        "For none — Git Flow is completely obsolete and has been replaced by trunk-based development",
      ],
      e: "A release branch is a place to stabilize before a release that can't be rolled back with a button click (app store review takes days). For a web app doing continuous delivery, Git Flow's ceremony is just overhead.",
    },
  },
  {
    t: "EnginX · Design patterns",
    q: "Каким паттерном заменить эту цепочку?\nif (status === 'loading') return <Spinner />;\nif (status === 'error') return <Retry />;\nif (status === 'ready') return <List />;",
    o: [
      "Observer: подписать компоненты на изменения переменной status",
      "Strategy: map Record<Status, Renderer> и вызов renderers[status]()",
      "Singleton: вынести проверку статуса в единый глобальный сервис",
      "Decorator: обернуть каждый компонент функцией проверки статуса",
    ],
    a: 1,
    e: "Map по ключу вместо if-цепочки — паттерн Strategy в JS-идиоме. Бонус с TS: Record<Status, ...> заставит добавить рендерер при расширении union-а.",
    en: {
      t: "EnginX · Design patterns",
      q: "What pattern can replace this chain?\nif (status === 'loading') return <Spinner />;\nif (status === 'error') return <Retry />;\nif (status === 'ready') return <List />;",
      o: [
        "Observer: subscribe components to changes in the status variable",
        "Strategy: a Record<Status, Renderer> map and calling renderers[status]()",
        "Singleton: move the status check into a single global service",
        "Decorator: wrap each component in a function that checks the status",
      ],
      e: "A key-based map instead of an if-chain — the Strategy pattern in a JS idiom. Bonus with TS: Record<Status, ...> forces you to add a renderer when the union is extended.",
    },
  },
  {
    t: "EnginX · Antipatterns",
    q: "Почему приложение шлёт тысячи запросов?\nuseEffect(() => {\n  fetch('/api/items').then(r => r.json()).then(setItems);\n}, [items]);",
    o: [
      "Сервер отвечает слишком медленно и fetch повторяет запросы сам",
      "Эффект пишет в state, от которого зависит: setItems меняет items → эффект снова → бесконечный цикл",
      "fetch без AbortController всегда дублирует запросы при ре-рендере",
      "then-цепочка создаёт новый запрос на каждое обновление промиса",
    ],
    a: 1,
    e: "Классика «найди антипаттерн»: эффект зависит от того, что сам изменяет. Фикс: deps [], а лучше — данные через query-библиотеку (кэш, отмена, статусы из коробки).",
    en: {
      t: "EnginX · Antipatterns",
      q: "Why does the app send thousands of requests?\nuseEffect(() => {\n  fetch('/api/items').then(r => r.json()).then(setItems);\n}, [items]);",
      o: [
        "The server responds too slowly and fetch retries the requests on its own",
        "The effect writes to the state it depends on: setItems changes items → the effect fires again → infinite loop",
        "fetch without an AbortController always duplicates requests on re-render",
        "The then-chain creates a new request on every promise update",
      ],
      e: "A classic 'spot the antipattern': the effect depends on the very thing it changes. Fix: an empty deps array, or better — fetch data through a query library (cache, cancellation, and statuses out of the box).",
    },
  },
  {
    t: "EnginX · OWASP",
    q: "Какие практики закрывают supply chain-риски npm-зависимостей?",
    o: [
      "Минификация и обфускация бандла при продакшен-сборке проекта",
      "npm audit/Dependabot, lockfile в репозитории, осторожность с postinstall и typosquatting",
      "Установка зависимостей только из зеркала компании без интернета",
      "Использование yarn вместо npm — у него встроенная защита пакетов",
    ],
    a: 1,
    e: "Аудит ловит известные CVE, lockfile фиксирует версии от подмены, postinstall-скрипты — вектор исполнения чужого кода, typosquatting (reakt) — вектор установки зловреда.",
    en: {
      t: "EnginX · OWASP",
      q: "What practices mitigate supply chain risks in npm dependencies?",
      o: [
        "Minifying and obfuscating the bundle during the project's production build",
        "npm audit/Dependabot, committing a lockfile, being cautious with postinstall scripts and typosquatting",
        "Installing dependencies only from a company mirror with no internet access",
        "Using yarn instead of npm — it has built-in package protection",
      ],
      e: "Auditing catches known CVEs, a lockfile pins versions against tampering, postinstall scripts are a vector for executing someone else's code, and typosquatting (e.g. reakt) is a vector for installing malware.",
    },
  },
  {
    t: "EnginX · SDLC",
    q: "Что произойдёт, если сравнивать команды по velocity (story points за спринт)?",
    o: [
      "Здоровая конкуренция: команды начнут работать заметно быстрее",
      "Инфляция оценок: поинты растут без роста работы и теряют смысл для планирования",
      "Ничего: поинты — объективная метрика, сравнимая между командами",
      "Команды откажутся от Scrum и перейдут на Kanban без оценок",
    ],
    a: 1,
    e: "Поинты — внутренняя валюта команды для планирования ёмкости, откалиброванная только внутри неё. Сравнение и таргеты превращают их в KPI — оценки раздуваются за квартал.",
    en: {
      t: "EnginX · SDLC",
      q: "What happens when teams are compared by velocity (story points per sprint)?",
      o: [
        "Healthy competition: teams start working noticeably faster",
        "Estimate inflation: points grow without any growth in actual work and lose their meaning for planning",
        "Nothing: points are an objective metric that's comparable across teams",
        "Teams abandon Scrum and switch to Kanban without estimates",
      ],
      e: "Points are a team's internal currency for capacity planning, calibrated only within that team. Comparisons and targets turn them into a KPI — estimates inflate within a quarter.",
    },
  },
];
