// Вопросы квиза: секция GraphQL
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

import type { Question } from "../types";

export const GRAPHQL_QUESTIONS: Question[] = [
  {
    t: "GraphQL · vs REST",
    q: "Какие две проблемы REST решает GraphQL?",
    o: [
      "Медленную сериализацию JSON и большие HTTP-заголовки",
      "Over-fetching (лишние поля) и under-fetching (каскад запросов)",
      "Отсутствие встроенного кэша и системы авторизации",
      "Проблемы с CORS-политикой и передачей cookies",
    ],
    a: 1,
    e: "Клиент декларирует нужные поля (нет лишнего) и получает весь граф одним запросом (нет каскада /user → /posts → /comments).",
    en: {
      t: "GraphQL · vs REST",
      q: "What two problems does GraphQL solve that REST has?",
      o: [
        "Slow JSON serialization and large HTTP headers",
        "Over-fetching (extra fields) and under-fetching (cascading requests)",
        "Lack of built-in caching and an authorization system",
        "Issues with CORS policy and cookie handling",
      ],
      e: "The client declares exactly the fields it needs (no over-fetching) and receives the whole graph in a single request (no cascade of /user → /posts → /comments).",
    },
  },
  {
    t: "GraphQL · Операции",
    q: "Чем subscription отличается от query?",
    o: [
      "Ничем не отличается, это просто синоним обычного query",
      "Это push от СЕРВЕРА по постоянному соединению (WebSocket), а не запрос клиента",
      "Отличается только более агрессивной политикой кэширования",
      "Работает исключительно в связке с клиентом Apollo",
    ],
    a: 1,
    e: "Query/mutation инициирует клиент по HTTP; subscription — долгоживущее соединение, по которому сервер пушит события (чат, уведомления).",
    en: {
      t: "GraphQL · Operations",
      q: "How does a subscription differ from a query?",
      o: [
        "It doesn't differ at all — it's just a synonym for a regular query",
        "It's a PUSH from the SERVER over a persistent connection (WebSocket), not a request initiated by the client",
        "It differs only in having a more aggressive caching policy",
        "It only works in combination with the Apollo Client",
      ],
      e: "A query/mutation is initiated by the client over HTTP; a subscription is a long-lived connection over which the server pushes events (chat, notifications).",
    },
  },
  {
    t: "GraphQL · Клиент",
    q: "GraphQL-запрос вернул HTTP 200. Значит ли это успех?",
    o: [
      "Да, HTTP-статус 200 всегда означает полный успех запроса",
      "Нет — ошибки приходят в поле errors тела ответа при 200",
      "Нет, успешным ответом GraphQL считается только статус 201",
      "GraphQL вообще не использует HTTP-статусы в ответах",
    ],
    a: 1,
    e: "GraphQL-ошибки живут в теле: { data, errors }. Проверять массив errors, а не только статус — классика интеграции.",
    en: {
      t: "GraphQL · Client",
      q: "A GraphQL request returned HTTP 200. Does that mean it succeeded?",
      o: [
        "Yes, an HTTP 200 status always means the request fully succeeded",
        "No — errors are delivered in the errors field of the response body even with a 200 status",
        "No, a successful GraphQL response is only ever indicated by status 201",
        "GraphQL doesn't use HTTP status codes in responses at all",
      ],
      e: "GraphQL errors live in the response body: { data, errors }. Checking the errors array instead of relying solely on the status code is a classic integration gotcha.",
    },
  },
  {
    t: "GraphQL · Кэш",
    q: "Почему Apollo просит запрашивать id в каждом фрагменте?",
    o: [
      "Поле id нужно исключительно для удобства логирования",
      "Нормализованный кэш строит ключ __typename + id — без id объект не нормализуется",
      "Сервер требует id в каждом запросе для авторизации",
      "Без поля id просто не будет работать проверка TypeScript",
    ],
    a: 1,
    e: "Без id объект не попадает в нормализованный кэш → экраны не обновятся после мутаций, кэш-промахи.",
    en: {
      t: "GraphQL · Caching",
      q: "Why does Apollo ask you to request id in every fragment?",
      o: [
        "The id field is only useful for logging convenience",
        "The normalized cache builds its key from __typename + id — without id the object can't be normalized",
        "The server requires id in every request for authorization",
        "Without the id field, TypeScript type checking simply won't work",
      ],
      e: "Without id the object never lands in the normalized cache → screens don't update after mutations, and you get cache misses.",
    },
  },
  {
    t: "GraphQL · Сервер",
    q: "Что такое resolver?",
    o: [
      "Механизм клиентского кэша, хранящий нормализованные данные",
      "Функция на сервере, возвращающая значение конкретного поля схемы",
      "Валидатор входящих запросов перед их выполнением",
      "Просто другое название для операции мутации",
    ],
    a: 1,
    e: "На каждое поле схемы — resolver (parent, args, context, info). GraphQL-сервер обходит запрос и вызывает resolvers; вложенные поля получают parent от родительского.",
    en: {
      t: "GraphQL · Server",
      q: "What is a resolver?",
      o: [
        "A client-side caching mechanism that stores normalized data",
        "A server-side function that returns the value of a specific schema field",
        "A validator that checks incoming requests before they run",
        "Just another name for a mutation operation",
      ],
      e: "Every schema field has a resolver (parent, args, context, info). The GraphQL server walks the query and calls resolvers; nested fields receive parent from their parent resolver.",
    },
  },
  {
    t: "GraphQL · Сервер",
    q: "Запрос тормозит: 1 SQL на users + 100 SQL на posts. Что это и как чинить?\nquery {\n  users {\n    posts { title }\n  }\n}",
    o: [
      "Over-fetching — нужно сузить набор запрашиваемых полей",
      "N+1 в resolvers — чинится DataLoader (батчинг + кэш в рамках запроса)",
      "Слишком медленное WebSocket-соединение с сервером",
      "Отсутствие пагинации в списке возвращаемых пользователей",
    ],
    a: 1,
    e: "N+1 из REST переехал на сервер: resolver posts зовётся для каждого user. DataLoader собирает id за тик и делает один WHERE id IN (...), плюс кэширует внутри запроса.",
    en: {
      t: "GraphQL · Server",
      q: "A query is slow: 1 SQL query for users plus 100 SQL queries for posts. What is this and how do you fix it?\nquery {\n  users {\n    posts { title }\n  }\n}",
      o: [
        "Over-fetching — you need to narrow the set of requested fields",
        "N+1 in the resolvers — fixed with DataLoader (batching + per-request cache)",
        "The WebSocket connection to the server is too slow",
        "Missing pagination on the returned list of users",
      ],
      e: "The N+1 problem moved from REST to the server: the posts resolver is called once per user. DataLoader collects ids within a tick and issues a single WHERE id IN (...), plus caches results within the request.",
    },
  },
  {
    t: "GraphQL · Синтаксис",
    q: "Зачем нужны variables ($id: ID!) вместо подстановки значения в строку запроса?",
    o: [
      "Только ради красоты синтаксиса, функционально не важны",
      "Типизация + защита от инъекций + кэшируемость одного текста запроса",
      "Без переменных запрос вообще откажется выполняться",
      "Переменные попросту быстрее парсятся движком сервера",
    ],
    a: 1,
    e: "Строковая интерполяция — антипаттерн: нет проверки типов, инъекции, каждый запрос уникален. Переменные валидируются схемой, текст запроса один — persisted queries возможны.",
    en: {
      t: "GraphQL · Syntax",
      q: "Why use variables ($id: ID!) instead of interpolating the value directly into the query string?",
      o: [
        "Purely for syntactic elegance — it has no functional importance",
        "Type checking + protection against injection + a single cacheable query text",
        "Without variables the query would simply refuse to execute",
        "Variables are just parsed faster by the server engine",
      ],
      e: "String interpolation is an anti-pattern: no type checking, injection risk, and every query becomes unique. Variables are validated against the schema and the query text stays constant — enabling persisted queries.",
    },
  },
  {
    t: "GraphQL · Синтаксис",
    q: "Что такое fragment?",
    o: [
      "Просто часть JSON-ответа, пришедшего от сервера клиенту",
      "Именованный переиспользуемый набор полей для типа (fragment UserCard on User)",
      "Отдельный кусок схемы, доступный только администратору",
      "Большой запрос, автоматически разбитый сервером на части",
    ],
    a: 1,
    e: "Фрагменты убирают дублирование полей между запросами и совпадают с компонентами (fragment colocation: каждый компонент декларирует свои поля).",
    en: {
      t: "GraphQL · Syntax",
      q: "What is a fragment?",
      o: [
        "Just a piece of the JSON response the server sent to the client",
        "A named, reusable set of fields for a type (fragment UserCard on User)",
        "A separate part of the schema accessible only to administrators",
        "A large query automatically split into parts by the server",
      ],
      e: "Fragments remove field duplication across queries and map naturally onto components (fragment colocation: each component declares the fields it needs).",
    },
  },
  {
    t: "GraphQL · Инструменты",
    q: "Что такое introspection?",
    o: [
      "Специальный режим отладки резолверов прямо на GraphQL-сервере",
      "API описывает сам себя: запрос __schema возвращает все типы — на этом работают GraphiQL и codegen",
      "Встроенный мониторинг производительности выполнения всех запросов",
      "Проверка прав доступа перед выполнением каждой отдельной операции",
    ],
    a: 1,
    e: "Самоописание схемы питает тулинг: автокомплит в GraphiQL/playground, генерация TS-типов (graphql-codegen). В проде introspection часто выключают.",
    en: {
      t: "GraphQL · Tooling",
      q: "What is introspection?",
      o: [
        "A special resolver-debugging mode running directly on the GraphQL server",
        "The API describing itself: a __schema query returns all types — this is what powers GraphiQL and codegen",
        "Built-in performance monitoring for every executed query",
        "An access-rights check performed before each individual operation runs",
      ],
      e: "Self-describing schemas power tooling: autocomplete in GraphiQL/Playground, TypeScript type generation (graphql-codegen). Introspection is often disabled in production.",
    },
  },
  {
    t: "GraphQL · Клиент",
    q: "fetchPolicy: 'cache-first' означает...",
    o: [
      "Всегда ходить в сеть, игнорируя содержимое кэша",
      "Есть в кэше — отдать из кэша без запроса; нет — сходить в сеть",
      "Сначала отдать кэш, а затем ВСЕГДА обновить из сети",
      "Кэшировать результат только самого первого запроса",
    ],
    a: 1,
    e: "Дефолт Apollo. «Кэш, потом сеть» — это cache-and-network; только сеть — network-only. Выбор политики = баланс свежести и трафика.",
    en: {
      t: "GraphQL · Client",
      q: "fetchPolicy: 'cache-first' means...",
      o: [
        "Always hit the network, ignoring whatever is in the cache",
        "If it's in the cache, return it from the cache without a request; if not, go to the network",
        "Return the cache first, then ALWAYS refresh from the network",
        "Cache the result of only the very first request",
      ],
      e: "This is Apollo's default. 'Cache first, then network' is cache-and-network; network only is network-only. Choosing a policy is a trade-off between freshness and network traffic.",
    },
  },
  {
    t: "GraphQL · Клиент",
    q: "Что делает optimisticResponse в useMutation?",
    o: [
      "Автоматически повторяет мутацию при сетевой ошибке",
      "Мгновенно пишет ожидаемый результат в кэш; при ошибке сервера — откат",
      "Просто сжимает тело ответа перед отправкой клиенту",
      "Полностью игнорирует любые ошибки, пришедшие от сервера",
    ],
    a: 1,
    e: "UI обновляется до ответа сервера (лайк, добавление в список), настоящий ответ заменяет временную запись, ошибка — автоматический откат. UX мгновенный.",
    en: {
      t: "GraphQL · Client",
      q: "What does optimisticResponse do in useMutation?",
      o: [
        "Automatically retries the mutation on a network error",
        "Immediately writes the expected result into the cache; rolls it back if the server returns an error",
        "Simply compresses the response body before sending it to the client",
        "Completely ignores any errors returned by the server",
      ],
      e: "The UI updates before the server responds (a like, adding to a list); the real response replaces the temporary entry, and an error triggers an automatic rollback. The result is instant UX.",
    },
  },
  {
    t: "GraphQL · Схема",
    q: "Какие базовые типы определяет SDL (Schema Definition Language)?",
    o: [
      "scalar, type, input, enum, interface, union — строительные блоки схемы",
      "class, interface, abstract — термины из ООП-языков программирования",
      "model, view, controller — слои классической MVC-архитектуры",
      "table, column, index — понятия из реляционных баз данных",
    ],
    a: 0,
    e: "SDL — язык описания схемы: scalar (примитив), type (объектный тип), input (аргументы мутаций), enum, interface и union (полиморфизм результата). Термины ООП/MVC/SQL тут ни при чём.",
    en: {
      t: "GraphQL · Schema",
      q: "What base types does SDL (Schema Definition Language) define?",
      o: [
        "scalar, type, input, enum, interface, union — the building blocks of a schema",
        "class, interface, abstract — terms from OOP programming languages",
        "model, view, controller — layers of the classic MVC architecture",
        "table, column, index — concepts from relational databases",
      ],
      e: "SDL is the language for describing a schema: scalar (primitive), type (object type), input (mutation arguments), enum, interface and union (result polymorphism). OOP/MVC/SQL terminology doesn't apply here.",
    },
  },
  {
    t: "GraphQL · Схема",
    q: "Что произойдёт?\ntype Query {\n  user(id: ID!): User\n}\ntype User {\n  name: String!\n}\n# resolver User.name вернул null",
    o: [
      "Поле name станет null, а остальной ответ придёт как обычно",
      "Ошибка уйдёт в errors, а null всплывёт до ближайшего nullable поля — до user или до data",
      "Сервер тихо подставит пустую строку вместо null в поле name",
      "Запрос завершится ошибкой валидации ещё до его выполнения",
    ],
    a: 1,
    e: "! — non-nullable контракт. Resolver вернул null там, где обещан String! — GraphQL пишет ошибку в errors и обнуляет (null bubbling) ближайшего nullable родителя: тут это поле user, а если бы и оно было non-null — всю data.",
    en: {
      t: "GraphQL · Schema",
      q: "What happens?\ntype Query {\n  user(id: ID!): User\n}\ntype User {\n  name: String!\n}\n# the User.name resolver returned null",
      o: [
        "The name field becomes null, and the rest of the response arrives as usual",
        "An error is added to errors, and null bubbles up to the nearest nullable field — either user or data",
        "The server silently substitutes an empty string for null in the name field",
        "The request fails with a validation error before it even executes",
      ],
      e: "! is a non-nullable contract. The resolver returned null where a String! was promised — GraphQL records an error in errors and nulls out (null bubbling) the nearest nullable ancestor: here that's the user field, and if it too were non-null, the entire data.",
    },
  },
  {
    t: "GraphQL · Пагинация",
    q: "Дан ответ:\nquery {\n  posts(first: 2, after: \"cursorA\") {\n    edges { cursor node { title } }\n    pageInfo { hasNextPage endCursor }\n  }\n}\nЗачем тут cursor, а не offset: 2, limit: 2?",
    o: [
      "cursor и offset — строго одно и то же, просто разные имена аргумента",
      "Cursor — непрозрачный указатель на позицию элемента, устойчивый к вставке/удалению между запросами",
      "offset/limit в GraphQL-схемах в принципе запрещены спецификацией",
      "Курсор используется только внутри подписок, а не в обычных query",
    ],
    a: 1,
    e: "При offset/limit вставка нового элемента сдвигает все страницы (дубликаты/пропуски при подгрузке). Курсор — стабильный указатель на позицию конкретного элемента (Relay connection spec: edges/node/cursor/pageInfo).",
    en: {
      t: "GraphQL · Pagination",
      q: "Given this response:\nquery {\n  posts(first: 2, after: \"cursorA\") {\n    edges { cursor node { title } }\n    pageInfo { hasNextPage endCursor }\n  }\n}\nWhy use cursor here instead of offset: 2, limit: 2?",
      o: [
        "cursor and offset are strictly the same thing, just different argument names",
        "A cursor is an opaque pointer to an item's position, resilient to insertions/deletions between requests",
        "offset/limit is fundamentally forbidden in GraphQL schemas by the specification",
        "Cursors are used only inside subscriptions, not in regular queries",
      ],
      e: "With offset/limit, inserting a new item shifts every subsequent page (duplicates/gaps while loading more). A cursor is a stable pointer to a specific item's position (the Relay connection spec: edges/node/cursor/pageInfo).",
    },
  },
  {
    t: "GraphQL · Синтаксис",
    q: "Что вернёт сервер?\nquery Post($withComments: Boolean!) {\n  post(id: 1) {\n    title\n    comments @include(if: $withComments) { text }\n  }\n}\n// variables: { \"withComments\": false }",
    o: [
      "Ответ без ключа comments — поле целиком не попадёт в data.post",
      "Поле comments придёт как пустой массив comments: []",
      "Сервер вернёт ошибку валидации переменной withComments",
      "comments придёт, но вложенное поле text будет равно null",
    ],
    a: 0,
    e: "@include(if: false) убирает поле из результата целиком — не пустой массив, а полное отсутствие ключа в data.post. Обратная директива @skip(if:) работает наоборот: исключает поле при true.",
    en: {
      t: "GraphQL · Syntax",
      q: "What will the server return?\nquery Post($withComments: Boolean!) {\n  post(id: 1) {\n    title\n    comments @include(if: $withComments) { text }\n  }\n}\n// variables: { \"withComments\": false }",
      o: [
        "A response without a comments key — the field is entirely absent from data.post",
        "The comments field arrives as an empty array comments: []",
        "The server returns a validation error for the withComments variable",
        "comments is included, but the nested text field is null",
      ],
      e: "@include(if: false) removes the field from the result entirely — not an empty array, but a complete absence of the key in data.post. The opposite directive, @skip(if:), works the other way: it excludes the field when the condition is true.",
    },
  },
  {
    t: "GraphQL · Кэш",
    q: "После мутации createTodo список todos на экране не обновился сам собой. Почему?",
    o: [
      "Кэш умеет мерджить только изменения уже существующего объекта по id, а не появление нового элемента в списке",
      "Мутации в принципе никогда не должны обращаться к кэшу Apollo Client",
      "Проблема в том, что вызов createTodo не был обёрнут в try/catch блок",
      "InMemoryCache полностью отключает автообновление при работе со списками",
    ],
    a: 0,
    e: "Автомердж кэша срабатывает только для полей уже существующего объекта (совпал __typename + id). Кэш не знает, в какой именно список положить новую сущность — нужен refetchQueries или ручной cache.modify.",
    en: {
      t: "GraphQL · Caching",
      q: "After the createTodo mutation, the todos list on screen didn't update automatically. Why?",
      o: [
        "The cache can only merge changes into an already existing object by id, not the appearance of a new item in a list",
        "Mutations should fundamentally never touch the Apollo Client cache",
        "The problem is that the createTodo call wasn't wrapped in a try/catch block",
        "InMemoryCache completely disables auto-updates when working with lists",
      ],
      e: "Cache auto-merging only kicks in for fields of an object that already exists (matched by __typename + id). The cache has no way of knowing which list a new entity should be added to — you need refetchQueries or a manual cache.modify.",
    },
  },
  {
    t: "GraphQL · Кэш",
    q: "refetchQueries против cache.modify после мутации — в чём компромисс?",
    o: [
      "refetchQueries проще, но лишний round-trip; cache.modify быстрее, но логику пишешь руками",
      "Это два разных имени одной и той же функции клиента Apollo",
      "cache.modify работает только с подписками, а не с мутациями",
      "refetchQueries нельзя использовать вместе со списками данных",
    ],
    a: 0,
    e: "refetchQueries перезапрашивает нужные query заново с сервера — надёжно и просто, но лишний сетевой запрос. cache.modify правит кэш локально без сети, но каждую операцию со списком описываешь вручную.",
    en: {
      t: "GraphQL · Caching",
      q: "refetchQueries vs cache.modify after a mutation — what's the trade-off?",
      o: [
        "refetchQueries is simpler but costs an extra round trip; cache.modify is faster but you write the logic yourself",
        "These are just two different names for the same Apollo Client function",
        "cache.modify only works with subscriptions, not with mutations",
        "refetchQueries can't be used together with lists of data",
      ],
      e: "refetchQueries re-fetches the relevant queries from the server again — reliable and simple, but at the cost of an extra network request. cache.modify updates the cache locally without a network round trip, but you have to describe every list operation by hand.",
    },
  },
  {
    t: "GraphQL · Клиент",
    q: "Чем fetchPolicy: 'network-only' отличается от 'cache-and-network'?",
    o: [
      "network-only игнорирует кэш перед запросом; cache-and-network сразу отдаёт кэш и параллельно обновляет из сети",
      "Это одна и та же политика Apollo Client, просто под разными названиями",
      "network-only применим только к мутациям, но не применим к обычным query",
      "cache-and-network в принципе вообще не делает сетевых запросов к серверу",
    ],
    a: 0,
    e: "network-only не читает кэш перед запросом (но пишет в него после) — UI ждёт ответ сервера. cache-and-network мгновенно показывает то, что уже в кэше, а затем обновляет данными с сервера.",
    en: {
      t: "GraphQL · Client",
      q: "How does fetchPolicy: 'network-only' differ from 'cache-and-network'?",
      o: [
        "network-only ignores the cache before the request; cache-and-network immediately returns the cache and refreshes from the network in parallel",
        "It's the same Apollo Client policy, just under two different names",
        "network-only applies only to mutations, not to regular queries",
        "cache-and-network never actually makes network requests to the server",
      ],
      e: "network-only doesn't read the cache before the request (but writes to it afterward) — the UI waits for the server's response. cache-and-network shows what's already in the cache instantly, then updates it with data from the server.",
    },
  },
  {
    t: "GraphQL · Инфраструктура",
    q: "Что решают persisted queries (персистентные запросы)?",
    o: [
      "Клиент шлёт короткий hash вместо полного текста запроса — меньше трафик и безопаснее прод-эндпоинт",
      "Запросы автоматически сохраняются в localStorage браузера клиента",
      "Механизм офлайн-очереди для мутаций, не отправленных из-за сети",
      "Способ навсегда закэшировать ответы сервера прямо на локальном диске",
    ],
    a: 0,
    e: "Сервер заранее знает соответствие хэш → полный текст запроса; клиент шлёт только хэш. Экономит трафик и позволяет держать allowlist разрешённых запросов в проде вместо произвольного GraphQL.",
    en: {
      t: "GraphQL · Infrastructure",
      q: "What problem do persisted queries solve?",
      o: [
        "The client sends a short hash instead of the full query text — less traffic and a more secure production endpoint",
        "Queries are automatically saved to the client browser's localStorage",
        "An offline queueing mechanism for mutations that failed to send due to network issues",
        "A way to permanently cache server responses directly on the local disk",
      ],
      e: "The server already knows the hash-to-full-query-text mapping in advance; the client only sends the hash. This saves bandwidth and lets you maintain an allowlist of permitted queries in production instead of accepting arbitrary GraphQL.",
    },
  },
  {
    t: "GraphQL · Ошибки",
    q: "Как клиенту машинно отличить «не найдено» от «нет прав», если оба пришли как обычная ошибка GraphQL?",
    o: [
      "По полю extensions.code в объекте ошибки (например NOT_FOUND, FORBIDDEN)",
      "GraphQL в принципе не различает разные типы ошибок между собой",
      "По длине текстового сообщения message в объекте ошибки",
      "По специальному HTTP-заголовку X-Error-Type в ответе сервера",
    ],
    a: 0,
    e: "errors[].extensions — место для машиночитаемых деталей (code, http.status и т.п.), message — для людей. Альтернатива без слоя errors — union-типы результата прямо в схеме: Payload = Success | NotFoundError | ForbiddenError.",
    en: {
      t: "GraphQL · Errors",
      q: "How can a client programmatically distinguish 'not found' from 'no permission' when both arrive as a regular GraphQL error?",
      o: [
        "Via the extensions.code field on the error object (e.g. NOT_FOUND, FORBIDDEN)",
        "GraphQL fundamentally doesn't distinguish between different error types",
        "By the length of the error object's message text",
        "Via a special X-Error-Type HTTP header in the server response",
      ],
      e: "errors[].extensions is where machine-readable details go (code, http.status, etc.), while message is for humans. An alternative that avoids the errors layer altogether is to model results as union types right in the schema: Payload = Success | NotFoundError | ForbiddenError.",
    },
  },
];
