// Вопросы квиза: секция JS
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

export const JS_QUESTIONS = [
  {
    t: "JS · let/var/const",
    q: "Что выведет?\nfor (var i = 0; i < 3; i++) setTimeout(() => console.log(i));",
    o: [
      "0 1 2 — будто на каждой итерации создаётся своя переменная i",
      "3 3 3 — var общий на весь цикл, колбэки видят i таким, каким он стал после его завершения",
      "0 0 0 — будто setTimeout выполняется мгновенно, до следующей итерации",
      "undefined ×3 — будто i выходит из области видимости и не сохраняется в замыкании",
    ],
    a: 1,
    e: "var — одна переменная на весь цикл (function scope). Таймеры сработают после цикла, когда i уже 3. С let было бы 0 1 2.",
    en: {
      t: "JS · let/var/const",
      q: "What does this print?\nfor (var i = 0; i < 3; i++) setTimeout(() => console.log(i));",
      o: [
        "0 1 2 — as if a new variable i is created on every iteration",
        "3 3 3 — var is shared across the whole loop, so the callbacks see i as it ended up after the loop finished",
        "0 0 0 — as if setTimeout ran instantly, before the next iteration",
        "undefined ×3 — as if i goes out of scope and isn't kept alive by the closure",
      ],
      a: 1,
      e: "var creates a single variable shared by the entire loop (function scope). The timers fire after the loop ends, when i is already 3. With let it would be 0 1 2.",
    },
  },
  {
    t: "JS · let/var/const",
    q: "const arr = [1, 2]; arr.push(3); — что произойдёт?",
    o: [
      "TypeError: нельзя изменять содержимое const-массива",
      "arr станет [1,2,3] — const запрещает менять ссылку, но не содержимое",
      "SyntaxError при попытке вызвать push на константе",
      "push вернёт новый массив, не изменяя исходный arr",
    ],
    a: 1,
    e: "const запрещает переприсваивание ссылки (arr = ...), но мутировать содержимое можно. Константна ссылка, не объект.",
    en: {
      t: "JS · let/var/const",
      q: "const arr = [1, 2]; arr.push(3); — what happens?",
      o: [
        "TypeError: you can't change the contents of a const array",
        "arr becomes [1,2,3] — const forbids reassigning the reference, but not mutating its contents",
        "SyntaxError when trying to call push on a constant",
        "push returns a new array without changing the original arr",
      ],
      a: 1,
      e: "const forbids reassigning the reference (arr = ...), but mutating its contents is fine. It's the binding that's constant, not the object.",
    },
  },
  {
    t: "JS · let/var/const",
    q: "Какая область видимости у var?",
    o: [
      "Блочная — как у let, ограничена фигурными скобками",
      "Функциональная — var игнорирует блоки {}, видна во всей функции",
      "Модульная всегда — как у переменных ES-модулей",
      "Только глобальная — var нельзя объявить внутри функции",
    ],
    a: 1,
    e: "var игнорирует блоки {} — его границей является только функция. let/const — блочные.",
    en: {
      t: "JS · let/var/const",
      q: "What is the scope of var?",
      o: [
        "Block scope — like let, limited to curly braces",
        "Function scope — var ignores {} blocks and is visible throughout the whole function",
        "Always module scope — like ES module bindings",
        "Global only — var can't be declared inside a function",
      ],
      a: 1,
      e: "var ignores {} blocks — its only boundary is the enclosing function. let/const are block-scoped.",
    },
  },
  {
    t: "JS · Hoisting",
    q: "console.log(x); var x = 5; — что выведет?",
    o: [
      "5 — будто присваивание тоже всплывает вместе с объявлением",
      "ReferenceError — будто var ведёт себя как let и попадает в TDZ",
      "undefined — объявление всплыло, а присваивание выполнится позже",
      "null — будто необъявленная переменная получает null по умолчанию",
    ],
    a: 2,
    e: "Объявление var всплывает со значением undefined, присваивание остаётся на месте. С let была бы ReferenceError (TDZ).",
    en: {
      t: "JS · Hoisting",
      q: "console.log(x); var x = 5; — what does this print?",
      o: [
        "5 — as if the assignment is hoisted along with the declaration",
        "ReferenceError — as if var behaved like let and landed in the TDZ",
        "undefined — the declaration is hoisted, but the assignment runs later, in place",
        "null — as if an undeclared variable defaults to null",
      ],
      a: 2,
      e: "The var declaration is hoisted with the value undefined; the assignment stays where it was written. With let this would throw ReferenceError (TDZ).",
    },
  },
  {
    t: "JS · Hoisting",
    q: "Можно ли вызвать функцию ДО её объявления через function f() {}?",
    o: [
      "Нет, ReferenceError — функция ещё не определена в момент вызова",
      "Да — declaration всплывает целиком, включая тело функции",
      "Только в strict mode — вне его вызов до объявления запрещён",
      "Да, но вернёт undefined — тело функции ещё не подключено",
    ],
    a: 1,
    e: "Function declaration всплывает целиком вместе с телом. Function expression (const f = function(){}) — нет.",
    en: {
      t: "JS · Hoisting",
      q: "Can you call a function BEFORE its declaration via function f() {}?",
      o: [
        "No, ReferenceError — the function isn't defined yet at the point of the call",
        "Yes — a function declaration is hoisted whole, body included",
        "Only in strict mode — outside it, calling before declaration is forbidden",
        "Yes, but it returns undefined — the function body isn't attached yet",
      ],
      a: 1,
      e: "A function declaration is hoisted in its entirety, body included. A function expression (const f = function(){}) is not.",
    },
  },
  {
    t: "JS · Hoisting",
    q: "console.log(typeof f); f(); var f = function () {}; — что будет?",
    o: [
      "\"undefined\", потом TypeError — f это ещё undefined, вызвать его нельзя",
      "\"function\", вызов сработает — будто объявление функции всплывает целиком",
      "ReferenceError сразу — будто переменная f вообще не была объявлена",
      "\"undefined\", потом ReferenceError — будто вызов возможен, а обращение позже — нет",
    ],
    a: 0,
    e: "Всплывает только var f (undefined). typeof undefined → 'undefined', а вызов undefined() — TypeError: f is not a function.",
    en: {
      t: "JS · Hoisting",
      q: "console.log(typeof f); f(); var f = function () {}; — what happens?",
      o: [
        "\"undefined\", then TypeError — f is still undefined at that point, so it can't be called",
        "\"function\", and the call succeeds — as if the whole function is hoisted",
        "ReferenceError right away — as if the variable f was never declared",
        "\"undefined\", then ReferenceError — as if the call works but accessing it later doesn't",
      ],
      a: 0,
      e: "Only var f is hoisted (as undefined). typeof undefined → 'undefined', and calling undefined() throws TypeError: f is not a function.",
    },
  },
  {
    t: "JS · TDZ",
    q: "console.log(x); let x = 5; — что выведет?",
    o: [
      "undefined — будто let ведёт себя как var и всплывает со значением",
      "5 — будто присваивание тоже всплывает вместе с объявлением let",
      "ReferenceError — обращение к переменной в TDZ до её объявления",
      "null — будто необъявленная переменная получает null по умолчанию",
    ],
    a: 2,
    e: "let всплывает, но до своей строки лежит в TDZ — обращение даёт ReferenceError, а не undefined как var.",
    en: {
      t: "JS · TDZ",
      q: "console.log(x); let x = 5; — what does this print?",
      o: [
        "undefined — as if let behaved like var and got hoisted with a value",
        "5 — as if the assignment is also hoisted along with the let declaration",
        "ReferenceError — accessing the variable while it's still in the TDZ, before its declaration line",
        "null — as if an undeclared variable defaults to null",
      ],
      a: 2,
      e: "let is hoisted, but sits in the temporal dead zone until its declaration line — accessing it there throws ReferenceError, not undefined like var.",
    },
  },
  {
    t: "JS · TDZ",
    q: "typeof y, если ниже есть let y = 1?",
    o: [
      "\"undefined\" — как для обычной необъявленной переменной",
      "ReferenceError — переменная в TDZ, typeof её не спасает",
      "\"object\" — до инициализации let ведёт себя как null",
      "typeof всегда безопасен — не бросает исключений ни для одной переменной",
    ],
    a: 1,
    e: "Парадокс TDZ: typeof несуществующей переменной → 'undefined', но typeof переменной в TDZ — ReferenceError. TDZ строже отсутствия.",
    en: {
      t: "JS · TDZ",
      q: "What is typeof y, if there's a let y = 1 further down?",
      o: [
        "\"undefined\" — same as for an ordinary undeclared variable",
        "ReferenceError — the variable is in the TDZ, and typeof doesn't save you here",
        "\"object\" — before initialization, let behaves like null",
        "typeof is always safe — it never throws for any variable",
      ],
      a: 1,
      e: "The TDZ paradox: typeof on a nonexistent variable gives 'undefined', but typeof on a variable in the TDZ throws ReferenceError. The TDZ is stricter than plain absence.",
    },
  },
  {
    t: "JS · Scope",
    q: "Функция ищет внешнюю переменную в скоупе...",
    o: [
      "...откуда её вызвали — this как раз работает по этому принципу",
      "...где она была СОЗДАНА — лексический скоуп фиксируется при написании кода",
      "...глобальном всегда — будто у функций нет собственной области видимости",
      "...случайном — порядок объявления переменных не имеет значения",
    ],
    a: 1,
    e: "Скоуп в JS лексический — определяется местом написания кода. Контраст: this наоборот зависит от места вызова.",
    en: {
      t: "JS · Scope",
      q: "A function looks up an outer variable in the scope...",
      o: [
        "...it was called from — that's actually how this works",
        "...where it was DEFINED — lexical scope is fixed at the point the code is written",
        "...always the global scope — as if functions have no scope of their own",
        "...chosen at random — the order variables are declared in doesn't matter",
      ],
      a: 1,
      e: "Scope in JS is lexical — determined by where the code is written. By contrast, this depends on where the function is called from.",
    },
  },
  {
    t: "JS · Closure",
    q: "Что вернёт c2()?\nconst c1 = makeCounter();\nconst c2 = makeCounter();\nc1(); c1();\nc2(); // ?",
    o: [
      "3 — будто c1 и c2 используют общий счётчик",
      "1 — c2 создаёт собственное замыкание, независимое от c1",
      "2 — будто оба счётчика делят одно значение n",
      "undefined — будто счётчик не инициализируется при первом вызове",
    ],
    a: 1,
    e: "Каждый вызов makeCounter создаёт НОВОЕ замыкание со своей переменной n. c1 и c2 независимы.",
    en: {
      t: "JS · Closure",
      q: "What does c2() return?\nconst c1 = makeCounter();\nconst c2 = makeCounter();\nc1(); c1();\nc2(); // ?",
      o: [
        "3 — as if c1 and c2 share a common counter",
        "1 — c2 creates its own closure, independent of c1",
        "2 — as if both counters share a single n value",
        "undefined — as if the counter isn't initialized on the first call",
      ],
      a: 1,
      e: "Each call to makeCounter creates a NEW closure with its own n variable. c1 and c2 are independent of each other.",
    },
  },
  {
    t: "JS · Closure",
    q: "Замыкание захватывает внешние переменные...",
    o: [
      "копией значения",
      "ссылкой на переменную",
      "только примитивы",
      "только на момент вызова",
    ],
    a: 1,
    e: "Ссылкой! Поэтому get/set над одной переменной видят изменения друг друга, а var в цикле даёт всем таймерам одно значение.",
    en: {
      t: "JS · Closure",
      q: "A closure captures outer variables...",
      o: [
        "as a copy of the value",
        "by reference to the variable",
        "only primitives",
        "only at the moment it's called",
      ],
      a: 1,
      e: "By reference! That's why get/set functions over the same variable see each other's changes, and why var in a loop gives every timer the same value.",
    },
  },
  {
    t: "JS · Closure",
    q: "Что из этого НЕ строится на замыканиях?",
    o: [
      "debounce/throttle — таймер хранит доступ к переменным через замыкание",
      "приватное состояние модуля — переменные скрыты в области видимости IIFE или модуля",
      "каррирование — каждая частичная функция замыкает предыдущие аргументы",
      "hoisting — механизм всплытия объявлений, не связан с замыканиями",
    ],
    a: 3,
    e: "Hoisting — механизм всплытия объявлений, к замыканиям отношения не имеет. Остальные три — классические применения замыканий.",
    en: {
      t: "JS · Closure",
      q: "Which of these is NOT built on closures?",
      o: [
        "debounce/throttle — the timer keeps access to variables through a closure",
        "private module state — variables hidden inside an IIFE's or a module's scope",
        "currying — each partially applied function closes over the previous arguments",
        "hoisting — the mechanism for lifting declarations, unrelated to closures",
      ],
      a: 3,
      e: "Hoisting is the mechanism that lifts declarations — it has nothing to do with closures. The other three are classic applications of closures.",
    },
  },
  {
    t: "JS · Destructuring",
    q: "const { name: userName } = user; — что делает эта запись?",
    o: [
      "Создаёт name и userName — обе переменные появляются в скоупе",
      "Кладёт значение user.name в переменную userName, name не создаётся",
      "Переименовывает свойство в объекте — исходный объект user изменяется",
      "SyntaxError — такой синтаксис деструктуризации недопустим",
    ],
    a: 1,
    e: "Это rename: «возьми свойство name, положи в переменную userName». Переменной name при этом НЕ появится.",
    en: {
      t: "JS · Destructuring",
      q: "const { name: userName } = user; — what does this statement do?",
      o: [
        "Creates both name and userName — both variables end up in scope",
        "Puts the value of user.name into the variable userName; no name variable is created",
        "Renames the property on the object — the original user object is changed",
        "SyntaxError — this destructuring syntax isn't allowed",
      ],
      a: 1,
      e: "This is a rename: \"take the property name, store it in the variable userName.\" No name variable is created in the process.",
    },
  },
  {
    t: "JS · Destructuring",
    q: "const { x = 10 } = { x: null }; — чему равен x?",
    o: [
      "10 — будто дефолт срабатывает на любое ложное значение, включая null",
      "null — дефолт применяется только к undefined, а не к null",
      "undefined — будто деструктуризация всегда даёт undefined без явного значения",
      "TypeError — будто null нельзя деструктурировать с дефолтом",
    ],
    a: 1,
    e: "Дефолт срабатывает ТОЛЬКО на undefined. null — это значение, поэтому x = null.",
    en: {
      t: "JS · Destructuring",
      q: "const { x = 10 } = { x: null }; — what is x equal to?",
      o: [
        "10 — as if the default kicks in for any falsy value, including null",
        "null — the default only applies to undefined, not to null",
        "undefined — as if destructuring always yields undefined without an explicit value",
        "TypeError — as if null can't be destructured with a default",
      ],
      a: 1,
      e: "The default kicks in ONLY for undefined. null is a real value, so x ends up being null.",
    },
  },
  {
    t: "JS · Destructuring",
    q: "Как обменять значения x и y без временной переменной?",
    o: [
      "x = y; y = x",
      "[x, y] = [y, x]",
      "{x, y} = {y, x}",
      "swap(x, y)",
    ],
    a: 1,
    e: "Деструктуризация массива: справа создаётся [y, x], потом раскладывается. Вариант 1 потеряет старый x.",
    en: {
      t: "JS · Destructuring",
      q: "How do you swap the values of x and y without a temporary variable?",
      o: [
        "x = y; y = x",
        "[x, y] = [y, x]",
        "{x, y} = {y, x}",
        "swap(x, y)",
      ],
      a: 1,
      e: "Array destructuring: the array [y, x] is built on the right first, then unpacked. Option 1 would lose the original x.",
    },
  },
  {
    t: "JS · First-class functions",
    q: "Функции в JS — first-class citizens (объекты первого класса). Что это означает?",
    o: [
      "функции быстрее объектов — движок оптимизирует их выполнение",
      "функцию можно хранить в переменных, передавать аргументом и возвращать из другой функции",
      "функции нельзя изменять — их нельзя переопределить после создания",
      "функции всплывают — как var, они поднимаются в начало области видимости",
    ],
    a: 1,
    e: "Функция — обычное значение. Отсюда колбэки, HOF (map/filter), замыкания, HOC в React.",
    en: {
      t: "JS · First-class functions",
      q: "Functions in JS are first-class citizens. What does that mean?",
      o: [
        "functions run faster than objects — the engine optimizes their execution",
        "a function can be stored in variables, passed as an argument, and returned from another function",
        "functions can't be changed — they can't be redefined after creation",
        "functions are hoisted — like var, they get lifted to the top of the scope",
      ],
      a: 1,
      e: "A function is just an ordinary value. This is where callbacks, higher-order functions (map/filter), closures, and HOCs in React all come from.",
    },
  },
  {
    t: "JS · First-class functions",
    q: "Чего НЕТ у стрелочной функции?",
    o: [
      "замыкания — стрелка якобы не видит внешние переменные",
      "своего this и arguments — берёт их из внешней лексической области",
      "возможности вернуть значение — стрелочная функция не может использовать return",
      "параметров по умолчанию — их разрешено указывать только обычным функциям",
    ],
    a: 1,
    e: "Стрелка берёт this из места создания (лексически), не имеет arguments и не может вызываться с new.",
    en: {
      t: "JS · First-class functions",
      q: "What does an arrow function NOT have?",
      o: [
        "closures — supposedly an arrow function can't see outer variables",
        "its own this and arguments — it takes them from the surrounding lexical scope",
        "the ability to return a value — an arrow function can't use return",
        "default parameters — only regular functions are allowed to declare them",
      ],
      a: 1,
      e: "An arrow function takes this from where it was defined (lexically), has no arguments object, and can't be called with new.",
    },
  },
  {
    t: "JS · Coercion",
    q: "1 + \"2\" = ?",
    o: [
      "3 — будто строка сначала приводится к числу",
      "\"12\" — строка вызывает конкатенацию, число приводится к строке",
      "NaN — будто число и строку нельзя сложить оператором +",
      "TypeError — будто плюс не работает между разными типами",
    ],
    a: 1,
    e: "+ со строкой — конкатенация: число приводится к строке. А вот \"5\" - 1 = 4, минус всегда числовой.",
    en: {
      t: "JS · Coercion",
      q: "1 + \"2\" = ?",
      o: [
        "3 — as if the string is coerced to a number first",
        "\"12\" — the string triggers concatenation, so the number is coerced to a string",
        "NaN — as if a number and a string can't be combined with the + operator",
        "TypeError — as if + doesn't work between different types",
      ],
      a: 1,
      e: "+ with a string means concatenation: the number gets coerced to a string. Compare with \"5\" - 1 = 4 — minus is always numeric.",
    },
  },
  {
    t: "JS · Coercion",
    q: "[] + [] = ?",
    o: [
      "[] — будто массивы складываются как коллекции",
      "\"\" — оба массива приводятся к пустым строкам и склеиваются",
      "0 — будто пустой массив числовым эквивалентом равен нулю",
      "undefined — будто сложение пустых массивов не определено",
    ],
    a: 1,
    e: "Массивы приводятся к строкам ('' и ''), конкатенация пустых строк — пустая строка.",
    en: {
      t: "JS · Coercion",
      q: "[] + [] = ?",
      o: [
        "[] — as if arrays are added together as collections",
        "\"\" — both arrays are coerced to empty strings and then concatenated",
        "0 — as if an empty array's numeric equivalent is zero",
        "undefined — as if adding empty arrays is undefined behavior",
      ],
      a: 1,
      e: "Arrays are coerced to strings ('' and ''); concatenating two empty strings gives an empty string.",
    },
  },
  {
    t: "JS · Coercion",
    q: "Что из этого truthy?",
    o: [
      "\"\" — пустая строка считается falsy-значением",
      "0 — число ноль относится к falsy-значениям",
      "[] — любой объект, включая пустой массив, truthy",
      "NaN — специальное числовое значение относится к falsy",
    ],
    a: 2,
    e: "Любой объект truthy, даже пустой массив/объект. Falsy ровно шесть: false, 0, '', null, undefined, NaN.",
    en: {
      t: "JS · Coercion",
      q: "Which of these is truthy?",
      o: [
        "\"\" — an empty string is considered a falsy value",
        "0 — the number zero is one of the falsy values",
        "[] — any object, including an empty array, is truthy",
        "NaN — this special numeric value is falsy",
      ],
      a: 2,
      e: "Any object is truthy, even an empty array or object. There are exactly six falsy values: false, 0, '', null, undefined, NaN.",
    },
  },
  {
    t: "JS · Coercion",
    q: "null == undefined и null == 0 — соответственно?",
    o: [
      "true, true",
      "false, false",
      "true, false",
      "false, true",
    ],
    a: 2,
    e: "Спец-правило: null == undefined → true. Но null НЕ приводится к числу при ==, поэтому null == 0 → false.",
    en: {
      t: "JS · Coercion",
      q: "null == undefined and null == 0 — respectively?",
      o: [
        "true, true",
        "false, false",
        "true, false",
        "false, true",
      ],
      a: 2,
      e: "Special rule: null == undefined evaluates to true. But null is NOT coerced to a number for ==, so null == 0 evaluates to false.",
    },
  },
  {
    t: "JS · Coercion",
    q: "NaN === NaN = ?",
    o: [
      "true — будто NaN равен самому себе при строгом сравнении",
      "false — NaN является единственным значением, не равным самому себе",
      "TypeError — будто сравнение с NaN считается ошибкой",
      "undefined — будто результат сравнения с NaN не определён",
    ],
    a: 1,
    e: "NaN не равен ничему, включая себя. Проверка: Number.isNaN(x) или Object.is(x, NaN).",
    en: {
      t: "JS · Coercion",
      q: "NaN === NaN = ?",
      o: [
        "true — as if NaN equals itself under strict comparison",
        "false — NaN is the only value that isn't equal to itself",
        "TypeError — as if comparing against NaN is considered an error",
        "undefined — as if the result of comparing with NaN is undefined",
      ],
      a: 1,
      e: "NaN isn't equal to anything, including itself. Check for it with Number.isNaN(x) or Object.is(x, NaN).",
    },
  },
  {
    t: "JS · Objects",
    q: "{} === {} = ?",
    o: [
      "true — будто два одинаковых литерала считаются равными",
      "false — сравниваются ссылки на объекты, а не их содержимое",
      "TypeError — будто сравнение объектов оператором === недопустимо",
      "зависит от содержимого — будто объекты сравниваются по значениям, как примитивы",
    ],
    a: 1,
    e: "Объекты сравниваются ПО ССЫЛКЕ. Два литерала — два разных объекта в памяти. На этом стоит вся иммутабельность React.",
    en: {
      t: "JS · Objects",
      q: "{} === {} = ?",
      o: [
        "true — as if two identical literals are considered equal",
        "false — object references are compared, not their contents",
        "TypeError — as if comparing objects with === isn't allowed",
        "it depends on the contents — as if objects are compared by value, like primitives",
      ],
      a: 1,
      e: "Objects are compared BY REFERENCE. Two literals are two distinct objects in memory. This is the whole foundation React's immutability relies on.",
    },
  },
  {
    t: "JS · Objects",
    q: "Что станет с user.address.city?\nconst copy = { ...user };\ncopy.address.city = 'Lviv';",
    o: [
      "Не изменится — spread будто создаёт полностью независимую глубокую копию",
      "Тоже станет 'Lviv' — spread копирует только верхний уровень, вложенный объект общий",
      "TypeError — будто нельзя менять свойства вложенного объекта после spread",
      "undefined — будто после spread обращение к вложенным полям ломается",
    ],
    a: 1,
    e: "Spread — ПОВЕРХНОСТНАЯ копия: вложенный address остался общим объектом. Глубокая копия — structuredClone.",
    en: {
      t: "JS · Objects",
      q: "What happens to user.address.city?\nconst copy = { ...user };\ncopy.address.city = 'Lviv';",
      o: [
        "It stays unchanged — as if spread creates a fully independent deep copy",
        "It also becomes 'Lviv' — spread only copies the top level, the nested object is shared",
        "TypeError — as if you can't change properties of a nested object after spreading",
        "undefined — as if accessing nested fields breaks after a spread",
      ],
      a: 1,
      e: "Spread is a SHALLOW copy: the nested address object is still shared. For a deep copy, use structuredClone.",
    },
  },
  {
    t: "JS · Objects",
    q: "Где JS ищет свойство, которого нет у объекта?",
    o: [
      "Нигде — сразу undefined, JS не ищет дальше собственных свойств объекта",
      "В цепочке прототипов — поиск идёт вверх по __proto__ до Object.prototype",
      "В глобальном объекте — будто отсутствующие свойства ищутся в window/global",
      "В замыкании — будто нужно искать среди переменных внешней функции",
    ],
    a: 1,
    e: "Поиск идёт по __proto__-цепочке. Так [].map находится в Array.prototype. Не нашлось нигде — undefined.",
    en: {
      t: "JS · Objects",
      q: "Where does JS look for a property the object doesn't have?",
      o: [
        "Nowhere — it's undefined right away, JS doesn't look past the object's own properties",
        "In the prototype chain — the lookup walks up __proto__ all the way to Object.prototype",
        "In the global object — as if missing properties are looked up on window/global",
        "In the closure — as if it needs to search among the enclosing function's variables",
      ],
      a: 1,
      e: "The lookup walks the __proto__ chain. That's how [].map is found on Array.prototype. If it's not found anywhere, you get undefined.",
    },
  },
  {
    t: "JS · Array methods",
    q: "[1, 10, 2].sort() = ?",
    o: [
      "[1, 2, 10]",
      "[1, 10, 2]",
      "[10, 2, 1]",
      "TypeError",
    ],
    a: 1,
    e: "Без компаратора sort сравнивает КАК СТРОКИ: '1' < '10' < '2'. Числа: sort((a, b) => a - b). И помни: sort мутирует!",
    en: {
      t: "JS · Array methods",
      q: "[1, 10, 2].sort() = ?",
      o: [
        "[1, 2, 10]",
        "[1, 10, 2]",
        "[10, 2, 1]",
        "TypeError",
      ],
      a: 1,
      e: "Without a comparator, sort compares elements AS STRINGS: '1' < '10' < '2'. For numbers use sort((a, b) => a - b). And remember: sort mutates the array!",
    },
  },
  {
    t: "JS · Array methods",
    q: "Какой метод МУТИРУЕТ исходный массив?",
    o: [
      "map — возвращает новый массив, исходный остаётся нетронутым",
      "filter — тоже создаёт новый массив с отфильтрованными элементами",
      "splice — удаляет и/или добавляет элементы прямо в исходном массиве",
      "concat — склеивает массивы в новый, не трогая исходные",
    ],
    a: 2,
    e: "Мутируют: push/pop/shift/unshift/splice/sort/reverse/fill. map/filter/concat/slice возвращают новый массив.",
    en: {
      t: "JS · Array methods",
      q: "Which method MUTATES the original array?",
      o: [
        "map — returns a new array, the original stays untouched",
        "filter — also creates a new array with the filtered elements",
        "splice — removes and/or inserts elements directly in the original array",
        "concat — merges arrays into a new one, without touching the originals",
      ],
      a: 2,
      e: "Mutating methods: push/pop/shift/unshift/splice/sort/reverse/fill. map/filter/concat/slice return a new array.",
    },
  },
  {
    t: "JS · Array methods",
    q: "[].reduce((a, b) => a + b) — без второго аргумента?",
    o: [
      "0 — будто пустой массив аккумулируется в ноль по умолчанию",
      "undefined — будто пустой массив просто возвращает undefined",
      "TypeError — reduce пустого массива без initialValue кидает ошибку",
      "NaN — будто сложение несуществующих элементов даёт NaN",
    ],
    a: 2,
    e: "Без initialValue первый элемент берётся как старт — а его нет: TypeError: Reduce of empty array with no initial value. Всегда передавай initialValue.",
    en: {
      t: "JS · Array methods",
      q: "[].reduce((a, b) => a + b) — without the second argument?",
      o: [
        "0 — as if an empty array accumulates to zero by default",
        "undefined — as if an empty array simply returns undefined",
        "TypeError — reduce on an empty array with no initialValue throws",
        "NaN — as if adding nonexistent elements produces NaN",
      ],
      a: 2,
      e: "Without an initialValue, the first element is used as the starting accumulator — and there isn't one: TypeError: Reduce of empty array with no initial value. Always pass an initialValue.",
    },
  },
  {
    t: "JS · Array methods",
    q: "Самый короткий способ убрать дубликаты из массива примитивов?",
    o: [
      "arr.dedupe()",
      "[...new Set(arr)]",
      "arr.filter(Boolean)",
      "arr.unique()",
    ],
    a: 1,
    e: "Set хранит только уникальные значения, спред возвращает их в массив. filter(Boolean) убирает falsy, а не дубли.",
    en: {
      t: "JS · Array methods",
      q: "What's the shortest way to remove duplicates from an array of primitives?",
      o: [
        "arr.dedupe()",
        "[...new Set(arr)]",
        "arr.filter(Boolean)",
        "arr.unique()",
      ],
      a: 1,
      e: "A Set only keeps unique values, and spreading it turns them back into an array. filter(Boolean) removes falsy values, not duplicates.",
    },
  },
  {
    t: "JS · Event loop",
    q: "В каком порядке выведутся числа?\nconsole.log(1);\nsetTimeout(() => console.log(2), 0);\nPromise.resolve().then(() => console.log(3));\nconsole.log(4);",
    o: [
      "1 2 3 4",
      "1 4 3 2",
      "1 4 2 3",
      "1 3 4 2",
    ],
    a: 1,
    e: "Синхронный код (1, 4) → ВСЕ микротаски (3) → макротаски (2). Промисы всегда раньше setTimeout.",
    en: {
      t: "JS · Event loop",
      q: "In what order do the numbers print?\nconsole.log(1);\nsetTimeout(() => console.log(2), 0);\nPromise.resolve().then(() => console.log(3));\nconsole.log(4);",
      o: [
        "1 2 3 4",
        "1 4 3 2",
        "1 4 2 3",
        "1 3 4 2",
      ],
      a: 1,
      e: "Synchronous code (1, 4) runs first, then ALL microtasks (3), then macrotasks (2). Promises always run before setTimeout.",
    },
  },
  {
    t: "JS · Event loop",
    q: "Сколько микротасок выполнится перед следующей макротаской?",
    o: [
      "Одна — на каждую макротаску выполняется только один микротаск",
      "ВСЕ, включая созданные по ходу — очередь микротасок опустошается полностью",
      "Максимум 10 — движок ограничивает число микротасок за цикл",
      "Ни одной — микротаски ждут своей отдельной фазы event loop",
    ],
    a: 1,
    e: "Очередь микротасок опустошается ДО КОНЦА — даже те, что породили друг друга. Макротаски — по одной за цикл.",
    en: {
      t: "JS · Event loop",
      q: "How many microtasks run before the next macrotask?",
      o: [
        "One — only a single microtask runs per macrotask",
        "ALL of them, including ones created along the way — the microtask queue is drained completely",
        "At most 10 — the engine caps how many microtasks can run per cycle",
        "None — microtasks wait for their own separate event loop phase",
      ],
      a: 1,
      e: "The microtask queue is drained COMPLETELY — even microtasks that spawn other microtasks. Macrotasks run one per loop iteration.",
    },
  },
  {
    t: "JS · Event loop",
    q: "В каком порядке выведутся буквы?\nasync function f() {\n  console.log('A');\n  await null;\n  console.log('B');\n}\nf();\nconsole.log('C');",
    o: [
      "A B C",
      "A C B",
      "C A B",
      "B A C",
    ],
    a: 1,
    e: "До первого await функция выполняется СИНХРОННО (A). Всё после await — микротаска, ждёт конца синхронного кода (C), потом B.",
    en: {
      t: "JS · Event loop",
      q: "In what order do the letters print?\nasync function f() {\n  console.log('A');\n  await null;\n  console.log('B');\n}\nf();\nconsole.log('C');",
      o: [
        "A B C",
        "A C B",
        "C A B",
        "B A C",
      ],
      a: 1,
      e: "Everything up to the first await runs SYNCHRONOUSLY (A). Everything after await is a microtask, so it waits for the synchronous code to finish (C), then B runs.",
    },
  },
  {
    t: "JS · Bind/call/apply",
    q: "Чем call отличается от apply?",
    o: [
      "call не меняет this — эта функция вообще не влияет на контекст",
      "apply принимает аргументы массивом, call — через запятую по одному",
      "apply возвращает функцию, а не вызывает её сразу",
      "ничем — это два совершенно взаимозаменяемых метода",
    ],
    a: 1,
    e: "Мнемоника: Apply = Array, Call = Comma. Оба вызывают функцию сразу с указанным this.",
    en: {
      t: "JS · Bind/call/apply",
      q: "How does call differ from apply?",
      o: [
        "call doesn't change this — it has no effect on the context at all",
        "apply takes its arguments as an array, call takes them comma-separated one by one",
        "apply returns a function instead of calling it right away",
        "no difference — they're two completely interchangeable methods",
      ],
      a: 1,
      e: "Mnemonic: Apply = Array, Call = Comma. Both invoke the function immediately with the given this.",
    },
  },
  {
    t: "JS · Bind/call/apply",
    q: "Какой this окажется внутри who?\nconst a = who.bind({ n: 'A' });\na.call({ n: 'B' });",
    o: [
      "{n: 'B'}",
      "{n: 'A'}",
      "undefined",
      "window",
    ],
    a: 1,
    e: "bind прибивает this намертво — перебить его call/apply/повторным bind нельзя. Исключение одно: оператор new.",
    en: {
      t: "JS · Bind/call/apply",
      q: "What will this be inside who?\nconst a = who.bind({ n: 'A' });\na.call({ n: 'B' });",
      o: [
        "{n: 'B'}",
        "{n: 'A'}",
        "undefined",
        "window",
      ],
      a: 1,
      e: "bind locks this in permanently — it can't be overridden by call, apply, or another bind. The one exception is the new operator.",
    },
  },
  {
    t: "JS · Bind/call/apply",
    q: "В чём ошибка: const f = obj.method.bind(obj)(); f();",
    o: [
      "bind так не работает — метод не поддерживает вызов сразу после bind",
      "Лишние () — bind(obj)() вызывает метод сразу, и в f попадает результат, а не функция",
      "Нельзя bind к obj — bind работает только с явно созданными объектами",
      "Ошибки нет — f() благополучно вызовет метод объекта повторно с тем же контекстом",
    ],
    a: 1,
    e: "bind(obj)() вызывает функцию сразу — f получит возвращённое значение, и f() упадёт. Для отложенного вызова скобки не нужны.",
    en: {
      t: "JS · Bind/call/apply",
      q: "What's the bug here: const f = obj.method.bind(obj)(); f();",
      o: [
        "bind doesn't work that way — a method doesn't support being called right after bind",
        "The extra () — bind(obj)() invokes the method immediately, so f ends up holding the result, not a function",
        "You can't bind to obj — bind only works with explicitly created objects",
        "There's no bug — f() will happily call the object's method again with the same context",
      ],
      a: 1,
      e: "bind(obj)() calls the function immediately — f ends up holding the returned value, so f() will fail. For a deferred call, drop the trailing parentheses.",
    },
  },
  {
    t: "JS · Bind/call/apply",
    q: "Что вернёт fn()?\nconst cat = { name: \"Барсик\", say() { return this.name; } };\nconst fn = cat.say;\nfn();",
    o: [
      "\"Барсик\" — будто this всегда указывает на объект, где метод был объявлен",
      "undefined — при «голом» вызове fn() this не привязан к cat, поэтому this.name пуст",
      "TypeError: say is not a function — будто присваивание fn = cat.say ломает саму функцию",
      "ReferenceError — будто переменная fn нигде не объявлена",
    ],
    a: 1,
    e: "this определяется в момент ВЫЗОВА, а не объявления. fn() — «голый» вызов без объекта: this = undefined/globalThis, this.name → undefined. Фиксы: cat.say.bind(cat), fn.call(cat) или обёртка () => cat.say().",
    en: {
      t: "JS · Bind/call/apply",
      q: "What does fn() return?\nconst cat = { name: \"Barsik\", say() { return this.name; } };\nconst fn = cat.say;\nfn();",
      o: [
        "\"Barsik\" — as if this always points to the object where the method was defined",
        "undefined — a \"bare\" call fn() has no this bound to cat, so this.name is empty",
        "TypeError: say is not a function — as if the assignment fn = cat.say breaks the function itself",
        "ReferenceError — as if the variable fn was never declared",
      ],
      a: 1,
      e: "this is determined at CALL time, not at definition time. fn() is a bare call with no object: this ends up as undefined/globalThis, so this.name is undefined. Fixes: cat.say.bind(cat), fn.call(cat), or a wrapper () => cat.say().",
    },
  },
  {
    t: "JS · Классы",
    q: "Где физически лежит метод walk?\nclass A { legs = 4; walk() {} }\nconst a = new A();",
    o: [
      "В экземпляре a, как и legs — будто методы объявляются так же, как обычные поля",
      "В A.prototype — одна копия метода используется всеми экземплярами класса",
      "В глобальной области — будто методы классов регистрируются как глобальные функции",
      "Копируется в каждый экземпляр при вызове — будто память тратится на каждый вызов",
    ],
    a: 1,
    e: "Класс — сахар над прототипами: методы идут в prototype (общие), поля-свойства создаются в каждом экземпляре. Отсюда разница по памяти между методом и полем-стрелкой.",
    en: {
      t: "JS · Classes",
      q: "Where does the walk method physically live?\nclass A { legs = 4; walk() {} }\nconst a = new A();",
      o: [
        "On the instance a, just like legs — as if methods are declared the same way as regular fields",
        "On A.prototype — a single copy of the method is shared by all instances of the class",
        "In the global scope — as if class methods get registered as global functions",
        "Copied into each instance on every call — as if memory is spent on every invocation",
      ],
      a: 1,
      e: "A class is sugar over prototypes: methods go on the prototype (shared), while field properties are created on each instance. That's where the memory difference between a method and an arrow-function field comes from.",
    },
  },
  {
    t: "JS · Классы",
    q: "Что произойдёт при new Child()?\nclass Child extends Base {\n  constructor() {\n    this.x = 1;\n    super();\n  }\n}",
    o: [
      "Работает — движок сам переставит this.x после вызова super()",
      "ReferenceError: обращение к this до вызова super() запрещено в конструкторе-наследнике",
      "super() вызовется автоматически раньше — компилятор сам исправит порядок",
      "TypeError при создании экземпляра — конструктор-наследник всегда падает без явного this",
    ],
    a: 1,
    e: "В наследнике this не существует, пока super() не создал объект. Порядок: super() → поля ребёнка → тело конструктора.",
    en: {
      t: "JS · Classes",
      q: "What happens on new Child()?\nclass Child extends Base {\n  constructor() {\n    this.x = 1;\n    super();\n  }\n}",
      o: [
        "It works — the engine silently reorders this.x to run after the super() call",
        "ReferenceError: accessing this before calling super() is forbidden in a derived class constructor",
        "super() gets called automatically earlier — the compiler fixes the order for you",
        "TypeError when creating the instance — a derived constructor always fails without an explicit this",
      ],
      a: 1,
      e: "In a derived class, this doesn't exist until super() has created the object. The order is: super() → child's fields → the rest of the constructor body.",
    },
  },
  {
    t: "JS · Классы",
    q: "Чем #private отличается от конвенции _private?",
    o: [
      "Ничем, обе — договорённость между разработчиками, движок их не различает",
      "#private обеспечивает движок: недоступно снаружи, не видно в Object.keys и JSON",
      "_private быстрее работает — движок оптимизирует поля с подчёркиванием",
      "#private доступно только в статических методах, а не в обычных",
    ],
    a: 1,
    e: "Подчёркивание — просто соглашение, поле остаётся публичным. # — настоящая приватность на уровне языка: обращение снаружи это синтаксическая ошибка.",
    en: {
      t: "JS · Classes",
      q: "How does #private differ from the _private naming convention?",
      o: [
        "No difference — both are just conventions between developers that the engine doesn't distinguish",
        "#private is enforced by the engine: inaccessible from outside, invisible to Object.keys and JSON",
        "_private runs faster — the engine optimizes fields with an underscore",
        "#private is only available in static methods, not in regular ones",
      ],
      a: 1,
      e: "An underscore is just a convention — the field is still public. # gives real, language-level privacy: accessing it from outside is a syntax error.",
    },
  },
  {
    t: "JS · Классы",
    q: "new Foo(); class Foo {} — что произойдёт?",
    o: [
      "Работает: объявления классов всплывают целиком, как function declaration",
      "ReferenceError: класс, как let/const, находится в TDZ до строки объявления",
      "undefined — будто необъявленный класс просто не создаёт экземпляр",
      "SyntaxError — будто использовать класс до объявления синтаксически запрещено",
    ],
    a: 1,
    e: "Класс регистрируется, но недоступен до строки объявления — ведёт себя как let/const, а не как function declaration.",
    en: {
      t: "JS · Classes",
      q: "new Foo(); class Foo {} — what happens?",
      o: [
        "It works: class declarations are hoisted whole, like function declarations",
        "ReferenceError: like let/const, a class sits in the TDZ until its declaration line",
        "undefined — as if an undeclared class simply doesn't create an instance",
        "SyntaxError — as if using a class before its declaration is a syntax violation",
      ],
      a: 1,
      e: "The class binding is registered, but stays inaccessible until its declaration line — it behaves like let/const, not like a function declaration.",
    },
  },
  {
    t: "JS · Коллекции",
    q: "Чем Map принципиально отличается от обычного объекта?",
    o: [
      "Map работает быстрее на любых операциях за счёт особой внутренней структуры",
      "Ключи любого типа (не только строки), гарантированный порядок, size, нет прототипа",
      "Map автоматически сериализуется в JSON без дополнительных преобразований",
      "Map хранит только примитивы — объекты и функции нельзя использовать как значения",
    ],
    a: 1,
    e: "У объекта ключи приводятся к строкам, есть унаследованные свойства, размер только через Object.keys. Зато объект сериализуется в JSON, а Map — нет.",
    en: {
      t: "JS · Collections",
      q: "How does Map fundamentally differ from a plain object?",
      o: [
        "Map is faster at every operation thanks to a special internal structure",
        "Keys of any type (not just strings), guaranteed iteration order, a size property, no inherited prototype noise",
        "Map serializes to JSON automatically, without any extra conversion",
        "Map can only store primitives — objects and functions can't be used as values",
      ],
      a: 1,
      e: "With a plain object, keys get coerced to strings, there are inherited properties, and getting the size requires Object.keys. On the other hand, an object serializes to JSON while a Map doesn't.",
    },
  },
  {
    t: "JS · Коллекции",
    q: "JSON.stringify(new Map([['a', 1]])) вернёт...",
    o: [
      "{\"a\":1} — будто Map автоматически превращается в обычный объект",
      "{} — Map не имеет собственных перечисляемых свойств для JSON",
      "[[\"a\",1]] — будто stringify сохраняет пары ключ-значение как массив",
      "TypeError — будто сериализовать Map в JSON вообще нельзя",
    ],
    a: 1,
    e: "Map и Set не сериализуются — получишь пустой объект. Конвертировать явно: JSON.stringify([...map]), обратно new Map(JSON.parse(str)).",
    en: {
      t: "JS · Collections",
      q: "What does JSON.stringify(new Map([['a', 1]])) return?",
      o: [
        "{\"a\":1} — as if a Map automatically turns into a plain object",
        "{} — a Map has no own enumerable properties for JSON to serialize",
        "[[\"a\",1]] — as if stringify preserves the key-value pairs as an array",
        "TypeError — as if serializing a Map to JSON isn't allowed at all",
      ],
      a: 1,
      e: "Map and Set don't serialize — you get an empty object. Convert explicitly: JSON.stringify([...map]), and back with new Map(JSON.parse(str)).",
    },
  },
  {
    t: "JS · Коллекции",
    q: "Зачем нужен WeakMap вместо Map?",
    o: [
      "Он быстрее на больших объёмах — оптимизирован под большие коллекции",
      "Держит ключи слабо: объект без других ссылок собирается GC вместе с записью",
      "Позволяет использовать примитивы как ключи, в отличие от обычного Map",
      "Умеет итерироваться в обратном порядке, в отличие от Map",
    ],
    a: 1,
    e: "Обычный Map удерживает объект в памяти вечно (утечка). WeakMap — для метаданных и кэшей по объектам/DOM-узлам. Цена: только объекты-ключи, без итерации и size.",
    en: {
      t: "JS · Collections",
      q: "Why would you use WeakMap instead of Map?",
      o: [
        "It's faster at large scale — optimized for big collections",
        "It holds keys weakly: an object with no other references gets garbage-collected along with its entry",
        "It lets you use primitives as keys, unlike a regular Map",
        "It can iterate in reverse order, unlike Map",
      ],
      a: 1,
      e: "A regular Map keeps an object alive in memory forever (a leak). WeakMap is meant for metadata and caches keyed by objects/DOM nodes. The trade-off: only object keys, and no iteration or size.",
    },
  },
  {
    t: "JS · Коллекции",
    q: "new Set([NaN, NaN]).size — сколько?",
    o: [
      "2 — будто NaN не равен самому себе даже при сравнении внутри коллекции",
      "1 — Set использует алгоритм SameValueZero, где NaN считается равным NaN",
      "0 — будто добавление NaN в Set игнорируется как невалидное значение",
      "TypeError — будто NaN нельзя использовать как элемент коллекции",
    ],
    a: 1,
    e: "Set сравнивает по SameValueZero: NaN считается равным самому себе (в отличие от ===), а +0 и -0 — одним значением. Поэтому includes находит NaN, а indexOf нет.",
    en: {
      t: "JS · Collections",
      q: "What is new Set([NaN, NaN]).size?",
      o: [
        "2 — as if NaN isn't equal to itself even when compared inside a collection",
        "1 — Set uses the SameValueZero algorithm, under which NaN is considered equal to NaN",
        "0 — as if adding NaN to a Set is ignored as an invalid value",
        "TypeError — as if NaN can't be used as an element of a collection",
      ],
      a: 1,
      e: "Set compares elements using SameValueZero: NaN is considered equal to itself (unlike with ===), and +0/-0 count as the same value. That's why includes finds NaN while indexOf doesn't.",
    },
  },
  {
    t: "JS · Итераторы",
    q: "Почему for...of по обычному объекту падает?",
    o: [
      "У объекта слишком много ключей — движок ограничивает перебор большими объектами",
      "У него нет метода [Symbol.iterator] — обычный объект не реализует протокол итерации",
      "for...of работает только с массивами и другими встроенными коллекциями",
      "Нужен строгий режим — вне 'use strict' for...of работать не будет",
    ],
    a: 1,
    e: "for...of требует протокол итерации. Для объекта используют for...in (по ключам, лезет в прототип) или for (const [k,v] of Object.entries(obj)).",
    en: {
      t: "JS · Iterators",
      q: "Why does for...of fail on a plain object?",
      o: [
        "The object has too many keys — the engine limits iteration on large objects",
        "It has no [Symbol.iterator] method — a plain object doesn't implement the iteration protocol",
        "for...of only works with arrays and other built-in collections",
        "Strict mode is required — outside 'use strict', for...of won't work",
      ],
      a: 1,
      e: "for...of requires the iteration protocol. For plain objects you'd use for...in (over keys, walks the prototype chain too) or for (const [k,v] of Object.entries(obj)).",
    },
  },
  {
    t: "JS · Итераторы",
    q: "Что вернёт второй спред?\nconst it = [1,2,3][Symbol.iterator]();\n[...it]; [...it];",
    o: [
      "[1,2,3] оба раза — будто итератор можно перебирать заново",
      "[] — итератор одноразовый: после первого прохода он полностью исчерпан",
      "TypeError — будто повторный спред одноразового итератора кидает ошибку",
      "[3,2,1] — будто повторный вызов возвращает элементы в обратном порядке",
    ],
    a: 1,
    e: "Массив итерируемый (можно перебирать многократно), а итератор — одноразовый курсор. Та же ловушка с генератором: повторный перебор даст пустоту.",
    en: {
      t: "JS · Iterators",
      q: "What does the second spread return?\nconst it = [1,2,3][Symbol.iterator]();\n[...it]; [...it];",
      o: [
        "[1,2,3] both times — as if the iterator can be walked through again",
        "[] — the iterator is single-use: it's fully exhausted after the first pass",
        "TypeError — as if spreading an already-exhausted iterator again throws",
        "[3,2,1] — as if the second call returns the elements in reverse order",
      ],
      a: 1,
      e: "An array is iterable (you can iterate it repeatedly), but an iterator is a one-time cursor. The same trap applies to generators: iterating them again yields nothing.",
    },
  },
  {
    t: "JS · Итераторы",
    q: "Что даёт генератор function* с yield?",
    o: [
      "Многопоточность в JS — будто генератор выполняется в отдельном потоке",
      "Функция приостанавливается на yield и продолжает с этого места, сохраняя состояние",
      "Автоматическую асинхронность — будто yield сам оборачивает результат в промис",
      "Кэширование результатов вызова — будто генератор запоминает прошлые значения",
    ],
    a: 1,
    e: "Пауза + сохранение локального состояния = ленивые и бесконечные последовательности, обход дерева без промежуточных массивов. async/await — сахар над этим механизмом.",
    en: {
      t: "JS · Iterators",
      q: "What does a function* generator with yield give you?",
      o: [
        "Multithreading in JS — as if the generator runs on a separate thread",
        "The function pauses at yield and resumes from that point, preserving its local state",
        "Automatic asynchrony — as if yield wraps the result in a promise on its own",
        "Caching of call results — as if the generator remembers previous values",
      ],
      a: 1,
      e: "Pausing plus preserved local state gives you lazy and infinite sequences, and tree traversal without intermediate arrays. async/await is sugar built on top of this same mechanism.",
    },
  },
  {
    t: "JS · Промисы",
    q: "Нужны результаты всех запросов, включая упавшие. Какой комбинатор?",
    o: [
      "Promise.all — вернёт всё, даже если один из промисов упал",
      "Promise.allSettled — не реджектится, отдаёт status/value/reason по каждому",
      "Promise.race — вернёт результат только первого завершившегося промиса",
      "Promise.any — вернёт результат первого успешно выполненного промиса",
    ],
    a: 1,
    e: "all — fail-fast: первая же ошибка отменяет весь результат. allSettled нужен для дашбордов и пакетных операций, где важен каждый исход.",
    en: {
      t: "JS · Promises",
      q: "You need the results of all requests, including the ones that failed. Which combinator?",
      o: [
        "Promise.all — returns everything, even if one of the promises rejects",
        "Promise.allSettled — never rejects, gives you status/value/reason for each one",
        "Promise.race — returns only the result of the first promise to settle",
        "Promise.any — returns the result of the first promise to succeed",
      ],
      a: 1,
      e: "all is fail-fast: a single rejection discards the whole result. allSettled is what you need for dashboards and batch operations, where every outcome matters.",
    },
  },
  {
    t: "JS · Промисы",
    q: "Чем Promise.race отличается от Promise.any?",
    o: [
      "Ничем, это синонимы — race и any полностью взаимозаменяемы",
      "race — первый ЗАВЕРШИВШИЙСЯ (в т.ч. ошибкой), any — первый УСПЕШНЫЙ",
      "any работает только с двумя промисами, race — с произвольным числом",
      "race отменяет остальные промисы, как только один из них завершится",
    ],
    a: 1,
    e: "race удобен для таймаутов (ошибка тоже считается). any реджектится только если провалились все — с AggregateError.",
    en: {
      t: "JS · Promises",
      q: "How does Promise.race differ from Promise.any?",
      o: [
        "No difference, they're synonyms — race and any are fully interchangeable",
        "race resolves with the first promise to SETTLE (rejection counts too), any resolves with the first to SUCCEED",
        "any only works with two promises, race works with any number",
        "race cancels the remaining promises as soon as one of them settles",
      ],
      a: 1,
      e: "race is handy for timeouts (a rejection counts as settling). any only rejects if every promise fails — with an AggregateError.",
    },
  },
  {
    t: "JS · Промисы",
    q: "Promise.all([slow, failsFast]) — что произойдёт со slow после реджекта?",
    o: [
      "Он будет отменён автоматически — Promise.all остановит все промисы при первом реджекте",
      "Продолжит выполняться — промис отменить нельзя, его результат просто никому не нужен",
      "Выполнится, но результат попадёт в catch вместе с ошибкой failsFast",
      "Зависнет в памяти навсегда, пока не будет собран сборщиком мусора",
    ],
    a: 1,
    e: "Промис не отменяем: all лишь перестаёт слушать. Для реальной отмены сетевого запроса нужен AbortController и signal.",
    en: {
      t: "JS · Promises",
      q: "Promise.all([slow, failsFast]) — what happens to slow after the rejection?",
      o: [
        "It gets cancelled automatically — Promise.all stops every promise on the first rejection",
        "It keeps running — a promise can't be cancelled, its result is simply no longer needed by anyone",
        "It finishes, and its result ends up in the catch block alongside the failsFast error",
        "It hangs in memory forever, until garbage collected",
      ],
      a: 1,
      e: "A promise can't be cancelled: all simply stops listening to it. To actually cancel a network request, you need an AbortController and its signal.",
    },
  },
  {
    t: "JS · Промисы",
    q: "Поймает ли ошибку этот код?\ntry {\n  setTimeout(() => { throw new Error('бум'); }, 0);\n} catch (e) {}",
    o: [
      "Да, catch отработает — try перехватывает исключения из любых колбэков внутри",
      "Нет — throw в колбэке произойдёт в другом тике, вне синхронного стека этого try",
      "Да, но только в strict mode — там try распространяется на асинхронный код",
      "Код не скомпилируется — throw внутри колбэка setTimeout является ошибкой",
    ],
    a: 1,
    e: "try/catch работает в пределах своего синхронного стека (или с await). Внутри колбэков нужен свой try/catch, для промисов — .catch.",
    en: {
      t: "JS · Promises",
      q: "Will this code catch the error?\ntry {\n  setTimeout(() => { throw new Error('boom'); }, 0);\n} catch (e) {}",
      o: [
        "Yes, the catch block runs — try catches exceptions from any callback inside it",
        "No — the throw inside the callback happens on a different tick, outside this try's synchronous stack",
        "Yes, but only in strict mode — there try extends to asynchronous code",
        "The code won't compile — throwing inside a setTimeout callback is a syntax error",
      ],
      a: 1,
      e: "try/catch only works within its own synchronous call stack (or with await). Callbacks need their own try/catch, and promises need .catch.",
    },
  },
  {
    t: "JS · Модули",
    q: "ESM-модуль: export let count = 0; export const inc = () => { count++ }.\nИмпортёр вызывает inc(). Что он увидит в count?",
    o: [
      "1 — экспорт ESM это live binding: импортёр видит актуальное значение",
      "0 — при импорте была снята копия значения на момент экспорта",
      "undefined — примитив let нельзя экспортировать, только объекты",
      "ReferenceError — count изменён вне модуля-владельца, это запрещено",
    ],
    a: 0,
    e: "Экспортируется ИМЯ, а не значение: импортёр читает живую ссылку. В CommonJS exports.count = count отдал бы копию, и импортёр остался бы с 0 — классический вопрос на разницу систем.",
    en: {
      t: "JS · Modules",
      q: "An ESM module: export let count = 0; export const inc = () => { count++ }.\nThe importer calls inc(). What does it see in count?",
      o: [
        "1 — an ESM export is a live binding: the importer sees the current value",
        "0 — a copy of the value was taken at export time during the import",
        "undefined — a let primitive can't be exported, only objects can",
        "ReferenceError — count was changed outside the owning module, forbidden",
      ],
      e: "The NAME is exported, not the value: the importer reads a live reference. In CommonJS exports.count = count would hand out a copy and the importer would be stuck with 0 — the classic systems-difference question.",
    },
  },
  {
    t: "JS · Модули",
    q: "За счёт чего работает tree shaking?",
    o: [
      "Импорты ESM статические: бандлер строит граф до выполнения и видит неиспользуемое",
      "Бандлер запускает код в песочнице и замеряет, какие функции реально вызывались",
      "Минификатор вырезает любой код, на который не нашлось ссылок в строках",
      "V8 в рантайме выгружает функции, которые долго не вызывались из бандла",
    ],
    a: 0,
    e: "Ключ — статичность ESM: import/export объявлены на верхнем уровне и анализируются без выполнения. С динамическим require так нельзя. Поэтому default-объект export default { a, b } шейкинг ломает.",
    en: {
      t: "JS · Modules",
      q: "What makes tree shaking possible?",
      o: [
        "ESM imports are static: the bundler builds the graph before execution and sees what's unused",
        "The bundler runs the code in a sandbox and measures which functions actually got called",
        "The minifier strips any code that has no references found in string literals",
        "V8 unloads functions from the bundle at runtime once they go uncalled for long enough",
      ],
      e: "The key is ESM's static nature: import/export are declared at the top level and analyzed without running the code. Dynamic require can't offer that. That's also why export default { a, b } breaks shaking.",
    },
  },
  {
    t: "JS · Модули",
    q: "Нужно грузить тяжёлый модуль только по клику. Как правильно?",
    o: [
      "const mod = await import(\"./heavy.js\") внутри обработчика клика",
      "Обернуть import { heavy } from \"./heavy.js\" в if внутри обработчика",
      "Вынести import в setTimeout — модуль загрузится после первого рендера",
      "Прописать модуль в lazy-секции package.json — бандлер отложит его сам",
    ],
    a: 0,
    e: "Статический import в if — SyntaxError: он объявляется только на верхнем уровне. Динамический import() возвращает промис и создаёт отдельный чанк (code splitting); в React поверх этого работает lazy + Suspense.",
    en: {
      t: "JS · Modules",
      q: "You need to load a heavy module only on click. What's the right way?",
      o: [
        "const mod = await import(\"./heavy.js\") inside the click handler",
        "Wrapping import { heavy } from \"./heavy.js\" in an if inside the handler",
        "Moving the import into a setTimeout so the module loads after first render",
        "Listing the module in a lazy section of package.json so the bundler defers it",
      ],
      e: "A static import inside an if is a SyntaxError: it's only allowed at the top level. Dynamic import() returns a promise and creates a separate chunk (code splitting); in React, lazy + Suspense build on top of it.",
    },
  },
];
