// Вопросы квиза: секция Native
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

import type { Question } from "../types";

export const NATIVE_QUESTIONS: Question[] = [
  {
    t: "Native · Архитектура",
    q: "Во что рендерится <View> в React Native?",
    o: [
      "В div внутри системного WebView, обёрнутого нативным контейнером",
      "В настоящую нативную вью (UIView / android.View)",
      "В элемент canvas, который приложение перерисовывает вручную",
      "В SwiftUI-компонент, скомпилированный из JSX на этапе сборки",
    ],
    a: 1,
    e: "RN ≠ Cordova: никакого WebView. Каждый RN-компонент маппится в реальную нативную вью — поэтому UI неотличим от нативного.",
    en: {
      t: "Native · Architecture",
      q: "What does <View> render into in React Native?",
      o: [
        "A div inside a system WebView wrapped in a native container",
        "A real native view (UIView / android.View)",
        "A canvas element that the app redraws manually",
        "A SwiftUI component compiled from JSX at build time",
      ],
      e: "RN ≠ Cordova: there's no WebView involved. Every RN component maps to a real native view — that's why the UI is indistinguishable from native.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Что было узким местом старой архитектуры RN и что это решило?",
    o: [
      "Медленный JS-код — решил переход всего проекта на TypeScript",
      "JSON-сериализация bridge — решил JSI (прямые C++-ссылки)",
      "Большой размер APK-файла — решил движок Hermes",
      "Отсутствие Flexbox в раскладке — решил движок Yoga 2",
    ],
    a: 1,
    e: "Bridge гонял асинхронные JSON-сообщения между JS и нативом. JSI даёт прямые ссылки без сериализации; сверху — Fabric и TurboModules.",
    en: {
      t: "Native · Architecture",
      q: "What was the bottleneck of RN's old architecture, and what solved it?",
      o: [
        "Slow JS code — solved by migrating the whole project to TypeScript",
        "JSON serialization over the bridge — solved by JSI (direct C++ references)",
        "Large APK size — solved by the Hermes engine",
        "Lack of Flexbox in layout — solved by the Yoga 2 engine",
      ],
      e: "The bridge shuttled asynchronous JSON messages between JS and native. JSI provides direct references without serialization; Fabric and TurboModules are built on top of it.",
    },
  },
  {
    t: "Native · Списки",
    q: "Чем FlatList отличается от ScrollView?",
    o: [
      "FlatList просто быстрее скроллится за счёт GPU-ускорения",
      "FlatList виртуализирует: рендерит только окно вокруг вьюпорта",
      "ScrollView физически не умеет вертикальный скролл контента",
      "Ничем не отличается, FlatList — это просто новое имя ScrollView",
    ],
    a: 1,
    e: "ScrollView рендерит ВСЕХ детей сразу (ок для форм), FlatList — только видимое окно (обязателен для длинных списков). Вложенный FlatList в ScrollView ломает виртуализацию.",
    en: {
      t: "Native · Lists",
      q: "How does FlatList differ from ScrollView?",
      o: [
        "FlatList just scrolls faster thanks to GPU acceleration",
        "FlatList virtualizes: it only renders a window around the viewport",
        "ScrollView is physically incapable of vertical content scrolling",
        "There's no difference — FlatList is just a new name for ScrollView",
      ],
      e: "ScrollView renders ALL children at once (fine for forms), FlatList renders only the visible window (essential for long lists). Nesting a FlatList inside a ScrollView breaks virtualization.",
    },
  },
  {
    t: "Native · Навигация",
    q: "Ушёл с экрана через navigate — сработает ли cleanup его useEffect?",
    o: [
      "Да, экран сразу размонтируется и cleanup сработает как обычно",
      "Нет — Stack держит экран в памяти; нужен useFocusEffect",
      "Да, но cleanup срабатывает с задержкой и только на iOS",
      "Только если у экрана вообще нет собственного state",
    ],
    a: 1,
    e: "Стек-навигация хранит прошлые экраны (это стек!). Уход с экрана ≠ unmount — таймеры и подписки живут. Для логики «на фокусе» — useFocusEffect / события focus/blur.",
    en: {
      t: "Native · Navigation",
      q: "You navigated away from a screen via navigate — will its useEffect cleanup run?",
      o: [
        "Yes, the screen unmounts immediately and cleanup runs as usual",
        "No — the Stack keeps the screen in memory; you need useFocusEffect",
        "Yes, but cleanup runs with a delay and only on iOS",
        "Only if the screen has no state of its own at all",
      ],
      e: "Stack navigation keeps past screens around (it's a stack!). Leaving a screen ≠ unmounting it — timers and subscriptions stay alive. For 'on focus' logic, use useFocusEffect / the focus/blur events.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Что делает Hermes?",
    o: [
      "Полностью заменяет Metro-бандлер и сборку JS-файлов",
      "Компилирует JS в байткод на этапе СБОРКИ → быстрый старт, меньше памяти",
      "Ускоряет нативные анимации, разгружая UI-поток",
      "Кэширует сетевые запросы приложения между сессиями",
    ],
    a: 1,
    e: "Hermes — JS-движок под RN (дефолт): AOT-компиляция в байткод вместо парсинга JS на старте. Выигрыш — TTI и память; JIT нет, но для мобильного UI это выгодный размен.",
    en: {
      t: "Native · Architecture",
      q: "What does Hermes do?",
      o: [
        "Fully replaces the Metro bundler and JS file building",
        "Compiles JS to bytecode at BUILD time → faster startup, less memory",
        "Speeds up native animations by offloading the UI thread",
        "Caches the app's network requests between sessions",
      ],
      e: "Hermes is RN's JS engine (the default): AOT-compiles to bytecode instead of parsing JS at startup. The payoff is TTI and memory; there's no JIT, but for mobile UI that's a worthwhile trade-off.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Какие три потока важно знать в RN?",
    o: [
      "main-поток, worker-поток, service-поток браузера",
      "JS-поток, UI (main) поток, shadow/layout-поток (Yoga)",
      "Фазы render, commit и paint из модели самого React",
      "Отдельный iOS-поток, отдельный Android-поток и JS-поток",
    ],
    a: 1,
    e: "JS-поток исполняет твой код и React; UI-поток рисует нативные вью и обрабатывает жесты; фоновый shadow-поток считает flexbox-раскладку (Yoga).",
    en: {
      t: "Native · Architecture",
      q: "What three threads are important to know in RN?",
      o: [
        "The browser's main thread, worker thread, and service thread",
        "The JS thread, the UI (main) thread, and the shadow/layout thread (Yoga)",
        "React's own render, commit, and paint phases",
        "A separate iOS thread, a separate Android thread, and the JS thread",
      ],
      e: "The JS thread runs your code and React; the UI thread draws native views and handles gestures; a background shadow thread computes flexbox layout (Yoga).",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Что такое Yoga?",
    o: [
      "Стейт-менеджер для React Native, альтернатива Redux",
      "C++ движок flexbox-раскладки, считающий layout в shadow tree",
      "Библиотека декларативных анимаций поверх Reanimated",
      "Система сборки iOS-проектов на замену Xcode",
    ],
    a: 1,
    e: "Yoga — кроссплатформенная реализация flexbox на C++. Поэтому в RN раскладка только flexbox, и работает одинаково на обеих ОС.",
    en: {
      t: "Native · Architecture",
      q: "What is Yoga?",
      o: [
        "A state manager for React Native, an alternative to Redux",
        "A C++ flexbox layout engine that computes layout in the shadow tree",
        "A declarative animation library built on top of Reanimated",
        "A build system for iOS projects that replaces Xcode",
      ],
      e: "Yoga is a cross-platform C++ implementation of flexbox. That's why RN layout is flexbox-only, and it behaves identically on both OSes.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Что такое TurboModules?",
    o: [
      "Оптимизированные npm-пакеты, ускоряющие установку зависимостей проекта",
      "Нативные модули новой архитектуры: ленивая загрузка + типизация codegen + вызовы через JSI",
      "Нативные модули, исполняющиеся внутри изолированного WebView-контекста",
      "Плагины сборщика Metro, трансформирующие исходный код на этапе сборки",
    ],
    a: 1,
    e: "В старой архитектуре все модули инициализировались на старте и общались через bridge. TurboModules грузятся при первом обращении и вызываются через JSI без JSON-сериализации.",
    en: {
      t: "Native · Architecture",
      q: "What are TurboModules?",
      o: [
        "Optimized npm packages that speed up installing project dependencies",
        "New-architecture native modules: lazy loading + codegen typing + calls via JSI",
        "Native modules that execute inside an isolated WebView context",
        "Metro bundler plugins that transform source code at build time",
      ],
      e: "In the old architecture, all modules were initialized at startup and communicated over the bridge. TurboModules load on first access and are invoked via JSI without JSON serialization.",
    },
  },
  {
    t: "Native · Styling",
    q: "Какой flexDirection по умолчанию в React Native?",
    o: [
      "row, как в вебе — элементы выстраиваются по горизонтали",
      "column (вертикальная стопка сверху вниз)",
      "row-reverse — элементы идут в обратном горизонтальном порядке",
      "нет дефолта: flexDirection обязателен для любого контейнера",
    ],
    a: 1,
    e: "В вебе дефолт row, в RN — column (мобильные экраны вертикальные). Один из самых частых сюрпризов при переходе с веба.",
    en: {
      t: "Native · Styling",
      q: "What is the default flexDirection in React Native?",
      o: [
        "row, like on the web — items lay out horizontally",
        "column (a vertical stack from top to bottom)",
        "row-reverse — items go in reverse horizontal order",
        "there is no default: flexDirection is required on every container",
      ],
      e: "On the web the default is row, in RN it's column (mobile screens are vertical). One of the most common surprises when coming from the web.",
    },
  },
  {
    t: "Native · Styling",
    q: "Что будет?\n<View>Привет</View>",
    o: [
      "Текст выведется как обычно, View умеет рендерить строки",
      "Ошибка: Text strings must be rendered within a <Text> component",
      "Текст выведется, но без применения текстовых стилей",
      "Появится предупреждение в консоли, но элемент отрендерится",
    ],
    a: 1,
    e: "В RN голый текст может жить только внутри <Text>. View — контейнер, текст в нём — Invariant Violation.",
    en: {
      t: "Native · Styling",
      q: "What happens here?\n<View>Hello</View>",
      o: [
        "The text renders as usual — View can render strings",
        "Error: Text strings must be rendered within a <Text> component",
        "The text renders, but without any text styles applied",
        "A console warning appears, but the element still renders",
      ],
      e: "In RN, bare text can only live inside <Text>. View is a container — putting text directly inside it is an Invariant Violation.",
    },
  },
  {
    t: "Native · Styling",
    q: "Как сделать кроссплатформенную тень?",
    o: [
      "Свойство box-shadow работает одинаково на обеих платформах",
      "shadowColor/Offset/Opacity для iOS + elevation для Android",
      "Свойство elevation само по себе работает везде без правок",
      "Тени в React Native в принципе нельзя реализовать",
    ],
    a: 1,
    e: "Классика OS-specific: shadow*-свойства — только iOS, elevation — только Android. Задавать оба (в новой архитектуре появился boxShadow).",
    en: {
      t: "Native · Styling",
      q: "How do you create a cross-platform shadow?",
      o: [
        "The box-shadow property works identically on both platforms",
        "shadowColor/Offset/Opacity for iOS + elevation for Android",
        "The elevation property alone works everywhere with no adjustments",
        "Shadows simply cannot be implemented in React Native",
      ],
      e: "A classic OS-specific case: shadow* properties are iOS-only, elevation is Android-only. You set both (the new architecture also introduced boxShadow).",
    },
  },
  {
    t: "Native · Styling",
    q: "{ padding: 16 } — 16 чего?",
    o: [
      "Пикселей физического экрана устройства, как в canvas",
      "Density-independent points (dp/pt) — физический размер похож на разных экранах",
      "Проценты от ширины родительского контейнера-обёртки",
      "Единица rem, как в вебе, относительно корневого шрифта",
    ],
    a: 1,
    e: "Числа в стилях RN — логические точки, масштабируемые под плотность экрана (PixelRatio). px/rem/em из веба здесь нет.",
    en: {
      t: "Native · Styling",
      q: "{ padding: 16 } — 16 of what?",
      o: [
        "Physical device screen pixels, like on a canvas",
        "Density-independent points (dp/pt) — physical size stays similar across screens",
        "Percent of the parent wrapper container's width",
        "The rem unit, like on the web, relative to the root font size",
      ],
      e: "Numbers in RN styles are logical points, scaled for screen density (PixelRatio). There's no px/rem/em here as on the web.",
    },
  },
  {
    t: "Native · Styling",
    q: "Оба стиля задают borderColor — чей победит?\n<View style={[styles.card, styles.active]} />",
    o: [
      "Первого в массиве — стили card, active игнорируется",
      "Последнего в массиве — active перекрывает card",
      "Будет ошибка конфликтующих значений borderColor",
      "Значения смешаются в некое усреднённое между ними",
    ],
    a: 1,
    e: "Массив стилей мерджится слева направо — поздние перекрывают ранние. Поэтому паттерн [base, isActive && active] работает как ожидается.",
    en: {
      t: "Native · Styling",
      q: "Both styles set borderColor — which one wins?\n<View style={[styles.card, styles.active]} />",
      o: [
        "The first in the array — card's styles apply, active is ignored",
        "The last in the array — active overrides card",
        "There will be a conflicting-borderColor-values error",
        "The values blend into some average between the two",
      ],
      e: "The style array merges left to right — later entries override earlier ones. That's why the pattern [base, isActive && active] works as expected.",
    },
  },
  {
    t: "Native · Styling",
    q: "Чем StyleSheet.create лучше инлайн-объекта style={{...}}?",
    o: [
      "Поддерживает CSS-анимации и transition, которых нет в inline",
      "Объект создаётся один раз (стабильная ссылка для memo) + валидация свойств в dev",
      "Работает примерно в десять раз быстрее на каждом рендере",
      "Ничем не отличается — это просто два синтаксиса одного и того же",
    ],
    a: 1,
    e: "Инлайн-объект — новая ссылка каждый рендер (ломает memo-детей). StyleSheet создаётся один раз на модуль и валидирует опечатки в dev.",
    en: {
      t: "Native · Styling",
      q: "How is StyleSheet.create better than an inline style={{...}} object?",
      o: [
        "It supports CSS animations and transitions, which inline styles lack",
        "The object is created once (a stable reference for memo) + property validation in dev",
        "It runs roughly ten times faster on every render",
        "There's no difference — it's just two syntaxes for the same thing",
      ],
      e: "An inline object is a new reference every render (breaks memoized children). StyleSheet is created once per module and validates typos in dev.",
    },
  },
  {
    t: "Native · Styling",
    q: "Platform.select({ ios: 'A', android: 'B' }) на iOS вернёт...",
    o: [
      "'B' — вернётся значение android-ветки объекта",
      "'A' — вернётся значение по ключу текущей ОС iOS",
      "{ ios: 'A' } — весь объект целиком без выбора ветки",
      "undefined — Platform.select не находит совпадения",
    ],
    a: 1,
    e: "Platform.select возвращает значение по текущей ОС (есть ещё ключ default). Для больших развилок — файлы Component.ios.tsx / Component.android.tsx.",
    en: {
      t: "Native · Styling",
      q: "Platform.select({ ios: 'A', android: 'B' }) on iOS returns...",
      o: [
        "'B' — the android branch's value is returned",
        "'A' — the value under the key for the current OS, iOS",
        "{ ios: 'A' } — the entire object, with no branch selected",
        "undefined — Platform.select finds no match",
      ],
      e: "Platform.select returns the value for the current OS (there's also a default key). For larger branching, use Component.ios.tsx / Component.android.tsx files.",
    },
  },
  {
    t: "Native · Styling",
    q: "Зачем SafeAreaView / react-native-safe-area-context?",
    o: [
      "Защититься от XSS-атак во встроенном WebView-компоненте",
      "Не дать контенту залезть под вырез, чёлку, статусбар и индикатор Home",
      "Изолировать стили экрана от остальной части приложения",
      "Ускорить первый рендер экрана за счёт кэширования layout",
    ],
    a: 1,
    e: "Safe area — зона экрана без системных элементов. Библиотека safe-area-context гибче встроенного SafeAreaView (хуки useSafeAreaInsets, работает на Android).",
    en: {
      t: "Native · Styling",
      q: "Why use SafeAreaView / react-native-safe-area-context?",
      o: [
        "To protect against XSS attacks in an embedded WebView component",
        "To keep content from being covered by the notch, camera cutout, status bar, and Home indicator",
        "To isolate a screen's styles from the rest of the app",
        "To speed up a screen's first render via layout caching",
      ],
      e: "The safe area is the part of the screen without system elements. The safe-area-context library is more flexible than the built-in SafeAreaView (useSafeAreaInsets hook, works on Android).",
    },
  },
  {
    t: "Native · Компоненты",
    q: "Pressable vs TouchableOpacity — что выбрать сегодня?",
    o: [
      "TouchableOpacity — более новый компонент, пришедший ему на замену",
      "Pressable — современный API: состояния pressed/hovered, hitSlop, гибкая кастомизация",
      "Button — единственный правильный выбор для любых нажатий",
      "Разницы никакой нет, оба компонента абсолютно идентичны",
    ],
    a: 1,
    e: "Pressable — рекомендуемая замена семейства Touchable*: функция-children с состоянием ({ pressed }) => ..., больше контроля над жестами.",
    en: {
      t: "Native · Components",
      q: "Pressable vs TouchableOpacity — which should you pick today?",
      o: [
        "TouchableOpacity — the newer component that replaced it",
        "Pressable — the modern API: pressed/hovered states, hitSlop, flexible customization",
        "Button — the only correct choice for any tap interaction",
        "There's no difference at all — the two components are identical",
      ],
      e: "Pressable is the recommended replacement for the Touchable* family: a function-as-children with state ({ pressed }) => ..., and more control over gestures.",
    },
  },
  {
    t: "Native · Компоненты",
    q: "Сетевой Image без width/height — что произойдёт?",
    o: [
      "Возьмёт натуральный размер картинки, как в браузере",
      "Отрендерится с нулевым размером (невидим) — размеры обязательны",
      "Растянется на весь доступный размер родителя",
      "Вызовет ошибку компиляции ещё до запуска приложения",
    ],
    a: 1,
    e: "Для сетевых изображений RN не знает размер заранее — без явных width/height элемент схлопывается в 0×0. Локальные (require) знают свой размер.",
    en: {
      t: "Native · Components",
      q: "A network Image with no width/height — what happens?",
      o: [
        "It takes the image's natural size, as in a browser",
        "It renders with zero size (invisible) — dimensions are required",
        "It stretches to fill all available space in its parent",
        "It causes a compile error before the app even runs",
      ],
      e: "For network images, RN doesn't know the size ahead of time — without explicit width/height the element collapses to 0×0. Local images (via require) know their own size.",
    },
  },
  {
    t: "Native · Компоненты",
    q: "KeyboardAvoidingView: какой behavior обычно на iOS и Android?",
    o: [
      "Одинаковый режим 'auto' работает на обеих платформах",
      "'padding' на iOS, 'height' на Android",
      "'height' на iOS, 'padding' на Android — наоборот",
      "behavior необязателен, платформы сами решают сдвиг",
    ],
    a: 1,
    e: "Платформы по-разному двигают layout при появлении клавиатуры — типовой код: behavior={Platform.OS === 'ios' ? 'padding' : 'height'}.",
    en: {
      t: "Native · Components",
      q: "KeyboardAvoidingView: what's the typical behavior on iOS vs Android?",
      o: [
        "The same 'auto' mode works on both platforms",
        "'padding' on iOS, 'height' on Android",
        "'height' on iOS, 'padding' on Android — the other way around",
        "behavior is optional; platforms handle the shift themselves",
      ],
      e: "Platforms shift layout differently when the keyboard appears — a typical pattern is: behavior={Platform.OS === 'ios' ? 'padding' : 'height'}.",
    },
  },
  {
    t: "Native · Списки",
    q: "Зачем FlatList нужен keyExtractor?",
    o: [
      "Нужен для сортировки элементов данных перед рендером",
      "Стабильная идентичность строк между рендерами (реиспользование, state, анимации)",
      "Даёт прямой доступ к элементу списка по строковому ключу",
      "Обязателен только для SectionList, для FlatList опционален",
    ],
    a: 1,
    e: "Тот же смысл, что key в React-списках: сопоставление строк при изменениях данных. Стабильный id из данных, НЕ index.",
    en: {
      t: "Native · Lists",
      q: "Why does FlatList need keyExtractor?",
      o: [
        "It's needed to sort the data items before rendering",
        "Stable row identity across renders (reuse, state, animations)",
        "It provides direct access to a list item by string key",
        "It's only required for SectionList; optional for FlatList",
      ],
      e: "Same idea as key in React lists: matching rows across data changes. Use a stable id from the data, NOT the index.",
    },
  },
  {
    t: "Native · Списки",
    q: "Что даёт getItemLayout?",
    o: [
      "Автоматически вычисляет высоту строк любой сложности",
      "Скип асинхронных замеров при фиксированной высоте + мгновенный scrollToIndex",
      "Добавляет красивую анимацию появления новых элементов",
      "Включает горизонтальный скролл вместо вертикального",
    ],
    a: 1,
    e: "Если высота строки известна, FlatList не измеряет их лениво: меньше blank cells, работает scrollToIndex без ошибок.",
    en: {
      t: "Native · Lists",
      q: "What does getItemLayout give you?",
      o: [
        "Automatically computes the height of rows of any complexity",
        "Skips async measurement for fixed-height rows + instant scrollToIndex",
        "Adds a nice appearance animation for new items",
        "Enables horizontal scrolling instead of vertical",
      ],
      e: "If a row's height is known up front, FlatList doesn't lazily measure it: fewer blank cells, and scrollToIndex works without errors.",
    },
  },
  {
    t: "Native · Списки",
    q: "Как сделать бесконечную ленту (пагинацию) в FlatList?",
    o: [
      "Ручной setInterval, который периодически дёргает fetch",
      "onEndReached + onEndReachedThreshold + дозагрузка страницы",
      "Обычный ScrollView с самописным обработчиком onScroll",
      "FlatList сам догружает следующие страницы без настройки",
    ],
    a: 1,
    e: "onEndReached срабатывает при приближении к концу (threshold в долях видимой высоты). В колбэке грузим следующую страницу и конкатенируем data.",
    en: {
      t: "Native · Lists",
      q: "How do you build an infinite feed (pagination) in FlatList?",
      o: [
        "A manual setInterval that periodically triggers a fetch",
        "onEndReached + onEndReachedThreshold + loading the next page",
        "A plain ScrollView with a hand-rolled onScroll handler",
        "FlatList loads the next pages automatically with no setup",
      ],
      e: "onEndReached fires as you approach the end (threshold as a fraction of visible height). In the callback you load the next page and concatenate it into data.",
    },
  },
  {
    t: "Native · Списки",
    q: "При быстром скролле FlatList мелькают пустые места. Причина?",
    o: [
      "Слишком медленное интернет-соединение у пользователя",
      "Рендер окна не успевает за скроллом (границы виртуализации)",
      "Известный неисправимый баг самого React Native",
      "Слишком короткий или неуникальный keyExtractor у строк",
    ],
    a: 1,
    e: "Blank cells — скролл обогнал рендер. Фиксы: getItemLayout, увеличить windowSize/maxToRenderPerBatch, упростить и мемоизировать строки, FlashList.",
    en: {
      t: "Native · Lists",
      q: "Blank spaces flash in FlatList during fast scrolling. Why?",
      o: [
        "The user's internet connection is too slow",
        "Rendering the window can't keep up with scrolling (virtualization boundaries)",
        "A known, unfixable bug in React Native itself",
        "The row keyExtractor is too short or not unique",
      ],
      e: "Blank cells mean scrolling outran rendering. Fixes: getItemLayout, increase windowSize/maxToRenderPerBatch, simplify and memoize rows, or use FlashList.",
    },
  },
  {
    t: "Native · Списки",
    q: "Чем FlashList быстрее FlatList?",
    o: [
      "Написан на Rust и компилируется в нативный бинарник",
      "Recycling: переиспользует вью-контейнеры строк вместо создания новых",
      "Пропускает рендер каждой второй строки для экономии",
      "Загружает данные с сервера самостоятельно, без fetch",
    ],
    a: 1,
    e: "FlashList (Shopify) перерабатывает ушедшие с экрана вью под новые данные (как RecyclerView в Android). Требует estimatedItemSize.",
    en: {
      t: "Native · Lists",
      q: "How is FlashList faster than FlatList?",
      o: [
        "It's written in Rust and compiles to a native binary",
        "Recycling: it reuses row view containers instead of creating new ones",
        "It skips rendering every other row to save time",
        "It fetches data from the server on its own, without fetch",
      ],
      e: "FlashList (Shopify) recycles views that leave the screen for new data (like Android's RecyclerView). It requires estimatedItemSize.",
    },
  },
  {
    t: "Native · Списки",
    q: "Как устроен UI чата (новые сообщения снизу)?",
    o: [
      "ScrollView со scrollToEnd, вызванным внутри useEffect",
      "FlatList с inverted: список перевёрнут, данные в обратном порядке",
      "position: absolute, расставленный вручную для каждого сообщения",
      "SectionList с отдельной секцией «сегодня» наверху списка",
    ],
    a: 1,
    e: "inverted переворачивает FlatList (и каждую строку) — «низ» становится началом списка: новые сообщения просто unshift в data, скролл ведёт себя как в мессенджерах.",
    en: {
      t: "Native · Lists",
      q: "How is a chat UI built (new messages at the bottom)?",
      o: [
        "A ScrollView with scrollToEnd called inside useEffect",
        "A FlatList with inverted: the list is flipped, data is in reverse order",
        "position: absolute, manually placed for each message",
        "A SectionList with a separate 'today' section at the top of the list",
      ],
      e: "inverted flips the FlatList (and each row) — the 'bottom' becomes the start of the list: new messages are simply unshifted into data, and scrolling behaves like in messaging apps.",
    },
  },
  {
    t: "Native · Анимации",
    q: "Animated без useNativeDriver: почему анимация дёргается при загрузке JS?",
    o: [
      "Анимация просто неправильно написана в коде компонента",
      "Каждый кадр считается на JS-потоке — занят JS, пропущен кадр",
      "Устройству не хватает оперативной памяти для анимации",
      "Забыт проп key у анимируемого компонента",
    ],
    a: 1,
    e: "Без нативного драйвера значения анимации гонятся из JS каждый кадр. useNativeDriver: true уносит анимацию на UI-поток — JS может тормозить, анимация плавная.",
    en: {
      t: "Native · Animations",
      q: "Animated without useNativeDriver: why does the animation stutter while JS is busy loading?",
      o: [
        "The animation is simply written incorrectly in the component code",
        "Every frame is computed on the JS thread — JS is busy, a frame is dropped",
        "The device doesn't have enough RAM for the animation",
        "The animated component is missing a key prop",
      ],
      e: "Without the native driver, animation values are driven from JS every frame. useNativeDriver: true moves the animation to the UI thread — JS can lag, and the animation stays smooth.",
    },
  },
  {
    t: "Native · Анимации",
    q: "Ограничение useNativeDriver: true?",
    o: [
      "useNativeDriver работает исключительно на платформе iOS",
      "Только transform и opacity — layout-свойства (width, height, top) нельзя",
      "Одновременно можно анимировать не больше трёх значений",
      "Несовместим с методом Animated.spring и его конфигами",
    ],
    a: 1,
    e: "Нативный драйвер не умеет анимировать layout (его считает Yoga). Для анимаций layout-свойств на UI-потоке — Reanimated.",
    en: {
      t: "Native · Animations",
      q: "What is the limitation of useNativeDriver: true?",
      o: [
        "useNativeDriver only works on the iOS platform",
        "Only transform and opacity — layout properties (width, height, top) are not allowed",
        "No more than three values can be animated at the same time",
        "It's incompatible with the Animated.spring method and its configs",
      ],
      e: "The native driver can't animate layout (that's computed by Yoga). For animating layout properties on the UI thread, use Reanimated.",
    },
  },
  {
    t: "Native · Анимации",
    q: "Что такое worklets в Reanimated?",
    o: [
      "Аналог браузерных Web Workers, перенесённый в среду React Native",
      "Функции JS, выполняющиеся прямо на UI-потоке — анимации и жесты без участия JS-потока",
      "Плагины Babel, которые оптимизируют финальный размер бандла",
      "Нативные модули, написанные на Kotlin вместо JavaScript",
    ],
    a: 1,
    e: "Reanimated компилирует помеченные функции ('worklet') для исполнения на UI-потоке — анимации и обработка жестов не зависят от загрузки JS-потока вообще.",
    en: {
      t: "Native · Animations",
      q: "What are worklets in Reanimated?",
      o: [
        "The equivalent of browser Web Workers, ported to React Native",
        "JS functions that run directly on the UI thread — animations and gestures without involving the JS thread",
        "Babel plugins that optimize the final bundle size",
        "Native modules written in Kotlin instead of JavaScript",
      ],
      e: "Reanimated compiles functions marked 'worklet' to run on the UI thread — animations and gesture handling don't depend on the JS thread being free at all.",
    },
  },
  {
    t: "Native · Навигация",
    q: "navigate('Post') vs push('Post') — разница?",
    o: [
      "Ничем не отличаются, это просто два синонима одного метода",
      "navigate вернётся к существующему экрану в стеке, push всегда добавляет новый",
      "push работает только внутри табов, а не в стековой навигации",
      "navigate всегда удаляет текущий экран перед переходом",
    ],
    a: 1,
    e: "navigate ищет экран с таким именем в стеке и возвращается к нему; push кладёт новый экземпляр всегда (Post → Post → Post для ленты постов).",
    en: {
      t: "Native · Navigation",
      q: "navigate('Post') vs push('Post') — what's the difference?",
      o: [
        "No difference — they're just two synonyms for the same method",
        "navigate returns to an existing screen in the stack, push always adds a new one",
        "push only works inside tabs, not in stack navigation",
        "navigate always removes the current screen before transitioning",
      ],
      e: "navigate looks for a screen with that name in the stack and returns to it; push always pushes a new instance (Post → Post → Post for a feed of posts).",
    },
  },
  {
    t: "Native · Навигация",
    q: "navigation.navigate('Post', { post: bigObject }) — что не так?",
    o: [
      "Всё в порядке, объекты любой сложности передаются свободно",
      "Params должны быть сериализуемыми: warning, ломается deep linking и восстановление state",
      "Просто будет работать слишком медленно на больших объектах",
      "Объекты можно передавать только через React Context провайдер",
    ],
    a: 1,
    e: "Передавать id, а данные брать из стора/кэша запросов. Несериализуемые params (объекты с методами, колбэки) ломают persistence и deep links.",
    en: {
      t: "Native · Navigation",
      q: "navigation.navigate('Post', { post: bigObject }) — what's wrong with this?",
      o: [
        "Nothing — objects of any complexity can be passed freely",
        "Params must be serializable: warning, breaks deep linking and state restoration",
        "It will simply run too slowly with large objects",
        "Objects can only be passed via a React Context provider",
      ],
      e: "Pass an id and pull the data from the store/query cache. Non-serializable params (objects with methods, callbacks) break persistence and deep links.",
    },
  },
  {
    t: "Native · Навигация",
    q: "Что такое deep linking?",
    o: [
      "Вложенные навигаторы внутри друг друга в дереве экранов",
      "Открытие конкретного экрана по URL (myapp://post/42, universal links)",
      "Переход между экранами без анимации перехода",
      "Обычные ссылки, открывающиеся внутри встроенного WebView",
    ],
    a: 1,
    e: "URL-схемы и universal/app links маппятся на экраны через конфиг linking в NavigationContainer — пуш-уведомления и ссылки ведут сразу на нужный экран.",
    en: {
      t: "Native · Navigation",
      q: "What is deep linking?",
      o: [
        "Nested navigators placed inside one another in the screen tree",
        "Opening a specific screen via a URL (myapp://post/42, universal links)",
        "Transitioning between screens without a transition animation",
        "Regular links that open inside an embedded WebView",
      ],
      e: "URL schemes and universal/app links map to screens via the linking config in NavigationContainer — push notifications and links take you straight to the right screen.",
    },
  },
  {
    t: "Native · Навигация",
    q: "Как обработать аппаратную кнопку «назад» на Android?",
    o: [
      "Аппаратная кнопка «назад» в принципе не перехватывается",
      "BackHandler.addEventListener('hardwareBackPress', handler)",
      "Событие window.onpopstate, как в браузере",
      "Встроенный метод navigation.onBack() из React Navigation",
    ],
    a: 1,
    e: "BackHandler — API для аппаратной кнопки: вернуть true из обработчика = событие поглощено (например, закрыть модалку вместо выхода с экрана).",
    en: {
      t: "Native · Navigation",
      q: "How do you handle the hardware back button on Android?",
      o: [
        "The hardware back button can't be intercepted at all",
        "BackHandler.addEventListener('hardwareBackPress', handler)",
        "The window.onpopstate event, like in a browser",
        "The built-in navigation.onBack() method from React Navigation",
      ],
      e: "BackHandler is the API for the hardware button: returning true from the handler means the event was consumed (e.g. close a modal instead of leaving the screen).",
    },
  },
  {
    t: "Native · Навигация",
    q: "Чем native-stack лучше обычного stack?",
    o: [
      "Даёт больше опций кастомной анимации, написанной прямо на JS",
      "Использует настоящие UINavigationController/Fragment — нативные жесты и переходы, быстрее",
      "Не требует оборачивания приложения в NavigationContainer",
      "Ничем не лучше, native-stack давно и полностью депрекейтнут",
    ],
    a: 1,
    e: "createNativeStackNavigator делегирует переходы нативной платформе (жест свайпа, шапки). JS-stack гибче кастомизируется, но тяжелее.",
    en: {
      t: "Native · Navigation",
      q: "How is native-stack better than the regular stack?",
      o: [
        "It offers more custom animation options written entirely in JS",
        "It uses real UINavigationController/Fragment — native gestures and transitions, faster",
        "It doesn't require wrapping the app in NavigationContainer",
        "It isn't better in any way — native-stack has long been fully deprecated",
      ],
      e: "createNativeStackNavigator delegates transitions to the native platform (swipe gesture, headers). The JS stack is more customizable, but heavier.",
    },
  },
  {
    t: "Native · Инфраструктура",
    q: "Что такое Metro?",
    o: [
      "Библиотека для навигации между экранами приложения",
      "JS-бандлер React Native (аналог Vite/webpack) с Fast Refresh",
      "Каталог готовых нативных модулей для установки",
      "Эмулятор Android, встроенный в инструменты разработчика",
    ],
    a: 1,
    e: "Metro собирает JS-бандл для RN, отдаёт его в dev-режиме и делает Fast Refresh. Резолвит платформенные расширения .ios.js/.android.js.",
    en: {
      t: "Native · Infrastructure",
      q: "What is Metro?",
      o: [
        "A library for navigating between screens in an app",
        "React Native's JS bundler (a counterpart to Vite/webpack) with Fast Refresh",
        "A catalog of ready-made native modules to install",
        "An Android emulator built into the developer tools",
      ],
      e: "Metro builds the JS bundle for RN, serves it in dev mode, and provides Fast Refresh. It resolves platform-specific extensions like .ios.js/.android.js.",
    },
  },
  {
    t: "Native · Инфраструктура",
    q: "Что можно доставить через OTA (CodePush / EAS Update)?",
    o: [
      "Абсолютно всё, включая новые нативные модули и код",
      "Только JS-бандл и ассеты; изменения нативного кода — через сторы",
      "Только статичные картинки без обновления логики",
      "Только текстовые конфиги без изменения экранов",
    ],
    a: 1,
    e: "OTA подменяет JS-бандл. Добавил нативную зависимость / поменял iOS/Android-код — полноценный релиз в App Store/Google Play.",
    en: {
      t: "Native · Infrastructure",
      q: "What can be delivered via OTA (CodePush / EAS Update)?",
      o: [
        "Absolutely everything, including new native modules and code",
        "Only the JS bundle and assets; native code changes go through the app stores",
        "Only static images, without updating any logic",
        "Only text configs, without changing any screens",
      ],
      e: "OTA swaps out the JS bundle. Add a native dependency or change iOS/Android code, and you need a full release through the App Store/Google Play.",
    },
  },
  {
    t: "Native · Мониторинг",
    q: "Краш-репорты из прода нечитаемы (минифицированный стек). Что забыли?",
    o: [
      "Включить dev-режим прямо в продакшен-сборке",
      "Загрузить source maps в Sentry/Crashlytics при релизе (шаг CI)",
      "Полностью отключить движок Hermes в релизной сборке",
      "Добавить побольше вызовов console.log перед релизом",
    ],
    a: 1,
    e: "Без source maps стеки Hermes-байткода бесполезны. Загрузка карт при каждом релизе — обязательный шаг CI, иначе мониторинг слепой.",
    en: {
      t: "Native · Monitoring",
      q: "Production crash reports are unreadable (minified stack traces). What was forgotten?",
      o: [
        "Enabling dev mode directly in the production build",
        "Uploading source maps to Sentry/Crashlytics on release (a CI step)",
        "Completely disabling the Hermes engine in the release build",
        "Adding more console.log calls before releasing",
      ],
      e: "Without source maps, Hermes bytecode stack traces are useless. Uploading maps on every release is a required CI step, otherwise monitoring is blind.",
    },
  },
  {
    t: "Native · Мониторинг",
    q: "JS FPS = 60, UI FPS = 20. Где искать проблему?",
    o: [
      "В JS-коде: избыточные рендеры и тяжёлые вычисления",
      "На нативной стороне: тяжёлые вью, оверлеи, тени, большие изображения",
      "Проблема сетевого соединения между клиентом и сервером",
      "Такие метрики в принципе не могут расходиться",
    ],
    a: 1,
    e: "Два потока — два FPS. Просел UI-поток → проблема в нативном рендере (глубокие иерархии вью, дорогие тени/блюры, декодинг картинок), JS тут ни при чём.",
    en: {
      t: "Native · Monitoring",
      q: "JS FPS = 60, UI FPS = 20. Where should you look for the problem?",
      o: [
        "In the JS code: excessive re-renders and heavy computations",
        "On the native side: heavy views, overlays, shadows, large images",
        "A network connectivity problem between client and server",
        "These metrics can't diverge from each other in principle",
      ],
      e: "Two threads, two FPS numbers. A dropping UI thread means the problem is in native rendering (deep view hierarchies, expensive shadows/blurs, image decoding) — JS has nothing to do with it here.",
    },
  },
  {
    t: "Native · Мониторинг",
    q: "Что такое ANR?",
    o: [
      "Внутренний служебный формат описания нативных модулей приложения",
      "Application Not Responding: main-поток Android заблокирован ~5 секунд — системный диалог",
      "Ошибка сборки Gradle, возникающая на этапе линковки модулей",
      "Один из служебных типов пуш-уведомлений в системе Android",
    ],
    a: 1,
    e: "ANR — Android-аналог «приложение зависло»: блокировка main-потока. Считается в vitals Google Play и влияет на видимость приложения в сторе.",
    en: {
      t: "Native · Monitoring",
      q: "What is ANR?",
      o: [
        "An internal service format for describing an app's native modules",
        "Application Not Responding: Android's main thread is blocked for ~5 seconds — a system dialog appears",
        "A Gradle build error that occurs during module linking",
        "One of the service push notification types on Android",
      ],
      e: "ANR is Android's version of 'the app froze': the main thread is blocked. It's tracked in Google Play vitals and affects the app's visibility in the store.",
    },
  },
  {
    t: "Native · Перформанс",
    q: "Тяжёлую работу нужно запустить после перехода на экран. Как не убить анимацию?",
    o: [
      "Просто вызвать тяжёлую работу напрямую внутри useEffect",
      "InteractionManager.runAfterInteractions(() => работа) — после завершения анимаций",
      "Отложить работу через setTimeout с интервалом 5000 мс",
      "Запустить тяжёлые вычисления прямо в теле функции render",
    ],
    a: 1,
    e: "useEffect срабатывает до конца анимации перехода — работа уронит её FPS. runAfterInteractions ждёт завершения взаимодействий/анимаций.",
    en: {
      t: "Native · Performance",
      q: "Heavy work needs to run right after navigating to a screen. How do you avoid killing the transition animation?",
      o: [
        "Just call the heavy work directly inside useEffect",
        "InteractionManager.runAfterInteractions(() => work) — after animations finish",
        "Defer the work with setTimeout using a 5000ms interval",
        "Run the heavy computation directly in the render function body",
      ],
      e: "useEffect fires before the transition animation finishes — the work will tank its FPS. runAfterInteractions waits for interactions/animations to complete.",
    },
  },
  {
    t: "Native · Перформанс",
    q: "TTI — это...",
    o: [
      "Time To Install — время установки приложения из стора",
      "Time To Interactive: время от запуска до готовности приложения к взаимодействию",
      "Total Thread Idle — суммарное время простоя потоков",
      "Служебная метрика итогового размера JS-бандла приложения",
    ],
    a: 1,
    e: "Ключевая стартовая метрика RN-приложения. Улучшается: Hermes (байткод), ленивая загрузка экранов, меньше работы до первого экрана, inline requires.",
    en: {
      t: "Native · Performance",
      q: "TTI stands for...",
      o: [
        "Time To Install — the time it takes to install the app from the store",
        "Time To Interactive: the time from launch until the app is ready for interaction",
        "Total Thread Idle — the total idle time across threads",
        "An internal metric for the final size of the app's JS bundle",
      ],
      e: "A key startup metric for RN apps. Improved by: Hermes (bytecode), lazy-loading screens, doing less work before the first screen, inline requires.",
    },
  },
  {
    t: "Native · Отличия от веба",
    q: "Чего НЕТ в React Native из веба?",
    o: [
      "Хуков useState и useEffect — они работают точно так же",
      "DOM, CSS-каскада, localStorage (вместо него AsyncStorage/MMKV)",
      "fetch и Promise — сетевые API доступны без изменений",
      "JSX-синтаксиса — компоненты пишутся так же, как в вебе",
    ],
    a: 1,
    e: "React тот же (хуки, рендер), но: нет DOM (нативные вью), нет каскада CSS, нет window/document, хранение — AsyncStorage/MMKV, навигация — не URL-роутер.",
    en: {
      t: "Native · Differences from the web",
      q: "What is NOT present in React Native from the web?",
      o: [
        "The useState and useEffect hooks — they work exactly the same",
        "The DOM, CSS cascade, localStorage (replaced by AsyncStorage/MMKV)",
        "fetch and Promise — networking APIs are available unchanged",
        "JSX syntax — components are written the same way as on the web",
      ],
      e: "React itself is the same (hooks, rendering), but: there's no DOM (native views instead), no CSS cascade, no window/document, storage is AsyncStorage/MMKV, and navigation isn't a URL router.",
    },
  },
  {
    t: "Native · Формы",
    q: "Почему controlled TextInput на Android может терять символы при быстром вводе?",
    o: [
      "Известный баг именно клавиатуры на устройствах Samsung",
      "Асинхронный мост: value из state прилетает с задержкой и перетирает ввод",
      "Инпуту просто не хватает включённого autoFocus",
      "Не указан подходящий проп keyboardType для инпута",
    ],
    a: 1,
    e: "Круг «ввод → JS → setState → назад в натив» асинхронный: при быстром вводе старое value перезаписывает новые символы. Фиксы: uncontrolled + react-hook-form (Controller), defaultValue + onChangeText.",
    en: {
      t: "Native · Forms",
      q: "Why can a controlled TextInput on Android lose characters during fast typing?",
      o: [
        "A known bug specific to keyboards on Samsung devices",
        "Asynchronous bridge: the value from state arrives late and overwrites the input",
        "The input simply lacks autoFocus enabled",
        "The keyboardType prop for the input isn't set correctly",
      ],
      e: "The 'input → JS → setState → back to native' loop is asynchronous: during fast typing, a stale value overwrites new characters. Fixes: uncontrolled + react-hook-form (Controller), or defaultValue + onChangeText.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Что генерирует codegen в новой архитектуре RN?",
    o: [
      "JS-байткод Hermes из исходников TypeScript при каждой сборке",
      "Типизированные C++/ObjC/Kotlin-биндинги из TS-спеки модуля или компонента",
      "JSON-схемы для сериализации сообщений старого моста между потоками",
      "Автоматические тесты для нативных модулей на основе их публичного API",
    ],
    a: 1,
    e: "Спека на TypeScript — источник правды: codegen превращает её в нативные интерфейсы для TurboModules И Fabric-компонентов. Несовпадение типов ловится на этапе сборки, а не в рантайме.",
    en: {
      t: "Native · Architecture",
      q: "What does codegen generate in RN's new architecture?",
      o: [
        "Hermes JS bytecode from TypeScript sources on every build",
        "Typed C++/ObjC/Kotlin bindings from a module's or component's TS spec",
        "JSON schemas for serializing messages over the old cross-thread bridge",
        "Automated tests for native modules based on their public API",
      ],
      e: "A TypeScript spec is the source of truth: codegen turns it into native interfaces for both TurboModules AND Fabric components. Type mismatches are caught at build time, not at runtime.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Что такое HostObject в JSI?",
    o: [
      "JSON-обёртка над нативным модулем для передачи через мост",
      "C++-объект, просунутый в JS: обращение к его свойствам синхронно выполняет C++-код",
      "Объект-синглтон, в котором рантайм хранит конфигурацию и настройки хост-приложения",
      "Прокси-объект для асинхронного вызова методов, выполняющихся в другом JS-потоке",
    ],
    a: 1,
    e: "HostObject — сердце JSI: JS держит прямую ссылку на C++-объект без сериализации. На этом построены MMKV (синхронное хранилище), Reanimated, VisionCamera.",
    en: {
      t: "Native · Architecture",
      q: "What is a HostObject in JSI?",
      o: [
        "A JSON wrapper around a native module for passing over the bridge",
        "A C++ object exposed to JS: accessing its properties synchronously runs C++ code",
        "A singleton object where the runtime stores the host app's configuration and settings",
        "A proxy object for asynchronously invoking methods that run on another JS thread",
      ],
      e: "HostObject is the heart of JSI: JS holds a direct reference to a C++ object with no serialization. MMKV (synchronous storage), Reanimated, and VisionCamera are all built on this.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Почему AsyncStorage асинхронный, а MMKV может быть синхронным?",
    o: [
      "AsyncStorage всегда пишет данные на диск, а MMKV держит всё исключительно в оперативной памяти",
      "AsyncStorage ограничен природой bridge (только очередь), MMKV работает через JSI напрямую",
      "MMKV синхронно блокирует UI-поток при каждом чтении, поэтому его использовать не рекомендуется",
      "Разница только во внешнем API — внутри оба хранилища устроены совершенно одинаково",
    ],
    a: 1,
    e: "Асинхронность AsyncStorage — не дизайн-решение, а ограничение моста. JSI дал прямые синхронные вызовы C++ — и появились синхронные API там, где это удобнее.",
    en: {
      t: "Native · Architecture",
      q: "Why is AsyncStorage asynchronous while MMKV can be synchronous?",
      o: [
        "AsyncStorage always writes data to disk, while MMKV keeps everything purely in RAM",
        "AsyncStorage is limited by the nature of the bridge (queue only), MMKV works directly through JSI",
        "MMKV synchronously blocks the UI thread on every read, so it's not recommended",
        "The difference is only in the external API — internally both stores work exactly the same way",
      ],
      e: "AsyncStorage's asynchrony isn't a design choice — it's a limitation of the bridge. JSI enabled direct synchronous calls into C++, which is why synchronous APIs appeared where they're more convenient.",
    },
  },
  {
    t: "Native · Архитектура",
    q: "Назови три фазы рендера Fabric.",
    o: [
      "parse → compile → execute — те же стадии, что проходит код в браузерном JS-движке",
      "render (JS строит дерево) → commit (Yoga считает layout) → mount (diff и операции с вью)",
      "diff → patch → repaint — так же, как работает virtual DOM в браузерном React",
      "measure → layout → draw — тот же конвейер, что в нативной Android View system",
    ],
    a: 1,
    e: "Shadow tree на C++ делится между потоками без копий (раньше дерево существовало в трёх экземплярах). Плюс синхронный measure и приоритеты обновлений для concurrent rendering.",
    en: {
      t: "Native · Architecture",
      q: "Name Fabric's three render phases.",
      o: [
        "parse → compile → execute — the same stages code goes through in a browser's JS engine",
        "render (JS builds the tree) → commit (Yoga computes layout) → mount (diffing and view operations)",
        "diff → patch → repaint — the same as how virtual DOM works in browser React",
        "measure → layout → draw — the same pipeline as the native Android View system",
      ],
      e: "The shadow tree is in C++ and is shared between threads without copying (previously the tree existed in three separate instances). Plus synchronous measure and update priorities for concurrent rendering.",
    },
  },
];
