// Вопросы квиза: секция React
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

export const REACT_QUESTIONS = [
  {
    t: "React · Render",
    q: "Что из этого НЕ вызывает ре-рендер компонента?",
    o: [
      "Собственный setState с новым значением",
      "Ре-рендер родительского компонента",
      "Изменение значения читаемого React-контекста",
      "Изменение props «само по себе»",
    ],
    a: 3,
    e: "Props не меняются «сами» — их передаёт родитель при СВОЁМ ре-рендере. Триггеры: state, родитель, context.",
    en: {
      t: "React · Rendering",
      q: "Which of these does NOT trigger a component re-render?",
      o: [
        "Its own setState call with a new value",
        "A re-render of the parent component",
        "A change in the value of a React context it reads",
        "Props changing \"on their own\"",
      ],
      e: "Props never change \"on their own\" — the parent passes new props during ITS OWN re-render. The real triggers are: state, parent re-render, and context.",
    },
  },
  {
    t: "React · Render",
    q: "Две фазы обновления React — это...",
    o: [
      "Фазы mount при монтировании и update при обновлении",
      "render (чистая, прерываемая) и commit (синхронная, пишет в DOM)",
      "Фазы diff и patch при сравнении двух деревьев",
      "Фазы layout и paint, которые выполняет браузер",
    ],
    a: 1,
    e: "Render строит новое дерево в памяти и может быть отброшен; commit синхронно применяет изменения, затем layout-эффекты, затем passive.",
    en: {
      t: "React · Rendering",
      q: "React's two update phases are...",
      o: [
        "The mount phase during mounting and the update phase during updates",
        "render (pure, interruptible) and commit (synchronous, writes to the DOM)",
        "The diff and patch phases when comparing two trees",
        "The layout and paint phases performed by the browser",
      ],
      e: "Render builds a new tree in memory and can be discarded; commit synchronously applies the changes, then runs layout effects, then passive effects.",
    },
  },
  {
    t: "React · Render",
    q: "Три setState подряд в одном обработчике (React 18) — сколько ре-рендеров?",
    o: [
      "3 — рендер после каждого вызова setState",
      "1 — все три объединяются в один рендер (batching)",
      "0 — React проигнорирует все три вызова",
      "2 — batching объединяет только часть вызовов",
    ],
    a: 1,
    e: "React 18 батчит обновления везде (включая setTimeout и промисы). До 18-го — только в обработчиках событий React.",
    en: {
      t: "React · Rendering",
      q: "Three consecutive setState calls in one event handler (React 18) — how many re-renders?",
      o: [
        "3 — a render after each setState call",
        "1 — all three are merged into a single render (batching)",
        "0 — React ignores all three calls",
        "2 — batching only merges some of the calls",
      ],
      e: "React 18 batches updates everywhere (including inside setTimeout and promises). Before React 18, batching only happened inside React event handlers.",
    },
  },
  {
    t: "React · Render",
    q: "setCount(5), когда count уже 5 — что произойдёт?",
    o: [
      "Ре-рендер произойдёт как обычно, компонент отрисуется заново",
      "React выбросит ошибку из-за повторного одинакового значения",
      "Bail-out: сравнение по Object.is, ре-рендера нет",
      "Рендер выполнится, но commit-фаза будет пропущена",
    ],
    a: 2,
    e: "React сравнивает новое значение со старым через Object.is и при равенстве выходит досрочно. Поэтому setUser({...user}) рендерит ВСЕГДА — новая ссылка.",
    en: {
      t: "React · Rendering",
      q: "Calling setCount(5) when count is already 5 — what happens?",
      o: [
        "A re-render happens as usual and the component renders again",
        "React throws an error because the value did not change",
        "Bail-out: React compares with Object.is, no re-render happens",
        "The render phase runs but the commit phase is skipped",
      ],
      e: "React compares the new value to the old one with Object.is and bails out early on equality. That's why setUser({...user}) ALWAYS renders — it's a new reference.",
    },
  },
  {
    t: "React · Lifecycle",
    q: "Порядок при монтировании классового компонента?",
    o: [
      "render → constructor → затем componentDidMount",
      "constructor → getDerivedStateFromProps → render → componentDidMount",
      "constructor → componentDidMount → затем render",
      "getDerivedStateFromProps → constructor → затем render",
    ],
    a: 1,
    e: "constructor → static getDerivedStateFromProps → render → (React пишет в DOM) → componentDidMount.",
    en: {
      t: "React · Lifecycle",
      q: "What is the order of calls when a class component mounts?",
      o: [
        "render → constructor → then componentDidMount",
        "constructor → getDerivedStateFromProps → render → componentDidMount",
        "constructor → componentDidMount → then render",
        "getDerivedStateFromProps → constructor → then render",
      ],
      e: "constructor → static getDerivedStateFromProps → render → (React writes to the DOM) → componentDidMount.",
    },
  },
  {
    t: "React · Lifecycle",
    q: "Чем useEffect(fn, []) отличается от componentDidMount?",
    o: [
      "Ничем не отличается вообще, это полные и точные синонимы друг друга",
      "useEffect асинхронный (после отрисовки), в dev StrictMode двойной, замыкает первый рендер",
      "useEffect срабатывает значительно раньше, ещё до самой фазы render",
      "componentDidMount всегда асинхронный, а useEffect выполняется синхронно",
    ],
    a: 1,
    e: "didMount — синхронно до paint; useEffect — после paint, в StrictMode dev вызывается дважды, и захватывает props/state первого рендера (stale closure). По таймингу ближе useLayoutEffect.",
    en: {
      t: "React · Lifecycle",
      q: "How does useEffect(fn, []) differ from componentDidMount?",
      o: [
        "It doesn't differ at all — they are exact synonyms",
        "useEffect is asynchronous (runs after paint), fires twice in dev StrictMode, and closes over the first render's values",
        "useEffect fires much earlier, even before the render phase itself",
        "componentDidMount is always asynchronous, while useEffect runs synchronously",
      ],
      e: "componentDidMount runs synchronously before paint; useEffect runs after paint, is called twice in dev StrictMode, and captures the props/state of the first render (a stale closure). useLayoutEffect is closer in timing.",
    },
  },
  {
    t: "React · Lifecycle",
    q: "Когда выполняется cleanup эффекта useEffect(fn, [dep])?",
    o: [
      "Только один раз при unmount компонента",
      "Перед КАЖДЫМ следующим запуском эффекта и при unmount",
      "После каждого рендера компонента, включая самый первый",
      "Никогда не выполняется, если массив deps не пустой",
    ],
    a: 1,
    e: "Сначала уборка за старым эффектом (отписка, clearTimeout), потом новый запуск. Это видно в логах нашего демо lifecycle.",
    en: {
      t: "React · Lifecycle",
      q: "When does the cleanup function of useEffect(fn, [dep]) run?",
      o: [
        "Only once, when the component unmounts",
        "Before EVERY subsequent run of the effect, and on unmount",
        "After every render of the component, including the very first one",
        "Never, as long as the deps array is not empty",
      ],
      e: "React first cleans up after the old effect (unsubscribing, clearTimeout), then runs the new one. You can see this in our lifecycle demo logs.",
    },
  },
  {
    t: "React · Lifecycle",
    q: "Error boundary можно сделать...",
    o: [
      "специальным встроенным хуком useErrorBoundary из React",
      "только классом (getDerivedStateFromError / componentDidCatch) или библиотекой",
      "обычным try/catch, просто обёрнутым вокруг JSX-разметки",
      "глобальным обработчиком ошибок window.onerror в браузере",
    ],
    a: 1,
    e: "Хук-аналога до сих пор нет. Boundary не ловит ошибки в обработчиках событий и асинхронном коде — только в render-фазе поддерева.",
    en: {
      t: "React · Lifecycle",
      q: "An error boundary can be implemented...",
      o: [
        "with a special built-in useErrorBoundary hook from React",
        "only as a class (getDerivedStateFromError / componentDidCatch) or via a library",
        "with a plain try/catch simply wrapped around the JSX markup",
        "with a global window.onerror handler in the browser",
      ],
      e: "There is still no hook equivalent. A boundary does not catch errors in event handlers or async code — only in the render phase of its subtree.",
    },
  },
  {
    t: "React · Lifecycle",
    q: "Что делает StrictMode в dev-режиме (React 18)?",
    o: [
      "Это просто немного ускоряет рендер компонентов в разработке",
      "Монтирует → размонтирует → монтирует повторно, чтобы поймать неидемпотентные эффекты",
      "Полностью отключает вывод console.log в консоль браузера",
      "Включает полноценный режим продакшен-сборки прямо в разработке",
    ],
    a: 1,
    e: "Двойной mount проверяет, что эффекты правильно убирают за собой (cleanup). Код «один раз за жизнь» без cleanup даст дубли подписок/запросов.",
    en: {
      t: "React · Lifecycle",
      q: "What does StrictMode do in dev mode (React 18)?",
      o: [
        "It simply makes component rendering a bit faster in development",
        "It mounts → unmounts → mounts again, to catch non-idempotent effects",
        "It completely disables console.log output in the browser console",
        "It turns on a full production build mode right inside development",
      ],
      e: "The double mount checks that effects clean up properly after themselves. \"Run once for the lifetime\" code without cleanup will produce duplicate subscriptions/requests.",
    },
  },
  {
    t: "React · Hooks",
    q: "Почему хуки нельзя вызывать в if/циклах?",
    o: [
      "Потому что так вызовы хуков работают заметно медленнее",
      "React сопоставляет хуки ПО ПОРЯДКУ ВЫЗОВА в списке fiber-а",
      "Это считается синтаксической ошибкой прямо в JSX",
      "Можно, если хук вызван самым последним в компоненте",
    ],
    a: 1,
    e: "У хуков нет имён — только порядковый номер. Пропущенный вызов сдвинет все последующие, и state перепутается.",
    en: {
      t: "React · Hooks",
      q: "Why can't hooks be called inside if statements or loops?",
      o: [
        "Because hook calls run noticeably slower that way",
        "React matches hooks by their CALL ORDER in the fiber's linked list",
        "It is treated as a syntax error directly in JSX",
        "It's fine, as long as the hook is called last in the component",
      ],
      e: "Hooks have no names — only a call-order index. A skipped call shifts every subsequent hook, and their state gets mixed up.",
    },
  },
  {
    t: "React · Hooks",
    q: "Изменение ref.current вызывает...",
    o: [
      "Вызывает немедленный ре-рендер компонента",
      "ничего — ref мутабелен и не триггерит рендер",
      "Приводит к ошибке при следующем рендере",
      "Запускает перезапуск всех эффектов компонента",
    ],
    a: 1,
    e: "useRef — «коробка», живущая между рендерами. Для отображаемых данных — useState; для «запомнить без рендера» (id таймера, DOM) — useRef.",
    en: {
      t: "React · Hooks",
      q: "Changing ref.current...",
      o: [
        "triggers an immediate re-render of the component",
        "does nothing — a ref is mutable and doesn't trigger a render",
        "causes an error on the next render",
        "restarts all of the component's effects",
      ],
      e: "useRef is a \"box\" that persists across renders. Use useState for data that should be displayed; use useRef to \"remember without rendering\" (a timer id, a DOM node, etc.).",
    },
  },
  {
    t: "React · Hooks",
    q: "useCallback(fn, deps) — это то же самое, что...",
    o: [
      "useEffect(fn, deps) — другой хук",
      "useMemo(() => fn, deps)",
      "useRef(fn) с постоянной ссылкой",
      "memo(fn) — обёртка компонента",
    ],
    a: 1,
    e: "useCallback кэширует саму функцию, useMemo — результат вызова. useCallback(fn, deps) === useMemo(() => fn, deps).",
    en: {
      t: "React · Hooks",
      q: "useCallback(fn, deps) is equivalent to...",
      o: [
        "useEffect(fn, deps) — a different hook",
        "useMemo(() => fn, deps)",
        "useRef(fn) with a stable reference",
        "memo(fn) — a component wrapper",
      ],
      e: "useCallback caches the function itself, useMemo caches the result of calling something. useCallback(fn, deps) === useMemo(() => fn, deps).",
    },
  },
  {
    t: "React · Hooks",
    q: "Когда useCallback реально нужен?",
    o: [
      "Всегда — буквально для любой функции внутри компонента",
      "Функция идёт в memo-компонент, в deps хука, или её идентичность важна извне",
      "Только внутри классовых компонентов, в функциональных не нужен",
      "Когда тело самой функции получилось довольно длинным и сложным",
    ],
    a: 1,
    e: "Мемоизация не бесплатна (сравнение deps + хранение). «Оборачиваю всё на всякий случай» — известный red flag.",
    en: {
      t: "React · Hooks",
      q: "When is useCallback actually needed?",
      o: [
        "Always — literally for every function inside a component",
        "When the function is passed to a memoized component, used in a hook's deps, or its identity matters elsewhere",
        "Only inside class components; it's unnecessary in function components",
        "When the function's body has become fairly long and complex",
      ],
      e: "Memoization isn't free (comparing deps + storing the result). \"Wrap everything just in case\" is a well-known red flag.",
    },
  },
  {
    t: "React · HOC",
    q: "Что будет, если создавать HOC (или компонент) внутри render?",
    o: [
      "Ничего страшного, React просто переиспользует компонент",
      "Новый тип каждый рендер → React размонтирует и пересоздаёт всё поддерево",
      "React выдаст ошибку компиляции прямо при сборке проекта",
      "Приложение начнёт утекать по памяти, но UI отрисуется нормально",
    ],
    a: 1,
    e: "Для reconciliation новый тип ≠ старый: state теряется, инпуты сбрасываются, эффекты перезапускаются. HOC вызывают один раз на уровне модуля.",
    en: {
      t: "React · HOC",
      q: "What happens if you create a HOC (or a component) inside render?",
      o: [
        "Nothing bad — React simply reuses the component",
        "A new type on every render → React unmounts and recreates the whole subtree",
        "React throws a compile error right when the project is built",
        "The app starts leaking memory, but the UI renders fine",
      ],
      e: "For reconciliation, a new type is never equal to the old one: state is lost, inputs reset, effects restart. HOCs should be created once, at module scope.",
    },
  },
  {
    t: "React · Forms",
    q: "Controlled input — это...",
    o: [
      "value из state + onChange, React — источник правды",
      "ref и defaultValue, DOM сам хранит текущее значение",
      "Input с добавленной валидацией по событию onBlur",
      "Обычный input, находящийся внутри тега <form>",
    ],
    a: 0,
    e: "Controlled: рендер на каждый символ, зато мгновенная валидация и маски. Uncontrolled (ref + defaultValue) — ноль рендеров при вводе.",
    en: {
      t: "React · Forms",
      q: "A controlled input is...",
      o: [
        "value coming from state plus onChange, with React as the source of truth",
        "a ref and defaultValue, with the DOM itself holding the current value",
        "an input with validation added on the onBlur event",
        "a plain input that happens to sit inside a <form> tag",
      ],
      e: "Controlled: a render on every keystroke, but you get instant validation and input masks. Uncontrolled (ref + defaultValue) means zero renders while typing.",
    },
  },
  {
    t: "React · Context",
    q: "При изменении value провайдера ре-рендерятся...",
    o: [
      "только компоненты, обёрнутые в React.memo",
      "ВСЕ компоненты, читающие этот контекст",
      "абсолютно все компоненты во всём приложении",
      "никто, пока заново не вызовут useContext вручную",
    ],
    a: 1,
    e: "Все consumer-ы, без селекторов из коробки. Поэтому: мемоизировать value, дробить контексты, а частые обновления — во внешний стор.",
    en: {
      t: "React · Context",
      q: "When a provider's value changes, which components re-render?",
      o: [
        "Only the components wrapped in React.memo",
        "ALL components that read this context",
        "Absolutely every component in the entire application",
        "None, until useContext is manually called again",
      ],
      e: "Every consumer re-renders — there are no built-in selectors. That's why you should memoize the value, split contexts up, and move frequently-changing state to an external store.",
    },
  },
  {
    t: "React · Context",
    q: "<Ctx.Provider value={{ user }}> — в чём проблема?",
    o: [
      "Провайдера в таком виде вообще писать так нельзя никогда",
      "Новый объект value каждый рендер → все consumer-ы рендерятся зря; нужен useMemo",
      "Поле user попадёт прямиком в глобальную область видимости",
      "Никакой проблемы тут нет вообще, всё работает как надо",
    ],
    a: 1,
    e: "Инлайн-объект — новая ссылка на каждом рендере родителя. useMemo(() => ({ user }), [user]) стабилизирует ссылку.",
    en: {
      t: "React · Context",
      q: "<Ctx.Provider value={{ user }}> — what's the problem here?",
      o: [
        "A provider can never be written this way at all",
        "A new value object is created on every render → all consumers re-render needlessly; useMemo is needed",
        "The user field leaks straight into global scope",
        "There is no problem here at all, everything works as expected",
      ],
      e: "An inline object is a new reference on every render of the parent. useMemo(() => ({ user }), [user]) keeps the reference stable.",
    },
  },
  {
    t: "React · Reconciliation",
    q: "Зачем нужен key в списках?",
    o: [
      "Чтобы React не выводил предупреждение в консоль",
      "Определяет ИДЕНТИЧНОСТЬ элемента между рендерами при diff-е",
      "Ускоряет выполнение map по массиву элементов",
      "Автоматически сортирует все элементы списка",
    ],
    a: 1,
    e: "key говорит React «это тот же элемент, что и раньше» — чтобы переиспользовать DOM и state правильно при вставках/удалениях/сортировке.",
    en: {
      t: "React · Reconciliation",
      q: "Why is key needed in lists?",
      o: [
        "So React doesn't print a warning in the console",
        "It defines an element's IDENTITY across renders during the diff",
        "It speeds up running map over an array of elements",
        "It automatically sorts all the items in the list",
      ],
      e: "key tells React \"this is the same element as before\", so the DOM and state are reused correctly across insertions, deletions, and reordering.",
    },
  },
  {
    t: "React · Reconciliation",
    q: "Чем плох key={index} в изменяемом списке?",
    o: [
      "Индекс достаточно медленно вычисляется на очень больших списках",
      "При сдвиге элементов state (текст инпутов, фокус) прилипает к ПОЗИЦИИ, а не к данным",
      "Значение index иногда может оказаться отрицательным числом",
      "Ничем, это стандартный и всеми давно рекомендуемый способ",
    ],
    a: 1,
    e: "Удалили первый элемент — индексы сдвинулись, React думает «элемент 0 остался». key={Math.random()} ещё хуже: полный ремаунт каждый рендер.",
    en: {
      t: "React · Reconciliation",
      q: "What's wrong with key={index} in a mutable list?",
      o: [
        "The index is computed fairly slowly for very large lists",
        "When items shift, state (input text, focus) sticks to the POSITION instead of the data",
        "The index value can sometimes turn out to be negative",
        "Nothing — it's the standard, long-recommended approach",
      ],
      e: "Remove the first item and the indexes shift, so React thinks \"item 0 stayed the same\". key={Math.random()} is even worse: it fully remounts on every render.",
    },
  },
  {
    t: "React · Reconciliation",
    q: "Намеренная смена key у компонента — это...",
    o: [
      "Это всегда указывает на ошибку в коде",
      "Легитимный способ сбросить state компонента (ремаунт)",
      "Способ оптимизировать скорость рендера компонента",
      "Ещё один способ передать компоненту новые props",
    ],
    a: 1,
    e: "Новый key = новый элемент для React: компонент размонтируется и смонтируется с чистым state. Например, <Form key={userId}> при смене юзера.",
    en: {
      t: "React · Reconciliation",
      q: "Deliberately changing a component's key is...",
      o: [
        "always a sign of a bug in the code",
        "a legitimate way to reset a component's state (a remount)",
        "a way to optimize the component's render speed",
        "just another way to pass new props to a component",
      ],
      e: "A new key means a new element for React: the component unmounts and mounts again with clean state. For example, <Form key={userId}> when the user changes.",
    },
  },
  {
    t: "React · FP",
    q: "state.items.push(x); setState(state); — что произойдёт?",
    o: [
      "Произойдёт самый обычный ре-рендер компонента",
      "Ре-рендера НЕТ: та же ссылка → bail-out, а данные уже испорчены",
      "React выбросит ошибку «нельзя мутировать state»",
      "Метод push просто не сработает и ничего не изменит",
    ],
    a: 1,
    e: "React сравнивает по ссылке (Object.is). Мутация не меняет ссылку → «изменений нет». И memo/useMemo с этим массивом в deps тоже не заметят. Только новая ссылка: [...items, x].",
    en: {
      t: "React · Immutability",
      q: "state.items.push(x); setState(state); — what happens?",
      o: [
        "A perfectly normal re-render of the component happens",
        "There is NO re-render: same reference → bail-out, and the data is already corrupted",
        "React throws an error: \"you cannot mutate state\"",
        "The push method simply fails silently and changes nothing",
      ],
      e: "React compares by reference (Object.is). A mutation doesn't change the reference, so React sees \"no change\". memo/useMemo with this array in their deps won't notice it either. Only a new reference works: [...items, x].",
    },
  },
  {
    t: "React · Performance",
    q: "«Приложение тормозит» — с чего начинает senior?",
    o: [
      "Обернуть абсолютно все компоненты в React.memo",
      "Измерить: Profiler / why-did-you-render — найти ЧТО тормозит",
      "Сразу переписать приложение на классовые компоненты",
      "Добавить useCallback вообще ко всем функциям подряд",
    ],
    a: 1,
    e: "Сначала диагноз, потом лечение: причина может быть в ре-рендерах (memo), тяжёлом JS, списке без виртуализации, картинках... memo без замера — лечение симптома.",
    en: {
      t: "React · Performance",
      q: "\"The app is sluggish\" — what does a senior engineer do first?",
      o: [
        "Wrap absolutely every component in React.memo",
        "Measure: use the Profiler / why-did-you-render to find WHAT is slow",
        "Immediately rewrite the app using class components",
        "Add useCallback to literally every function across the board",
      ],
      e: "Diagnose first, treat second: the cause could be re-renders (fixed with memo), heavy JS, an un-virtualized list, images... Adding memo without measuring just treats a symptom.",
    },
  },
  {
    t: "React · Performance",
    q: "Почему React.memo может «не работать»?",
    o: [
      "React.memo уже давно устарел и больше не рекомендуется к использованию",
      "Инлайн-функции/объекты в props: новая ссылка каждый рендер → поверхностное сравнение видит «изменение»",
      "React.memo умеет работать только с классовыми компонентами, не с функциональными",
      "Компоненту попросту не хватает явно указанного уникального пропа key",
    ],
    a: 1,
    e: "memo сравнивает props поверхностно по ссылкам. onClick={() => ...} — каждый раз новая функция. Лечение: useCallback/useMemo/вынос констант.",
    en: {
      t: "React · Performance",
      q: "Why might React.memo \"not work\"?",
      o: [
        "React.memo has long been deprecated and is no longer recommended",
        "Inline functions/objects in props: a new reference on every render → the shallow comparison sees a \"change\"",
        "React.memo only works with class components, not function components",
        "The component simply lacks an explicitly specified unique key prop",
      ],
      e: "memo compares props shallowly by reference. onClick={() => ...} creates a brand-new function every time. The fix: useCallback/useMemo or hoisting constants out.",
    },
  },
  {
    t: "React · Snapshot tests",
    q: "Снапшоты упали после твоего изменения. Правильное действие?",
    o: [
      "Сразу же запустить jest --updateSnapshot без раздумий",
      "Посмотреть diff: намеренное изменение → обновить осознанно, нет → чинить код",
      "Просто удалить упавшие файлы снапшотов из репозитория",
      "Закомментировать упавший тест и разобраться с ним позже",
    ],
    a: 1,
    e: "Смысл снапшота — человек подтверждает изменение глядя на diff. Рефлекторный -u превращает тест в пустышку (это red flag про культуру).",
    en: {
      t: "React · Snapshot Tests",
      q: "Snapshots failed after your change. What is the correct action?",
      o: [
        "Immediately run jest --updateSnapshot without a second thought",
        "Look at the diff: if the change is intentional, update it deliberately; if not, fix the code",
        "Simply delete the failing snapshot files from the repository",
        "Comment out the failing test and deal with it later",
      ],
      e: "The whole point of a snapshot is that a human confirms the change by looking at the diff. Reflexively running -u turns the test into a rubber stamp (a red flag about team culture).",
    },
  },
  {
    t: "React · Props drilling",
    q: "Первое решение против prop drilling?",
    o: [
      "Сразу тянуть глобальный React.createContext",
      "Сразу подключать Redux или другой глобальный стор",
      "Composition: собрать компонент наверху и передать через children",
      "Завести глобальную переменную вне React-дерева",
    ],
    a: 2,
    e: "Composition решает большинство случаев бесплатно. Context — для редко меняющегося (тема, auth), стор — для частого глобального. По возрастанию тяжести!",
    en: {
      t: "React · Prop Drilling",
      q: "What's the first solution to reach for against prop drilling?",
      o: [
        "Immediately reach for a global React.createContext",
        "Immediately bring in Redux or another global store",
        "Composition: assemble the component higher up and pass it through children",
        "Set up a global variable outside the React tree",
      ],
      e: "Composition solves most cases for free. Context is for rarely-changing values (theme, auth); a store is for frequently-changing global state. Reach for them in increasing order of weight.",
    },
  },
  {
    t: "React · Suspense",
    q: "Что делает React.lazy?",
    o: [
      "Откладывает рендер компонента до простоя браузера",
      "Выносит код компонента в отдельный чанк, загружаемый при первом рендере",
      "Кэширует результат рендера между переходами по страницам",
      "Понижает приоритет обновления состояния этого компонента",
    ],
    a: 1,
    e: "lazy + динамический импорт = code splitting: начальный бандл меньше, чанк едет по требованию. Пока грузится — компонент suspend-ится, и Suspense показывает fallback.",
    en: {
      t: "React · Suspense",
      q: "What does React.lazy do?",
      o: [
        "It defers rendering the component until the browser is idle",
        "It splits the component's code into a separate chunk that loads on first render",
        "It caches the render result between page navigations",
        "It lowers the priority of state updates for this component",
      ],
      e: "lazy plus a dynamic import equals code splitting: the initial bundle gets smaller and the chunk loads on demand. While it's loading, the component suspends, and Suspense shows the fallback.",
    },
  },
  {
    t: "React · Suspense",
    q: "Компонент грузит данные через useEffect + fetch. Покажет ли Suspense свой fallback?",
    o: [
      "Да, Suspense самостоятельно перехватывает абсолютно любую загрузку данных",
      "Нет — useEffect не приостанавливает компонент; нужен источник, умеющий suspend (use(), RSC, Relay)",
      "Да, но только если явно пометить весь сам компонент как async-функцию",
      "Только если в самом приложении дополнительно включён режим StrictMode",
    ],
    a: 1,
    e: "Suspense реагирует на «приостановку» рендера, а обычный эффект просто рендерит компонент с пустым состоянием. Для данных — use() в React 19, RSC или библиотеки в suspense-режиме.",
    en: {
      t: "React · Suspense",
      q: "A component fetches data via useEffect + fetch. Will Suspense show its fallback?",
      o: [
        "Yes, Suspense automatically intercepts absolutely any data fetching",
        "No — useEffect doesn't suspend the component; you need a data source that can suspend (use(), RSC, Relay)",
        "Yes, but only if the whole component is explicitly marked as an async function",
        "Only if StrictMode is additionally enabled in the app",
      ],
      e: "Suspense reacts to a render \"suspending\", while a regular effect just renders the component with empty state first. For data, use use() in React 19, RSC, or a library operating in Suspense mode.",
    },
  },
  {
    t: "React · Suspense",
    q: "Последствие такого кода?\nfunction Page() {\n  const C = lazy(() => import('./C')); // внутри компонента!\n  return <C />;\n}",
    o: [
      "Ничего страшного, объявлять внутри компонента тоже можно",
      "Новый тип компонента каждый рендер → бесконечный ремаунт поддерева",
      "Чанк загрузится дважды подряд и потом закэшируется",
      "Сборка проекта завершится с ошибкой на этом месте",
    ],
    a: 1,
    e: "Та же природа, что у HOC внутри render: новый тип ≠ старый для reconciliation. lazy объявляют один раз на уровне модуля.",
    en: {
      t: "React · Suspense",
      q: "What's the consequence of this code?\nfunction Page() {\n  const C = lazy(() => import('./C')); // inside the component!\n  return <C />;\n}",
      o: [
        "Nothing bad — it's fine to declare it inside a component too",
        "A new component type on every render → infinite remounting of the subtree",
        "The chunk loads twice in a row and then gets cached",
        "The project build fails with an error at this line",
      ],
      e: "It's the same issue as a HOC defined inside render: a new type is never equal to the old one for reconciliation. lazy should be declared once, at module scope.",
    },
  },
  {
    t: "React · Concurrent",
    q: "Что делает startTransition из useTransition?",
    o: [
      "Ускоряет непосредственно рендер обёрнутого обновления",
      "Помечает обновление несрочным — React прервёт его ради срочного ввода",
      "Откладывает обновление по таймеру, как обычный debounce",
      "Переносит тяжёлые вычисления в отдельный Web Worker",
    ],
    a: 1,
    e: "Объём работы не меняется — меняется ПРИОРИТЕТ: инпут остаётся отзывчивым, тяжёлый рендер идёт в фоне и может быть отброшен. isPending даёт индикатор.",
    en: {
      t: "React · Concurrent Features",
      q: "What does startTransition from useTransition do?",
      o: [
        "It directly speeds up the render of the wrapped update",
        "It marks the update as non-urgent — React will interrupt it in favor of urgent input",
        "It delays the update with a timer, like a regular debounce",
        "It offloads heavy computations to a separate Web Worker",
      ],
      e: "The amount of work doesn't change — the PRIORITY does: input stays responsive, and the heavy render runs in the background and can be discarded. isPending gives you a loading indicator.",
    },
  },
  {
    t: "React · Concurrent",
    q: "Когда брать useDeferredValue вместо useTransition?",
    o: [
      "Когда нужен встроенный индикатор загрузки isPending",
      "Когда значение приходит извне (props/чужой state) и обернуть setState нельзя",
      "Когда обновлений случается больше, чем десять в секунду",
      "Когда сам компонент уже обёрнут в обёртку React.memo",
    ],
    a: 1,
    e: "useTransition — если ты сам вызываешь setState. useDeferredValue — берёшь значение и получаешь его отстающую копию для дорогого поддерева.",
    en: {
      t: "React · Concurrent Features",
      q: "When should you reach for useDeferredValue instead of useTransition?",
      o: [
        "When you need a built-in isPending loading indicator",
        "When the value comes from outside (props/someone else's state) and you can't wrap the setState call",
        "When updates happen more than ten times per second",
        "When the component itself is already wrapped in React.memo",
      ],
      e: "Use useTransition when you're the one calling setState. Use useDeferredValue when you take a value and get a lagging copy of it for an expensive subtree.",
    },
  },
  {
    t: "React · Concurrent",
    q: "Чем useDeferredValue отличается от debounce?",
    o: [
      "Ничем вообще не отличается друг от друга, deferred — это просто встроенный debounce",
      "Debounce откладывает само обновление по таймеру; deferred обновляет сразу, но рендер прерываемый и уступает срочному",
      "Debounce умеет работать исключительно только с текстовыми полями для самого ввода",
      "Deferred полностью и безвозвратно отбрасывает вообще все промежуточные значения",
    ],
    a: 1,
    e: "Debounce задерживает данные (фиксированный таймер), deferred — приоритет рендера без задержки данных. На быстрой машине deferred вообще не отстанет.",
    en: {
      t: "React · Concurrent Features",
      q: "How does useDeferredValue differ from debounce?",
      o: [
        "It doesn't differ at all — deferred is just a built-in debounce",
        "Debounce delays the update itself with a timer; deferred updates right away, but the render is interruptible and yields to urgent work",
        "Debounce can only work with text input fields",
        "Deferred completely and irrevocably discards all intermediate values",
      ],
      e: "Debounce delays the data (a fixed timer), while deferred prioritizes rendering without delaying the data. On a fast machine, the deferred value may not lag at all.",
    },
  },
  {
    t: "React · Refs",
    q: "Как передать ref в функциональный компонент в React 19?",
    o: [
      "Только через обёртку forwardRef — этот механизм в React 19 не менялся",
      "ref приходит обычным пропом — forwardRef больше не нужен, его депрекируют в будущих релизах",
      "Только вручную: передать ref через React Context в дочерний компонент",
      "Через useImperativeHandle, вызванный в родительском компоненте",
    ],
    a: 1,
    e: "React 19 сделал ref обычным пропом функциональных компонентов. forwardRef пока работает (команда React планирует депрекацию в будущем релизе) — знание нюанса это маркер версии.",
    en: {
      t: "React · Refs",
      q: "How do you pass a ref to a function component in React 19?",
      o: [
        "Only via the forwardRef wrapper — this mechanism hasn't changed in React 19",
        "ref arrives as a regular prop — forwardRef is no longer necessary and is planned for deprecation in a future release",
        "Only manually: pass the ref through React Context to the child component",
        "Via useImperativeHandle, called in the parent component",
      ],
      e: "React 19 made ref an ordinary prop on function components. forwardRef still works for now (the React team plans to deprecate it in a future release) — knowing this nuance is a good marker of version awareness.",
    },
  },
  {
    t: "React · Refs",
    q: "Зачем нужен useImperativeHandle?",
    o: [
      "Чтобы вручную вызвать ре-рендер из родительского компонента",
      "Чтобы отдать наружу ограниченный API (focus/clear) вместо сырого DOM-узла",
      "Чтобы подписаться на любые изменения значения ref",
      "Чтобы сохранить ref между полными размонтированиями",
    ],
    a: 1,
    e: "Узкий контракт вместо всего элемента: родитель дёргает только разрешённые методы. Использовать редко — императивный доступ это исключение, а не норма.",
    en: {
      t: "React · Refs",
      q: "What is useImperativeHandle for?",
      o: [
        "To manually trigger a re-render from the parent component",
        "To expose a limited API (focus/clear) instead of the raw DOM node",
        "To subscribe to any changes in a ref's value",
        "To preserve a ref across full unmount/remount cycles",
      ],
      e: "It exposes a narrow contract instead of the whole element: the parent can only call the allowed methods. Use it sparingly — imperative access is the exception, not the norm.",
    },
  },
  {
    t: "React · Refs",
    q: "Клик по контенту внутри createPortal(…, document.body). Куда всплывёт событие?",
    o: [
      "К DOM-родителю напрямую, то есть к элементу body",
      "К React-родителю — портал переносит DOM, но не место в React-дереве",
      "Никуда — портал полностью изолирует все события",
      "Событие всплывёт сразу в оба места одновременно",
    ],
    a: 1,
    e: "Портал меняет только точку монтирования в DOM. В React-дереве компонент остаётся на месте — поэтому работают и контекст, и всплытие к логическому родителю.",
    en: {
      t: "React · Refs",
      q: "A click on content inside createPortal(…, document.body). Where does the event bubble to?",
      o: [
        "Straight to the DOM parent, i.e. the body element",
        "To the React parent — a portal moves the DOM, but not its place in the React tree",
        "Nowhere — a portal fully isolates all events",
        "The event bubbles to both places at the same time",
      ],
      e: "A portal only changes the DOM mount point. In the React tree the component stays right where it is — that's why context and bubbling to the logical parent both still work.",
    },
  },
  {
    t: "React · Refs",
    q: "Что не так?\nfunction C() {\n  const r = useRef(0);\n  r.current += 1;\n  return <b>{r.current}</b>;\n}",
    o: [
      "Ничего страшного в этом совсем нет, это обычный счётчик рендеров",
      "Мутация ref в render-фазе: она обязана быть чистой, рендер может быть прерван или вызван дважды",
      "Здесь вместо useRef правильнее было бы использовать хук useState",
      "Так нельзя — ref в принципе нельзя создавать без начального значения",
    ],
    a: 1,
    e: "Render должен быть чистым: concurrent rendering может отбросить рендер, а StrictMode в dev вызывает его дважды — счётчик соврёт. Мутировать ref — в эффектах и обработчиках.",
    en: {
      t: "React · Refs",
      q: "What's wrong here?\nfunction C() {\n  const r = useRef(0);\n  r.current += 1;\n  return <b>{r.current}</b>;\n}",
      o: [
        "There's nothing wrong with this at all — it's just a plain render counter",
        "It mutates a ref during the render phase: render must be pure, and it can be discarded or invoked twice",
        "useState should have been used here instead of useRef",
        "This isn't allowed — a ref can't be created without an initial value at all",
      ],
      e: "Render must be pure: concurrent rendering can discard a render, and StrictMode in dev invokes it twice — so the counter will lie. Mutate refs in effects and event handlers instead.",
    },
  },
  {
    t: "React · RSC",
    q: "Чем Server Components отличаются от SSR?",
    o: [
      "Ничем, это просто два совершенно разных названия одного и того же подхода",
      "Код серверного компонента вообще не попадает в бандл и не гидрируется; при SSR тот же код едет на клиент",
      "Server Components умеют работать только с REST API, а не напрямую с базой",
      "SSR в принципе изначально совсем не умеет отдавать готовый HTML клиенту",
    ],
    a: 1,
    e: "SSR: рендер на сервере в HTML + гидратация тем же кодом на клиенте. RSC: компонент существует только на сервере, гидрировать нечего. Они сочетаются, а не исключают друг друга.",
    en: {
      t: "React · Server Components",
      q: "How do Server Components differ from SSR?",
      o: [
        "They don't — these are just two completely different names for the same approach",
        "A Server Component's code never ends up in the bundle and is never hydrated; with SSR, the same code also ships to the client",
        "Server Components can only work with a REST API, not directly with a database",
        "SSR fundamentally can't ever send ready-made HTML to the client",
      ],
      e: "SSR: render to HTML on the server, then hydrate on the client with the same code. RSC: the component exists only on the server — there's nothing to hydrate. The two are complementary, not mutually exclusive.",
    },
  },
  {
    t: "React · RSC",
    q: "Что нельзя сделать в серверном компоненте?",
    o: [
      "Сходить в базу данных напрямую прямо с самого сервера",
      "Использовать useState, useEffect и onClick — интерактив только в 'use client'",
      "Отрендерить самый обычный список элементов прямо на странице",
      "Прочитать содержимое обычного файла прямо с диска сервера",
    ],
    a: 1,
    e: "Серверный компонент выполняется один раз на сервере: состояния и событий там нет. Интерактивные части выносят в клиентские островки, а серверные передают внутрь через children.",
    en: {
      t: "React · Server Components",
      q: "What can't you do in a Server Component?",
      o: [
        "Query a database directly from the server itself",
        "Use useState, useEffect, and onClick — interactivity requires 'use client'",
        "Render a perfectly ordinary list of items on the page",
        "Read the contents of a regular file straight from the server's disk",
      ],
      e: "A Server Component runs once on the server: there's no state or events there. Interactive parts are moved into client islands, and server components are passed into them via children.",
    },
  },
  {
    t: "React · RSC",
    q: "Что произойдёт, если поставить 'use client' в корневом layout?",
    o: [
      "Ничего страшного, директива подействует только на этот файл",
      "Всё дерево ниже станет клиентским — выигрыш RSC обнулится",
      "Приложение попросту перестанет собираться совсем",
      "Серверные компоненты продолжат работать точно как раньше",
    ],
    a: 1,
    e: "Директива заразна вниз по импортам. Правильно: клиентские островки держать как можно ниже, на листьях дерева.",
    en: {
      t: "React · Server Components",
      q: "What happens if you put 'use client' in the root layout?",
      o: [
        "Nothing bad — the directive only affects this one file",
        "The entire tree below becomes client-side — all of RSC's benefit is wiped out",
        "The application simply stops building altogether",
        "Server components keep working exactly as before",
      ],
      e: "The directive is contagious down through imports. The right approach is to keep client islands as low as possible, at the leaves of the tree.",
    },
  },
  {
    t: "React · Fiber",
    q: "React Fiber — это...",
    o: [
      "Архитектура reconciler'а: связный список узлов-единиц работы, обход можно прерывать",
      "Облегчённая копия реального DOM, которую React держит в памяти и сравнивает при рендере",
      "Оптимизация Virtual DOM, ускоряющая каждый отдельный рендер компонента в несколько раз",
      "Отдельный поток (web worker), в котором React выполняет фазу рендера без блокировки UI",
    ],
    a: 0,
    e: "Fiber (React 16) — переписанный reconciler: вместо рекурсии — цикл по fiber-узлам с указателями child/sibling/return. Главное свойство — не «быстрее», а прерываемость работы.",
    en: {
      t: "React · Fiber",
      q: "React Fiber is...",
      o: [
        "The reconciler architecture: a linked list of work-unit nodes whose traversal can be paused",
        "A lightweight copy of the real DOM that React keeps in memory and diffs on every render",
        "A Virtual DOM optimization that makes each individual component render several times faster",
        "A separate thread (web worker) where React runs the render phase without blocking the UI",
      ],
      e: "Fiber (React 16) is the rewritten reconciler: recursion was replaced with a loop over fiber nodes linked by child/sibling/return pointers. Its key property isn't being \"faster\" — it's that work is interruptible.",
    },
  },
  {
    t: "React · Fiber",
    q: "Почему рендер в Fiber можно поставить на паузу, а в старом stack reconciler — нельзя?",
    o: [
      "Обход идёт циклом по указателям, и workInProgress помнит, где остановились",
      "Fiber выполняет рендер в отдельном потоке, который ОС умеет приостанавливать",
      "React 16 стал планировать рендер через requestAnimationFrame вместо setTimeout",
      "Старый reconciler работал напрямую с DOM, а Fiber — с виртуальным деревом",
    ],
    a: 0,
    e: "Рекурсия занимает стек вызовов — прерваться нельзя, только доработать. Цикл while (workInProgress && !shouldYield()) обрабатывает по одному fiber за шаг: пауза после любого узла, указатель хранит позицию.",
    en: {
      t: "React · Fiber",
      q: "Why can a Fiber render be paused, while the old stack reconciler's couldn't?",
      o: [
        "Traversal is a pointer-driven loop, and workInProgress remembers where it stopped",
        "Fiber renders on a separate thread that the OS knows how to suspend",
        "React 16 started scheduling renders via requestAnimationFrame instead of setTimeout",
        "The old reconciler worked directly on the DOM, while Fiber works on a virtual tree",
      ],
      e: "Recursion occupies the call stack — you can't pause, only finish. The while (workInProgress && !shouldYield()) loop processes one fiber per step: it can pause after any node, and the pointer stores the position.",
    },
  },
  {
    t: "React · Fiber",
    q: "Зачем Fiber держит два дерева одновременно (double buffering)?",
    o: [
      "Новое дерево строится в памяти, а в commit React атомарно переключает указатель",
      "Чтобы сравнивать два дерева диффом за O(n) вместо наивных O(n³) сравнений",
      "Одно дерево обслуживает клиентские компоненты, второе — серверные (RSC)",
      "Для time-travel отладки: React хранит прошлую версию дерева для отката",
    ],
    a: 0,
    e: "Double buffering: дерево workInProgress можно строить с паузами и даже выбросить, а пользователь видит только целостный current — переключение указателя в commit атомарно.",
    en: {
      t: "React · Fiber",
      q: "Why does Fiber keep two trees at the same time (double buffering)?",
      o: [
        "The new tree is built in memory, and in commit React atomically flips the pointer",
        "To diff the two trees in O(n) instead of the naive O(n³) tree comparisons",
        "One tree serves the client components, the other serves server components (RSC)",
        "For time-travel debugging: React keeps the previous tree version for rollback",
      ],
      e: "Double buffering: the workInProgress tree can be built with pauses or even thrown away, while the user only ever sees a consistent current — the pointer flip in commit is atomic.",
    },
  },
  {
    t: "React · Fiber",
    q: "Что такое lanes в архитектуре Fiber?",
    o: [
      "Битовая маска приоритетов обновлений: срочный ввод обгоняет фоновый transition",
      "Очереди микро- и макрозадач event loop, в которые React кладёт эффекты",
      "Слои DOM-дерева, которые React умеет обновлять параллельно друг другу",
      "Каналы стриминга данных между сервером и клиентом в Server Components",
    ],
    a: 0,
    e: "Lanes — система приоритетов на битовых масках. Именно она позволяет useTransition: React бросает низкоприоритетную работу ради срочного клика и возвращается к ней позже.",
    en: {
      t: "React · Fiber",
      q: "What are lanes in the Fiber architecture?",
      o: [
        "A bitmask of update priorities: urgent input overtakes a background transition",
        "The event loop's micro- and macrotask queues where React schedules effects",
        "Layers of the DOM tree that React can update in parallel with each other",
        "Data streaming channels between server and client in Server Components",
      ],
      e: "Lanes are a bitmask-based priority system. It's what makes useTransition possible: React abandons low-priority work for an urgent click and comes back to it later.",
    },
  },
  {
    t: "React · Fiber",
    q: "Пользователь печатает в input во время тяжёлого рендера внутри startTransition. Что сделает React?",
    o: [
      "Прервёт transition-рендер, синхронно отрендерит ввод, потом начнёт transition заново",
      "Дождётся конца transition-рендера и только после него обработает нажатие клавиши",
      "Отрендерит оба обновления одновременно — каждое в своём отдельном потоке",
      "Отбросит нажатия клавиш до конца рендера — пользователю придётся их повторить",
    ],
    a: 0,
    e: "Срочная lane вытесняет transition: недостроенное workInProgress-дерево выбрасывается, ввод рендерится синхронно, transition стартует заново. Именно поэтому ввод остаётся отзывчивым.",
    en: {
      t: "React · Fiber",
      q: "The user types into an input during a heavy render inside startTransition. What does React do?",
      o: [
        "Interrupts the transition render, renders the input synchronously, then restarts the transition",
        "Waits for the transition render to finish and only then processes the keystroke",
        "Renders both updates at the same time — each one on its own separate thread",
        "Drops the keystrokes until the render finishes — the user has to type them again",
      ],
      e: "The urgent lane preempts the transition: the half-built workInProgress tree is discarded, the input renders synchronously, and the transition restarts. That's exactly why input stays responsive.",
    },
  },
  {
    t: "React · i18n",
    q: "Чем плох подсчёт формы слова тернарником: count === 1 ? \"товар\" : \"товаров\"?",
    o: [
      "В русском три plural-формы: «2 товара» и «21 товар» тернарник отдаст неверно",
      "Тернарник пересчитывается на каждый рендер и заметно тормозит список",
      "Строки в JSX нельзя выбирать условно — React потребует отдельный компонент",
      "Ничем: для русского языка двух форм слова полностью достаточно",
    ],
    a: 0,
    e: "CLDR-категории русского: one (1, 21, 31...), few (2-4, 22-24...), many (0, 5-20...). i18next выбирает форму сам: ключи cart_one / cart_few / cart_many + t(\"cart\", { count }).",
    en: {
      t: "React · i18n",
      q: "What's wrong with picking a word form via a ternary: count === 1 ? \"item\" : \"items\"?",
      o: [
        "Russian has three plural forms: the ternary gets «2 товара» and «21 товар» wrong",
        "The ternary re-evaluates on every render and visibly slows down the list",
        "Strings can't be chosen conditionally in JSX — React demands a separate component",
        "Nothing: two word forms are completely sufficient for Russian",
      ],
      e: "Russian CLDR categories: one (1, 21, 31...), few (2-4, 22-24...), many (0, 5-20...). i18next picks the form itself: cart_one / cart_few / cart_many keys + t(\"cart\", { count }).",
    },
  },
  {
    t: "React · i18n",
    q: "Зачем в react-i18next нужен компонент <Trans>?",
    o: [
      "Переводить предложения с JSX внутри (ссылки, жирный), не разрезая фразу",
      "Оборачивать приложение и раздавать словарь переводов через контекст",
      "Подгружать переводы с сервера лениво, когда компонент попал во viewport",
      "Автоматически переводить текст машинным переводом при отсутствии ключа",
    ],
    a: 0,
    e: "Конкатенировать куски перевода нельзя — порядок слов в языках разный. Trans даёт переводчику предложение целиком с плейсхолдерами <1>...</1> на месте JSX-вложений.",
    en: {
      t: "React · i18n",
      q: "What is the <Trans> component in react-i18next for?",
      o: [
        "Translating sentences with JSX inside (links, bold) without slicing the phrase",
        "Wrapping the app and distributing the translation dictionary via context",
        "Lazy-loading translations from the server once the component enters the viewport",
        "Auto-translating text with machine translation when a key is missing",
      ],
      e: "You can't concatenate translation fragments — word order differs across languages. Trans gives the translator the whole sentence with <1>...</1> placeholders where the JSX goes.",
    },
  },
  {
    t: "React · i18n",
    q: "Как правильно форматировать даты и валюты в многоязычном приложении?",
    o: [
      "Нативным Intl (DateTimeFormat / NumberFormat) с текущей локалью",
      "Хранить шаблоны типа «DD.MM.YYYY» в JSON переводов для каждого языка",
      "Форматировать на бэкенде и присылать готовые строки для всех локалей",
      "Собирать строку вручную: символ валюты из переводов плюс toFixed(2)",
    ],
    a: 0,
    e: "Форматирование — не перевод: разделители, порядок дня/месяца и позицию символа валюты локаль знает сама. Intl.NumberFormat(\"de-DE\", { style: \"currency\", currency: \"EUR\" }) → «9.999,50 €».",
    en: {
      t: "React · i18n",
      q: "What's the right way to format dates and currency in a multilingual app?",
      o: [
        "With native Intl (DateTimeFormat / NumberFormat) and the current locale",
        "Storing patterns like \"DD.MM.YYYY\" in each language's translation JSON",
        "Formatting on the backend and shipping ready-made strings for all locales",
        "Assembling the string by hand: a currency symbol from translations plus toFixed(2)",
      ],
      e: "Formatting isn't translation: the locale itself knows separators, day/month order and currency-symbol position. Intl.NumberFormat(\"de-DE\", { style: \"currency\", currency: \"EUR\" }) → \"9.999,50 €\".",
    },
  },
];
