// Вопросы квиза: секция Redux
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

import type { Question } from "../types";

export const REDUX_QUESTIONS: Question[] = [
  {
    t: "Redux · Принципы",
    q: "Три принципа Redux?",
    o: [
      "Скорость выполнения, простота кода, небольшой размер бандла",
      "Один стор; state только для чтения; изменения — чистыми reducer-ами",
      "Actions, вспомогательные средства и классы-контроллеры",
      "Мутации напрямую, подписки на события и селекторы",
    ],
    a: 1,
    e: "Single source of truth, state is read-only (только dispatch), changes via pure functions. Из них следуют devtools, time-travel и тестируемость.",
    en: {
      t: "Redux · Principles",
      q: "What are the three principles of Redux?",
      o: [
        "Execution speed, simple code, small bundle size",
        "Single store; state is read-only; changes are made with pure reducers",
        "Actions, helper utilities, and controller classes",
        "Direct mutations, event subscriptions, and selectors",
      ],
      e: "Single source of truth, state is read-only (changes only via dispatch), and changes are made with pure functions. These principles enable devtools, time-travel debugging, and testability.",
    },
  },
  {
    t: "Redux · Принципы",
    q: "Что ЗАПРЕЩЕНО в reducer-е?",
    o: [
      "Использование конструкции switch/case внутри reducer-а",
      "Запросы к API, мутации state, Math.random()",
      "Возврат прежнего state без изменений",
      "Чтение поля action.payload внутри reducer-а",
    ],
    a: 1,
    e: "Reducer — чистая функция (state, action) → newState: без side effects и мутаций. Одинаковый вход всегда даёт одинаковый выход.",
    en: {
      t: "Redux · Principles",
      q: "What is FORBIDDEN inside a reducer?",
      o: [
        "Using a switch/case statement inside a reducer",
        "API calls, mutating state, Math.random()",
        "Returning the previous state unchanged",
        "Reading the action.payload field inside a reducer",
      ],
      e: "A reducer is a pure function (state, action) → newState: no side effects and no mutations. The same input must always produce the same output.",
    },
  },
  {
    t: "Redux · Core",
    q: "Единственный способ изменить state в Redux?",
    o: [
      "store.setState(...)",
      "store.dispatch(action)",
      "Мутировать store.getState()",
      "Изменить из компонента",
    ],
    a: 1,
    e: "dispatch(action) → reducer вычисляет новый state → подписчики уведомлены. Прямой записи в стор не существует.",
    en: {
      t: "Redux · Core",
      q: "What is the only way to change state in Redux?",
      o: [
        "store.setState(...)",
        "store.dispatch(action)",
        "Mutate store.getState()",
        "Change it directly from a component",
      ],
      e: "dispatch(action) → the reducer computes the new state → subscribers are notified. There is no way to write to the store directly.",
    },
  },
  {
    t: "Redux · Core",
    q: "Зачем нужны селекторы?",
    o: [
      "Чтобы просто весь код выглядел красивее и немного аккуратнее",
      "Читают СРЕЗ state: инкапсулируют форму стора + точечные ре-рендеры через useSelector",
      "Полностью и безусловно заменяют собой reducer-ы в приложении",
      "Валидируют структуру и полное содержимое каждого action целиком",
    ],
    a: 1,
    e: "useSelector ре-рендерит компонент только при изменении РЕЗУЛЬТАТА селектора — то, чего не умеет Context. Мемоизация — reselect/createSelector.",
    en: {
      t: "Redux · Core",
      q: "What are selectors for?",
      o: [
        "Just to make the code look nicer and a bit tidier",
        "They read a SLICE of state: encapsulating the store's shape and enabling targeted re-renders via useSelector",
        "They completely and unconditionally replace reducers in an application",
        "They validate the structure and full contents of every action",
      ],
      e: "useSelector re-renders the component only when the selector's RESULT changes — something Context can't do. Memoization is handled by reselect/createSelector.",
    },
  },
  {
    t: "Redux · Side effects",
    q: "Где в Redux живут запросы к API?",
    o: [
      "Прямо внутри reducer-ов вместе с логикой",
      "В middleware (thunk/saga) или RTK Query",
      "Напрямую в объекте store, минуя reducer",
      "Внутри самих action-объектов при их создании",
    ],
    a: 1,
    e: "Reducer-ы чистые и синхронные. Async-работа — в middleware: thunk диспатчит pending/fulfilled/rejected; для серверного кэша — RTK Query.",
    en: {
      t: "Redux · Side effects",
      q: "Where do API requests live in Redux?",
      o: [
        "Directly inside reducers, alongside the logic",
        "In middleware (thunk/saga) or RTK Query",
        "Directly in the store object, bypassing the reducer",
        "Inside the action objects themselves when they're created",
      ],
      e: "Reducers are pure and synchronous. Async work belongs in middleware: a thunk dispatches pending/fulfilled/rejected; for server-side caching, use RTK Query.",
    },
  },
  {
    t: "Redux · Side effects",
    q: "Thunk — это...",
    o: [
      "Особая разновидность reducer-а с побочными эффектами",
      "Диспатч ФУНКЦИИ, которую middleware вызывает с dispatch — внутри можно await",
      "Это просто другое название для обычного action-объекта",
      "Компонент-обёртка вокруг самого Provider из react-redux",
    ],
    a: 1,
    e: "redux-thunk перехватывает dispatch(fn) и вызывает fn(dispatch, getState). В RTK это createAsyncThunk с автогенерацией трёх actions.",
    en: {
      t: "Redux · Side effects",
      q: "A thunk is...",
      o: [
        "A special kind of reducer that has side effects",
        "Dispatching a FUNCTION that the middleware calls with dispatch — you can await inside it",
        "Just another name for a regular action object",
        "A wrapper component around react-redux's Provider",
      ],
      e: "redux-thunk intercepts dispatch(fn) and calls fn(dispatch, getState). In RTK, this is createAsyncThunk, which auto-generates three actions.",
    },
  },
  {
    t: "Redux · RTK",
    q: "В createSlice пишут state.items.push(x) — почему это ок?",
    o: [
      "Потому что RTK официально разрешил такие мутации state",
      "Внутри Immer: «мутации» записываются и превращаются в иммутабельный апдейт",
      "Это давно известный и признанный баг в самом Redux Toolkit",
      "На самом деле метод push здесь вообще ничего не мутирует",
    ],
    a: 1,
    e: "Мутировать нельзя нигде — Immer проксирует state и производит новый объект. Вне createSlice мутация осталась багом. «RTK разрешил мутации» — red flag.",
    en: {
      t: "Redux · RTK",
      q: "Inside createSlice you write state.items.push(x) — why is this okay?",
      o: [
        "Because RTK has officially allowed such state mutations",
        "Under the hood it uses Immer: the 'mutations' are recorded and turned into an immutable update",
        "It's a long-known, acknowledged bug in Redux Toolkit itself",
        "In fact, push here doesn't actually mutate anything at all",
      ],
      e: "Mutation is still off-limits everywhere — Immer proxies the state and produces a new object behind the scenes. Outside createSlice, mutating state is still a bug. 'RTK allows mutations' is a red flag answer.",
    },
  },
  {
    t: "Redux · RTK",
    q: "Что даёт configureStore из коробки?",
    o: [
      "Только голый createStore без каких-либо дополнений",
      "DevTools, thunk, dev-проверки на мутации и несериализуемое",
      "Автоматически сгенерированные тесты для reducer-ов",
      "Полноценный GraphQL-клиент со своим кэшем",
    ],
    a: 1,
    e: "Поэтому RTK — официальный стандарт: без ручной настройки composeEnhancers и applyMiddleware.",
    en: {
      t: "Redux · RTK",
      q: "What does configureStore give you out of the box?",
      o: [
        "Just plain createStore with no additions",
        "DevTools, thunk, and dev-mode checks for mutations and non-serializable values",
        "Automatically generated tests for reducers",
        "A full-fledged GraphQL client with its own cache",
      ],
      e: "That's why RTK is the official standard — no need to manually configure composeEnhancers and applyMiddleware.",
    },
  },
  {
    t: "Redux · Архитектура",
    q: "Что НЕ стоит класть в Redux-стор?",
    o: [
      "Данные корзины, общие сразу для нескольких страниц",
      "Открыт ли конкретный дропдаун (локальный UI-state) и серверный кэш",
      "Информацию о текущем авторизованном пользователе",
      "Фильтры списка, общие сразу для нескольких экранов",
    ],
    a: 1,
    e: "Локальный UI-state → useState; серверные данные → RTK Query/TanStack Query (кэш из коробки). «Всё в Redux» — red flag.",
    en: {
      t: "Redux · Architecture",
      q: "What should NOT be put in the Redux store?",
      o: [
        "Cart data shared across several pages",
        "Whether a particular dropdown is open (local UI state) and server-side cache",
        "Information about the currently authenticated user",
        "List filters shared across several screens",
      ],
      e: "Local UI state belongs in useState; server data belongs in RTK Query/TanStack Query, which provides caching out of the box. 'Put everything in Redux' is a red flag answer.",
    },
  },
  {
    t: "Redux · vs Context",
    q: "Почему «Context — замена Redux» — неверно?",
    o: [
      "Потому что Context абсолютно в любых сценариях работает заметно медленнее Redux",
      "Разные задачи: Context — доставка значения (DI), Redux — управление состоянием с селекторами, middleware, devtools",
      "Потому что Context считается полностью устаревшим и уже давно заброшенным API",
      "Потому что Redux умеет полноценно и совершенно стабильно работать вообще без React",
    ],
    a: 1,
    e: "Context не умеет: подписку на часть value, middleware, time-travel. Правильно: Context+useReducer — feature-level; Redux/Zustand — app-level с частыми обновлениями.",
    en: {
      t: "Redux · vs Context",
      q: "Why is the claim 'Context replaces Redux' wrong?",
      o: [
        "Because Context is noticeably slower than Redux in absolutely every scenario",
        "They solve different problems: Context is a value-delivery mechanism (DI), while Redux is state management with selectors, middleware, and devtools",
        "Because Context is considered a fully deprecated, long-abandoned API",
        "Because Redux can run fully and reliably without React at all",
      ],
      e: "Context can't do: subscribing to part of a value, middleware, or time-travel debugging. The right approach: Context+useReducer for feature-level state; Redux/Zustand for app-level state with frequent updates.",
    },
  },
  {
    t: "Redux · Middleware",
    q: "Что делает этот middleware?\nconst logger = store => next => action => {\n  console.log('dispatching', action);\n  return next(action);\n};",
    o: [
      "Логирует action и передаёт его дальше по цепочке через next(action)",
      "Полностью блокирует dispatch, next(action) никогда не вызывается",
      "Заменяет reducer и сам вычисляет новый state приложения",
      "Подписывается на store через store.subscribe и ничего не логирует",
    ],
    a: 0,
    e: "middleware — это store => next => action => {...}: получает store, следующий обработчик next и action; return next(action) передаёт его дальше по цепочке к reducer-у. Без next(action) action «зависнет» и до reducer не дойдёт.",
    en: {
      t: "Redux · Middleware",
      q: "What does this middleware do?\nconst logger = store => next => action => {\n  console.log('dispatching', action);\n  return next(action);\n};",
      o: [
        "Logs the action and passes it further down the chain via next(action)",
        "Completely blocks dispatch — next(action) is never called",
        "Replaces the reducer and computes the app's new state itself",
        "Subscribes to the store via store.subscribe and logs nothing",
      ],
      e: "A middleware has the shape store => next => action => {...}: it receives the store, the next handler in the chain, and the action; return next(action) passes the action further down the chain toward the reducer. Without next(action), the action would 'hang' and never reach the reducer.",
    },
  },
  {
    t: "Redux · useSelector",
    q: "const items = useSelector(state => state.cart.items.map(i => i.id));\nЧто произойдёт при КАЖДОМ dispatch любого action, даже не трогающего cart?",
    o: [
      "Компонент ре-рендерится: map создаёт новый массив, useSelector сравнивает по ===",
      "Ничего не произойдёт — useSelector сам запоминает предыдущий результат",
      "Redux выбросит ошибку из-за нечистого селектора внутри map",
      "Ре-рендер случится только если действительно изменился cart.items",
    ],
    a: 0,
    e: "useSelector по умолчанию сравнивает результат через ===. .map() возвращает НОВЫЙ массив при каждом вызове, даже если данные не изменились — компонент рендерится на любой dispatch. Чинится через createSelector (мемоизация) или shallowEqual вторым аргументом.",
    en: {
      t: "Redux · useSelector",
      q: "const items = useSelector(state => state.cart.items.map(i => i.id));\nWhat happens on EVERY dispatch of any action, even ones that don't touch cart at all?",
      o: [
        "The component re-renders: map creates a new array each time, and useSelector compares by ===",
        "Nothing happens — useSelector remembers the previous result on its own",
        "Redux throws an error because of an impure selector inside map",
        "A re-render happens only if cart.items actually changed",
      ],
      e: "By default, useSelector compares the result using ===. .map() returns a NEW array on every call, even when the underlying data hasn't changed — so the component re-renders on any dispatch. This is fixed with createSelector (memoization) or by passing shallowEqual as the second argument.",
    },
  },
  {
    t: "Redux · useSelector",
    q: "Зачем передавать shallowEqual вторым аргументом в useSelector?",
    o: [
      "Чтобы React сравнивал поля результата на один уровень вглубь, а не по ссылке",
      "Чтобы ускорить сам reducer при обработке этого action",
      "Чтобы полностью отключить ре-рендеры этого компонента",
      "Чтобы селектор автоматически кэшировался между разными компонентами",
    ],
    a: 0,
    e: "По умолчанию useSelector сравнивает результат через ===. shallowEqual вместо этого сравнивает объект/массив на один уровень по ключам — если селектор возвращает { id, name } с теми же примитивами внутри, лишнего ре-рендера не будет, хотя ссылка новая.",
    en: {
      t: "Redux · useSelector",
      q: "Why pass shallowEqual as the second argument to useSelector?",
      o: [
        "So React compares the result's fields one level deep instead of by reference",
        "To speed up the reducer itself when handling this action",
        "To completely disable re-renders of this component",
        "So the selector is automatically cached across different components",
      ],
      e: "By default, useSelector compares the result using ===. shallowEqual instead compares an object/array one level deep by keys — if the selector returns { id, name } with the same primitive values inside, there won't be an unnecessary re-render even though the reference is new.",
    },
  },
  {
    t: "Redux · RTK",
    q: "createAsyncThunk('user/fetch', fn) автоматически генерирует...",
    o: [
      "Три action types: pending, fulfilled и rejected — по стадиям промиса",
      "Один action type, одинаковый и для успеха, и для ошибки",
      "Готовый reducer, который сохранит данные без extraReducers",
      "Отдельный слайс стора специально под этот один запрос",
    ],
    a: 0,
    e: "createAsyncThunk сам не пишет reducer — только диспатчит user/fetch/pending при старте, user/fetch/fulfilled с payload при успехе и user/fetch/rejected с error при ошибке. Обработка этих трёх типов — в extraReducers слайса.",
    en: {
      t: "Redux · RTK",
      q: "createAsyncThunk('user/fetch', fn) automatically generates...",
      o: [
        "Three action types: pending, fulfilled, and rejected — matching the promise's stages",
        "A single action type, the same for both success and failure",
        "A ready-made reducer that stores the data without extraReducers",
        "A separate store slice dedicated to this one request",
      ],
      e: "createAsyncThunk doesn't write a reducer itself — it only dispatches user/fetch/pending when it starts, user/fetch/fulfilled with the payload on success, and user/fetch/rejected with the error on failure. Handling these three action types is done in the slice's extraReducers.",
    },
  },
  {
    t: "Redux · RTK Query",
    q: "В RTK Query для чего нужны providesTags и invalidatesTags?",
    o: [
      "Для кэш-инвалидации: мутация с invalidatesTags рефетчит запросы с тем же тегом",
      "Для визуального оформления состояния загрузки в компонентах",
      "Для описания типов TypeScript у всех аргументов запроса",
      "Для ограничения количества запросов в секунду к серверу",
    ],
    a: 0,
    e: "providesTags помечает, какие данные вернул запрос (например 'Post', id). invalidatesTags на мутации говорит: «после этого action данные с таким тегом устарели» — RTK Query сам рефетчит нужные запросы, кэш вручную обновлять не надо.",
    en: {
      t: "Redux · RTK Query",
      q: "In RTK Query, what are providesTags and invalidatesTags for?",
      o: [
        "For cache invalidation: a mutation with invalidatesTags refetches queries that share the same tag",
        "For styling the loading state visually in components",
        "For describing the TypeScript types of all query arguments",
        "For limiting the number of requests per second to the server",
      ],
      e: "providesTags marks what data a query returned (e.g., 'Post', id). invalidatesTags on a mutation says: 'after this action, data with this tag is stale' — RTK Query then refetches the relevant queries automatically, so you don't have to update the cache by hand.",
    },
  },
  {
    t: "Redux · RTK",
    q: "Зачем нужен createEntityAdapter?",
    o: [
      "Нормализует коллекцию в { ids, entities } и даёт готовые CRUD-редьюсеры и селекторы",
      "Хранит сущности простым массивом, как это делал бы обычный useState",
      "Автоматически подгружает недостающие сущности с сервера по их id",
      "Кэширует HTTP-запросы к REST API точно так же, как RTK Query",
    ],
    a: 0,
    e: "Массив [{...}, {...}] требует O(n) поиска по id и легко замутировать по ошибке. entityAdapter хранит { ids: [...], entities: { id: item } } — доступ по id за O(1), плюс готовые addOne/updateOne/removeOne и селекторы вроде selectAll/selectById.",
    en: {
      t: "Redux · RTK",
      q: "What is createEntityAdapter for?",
      o: [
        "It normalizes a collection into { ids, entities } and provides ready-made CRUD reducers and selectors",
        "It stores entities as a plain array, the way a regular useState would",
        "It automatically fetches missing entities from the server by id",
        "It caches HTTP requests to a REST API exactly like RTK Query does",
      ],
      e: "An array [{...}, {...}] requires an O(n) lookup by id and is easy to mutate by mistake. entityAdapter stores data as { ids: [...], entities: { id: item } } — giving O(1) access by id, plus ready-made addOne/updateOne/removeOne reducers and selectors like selectAll/selectById.",
    },
  },
  {
    t: "Redux · Reselect",
    q: "const selectVisible = createSelector([selectTodos, selectFilter], (todos, filter) => todos.filter(t => t.done === filter));\nПочему это лучше, чем то же самое прямо внутри useSelector?",
    o: [
      "Мемоизация: пересчёт .filter() происходит только если реально изменились todos или filter",
      "Это просто более короткая запись, по поведению они идентичны",
      "createSelector умеет обращаться напрямую к серверу за данными",
      "Так селектор становится доступен из любого компонента без импорта",
    ],
    a: 0,
    e: "Обычный inline-селектор с .filter() создаёт новый массив на КАЖДЫЙ dispatch — и рендерит компонент даже когда todos/filter не менялись. createSelector кэширует последний результат и пересчитывает функцию только когда изменился хотя бы один вход.",
    en: {
      t: "Redux · Reselect",
      q: "const selectVisible = createSelector([selectTodos, selectFilter], (todos, filter) => todos.filter(t => t.done === filter));\nWhy is this better than doing the same thing directly inside useSelector?",
      o: [
        "Memoization: .filter() is recomputed only when todos or filter actually change",
        "It's just a shorter syntax — behavior-wise they're identical",
        "createSelector can fetch data directly from the server",
        "This makes the selector available from any component without importing it",
      ],
      e: "A plain inline selector with .filter() creates a new array on EVERY dispatch — re-rendering the component even when todos/filter haven't changed. createSelector caches the last result and only recomputes the function when at least one input has changed.",
    },
  },
  {
    t: "Redux · Принципы",
    q: "Что не так с этим кодом?\nfunction reducer(state, action) {\n  if (action.type === 'save') {\n    store.dispatch({ type: 'saved' });\n  }\n  return state;\n}",
    o: [
      "Dispatch внутри reducer запрещён: он должен быть чистой функцией без side effects",
      "Ошибка синтаксиса — так писать reducer вообще нельзя никогда",
      "Всё верно, это стандартный способ вызвать цепочку actions",
      "Проблема только в отсутствии default-ветки в этом коде",
    ],
    a: 0,
    e: "Reducer обязан быть чистым: без side effects, включая dispatch. Redux даже кидает рантайм-ошибку «Reducers may not dispatch actions», потому что dispatch во время текущего dispatch ломает предсказуемый однонаправленный поток. Цепочку actions делают через middleware.",
    en: {
      t: "Redux · Principles",
      q: "What's wrong with this code?\nfunction reducer(state, action) {\n  if (action.type === 'save') {\n    store.dispatch({ type: 'saved' });\n  }\n  return state;\n}",
      o: [
        "Dispatching inside a reducer is forbidden: a reducer must be a pure function with no side effects",
        "This is a syntax error — a reducer can never be written this way at all",
        "This is fine — it's the standard way to chain actions",
        "The only problem is the missing default branch in this code",
      ],
      e: "A reducer must be pure: no side effects, including dispatch. Redux even throws a runtime error, 'Reducers may not dispatch actions,' because dispatching while another dispatch is in progress breaks the predictable, unidirectional data flow. Chaining actions is done through middleware instead.",
    },
  },
  {
    t: "Redux · Экосистема",
    q: "Для чего используют redux-persist?",
    o: [
      "Сохраняет выбранную часть state в хранилище и восстанавливает при перезагрузке",
      "Ускоряет dispatch actions за счёт очереди в фоновом потоке",
      "Автоматически откатывает state при возникновении ошибки",
      "Синхронизирует state сразу между несколькими открытыми вкладками",
    ],
    a: 0,
    e: "redux-persist оборачивает reducer, при каждом изменении сохраняет сериализуемую часть state (обычно в localStorage), а при старте приложения восстанавливает её через PersistGate — так корзина или токен переживают перезагрузку страницы.",
    en: {
      t: "Redux · Ecosystem",
      q: "What is redux-persist used for?",
      o: [
        "It saves a chosen part of the state to storage and restores it on reload",
        "It speeds up dispatching actions by queuing them on a background thread",
        "It automatically rolls back the state when an error occurs",
        "It synchronizes state across several open tabs at once",
      ],
      e: "redux-persist wraps the reducer, saving the serializable part of the state (usually to localStorage) on every change, and restores it on app startup via PersistGate — so things like the cart or an auth token survive a page reload.",
    },
  },
  {
    t: "Redux · Core",
    q: "Что такое store enhancer в Redux?",
    o: [
      "Функция высшего порядка вокруг createStore, расширяющая сам стор — например applyMiddleware",
      "Компонент React, оборачивающий сам Provider для доступа к стору",
      "Отдельный reducer, который просто объединяет несколько слайсов",
      "Утилита для аккуратного форматирования данных перед показом в devtools",
    ],
    a: 0,
    e: "Enhancer — это (createStore) => (...args) => enhancedStore: он оборачивает создание стора и может подменить/расширить dispatch, getState, subscribe. applyMiddleware(...) сам возвращает enhancer; несколько enhancer-ов объединяют через compose.",
    en: {
      t: "Redux · Core",
      q: "What is a store enhancer in Redux?",
      o: [
        "A higher-order function around createStore that extends the store itself — for example, applyMiddleware",
        "A React component that wraps Provider to give access to the store",
        "A separate reducer that simply combines several slices",
        "A utility for neatly formatting data before displaying it in devtools",
      ],
      e: "An enhancer has the shape (createStore) => (...args) => enhancedStore: it wraps store creation and can replace or extend dispatch, getState, and subscribe. applyMiddleware(...) itself returns an enhancer; multiple enhancers are combined with compose.",
    },
  },
];
