// Вопросы квиза: секция TS
// Формат и правила — см. скилл .claude/skills/quiz-questions/SKILL.md

import type { Question } from "../types";

export const TS_QUESTIONS: Question[] = [
  {
    t: "TS · Основы",
    q: "const user = (await res.json()) as User; — что проверит TS в рантайме?",
    o: [
      "Проверит абсолютно все поля интерфейса User в рантайме",
      "НИЧЕГО — типы стираются при компиляции; as — утверждение, не проверка",
      "Проверит только обязательные поля, опциональные пропустит",
      "Проверит типы примитивных полей, объекты пропустит",
    ],
    a: 1,
    e: "Типы существуют только на этапе компиляции. Внешние данные (API, формы) валидируются в рантайме схемой: zod.parse().",
    en: {
      t: "TS · Basics",
      q: "const user = (await res.json()) as User; — what does TS check at runtime?",
      o: [
        "It will check absolutely all fields of the User interface at runtime",
        "NOTHING — types are erased at compile time; as is an assertion, not a check",
        "It will check only required fields, skipping optional ones",
        "It will check the types of primitive fields, skipping objects",
      ],
      e: "Types exist only at compile time. External data (API responses, forms) must be validated at runtime with a schema: zod.parse().",
    },
  },
  {
    t: "TS · Основы",
    q: "Чем unknown лучше any?",
    o: [
      "unknown работает быстрее любых операций во время выполнения",
      "unknown требует сужения (narrowing) перед использованием; any отключает проверки",
      "unknown можно напрямую сериализовать в JSON без проверок",
      "Ничем не отличается, unknown и any — просто синонимы",
    ],
    a: 1,
    e: "any «заражает» код — всё дозволено и ошибки уходят в рантайм. unknown безопасен: сначала typeof/instanceof/схема, потом использование.",
    en: {
      t: "TS · Basics",
      q: "How is unknown better than any?",
      o: [
        "unknown runs faster than any for all operations at runtime",
        "unknown requires narrowing before use; any disables type checking",
        "unknown can be directly serialized to JSON without any checks",
        "No difference — unknown and any are just synonyms",
      ],
      e: "any is \"contagious\" — everything is allowed and errors surface at runtime. unknown is safe: you must narrow first (typeof/instanceof/schema), then use it.",
    },
  },
  {
    t: "TS · Type vs Interface",
    q: "Что умеет interface, чего НЕ умеет type?",
    o: [
      "Возможность описывать union-типы через вертикальную черту",
      "Declaration merging — повторное объявление сливает члены",
      "Поддержка кортежей фиксированной длины и типов",
      "Работа с дженериками и ограничениями extends",
    ],
    a: 1,
    e: "Merging — основа аугментации чужих типов (Express Request, window). А union/кортежи/mapped/conditional — наоборот, только type.",
    en: {
      t: "TS · Type vs Interface",
      q: "What can interface do that type CANNOT?",
      o: [
        "Describe union types using a vertical bar",
        "Declaration merging — re-declaring it merges the members",
        "Support fixed-length tuples and tuple types",
        "Work with generics and extends constraints",
      ],
      e: "Merging is the basis for augmenting third-party types (Express Request, window). Union types/tuples/mapped/conditional types, on the other hand, are only available with type.",
    },
  },
  {
    t: "TS · Utility types",
    q: "Omit<User, 'email'> — что это?",
    o: [
      "User, содержащий только поле email и ничего больше",
      "User без поля email — Omit вырезает указанный ключ",
      "User, где поле email становится опциональным",
      "Ошибка компиляции: Omit принимает лишь один аргумент типа",
    ],
    a: 1,
    e: "Omit вырезает ключи, Pick — оставляет только указанные. Классика для props: Omit<ButtonProps, 'onClick'>. Подвох: Omit не ругается на опечатку в ключе.",
    en: {
      t: "TS · Utility Types",
      q: "What is Omit<User, 'email'>?",
      o: [
        "User containing only the email field and nothing else",
        "User without the email field — Omit strips the specified key",
        "User where the email field becomes optional",
        "A compile error: Omit only accepts one type argument",
      ],
      e: "Omit strips keys, Pick keeps only the specified ones. A classic pattern for props: Omit<ButtonProps, 'onClick'>. Gotcha: Omit won't catch a typo in the key name.",
    },
  },
  {
    t: "TS · Основы",
    q: "Какой тип выведет TS?\nconst x = \"hello\";\nlet y = \"hello\";",
    o: [
      "Оба получат широкий тип string, разницы в выводе нет",
      "x: \"hello\" (литерал), y: string — const сужает, let расширяет",
      "Оба сузятся до литерального типа \"hello\" без widening",
      "x получит string, а y — литеральный тип \"hello\"",
    ],
    a: 1,
    e: "const не переприсваивается → сужается до литерального типа. let может измениться → расширяется (widening) до string.",
    en: {
      t: "TS · Basics",
      q: "What type will TS infer?\nconst x = \"hello\";\nlet y = \"hello\";",
      o: [
        "Both get the wide string type, there's no difference in inference",
        "x: \"hello\" (literal), y: string — const narrows, let widens",
        "Both narrow to the literal type \"hello\" without widening",
        "x gets string, and y gets the literal type \"hello\"",
      ],
      e: "const is never reassigned → it narrows to a literal type. let could change → it widens to string.",
    },
  },
  {
    t: "TS · Основы",
    q: "Что делает as const?",
    o: [
      "Просто приводит значение к строковому типу string",
      "Замораживает тип: литералы вместо широких типов + readonly для всех полей",
      "Создаёт настоящую константу уже во время выполнения",
      "Полностью эквивалентен вызову Object.freeze в рантайме",
    ],
    a: 1,
    e: "[\"a\", \"b\"] as const → readonly [\"a\", \"b\"] (кортеж литералов, не string[]). Рантайм не трогает — это только типы. Идиома: массивы опций, объекты-конфиги.",
    en: {
      t: "TS · Basics",
      q: "What does as const do?",
      o: [
        "It simply casts the value to the string type",
        "It freezes the type: literals instead of wide types + readonly for all fields",
        "It creates a real constant at runtime",
        "It's fully equivalent to calling Object.freeze at runtime",
      ],
      e: "[\"a\", \"b\"] as const → readonly [\"a\", \"b\"] (a tuple of literals, not string[]). It doesn't touch runtime at all — it's types only. Common idiom: option arrays, config objects.",
    },
  },
  {
    t: "TS · Основы",
    q: "Когда функция имеет тип never (а не void)?",
    o: [
      "Когда функция вообще ничего явно не возвращает",
      "Когда НИКОГДА не завершается нормально: всегда throw или бесконечный цикл",
      "Когда функция явно возвращает значение undefined",
      "Когда функция объявлена как асинхронная через async",
    ],
    a: 1,
    e: "void = «вернулась, но значение не интересно»; never = «не вернётся вообще». never также — пустой union и инструмент exhaustiveness-проверок.",
    en: {
      t: "TS · Basics",
      q: "When does a function have the type never (rather than void)?",
      o: [
        "When the function doesn't explicitly return anything at all",
        "When it NEVER completes normally: it always throws or loops forever",
        "When the function explicitly returns the value undefined",
        "When the function is declared as asynchronous using async",
      ],
      e: "void means \"it returned, but the value doesn't matter\"; never means \"it never returns at all.\" never is also the empty union and a tool for exhaustiveness checks.",
    },
  },
  {
    t: "TS · Основы",
    q: "Зачем в default-ветке switch пишут const _x: never = value?",
    o: [
      "Просто микрооптимизация производительности switch-конструкции",
      "Exhaustiveness-check: добавили вариант в union и забыли ветку — ошибка компиляции",
      "Нужно, чтобы switch не падал с исключением в рантайме",
      "Устаревший синтаксис, оставшийся от ранних версий TS",
    ],
    a: 1,
    e: "Если все варианты разобраны, в default тип сужен до never — присваивание валидно. Появился неразобранный вариант — тип не never, компилятор кричит. Бесплатная защита от забытых веток.",
    en: {
      t: "TS · Basics",
      q: "Why do people write const _x: never = value in a switch's default branch?",
      o: [
        "It's simply a micro-optimization for the switch statement's performance",
        "Exhaustiveness check: if a variant is added to the union and its branch is forgotten, it's a compile error",
        "It's needed so the switch doesn't throw an exception at runtime",
        "It's legacy syntax left over from early versions of TS",
      ],
      e: "If every variant has been handled, the type is narrowed to never in default — the assignment is valid. If an unhandled variant appears, the type is no longer never, and the compiler complains. Free protection against forgotten branches.",
    },
  },
  {
    t: "TS · Основы",
    q: "Что предпочесть и почему?\nenum Status { Idle, Loading }\n// vs\ntype Status = 'idle' | 'loading';",
    o: [
      "enum предпочтительнее — он строго типобезопаснее union литералов",
      "Union литералов: не генерирует рантайм-код, проще narrowing; enum — реальный объект в бандле",
      "Всегда стоит выбирать enum, union литералов считается устаревшим",
      "Разницы никакой нет, это два эквивалентных синтаксиса записи",
    ],
    a: 1,
    e: "enum компилируется в JS-объект (единственная конструкция TS с рантайм-следом, кроме decorators). Union строковых литералов бесплатен и дружит с narrowing. as const объект — компромисс, когда нужны значения.",
    en: {
      t: "TS · Basics",
      q: "Which should you prefer, and why?\nenum Status { Idle, Loading }\n// vs\ntype Status = 'idle' | 'loading';",
      o: [
        "enum is preferable — it's strictly more type-safe than literal unions",
        "A union of literals: generates no runtime code, narrows more easily; enum is a real object in the bundle",
        "You should always choose enum, union literals are considered outdated",
        "There's no difference at all, these are two equivalent syntaxes",
      ],
      e: "enum compiles to a JS object (the only TS construct with a runtime footprint besides decorators). A union of string literals is free and plays nicely with narrowing. An as const object is a compromise when you need actual values.",
    },
  },
  {
    t: "TS · Операторы типов",
    q: "keyof User (где User = { id: string; name: string }) — это...",
    o: [
      "string[] — обычный массив строковых имён ключей",
      "\"id\" | \"name\" — union имён ключей",
      "User без значений — объект с пустыми полями",
      "number — количество ключей в объекте User",
    ],
    a: 1,
    e: "keyof возвращает union литералов-ключей. База для дженериков: <K extends keyof T> — типобезопасный доступ obj[key].",
    en: {
      t: "TS · Type Operators",
      q: "keyof User (where User = { id: string; name: string }) is...",
      o: [
        "string[] — an ordinary array of key names as strings",
        "\"id\" | \"name\" — a union of key names",
        "User without values — an object with empty fields",
        "number — the count of keys in the User object",
      ],
      e: "keyof returns a union of key literal types. It's the foundation for generics: <K extends keyof T> for type-safe access via obj[key].",
    },
  },
  {
    t: "TS · Операторы типов",
    q: "typeof в позиции типа (type C = typeof config) — что делает?",
    o: [
      "То же самое, что typeof в рантайме — просто вернёт строку",
      "Извлекает ТИП из значения: тип переменной config становится типом C",
      "Проверяет соответствие типа значению во время выполнения",
      "Работает исключительно с функциями, для объектов не годится",
    ],
    a: 1,
    e: "Два разных typeof: JS-оператор (рантайм, строка) и TS-оператор (тип значения). Идиома: тип из конфига/объекта — один источник правды. Часто вместе: keyof typeof obj.",
    en: {
      t: "TS · Type Operators",
      q: "typeof in a type position (type C = typeof config) — what does it do?",
      o: [
        "The same thing as typeof at runtime — it just returns a string",
        "It extracts the TYPE from a value: the type of the config variable becomes the type C",
        "It checks that the type matches the value at runtime",
        "It only works with functions, not with objects",
      ],
      e: "There are two different typeofs: the JS operator (runtime, returns a string) and the TS operator (the type of a value). Common idiom: deriving a type from a config/object — a single source of truth. Often combined: keyof typeof obj.",
    },
  },
  {
    t: "TS · Narrowing",
    q: "Что такое type guard с предикатом (x is User)?",
    o: [
      "Специальный декоратор класса для валидации свойств",
      "Функция-проверка, которая при true сужает тип аргумента в вызывающем коде",
      "Автоматическая рантайм-валидация вообще всех полей объекта",
      "Просто синоним оператора instanceof для классов",
    ],
    a: 1,
    e: "function isUser(x: unknown): x is User { return ... } — вернула true → дальше по ветке x типизирован как User. Проверку внутри пишешь сам (или zod: schema.safeParse).",
    en: {
      t: "TS · Narrowing",
      q: "What is a type guard with a predicate (x is User)?",
      o: [
        "A special class decorator for validating properties",
        "A check function that, when true, narrows the argument's type at the call site",
        "Automatic runtime validation of absolutely every field of an object",
        "Just a synonym for the instanceof operator for classes",
      ],
      e: "function isUser(x: unknown): x is User { return ... } — if it returns true, then in that branch x is typed as User. You write the check yourself (or use zod: schema.safeParse).",
    },
  },
  {
    t: "TS · Narrowing",
    q: "Чем плох non-null assertion (user!.name)?",
    o: [
      "Просто немного замедляет выполнение выражения в рантайме",
      "Отключает проверку на null ТОЛЬКО в типах — в рантайме null никуда не делся: крашнется",
      "Код с ним вообще не скомпилируется в строгом режиме strict",
      "Ничем не плох, это рекомендуемый способ работы с null-значениями",
    ],
    a: 1,
    e: "! — «поверь мне, тут не null». Компилятор верит, рантайм — нет. Правильно: проверка, ?. с fallback, или инвариант с явным throw.",
    en: {
      t: "TS · Narrowing",
      q: "Why is the non-null assertion (user!.name) a problem?",
      o: [
        "It just slightly slows down evaluation of the expression at runtime",
        "It disables the null check ONLY in the type system — at runtime null is still there: it will crash",
        "Code using it won't compile at all in strict mode",
        "It isn't a problem at all, it's the recommended way to work with null values",
      ],
      e: "! means \"trust me, this isn't null.\" The compiler believes you; the runtime doesn't. The right approach: an actual check, ?. with a fallback, or an invariant with an explicit throw.",
    },
  },
  {
    t: "TS · Narrowing",
    q: "Как сузить этот union до конкретного варианта?\ntype Shape =\n  | { kind: 'circle'; r: number }\n  | { kind: 'square'; size: number };",
    o: [
      "Приведение типа через as Circle без всякой проверки",
      "switch/if по полю-дискриминатору kind — TS сузит тип в каждой ветке",
      "Оператор instanceof, проверяющий класс-конструктор",
      "Никак не сузить, для этого обязательно нужны классы",
    ],
    a: 1,
    e: "Discriminated union — главная идиома TS: общее литеральное поле kind + switch. В ветке case 'circle' доступен r, и работает exhaustiveness через never.",
    en: {
      t: "TS · Narrowing",
      q: "How do you narrow this union down to a specific variant?\ntype Shape =\n  | { kind: 'circle'; r: number }\n  | { kind: 'square'; size: number };",
      o: [
        "A type cast via as Circle without any check at all",
        "A switch/if on the discriminant field kind — TS narrows the type in each branch",
        "The instanceof operator, checking the constructor class",
        "There's no way to narrow it, classes are required for this",
      ],
      e: "A discriminated union is TS's central idiom: a shared literal field kind plus a switch. In the case 'circle' branch, r is accessible, and exhaustiveness checking works via never.",
    },
  },
  {
    t: "TS · Generics",
    q: "<T extends { id: string }>(item: T) => T — что даёт extends здесь?",
    o: [
      "Наследование класса от указанного в скобках базового типа",
      "Ограничение: T обязан иметь id, внутри можно item.id, а возвращается ТОЧНЫЙ тип аргумента",
      "Преобразование любого переданного типа T в объект { id: string }",
      "Объявление обычного условного типа, зависящего от значения T",
    ],
    a: 1,
    e: "Constraint сохраняет конкретный тип (вернётся User, а не { id: string }) и разрешает доступ к id. Без дженерика (item: { id: string }) тип «сплющился» бы.",
    en: {
      t: "TS · Generics",
      q: "<T extends { id: string }>(item: T) => T — what does extends give here?",
      o: [
        "Inheriting a class from the base type specified in the brackets",
        "A constraint: T must have an id, so item.id is usable inside, and the EXACT argument type is returned",
        "Converting any passed type T into the object { id: string }",
        "Declaring an ordinary conditional type that depends on the value of T",
      ],
      e: "The constraint preserves the specific type (it returns User, not just { id: string }) while allowing access to id. Without the generic (item: { id: string }), the type would have been \"flattened\".",
    },
  },
  {
    t: "TS · Generics",
    q: "useState(null), а потом setUser(userObj) — почему ошибка и как чинить?",
    o: [
      "useState в принципе не умеет работать с начальным null",
      "TS вывел тип state как null; нужен явный дженерик useState<User | null>(null)",
      "Нужно привести объект через as User перед вызовом",
      "Просто забыли обернуть вызов setUser в хук useEffect",
    ],
    a: 1,
    e: "Из initial-значения null TS выводит тип null — setUser(user) не пройдёт. Явный параметр типа — стандартная практика для «данных, которых пока нет».",
    en: {
      t: "TS · Generics",
      q: "useState(null), then setUser(userObj) — why the error, and how do you fix it?",
      o: [
        "useState simply can't work with an initial value of null at all",
        "TS inferred the state type as null; you need an explicit generic: useState<User | null>(null)",
        "You need to cast the object with as User before calling setUser",
        "You just forgot to wrap the setUser call in a useEffect hook",
      ],
      e: "From an initial value of null, TS infers the type null — setUser(user) won't type-check. Providing an explicit type parameter is the standard practice for \"data that doesn't exist yet\".",
    },
  },
  {
    t: "TS · Современное",
    q: "Что делает satisfies (config satisfies Config)?",
    o: [
      "Полностью то же самое, что и приведение as Config",
      "Проверяет соответствие типу, НЕ расширяя выведенный тип — литералы сохраняются",
      "Выполняет рантайм-валидацию объекта по схеме Config",
      "Создаёт глубокую копию объекта перед проверкой типа",
    ],
    a: 1,
    e: "const c: Config = {...} затирает вывод до Config (теряешь литеральные ключи). satisfies проверяет совместимость, но оставляет точный выведенный тип. as вообще не проверка.",
    en: {
      t: "TS · Modern TS",
      q: "What does satisfies do (config satisfies Config)?",
      o: [
        "Exactly the same thing as the as Config cast",
        "It checks conformance to the type WITHOUT widening the inferred type — literals are preserved",
        "It performs runtime validation of the object against the Config schema",
        "It creates a deep copy of the object before checking the type",
      ],
      e: "const c: Config = {...} overwrites the inferred type with Config (you lose the literal keys). satisfies checks compatibility but keeps the precise inferred type. as isn't a check at all.",
    },
  },
  {
    t: "TS · Инфраструктура",
    q: "Что такое .d.ts файлы?",
    o: [
      "Обычные конфигурационные файлы самого компилятора TS",
      "Файлы деклараций: только типы, без реализации — описывают JS-код для TS",
      "Уже скомпилированный из TypeScript обычный JS-код",
      "Файлы с тестами, которые запускает test-runner",
    ],
    a: 1,
    e: "Декларации дают типы JS-библиотекам: свои генерятся флагом declaration, чужие — пакеты @types/* (DefinitelyTyped). Плюс global.d.ts для аугментаций.",
    en: {
      t: "TS · Tooling",
      q: "What are .d.ts files?",
      o: [
        "Ordinary configuration files for the TS compiler itself",
        "Declaration files: types only, no implementation — they describe JS code for TS",
        "Regular JS code already compiled from TypeScript",
        "Files containing tests that a test runner executes",
      ],
      e: "Declaration files give types to JS libraries: your own are generated with the declaration flag, third-party ones come from @types/* packages (DefinitelyTyped). Plus global.d.ts for augmentations.",
    },
  },
  {
    t: "TS · Инфраструктура",
    q: "Что включает strict: true в tsconfig?",
    o: [
      "Простой запрет использовать тип any в коде проекта",
      "Пакет проверок: strictNullChecks, noImplicitAny, strictFunctionTypes и др.",
      "Настройки форматирования кода наподобие Prettier",
      "Запрет использовать console.log в исходном коде",
    ],
    a: 1,
    e: "strict — зонтичный флаг. Ключевые: noImplicitAny (нет молчаливых any), strictNullChecks (null/undefined явные). Новый проект без strict — red flag.",
    en: {
      t: "TS · Tooling",
      q: "What does strict: true enable in tsconfig?",
      o: [
        "Simply forbids using the any type in the project's code",
        "A bundle of checks: strictNullChecks, noImplicitAny, strictFunctionTypes, and others",
        "Code formatting settings similar to Prettier",
        "Forbids using console.log in source code",
      ],
      e: "strict is an umbrella flag. The key ones: noImplicitAny (no silent anys), strictNullChecks (null/undefined must be explicit). A new project without strict is a red flag.",
    },
  },
  {
    t: "TS · Type vs Interface",
    q: "Что произойдёт?\ntype C = { x: string } & { x: number };\nconst c: C = { x: ??? };",
    o: [
      "Ошибка компиляции прямо на строке объявления типа type",
      "Тип компилируется, но x получает тип never — присвоить ничего нельзя",
      "Поле x получит объединённый тип string | number",
      "Поле x станет просто string, побеждает первый член",
    ],
    a: 1,
    e: "Пересечение конфликтующих примитивов даёт never — ошибка вылезет позже и в неожиданном месте. interface extends сообщил бы о конфликте сразу и понятнее.",
    en: {
      t: "TS · Type vs Interface",
      q: "What happens here?\ntype C = { x: string } & { x: number };\nconst c: C = { x: ??? };",
      o: [
        "A compile error right on the line where the type is declared",
        "It compiles, but x gets the type never — nothing can be assigned to it",
        "The field x gets the union type string | number",
        "The field x becomes just string, the first member wins",
      ],
      e: "Intersecting conflicting primitives yields never — the error surfaces later, in an unexpected place. interface extends would report the conflict immediately and more clearly.",
    },
  },
  {
    t: "TS · Utility types",
    q: "Обязателен ли P['user']['name']?\ntype P = Partial<{\n  user: { name: string };\n}>;",
    o: [
      "Нет, Partial делает опциональным всё вложенное дерево полей",
      "Да — Partial неглубокий: опциональным стал только user",
      "Ошибка компиляции: Partial нельзя применять к вложенным объектам",
      "Зависит от флага strict, включённого в tsconfig проекта",
    ],
    a: 1,
    e: "Утилиты работают на один уровень (как spread при копировании). Для глубокой версии пишут свой рекурсивный DeepPartial.",
    en: {
      t: "TS · Utility Types",
      q: "Is P['user']['name'] optional?\ntype P = Partial<{\n  user: { name: string };\n}>;",
      o: [
        "No, Partial makes the entire nested tree of fields optional",
        "Yes — Partial is shallow: only user became optional",
        "Compile error: Partial cannot be applied to nested objects",
        "It depends on the strict flag enabled in the project's tsconfig",
      ],
      e: "Utility types operate one level deep (like spread when copying). For a deep version, you write your own recursive DeepPartial.",
    },
  },
  {
    t: "TS · Conditional/Mapped",
    q: "Что делает конструкция { [K in keyof T]?: T[K] }?",
    o: [
      "Обычный условный тип, зависящий от результата extends-проверки",
      "Mapped type: проходит по ключам T и делает каждое свойство опциональным (это Partial)",
      "Проверяет наличие всех перечисленных ключей уже в рантайме",
      "Создаёт union из всех строковых имён ключей исходного типа",
    ],
    a: 1,
    e: "Mapped type — «цикл по ключам» другого типа. Модификаторы можно и снимать: -? даёт Required, -readonly даёт Mutable.",
    en: {
      t: "TS · Conditional/Mapped Types",
      q: "What does the construct { [K in keyof T]?: T[K] } do?",
      o: [
        "An ordinary conditional type that depends on the result of an extends check",
        "A mapped type: it iterates over the keys of T and makes every property optional (this is Partial)",
        "It checks at runtime that all listed keys are present",
        "It creates a union of all the string key names of the source type",
      ],
      e: "A mapped type is a \"loop over the keys\" of another type. Modifiers can also be removed: -? gives you Required, -readonly gives you Mutable.",
    },
  },
  {
    t: "TS · Conditional/Mapped",
    q: "Что делает infer в этой конструкции?\ntype R<T> =\n  T extends (...a: any[]) => infer X\n    ? X\n    : never;",
    o: [
      "Просто приводит любой обрабатываемый тип к типу any",
      "Захватывает («выхватывает») тип в переменную X для использования в ветке true",
      "Выполняет проверку типа прямо во время выполнения кода",
      "Объявляет обычный дженерик-параметр самой функции",
    ],
    a: 1,
    e: "infer объявляет переменную типа прямо в conditional-типе. Так устроены ReturnType, Parameters, Awaited и распаковка элемента массива.",
    en: {
      t: "TS · Conditional/Mapped Types",
      q: "What does infer do in this construct?\ntype R<T> =\n  T extends (...a: any[]) => infer X\n    ? X\n    : never;",
      o: [
        "It simply casts whatever type is being processed to any",
        "It captures (\"extracts\") a type into the variable X for use in the true branch",
        "It performs a type check at runtime",
        "It declares an ordinary generic parameter for the function itself",
      ],
      e: "infer declares a type variable right inside a conditional type. This is how ReturnType, Parameters, Awaited, and array element unwrapping work.",
    },
  },
  {
    t: "TS · Conditional/Mapped",
    q: "Чему равен Exclude<'a' | 'b', 'a'>, если Exclude<T,U> = T extends U ? never : T?",
    o: [
      "never — весь union полностью исключается условием",
      "'b' — единственный оставшийся член union после исключения",
      "'a' | 'b' — Exclude ничего не меняет в исходном union",
      "boolean — Exclude возвращает булев результат сравнения",
    ],
    a: 1,
    e: "Дистрибутивность: conditional применяется к КАЖДОМУ члену union по отдельности ('a'→never, 'b'→'b'), never из union выпадает. Отключить распределение можно обёрткой в кортеж: [T] extends [U].",
    en: {
      t: "TS · Conditional/Mapped Types",
      q: "What does Exclude<'a' | 'b', 'a'> equal, given Exclude<T,U> = T extends U ? never : T?",
      o: [
        "never — the entire union is excluded entirely by the condition",
        "'b' — the only remaining member of the union after exclusion",
        "'a' | 'b' — Exclude doesn't change anything in the source union",
        "boolean — Exclude returns a boolean comparison result",
      ],
      e: "Distributivity: the conditional is applied to EACH member of the union separately ('a'→never, 'b'→'b'), and never drops out of the union. You can disable distribution by wrapping in a tuple: [T] extends [U].",
    },
  },
  {
    t: "TS · React",
    q: "Как типизировать onChange инпута в React?",
    o: [
      "(e: any) => e.target.value без всякой типизации события",
      "(e: React.ChangeEvent<HTMLInputElement>) => e.target.value",
      "(e: Event) => e.target.value, обычное DOM-событие",
      "Типизировать onChange в React в принципе нельзя",
    ],
    a: 1,
    e: "React оборачивает события в SyntheticEvent — типы React.ChangeEvent/MouseEvent/FormEvent с дженериком элемента дают типизированный e.target.",
    en: {
      t: "TS · React",
      q: "How do you type an input's onChange in React?",
      o: [
        "(e: any) => e.target.value, with no typing at all",
        "(e: React.ChangeEvent<HTMLInputElement>) => e.target.value",
        "(e: Event) => e.target.value, an ordinary DOM event",
        "It's simply not possible to type onChange in React",
      ],
      e: "React wraps events in a SyntheticEvent — types like React.ChangeEvent/MouseEvent/FormEvent with an element generic give you a typed e.target.",
    },
  },
];
